/**
 * Server-side Daily Puzzle generation + caching.
 *
 * The five non–Lights Out daily puzzles (alibi, spectrum, outcast, chainlink,
 * impostor) are generated by the DeepSeek chat model and cached in the
 * `DailyPuzzle` table, keyed by (gameMode, dateKey). The first request for a
 * given day generates the puzzle and stores it; every later request reads the
 * stored row, so the puzzle is byte-for-byte identical for everyone worldwide.
 *
 * Robustness is the top priority: this module never throws to its caller and
 * never surfaces an error to the player. If the DeepSeek key is unset, the API
 * call fails, or the model returns something that does not pass strict
 * validation, we fall back to the built-in deterministic generator for that
 * mode. Whatever is decided on the first request is persisted, so the day is
 * locked to a single puzzle. There is no user-visible retry loop.
 *
 * Server-only: imports Prisma + the OpenAI SDK. Never import from client code.
 */

import OpenAI from 'openai';
import { prisma } from '@/lib/prisma.server';
import { getPuzzleNumber } from './seed';
import {
    AI_PUZZLE_MODES,
    MAX_TOKENS,
    buildPrompt,
    fallbackPuzzle,
    isAIPuzzleMode,
    parseDateKey,
    parseJson,
    validateAndNormalize,
    type AnyPuzzle,
    type DailyPuzzleMode,
} from './generate-core';

export { AI_PUZZLE_MODES, isAIPuzzleMode };
export type { DailyPuzzleMode };

// maxRetries: 0 so there is no automatic retry loop — reliability comes from the
// deterministic fallback, not from retrying a slow/failing upstream.
const deepseek = new OpenAI({
    apiKey: process.env.DEEPSEEK_API_KEY || 'missing',
    baseURL: 'https://api.deepseek.com/v1',
    maxRetries: 0,
    timeout: 30_000,
});
const MODEL = process.env.RMHARK_AI_MODEL || 'deepseek-chat';

function isConfigured(): boolean {
    return Boolean(process.env.DEEPSEEK_API_KEY);
}

async function callDeepSeek(system: string, user: string, maxTokens: number): Promise<string> {
    const res = await deepseek.chat.completions.create({
        model: MODEL,
        messages: [
            { role: 'system', content: system },
            { role: 'user', content: user },
        ],
        max_tokens: maxTokens,
        temperature: 0.85,
        response_format: { type: 'json_object' },
        stream: false,
    });
    return res.choices[0]?.message?.content?.trim() ?? '';
}

async function generateForMode(
    mode: DailyPuzzleMode,
    dateKey: string,
): Promise<{ data: AnyPuzzle; source: 'deepseek' | 'fallback' }> {
    const date = parseDateKey(dateKey);
    const puzzleNumber = getPuzzleNumber(date);

    if (isConfigured()) {
        try {
            const { system, user } = buildPrompt(mode, dateKey, puzzleNumber);
            const raw = await callDeepSeek(system, user, MAX_TOKENS[mode]);
            const normalized = validateAndNormalize(mode, parseJson(raw), dateKey);
            if (normalized) return { data: normalized, source: 'deepseek' };
            console.warn(
                `daily-puzzle ${mode} ${dateKey}: model output failed validation, using fallback`,
            );
        } catch (e) {
            console.error(`daily-puzzle ${mode} ${dateKey}: generation error, using fallback:`, e);
        }
    }

    return { data: fallbackPuzzle(mode, date), source: 'fallback' };
}

function isUniqueConflict(e: unknown): boolean {
    return Boolean(
        e && typeof e === 'object' && 'code' in e && (e as { code?: string }).code === 'P2002',
    );
}

/**
 * Return the puzzle for a mode + day, generating and caching it on the first
 * request. The stored row is the single source of truth, so everyone who plays
 * that day gets the identical puzzle. Never throws.
 */
export async function getOrCreateDailyPuzzle(
    mode: DailyPuzzleMode,
    dateKey: string,
): Promise<{ data: AnyPuzzle; source: string }> {
    // Fast path: already generated.
    try {
        const existing = await prisma.dailyPuzzle.findUnique({
            where: { gameMode_dateKey: { gameMode: mode, dateKey } },
            select: { data: true, source: true },
        });
        if (existing) return { data: existing.data as unknown as AnyPuzzle, source: existing.source };
    } catch (e) {
        // DB read failed — still return a playable puzzle rather than erroring.
        console.error(`daily-puzzle ${mode} ${dateKey}: cache read failed:`, e);
        return { data: fallbackPuzzle(mode, parseDateKey(dateKey)), source: 'fallback' };
    }

    const { data, source } = await generateForMode(mode, dateKey);

    try {
        const created = await prisma.dailyPuzzle.create({
            data: { gameMode: mode, dateKey, source, data: data as object },
            select: { data: true, source: true },
        });
        return { data: created.data as unknown as AnyPuzzle, source: created.source };
    } catch (e) {
        // Another request won the race — read and return the winning row so the
        // day stays identical for everyone.
        if (isUniqueConflict(e)) {
            const row = await prisma.dailyPuzzle
                .findUnique({
                    where: { gameMode_dateKey: { gameMode: mode, dateKey } },
                    select: { data: true, source: true },
                })
                .catch(() => null);
            if (row) return { data: row.data as unknown as AnyPuzzle, source: row.source };
        } else {
            console.error(`daily-puzzle ${mode} ${dateKey}: cache write failed:`, e);
        }
        // Persistence failed but we still have a valid puzzle to serve.
        return { data, source };
    }
}
