/**
 * Slice It — importing charts from other games (`C9`).
 *
 * Every chart in the library is generated by our own analyser, so two decades
 * of community charting is unreachable. These parsers map `.osu` (osu!mania),
 * `.sm`/`.ssc` (StepMania) and `.chart` (Clone Hero / Moonscraper) onto
 * {@link Slice}.
 *
 * ## What an import is NOT allowed to do
 *
 * An imported chart is **marked as a conversion and stays out of the ranked
 * pool** unless a human verifies it. Two reasons, and only one of them is about
 * quality: a converted chart's note times come from someone else's timing
 * assumptions against someone else's audio file, and the uploader supplies the
 * audio here — so a chart that is perfect against the original release can be
 * systematically 40 ms out against a different master of the same song. That is
 * invisible to everyone except the leaderboard.
 *
 * ## Lane folding
 *
 * Slice It is two lanes. Every source format has more. Folding is lossy by
 * definition, and the honest thing is to do it in one documented place rather
 * than letting each parser invent its own — see {@link foldLanes}.
 *
 * Pure and browser-free, so the upload route and a future client-side preview
 * run the same parser.
 */

import type { Slice } from '../types';

export type ImportSource = 'osu' | 'stepmania' | 'chart';

export interface ImportedChart {
  source: ImportSource;
  /** Key count in the SOURCE format, before folding. */
  keys: number;
  /** Difficulty name as the source called it — metadata, not our vocabulary. */
  name: string;
  title?: string;
  artist?: string;
  /** Seconds. The source's own offset, already applied to `notes`. */
  notes: Slice[];
  /** Non-fatal things a human should know about this conversion. */
  warnings: string[];
}

export class ImportError extends Error {}

/**
 * Fold an N-key chart onto two lanes.
 *
 * **By position, not round-robin.** The left half of the source playfield
 * becomes lane 0 and the right half lane 1, so a chart's left-hand and
 * right-hand patterns stay on the hands that played them. Round-robin (`column
 * % 2`) is simpler and destroys exactly that: an alternating 4K stream folds to
 * a jack, which is unplayable and reads as the import being broken.
 *
 * The odd-column case (5K, 7K) puts the middle column on lane 0. Arbitrary, but
 * it has to be one of them and consistency beats cleverness.
 */
export function foldLanes(column: number, keys: number): number {
  if (keys <= 1) return 0;
  return column < Math.ceil(keys / 2) ? 0 : 1;
}

/**
 * Drop notes that folded onto the same lane at the same instant.
 *
 * Folding turns a source chord into two notes on one lane at gap zero, which
 * the engine's per-lane input debounce makes literally unhittable. Keeping the
 * first is the only defensible choice: dropping both loses the beat, and moving
 * one changes the rhythm the charter wrote.
 *
 * Returns the surviving notes and how many were dropped, because "this import
 * lost 340 notes" is something the uploader has to be told rather than
 * discover.
 */
export function dedupeFolded(
  notes: Slice[],
  minGapSeconds: number,
): { notes: Slice[]; dropped: number } {
  const sorted = [...notes].sort((a, b) => a.time - b.time || a.lane - b.lane);
  const lastByLane = [-Infinity, -Infinity];
  const kept: Slice[] = [];
  let dropped = 0;
  for (const note of sorted) {
    if (note.time - lastByLane[note.lane] < minGapSeconds) {
      dropped++;
      continue;
    }
    lastByLane[note.lane] = note.time;
    kept.push(note);
  }
  return { notes: kept, dropped };
}

/**
 * The lines inside a bracketed section.
 *
 * Shared by the `.osu` and `.chart` parsers because both use the same
 * `[Section]` … next-`[Section]` shape — `.osu` runs to the next header,
 * `.chart` wraps its body in braces, and stripping bare `{`/`}` lines makes one
 * scanner serve both. Anything before the first header is not in any section
 * and is skipped.
 */
function sectionLines(text: string, name: string): string[] {
  const out: string[] = [];
  let inside = false;
  for (const raw of text.split(/\r?\n/)) {
    const line = raw.trim();
    if (/^\[.+\]$/.test(line)) {
      inside = line === `[${name}]`;
      continue;
    }
    if (!inside) continue;
    if (line === '{' || line === '}' || line.length === 0) continue;
    out.push(line);
  }
  return out;
}

/** Detect the format from the file's own content, never from its extension. */
export function detectFormat(text: string): ImportSource | null {
  if (/^\s*osu file format v\d+/m.test(text)) return 'osu';
  if (/^\s*#NOTES\s*:/m.test(text) || /^\s*#BPMS\s*:/m.test(text)) return 'stepmania';
  if (/^\s*\[Song\]/m.test(text) && /^\s*\[SyncTrack\]/m.test(text)) return 'chart';
  return null;
}

/* ─── osu!mania ──────────────────────────────────────────────────────────── */

/**
 * `.osu`, osu!mania mode only.
 *
 * The column formula is the part worth getting right: osu!'s playfield is
 * **512 units wide regardless of key count**, so column = `floor(x * keys /
 * 512)`. Getting it wrong shifts every note by one lane, which reads as "the
 * import is bad" rather than "the constant is".
 */
export function parseOsu(text: string): ImportedChart {
  const mode = Number(/^Mode:\s*(\d+)/m.exec(text)?.[1] ?? '0');
  // Mode 3 is mania. Taiko and catch have no column concept at all, and
  // standard's x/y are positions on a circle — importing either would produce
  // note times attached to meaningless lanes.
  if (mode !== 3) {
    throw new ImportError('Only osu!mania charts (Mode: 3) can be imported.');
  }

  const keys = Math.max(1, Math.round(Number(/^CircleSize:\s*([\d.]+)/m.exec(text)?.[1] ?? '4')));
  const warnings: string[] = [];
  const notes: Slice[] = [];

  for (const line of sectionLines(text, 'HitObjects')) {
    const parts = line.split(',');
    if (parts.length < 5) continue;
    const x = Number(parts[0]);
    const time = Number(parts[2]);
    const type = Number(parts[3]);
    if (!Number.isFinite(x) || !Number.isFinite(time)) continue;

    const column = Math.min(keys - 1, Math.max(0, Math.floor((x * keys) / 512)));
    const isHold = (type & 128) !== 0;

    let duration: number | undefined;
    if (isHold) {
      // The hold end is the first colon-separated field of the last comma
      // field: `endTime:hitSample`.
      const end = Number(parts[5]?.split(':')[0]);
      if (Number.isFinite(end) && end > time) duration = (end - time) / 1000;
    }

    notes.push({
      id: `osu${notes.length}`,
      time: time / 1000,
      lane: foldLanes(column, keys),
      type: duration !== undefined ? 'LONG' : 'STANDARD',
      ...(duration !== undefined ? { duration } : {}),
    });
  }

  if (notes.length === 0) throw new ImportError('No hit objects found in that .osu file.');
  if (keys > 2) warnings.push(`Folded ${keys} columns onto 2 lanes.`);

  return {
    source: 'osu',
    keys,
    name: /^Version:\s*(.+)$/m.exec(text)?.[1]?.trim() || 'Imported',
    title: /^Title:\s*(.+)$/m.exec(text)?.[1]?.trim(),
    artist: /^Artist:\s*(.+)$/m.exec(text)?.[1]?.trim(),
    notes: notes.sort((a, b) => a.time - b.time),
    warnings,
  };
}

/* ─── StepMania ──────────────────────────────────────────────────────────── */

/**
 * `.sm` / `.ssc`, first chart only.
 *
 * StepMania's format is measures of rows, so a note's time is derived from the
 * BPM map rather than stated — which means the BPM parse is not optional
 * decoration, it IS the timing. A chart imported with a missing or wrong BPM
 * list is not "slightly off"; it drifts unboundedly.
 *
 * Only the first `#NOTES` block is read. Importing all of them would mean
 * deciding which of five StepMania difficulties maps onto which of our four,
 * and that is a judgement the uploader should make one chart at a time.
 */
export function parseStepMania(text: string): ImportedChart {
  const bpms = parseBpms(text);
  if (bpms.length === 0) throw new ImportError('That file has no #BPMS, so notes cannot be timed.');

  // `#OFFSET` is the seconds from the audio start to beat 0. StepMania's sign
  // convention is inverted from what "offset" suggests: a positive value means
  // the chart starts EARLIER than the audio, so it is subtracted.
  const offset = Number(/#OFFSET:\s*(-?[\d.]+)\s*;/.exec(text)?.[1] ?? '0');

  const block = /#NOTES\s*:([\s\S]*?);/.exec(text);
  if (!block) throw new ImportError('That file has no #NOTES block.');

  // The header is 5 colon-separated fields (type, author, difficulty, meter,
  // groove radar), then the measure data.
  const fields = block[1].split(':');
  const name = (fields[2] ?? '').trim() || 'Imported';
  const body = fields.slice(5).join(':');

  const notes: Slice[] = [];
  const holdOpen = new Map<number, number>();
  const warnings: string[] = [];
  let keys = 4;

  const measures = body
    .split(',')
    .map((measure) =>
      measure
        .split('\n')
        .map((row) => row.trim())
        .filter((row) => row.length > 0 && !row.startsWith('//')),
    )
    .filter((rows) => rows.length > 0);

  for (let m = 0; m < measures.length; m++) {
    const rows = measures[m];
    for (let r = 0; r < rows.length; r++) {
      const row = rows[r];
      keys = Math.max(keys, row.length);
      // A measure is 4 beats, subdivided by however many rows it has.
      const beat = m * 4 + (r / rows.length) * 4;
      for (let column = 0; column < row.length; column++) {
        const symbol = row[column];
        if (symbol === '0' || symbol === 'M') continue; // empty, or a mine
        const time = beatToSeconds(beat, bpms) - offset;

        if (symbol === '2' || symbol === '4') {
          // Hold / roll head. Both become a LONG note; the roll's re-tap
          // requirement has no equivalent here, and pretending otherwise would
          // make rolls unclearable.
          holdOpen.set(column, time);
          if (symbol === '4') warnings.push('Rolls were converted to holds.');
          continue;
        }
        if (symbol === '3') {
          const start = holdOpen.get(column);
          holdOpen.delete(column);
          if (start === undefined) continue; // tail with no head: malformed
          notes.push({
            id: `sm${notes.length}`,
            time: start,
            lane: foldLanes(column, row.length),
            type: 'LONG',
            duration: Math.max(0.05, time - start),
          });
          continue;
        }
        // '1' and anything else printable is a tap.
        notes.push({
          id: `sm${notes.length}`,
          time,
          lane: foldLanes(column, row.length),
          type: 'STANDARD',
        });
      }
    }
  }

  if (notes.length === 0) throw new ImportError('No notes found in that file.');
  if (keys > 2) warnings.push(`Folded ${keys} columns onto 2 lanes.`);

  return {
    source: 'stepmania',
    keys,
    name,
    title: /#TITLE:\s*(.*?)\s*;/.exec(text)?.[1],
    artist: /#ARTIST:\s*(.*?)\s*;/.exec(text)?.[1],
    notes: notes.sort((a, b) => a.time - b.time),
    warnings: [...new Set(warnings)],
  };
}

interface BpmPoint {
  beat: number;
  bpm: number;
}

function parseBpms(text: string): BpmPoint[] {
  const raw = /#BPMS:\s*([\s\S]*?);/.exec(text)?.[1];
  if (!raw) return [];
  const points: BpmPoint[] = [];
  for (const entry of raw.split(',')) {
    const [beat, bpm] = entry.split('=').map((value) => Number(value.trim()));
    if (Number.isFinite(beat) && Number.isFinite(bpm) && bpm > 0) points.push({ beat, bpm });
  }
  return points.sort((a, b) => a.beat - b.beat);
}

/**
 * Beat → seconds through a BPM map.
 *
 * Walks the segments rather than assuming one tempo, because a StepMania chart
 * with a mid-song BPM change is common and treating it as constant makes every
 * note after the change wrong by a growing amount.
 */
export function beatToSeconds(beat: number, bpms: BpmPoint[]): number {
  if (bpms.length === 0) return 0;
  let seconds = 0;
  let cursor = bpms[0].beat;
  let bpm = bpms[0].bpm;
  for (let i = 1; i < bpms.length && bpms[i].beat < beat; i++) {
    seconds += ((bpms[i].beat - cursor) * 60) / bpm;
    cursor = bpms[i].beat;
    bpm = bpms[i].bpm;
  }
  return seconds + ((beat - cursor) * 60) / bpm;
}

/* ─── Clone Hero / Moonscraper ───────────────────────────────────────────── */

/**
 * `.chart`.
 *
 * Positions are in ticks against a `Resolution` (ticks per quarter note) stated
 * in `[Song]`, with tempo changes in `[SyncTrack]` as `B` events in
 * thousandths of a BPM. Everything else in the file is guitar-specific and
 * ignored.
 */
export function parseChart(text: string): ImportedChart {
  const resolution = Number(/Resolution\s*=\s*(\d+)/.exec(text)?.[1] ?? '192');
  if (!Number.isFinite(resolution) || resolution <= 0) {
    throw new ImportError('That .chart file has no usable Resolution.');
  }

  // `B` events: tick → BPM×1000. Converted to a beat-indexed map so the same
  // walker as StepMania times them.
  const tempos: BpmPoint[] = [];
  for (const line of sectionLines(text, 'SyncTrack')) {
    const match = /^(\d+)\s*=\s*B\s+(\d+)/.exec(line.trim());
    if (!match) continue;
    tempos.push({ beat: Number(match[1]) / resolution, bpm: Number(match[2]) / 1000 });
  }
  if (tempos.length === 0) tempos.push({ beat: 0, bpm: 120 });
  tempos.sort((a, b) => a.beat - b.beat);

  // The first note track present, in descending difficulty. Expert is the
  // densest and therefore the most useful source for a fold.
  const trackName = ['ExpertSingle', 'HardSingle', 'MediumSingle', 'EasySingle'].find(
    (name) => sectionLines(text, name).length > 0,
  );
  if (!trackName) throw new ImportError('No note track found in that .chart file.');

  const notes: Slice[] = [];
  const warnings: string[] = [];
  // Five frets, plus 7 = open. Open notes have no column, so they land on lane
  // 0 rather than being dropped — an open strum is a beat the chart intends.
  const KEYS = 5;

  for (const line of sectionLines(text, trackName)) {
    const match = /^(\d+)\s*=\s*N\s+(\d+)\s+(\d+)/.exec(line.trim());
    if (!match) continue;
    const fret = Number(match[2]);
    // 5 and 6 are the force/tap modifier flags, not notes.
    if (fret === 5 || fret === 6) continue;

    const beat = Number(match[1]) / resolution;
    const sustainBeats = Number(match[3]) / resolution;
    const time = beatToSeconds(beat, tempos);
    const duration =
      sustainBeats > 0 ? beatToSeconds(beat + sustainBeats, tempos) - time : undefined;

    notes.push({
      id: `ch${notes.length}`,
      time,
      lane: fret === 7 ? 0 : foldLanes(fret, KEYS),
      type: duration !== undefined && duration > 0.05 ? 'LONG' : 'STANDARD',
      ...(duration !== undefined && duration > 0.05 ? { duration } : {}),
    });
  }

  if (notes.length === 0) throw new ImportError('No notes found in that .chart file.');
  warnings.push('Folded 5 frets onto 2 lanes.');

  return {
    source: 'chart',
    keys: KEYS,
    name: trackName,
    title: /Name\s*=\s*"(.*?)"/.exec(text)?.[1],
    artist: /Artist\s*=\s*"(.*?)"/.exec(text)?.[1],
    notes: notes.sort((a, b) => a.time - b.time),
    warnings,
  };
}

/* ─── Entry point ────────────────────────────────────────────────────────── */

/**
 * Parse whatever this is, fold it, and report what the fold cost.
 *
 * `minGapSeconds` should be the engine's own per-lane input cooldown: a note
 * closer than that to the previous one in the same lane cannot be hit at all,
 * and folding is the operation that creates them.
 */
export function importChart(text: string, minGapSeconds: number): ImportedChart {
  const format = detectFormat(text);
  if (!format) throw new ImportError('That file is not a recognised chart format.');

  const parsed =
    format === 'osu'
      ? parseOsu(text)
      : format === 'stepmania'
        ? parseStepMania(text)
        : parseChart(text);

  const { notes, dropped } = dedupeFolded(parsed.notes, minGapSeconds);
  const warnings = [...parsed.warnings];
  if (dropped > 0) {
    warnings.push(`${dropped} notes were unhittable after folding and were dropped.`);
  }
  // Ids are reassigned AFTER the drop so they are dense and sequential; a chart
  // whose ids have holes in it is fine but confuses every diff of it.
  return {
    ...parsed,
    notes: notes.map((note, index) => ({ ...note, id: `i${index}` })),
    warnings,
  };
}
