/**
 * RMHHomes — AI listing-image generation API.
 *
 * POST /api/homes/ai-image  { prompt }  → { url }
 *
 * Auth-gated and tightly rate-limited (each call is a paid xAI generation).
 * Returns the stored image URL; the client adds it to the listing's photos and
 * marks it AI-generated so the "Generated by AI" disclaimer shows.
 */
import { createFileRoute } from '@tanstack/react-router';
import { z } from 'zod';
import { auth } from '@/lib/auth';
import { rateLimit, getClientIp } from '@/lib/rate-limit';
import { generateListingImage, isListingImageAIConfigured } from '@/lib/homes/ai-image.server';

const schema = z.object({ prompt: z.string().min(1).max(500) });

export const Route = createFileRoute('/api/homes/ai-image')({
  server: {
    handlers: {
      GET: async ({ request }) => {
        // Lets the UI hide the AI button when the feature is unconfigured.
        const session = await auth.api.getSession({ headers: request.headers });
        if (!session) return Response.json({ error: 'Unauthorized' }, { status: 401 });
        return Response.json({ available: isListingImageAIConfigured() });
      },

      POST: async ({ request }) => {
        try {
          const session = await auth.api.getSession({ headers: request.headers });
          if (!session) return Response.json({ error: 'Unauthorized' }, { status: 401 });

          const ip = getClientIp(request);
          const { allowed, retryAfter } = rateLimit(ip, {
            limit: 10,
            windowMs: 60_000,
            prefix: 'homes-ai-image',
          });
          if (!allowed) {
            return Response.json(
              { error: 'Slow down — too many image generations.' },
              { status: 429, headers: { 'Retry-After': String(retryAfter) } },
            );
          }

          const parsed = schema.safeParse(await request.json());
          if (!parsed.success) {
            return Response.json({ error: 'Enter a description to generate.' }, { status: 400 });
          }

          const result = await generateListingImage(session.user.id, parsed.data.prompt);
          if ('error' in result) {
            return Response.json({ error: result.error }, { status: 502 });
          }
          return Response.json({ url: result.url });
        } catch (error) {
          console.error('Homes ai-image error:', error);
          return Response.json({ error: 'Could not generate an image.' }, { status: 500 });
        }
      },
    },
  },
});
