// pet_image.go generates a picture of Alex in his current life-stage + mood using
// the xAI (Grok) image API — the same provider and shared daily spend budget as
// the bot-worker's feed images. The generated bytes are attached to the Discord
// message directly (attachment://alex.png), so there is no dependency on a
// public object-storage URL.
//
// Cost is controlled three ways: (1) an in-memory per-guild cache keyed by
// stage+mood (identical requests never re-generate), (2) the global
// image_gen_budget daily cap (shared with the bot-worker), and (3) a per-guild
// cooldown enforced by the service. Returns an error on ANY failure so a missing
// key / over-budget / API hiccup degrades to "stats only, no picture" rather than
// breaking the command.
package discordbot

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/rmhstudios/rmh-go/pkg/log"
)

const (
	alexXAIBaseURL      = "https://api.x.ai/v1"
	alexDefaultXAIModel = "grok-imagine-image"
	alexImageCacheTTL   = 24 * time.Hour // reuse a stage+mood image for up to a day
)

// alexImage is a generated (or cached) picture ready to attach to a message.
type alexImage struct {
	Bytes    []byte
	Ext      string // ".png" / ".jpg" / ...
	Filename string // e.g. "alex.png"
}

type cachedAlexImage struct {
	key string // stage:mood:genN
	img *alexImage
	at  time.Time
}

// alexImager turns pet state into an image.
type alexImager struct {
	apiKey string
	model  string
	repo   *petRepo // for the shared budget reservation
	http   *http.Client
	logger *log.Logger

	mu    sync.Mutex
	cache map[string]cachedAlexImage // keyed by guildId
}

func newAlexImager(repo *petRepo, logger *log.Logger) *alexImager {
	model := os.Getenv("XAI_IMAGE_MODEL")
	if model == "" {
		model = alexDefaultXAIModel
	}
	return &alexImager{
		apiKey: os.Getenv("XAI_API_KEY"),
		model:  model,
		repo:   repo,
		http:   &http.Client{Timeout: 60 * time.Second},
		logger: logger,
		cache:  make(map[string]cachedAlexImage),
	}
}

// configured reports whether a key is set and the image kill switch is off.
func (g *alexImager) configured() bool {
	return g.apiKey != "" && os.Getenv("XAI_IMAGE_ENABLED") != "false"
}

// cacheKey identifies a unique look: stage + mood + generation (a new life gets
// fresh art even at the same stage/mood).
func cacheKey(p *PetState, mood Mood) string {
	return string(p.LifeStage) + ":" + mood.Key + ":g" + strconv.Itoa(p.Generation)
}

// cached returns a fresh cached image for the pet's current look, if any.
func (g *alexImager) cached(p *PetState, mood Mood, now time.Time) (*alexImage, bool) {
	key := cacheKey(p, mood)
	g.mu.Lock()
	defer g.mu.Unlock()
	c, ok := g.cache[p.GuildID]
	if ok && c.key == key && now.Sub(c.at) < alexImageCacheTTL {
		return c.img, true
	}
	return nil, false
}

func (g *alexImager) store(guildID, key string, img *alexImage, now time.Time) {
	g.mu.Lock()
	g.cache[guildID] = cachedAlexImage{key: key, img: img, at: now}
	g.mu.Unlock()
}

// generate returns an image of Alex's current look, using the cache when possible
// and otherwise calling xAI (reserving budget first). Returns an error on any
// failure; the caller should fall back to a text/stats-only response.
func (g *alexImager) generate(ctx context.Context, p *PetState, mood Mood, now time.Time) (*alexImage, error) {
	if img, ok := g.cached(p, mood, now); ok {
		return img, nil
	}
	if !g.configured() {
		return nil, fmt.Errorf("image generation not configured")
	}

	ok, err := g.repo.reserveImageBudget(ctx, now.UTC().Format("2006-01-02"), imageDailyCapEnv())
	if err != nil || !ok {
		return nil, fmt.Errorf("image budget unavailable")
	}

	prompt := buildAlexImagePrompt(p, mood)
	url, err := g.requestImage(ctx, prompt)
	if err != nil || url == "" {
		return nil, fmt.Errorf("xai request failed: %w", err)
	}
	raw, err := g.download(ctx, url)
	if err != nil || len(raw) == 0 {
		return nil, fmt.Errorf("image download failed: %w", err)
	}
	ext := detectAlexImageExt(raw)
	if ext == "" {
		return nil, fmt.Errorf("unrecognized image bytes")
	}

	img := &alexImage{Bytes: raw, Ext: ext, Filename: "alex" + ext}
	g.store(p.GuildID, cacheKey(p, mood), img, now)
	return img, nil
}

// imageDailyCapEnv resolves XAI_IMAGE_DAILY_CAP (default 50).
func imageDailyCapEnv() int {
	if n, err := strconv.Atoi(os.Getenv("XAI_IMAGE_DAILY_CAP")); err == nil && n > 0 {
		return n
	}
	return 50
}

// requestImage POSTs to xAI images.generate and returns the first URL.
func (g *alexImager) requestImage(ctx context.Context, prompt string) (string, error) {
	body, err := json.Marshal(struct {
		Model  string `json:"model"`
		Prompt string `json:"prompt"`
		N      int    `json:"n"`
	}{Model: g.model, Prompt: prompt, N: 1})
	if err != nil {
		return "", err
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, alexXAIBaseURL+"/images/generations", bytes.NewReader(body))
	if err != nil {
		return "", err
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", "Bearer "+g.apiKey)

	resp, err := g.http.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()
	data, err := io.ReadAll(io.LimitReader(resp.Body, 1<<20))
	if err != nil {
		return "", err
	}
	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		return "", fmt.Errorf("xai HTTP %d", resp.StatusCode)
	}
	var parsed struct {
		Data []struct {
			URL string `json:"url"`
		} `json:"data"`
	}
	if err := json.Unmarshal(data, &parsed); err != nil {
		return "", err
	}
	if len(parsed.Data) == 0 {
		return "", nil
	}
	return parsed.Data[0].URL, nil
}

// download fetches the generated image bytes (capped at 10 MB).
func (g *alexImager) download(ctx context.Context, url string) ([]byte, error) {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, url, nil)
	if err != nil {
		return nil, err
	}
	resp, err := g.http.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		return nil, fmt.Errorf("download HTTP %d", resp.StatusCode)
	}
	return io.ReadAll(io.LimitReader(resp.Body, 10<<20))
}

// ─── Prompt construction ────────────────────────────────────────────────

// stagePromptDescriptor describes how Alex looks at each life stage.
var stagePromptDescriptor = map[LifeStage]string{
	StageInfant:  "a chubby-cheeked BABY version, big round sparkly eyes, a tiny tuft of black hair, wearing a cozy onesie, cradling a baby bottle filled with boba",
	StageToddler: "an adorable TODDLER with messy black hair, wearing an oversized hoodie, clutching a tiny tablet",
	StageChild:   "a cheerful KID around 8 years old, black bowl-cut hair, graphic tee, little backpack",
	StageTeen:    "a lanky TEENAGER with a black hair fade, hoodie and AirPods, scrolling a phone",
	StageAdult:   "a 21-year-old college tech-intern with a clean black hair fade, wearing a startup hoodie with a conference lanyard, holding a boba tea",
}

// moodPromptDescriptor describes Alex's expression/pose for the current mood.
var moodPromptDescriptor = map[string]string{
	"thriving": "beaming with a big confident smile, radiating positive energy, sparkles around him",
	"chillin":  "relaxed and content, easy smile, sipping boba",
	"hungry":   "looking hungry with a rumbling tummy, holding an empty boba cup upside down, pleading eyes",
	"sleepy":   "mid-yawn with sleepy droopy eyes, rubbing one eye, little Zzz floating",
	"stinky":   "looking disheveled and grimy with a small green stink cloud, hair a mess",
	"sad":      "looking sad and lonely with teary puppy-dog eyes",
	"sick":     "looking pale and sick with a thermometer in his mouth and a sweat drop, ice pack on head",
	"gone":     "drawn as a cute little friendly ghost with swirly X eyes, floating",
}

// buildAlexImagePrompt assembles the full text-to-image prompt from the pet's
// stage and mood. Kept fully descriptive (no user text) so it's safe and stable.
func buildAlexImagePrompt(p *PetState, mood Mood) string {
	stage := stagePromptDescriptor[p.LifeStage]
	if stage == "" {
		stage = stagePromptDescriptor[StageAdult]
	}
	expr := moodPromptDescriptor[mood.Key]
	if expr == "" {
		expr = moodPromptDescriptor["chillin"]
	}
	var b strings.Builder
	b.WriteString("Cute chibi digital illustration in a wholesome virtual-pet / Tamagotchi art style of Alex Wu, ")
	b.WriteString("an Asian-American Gen-Z computer-science student and tech intern who is obsessed with boba tea. ")
	b.WriteString("Depict him as ")
	b.WriteString(stage)
	b.WriteString(", ")
	b.WriteString(expr)
	b.WriteString(". Single centered character, full body, expressive, vibrant saturated colors, ")
	b.WriteString("soft studio lighting, clean simple pastel gradient background, thick clean outlines. ")
	b.WriteString("No text, no words, no letters, no logos in the image.")
	return b.String()
}

// ─── Image magic-byte validation (mirrors botworker) ───────────────────

func detectAlexImageExt(buf []byte) string {
	switch {
	case len(buf) >= 3 && buf[0] == 0xFF && buf[1] == 0xD8 && buf[2] == 0xFF:
		return ".jpg"
	case len(buf) >= 8 && bytes.Equal(buf[:8], []byte{0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A}):
		return ".png"
	case len(buf) >= 4 && string(buf[:4]) == "GIF8":
		return ".gif"
	case len(buf) >= 12 && string(buf[:4]) == "RIFF" && string(buf[8:12]) == "WEBP":
		return ".webp"
	default:
		return ""
	}
}
