allowBuilds:
  '@prisma/engines': set this to true or false
  core-js: set this to true or false
  es5-ext: set this to true or false
  esbuild: set this to true or false
  prisma: set this to true or false
  sharp: set this to true or false

ignoredBuiltDependencies:
  - '@prisma/engines'
  - prisma
  - sharp
  - unrs-resolver

onlyBuiltDependencies:
  - esbuild
  - '@swc/core'
