/**
 * Site knowledge retrieval for the AI Concierge (§11), server-only.
 *
 * Loads `data/site-knowledge.json` (generated by
 * `scripts/build-site-knowledge.ts`) and ranks entries against a query with a
 * simple keyword-overlap score — tokenize both sides, weight matches in the
 * title/tags above matches in the body. Deliberately NO vector DB / embeddings:
 * the corpus is ~60 short entries, so lexical overlap is plenty and free.
 */

import { readFileSync } from 'node:fs';
import { join } from 'node:path';

export interface KnowledgeEntry {
  id: string;
  kind: 'game' | 'app' | 'help';
  title: string;
  tags: string[];
  route?: string;
  players?: string;
  text: string;
}

interface IndexedEntry {
  entry: KnowledgeEntry;
  titleTokens: Set<string>;
  tagTokens: Set<string>;
  bodyTokens: Set<string>;
}

// Very small stopword list — enough to stop "how do i" style filler from
// dominating the overlap score.
const STOPWORDS = new Set([
  'the', 'a', 'an', 'and', 'or', 'to', 'of', 'in', 'on', 'for', 'is', 'are', 'do', 'does',
  'how', 'what', 'where', 'when', 'can', 'i', 'my', 'me', 'you', 'your', 'it', 'this', 'that',
  'with', 'at', 'be', 'get', 'find', 'use', 'am',
]);

function tokenize(value: string): string[] {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, ' ')
    .split(/\s+/)
    .filter((t) => t.length >= 2 && !STOPWORDS.has(t));
}

let indexCache: IndexedEntry[] | null = null;

function loadIndex(): IndexedEntry[] {
  if (indexCache) return indexCache;
  let entries: KnowledgeEntry[] = [];
  try {
    const raw = readFileSync(join(process.cwd(), 'data', 'site-knowledge.json'), 'utf8');
    const parsed = JSON.parse(raw) as { entries?: KnowledgeEntry[] };
    entries = Array.isArray(parsed.entries) ? parsed.entries : [];
  } catch (error) {
    console.error('[assistant] failed to load site-knowledge.json:', error instanceof Error ? error.message : error);
    entries = [];
  }
  indexCache = entries.map((entry) => ({
    entry,
    titleTokens: new Set(tokenize(entry.title)),
    tagTokens: new Set(entry.tags.flatMap(tokenize)),
    bodyTokens: new Set(tokenize(entry.text)),
  }));
  return indexCache;
}

/**
 * Return the top-`k` knowledge entries for `query`, ranked by weighted keyword
 * overlap. Returns the corpus head (help entries first) for an empty/blank
 * query so the model always has some grounding context.
 */
export function searchKnowledge(query: string, k = 6): KnowledgeEntry[] {
  const index = loadIndex();
  const terms = tokenize(query);
  if (terms.length === 0) return index.slice(0, k).map((i) => i.entry);

  const scored = index.map((item) => {
    let score = 0;
    for (const term of terms) {
      if (item.titleTokens.has(term)) score += 5;
      if (item.tagTokens.has(term)) score += 4;
      if (item.bodyTokens.has(term)) score += 1;
    }
    // Small boost for exact title substring matches ("temple of joy").
    if (item.entry.title.toLowerCase().includes(query.trim().toLowerCase())) score += 6;
    return { entry: item.entry, score };
  });

  return scored
    .filter((s) => s.score > 0)
    .sort((a, b) => b.score - a.score)
    .slice(0, k)
    .map((s) => s.entry);
}
