import { CDN_BASE } from "./asset";

export const FEED_IMAGE_PREFIX = "rmharks/";

const SAFE_FILENAME_RE = /^[A-Za-z0-9._-]+$/;

export function isSafeFilename(name: string): boolean {
  if (!name || name === "." || name === "..") return false;
  return SAFE_FILENAME_RE.test(name);
}

const CONTENT_TYPES: Record<string, string> = {
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".webp": "image/webp",
  ".gif": "image/gif",
};

export function contentTypeForFilename(filename: string): string {
  const dot = filename.lastIndexOf(".");
  const ext = dot >= 0 ? filename.slice(dot).toLowerCase() : "";
  return CONTENT_TYPES[ext] ?? "application/octet-stream";
}

export function feedImageKey(filename: string): string {
  return `${FEED_IMAGE_PREFIX}${filename}`;
}

export function feedImageUrl(filename: string): string {
  // With R2 + a public CDN domain configured, serve feed images straight from
  // the edge. Otherwise (local dev / MinIO) fall back to the Node proxy route,
  // which streams the object out of object storage.
  return CDN_BASE
    ? `${CDN_BASE}/${feedImageKey(filename)}`
    : `/api/feed/image/${filename}`;
}

// AI-generated persona avatars live in their own namespace so they're never
// confused with user-posted feed images (different ownership/serving rules).
export const PERSONA_AVATAR_PREFIX = "personas/avatars/";

export function personaAvatarKey(filename: string): string {
  return `${PERSONA_AVATAR_PREFIX}${filename}`;
}

export function personaAvatarUrl(filename: string): string {
  // Same CDN-vs-proxy split as feed images: serve from the edge when a public
  // CDN domain is set, else through the Node proxy route that streams from
  // object storage (see app/routes/api/personas/avatar/$filename.ts).
  return CDN_BASE
    ? `${CDN_BASE}/${personaAvatarKey(filename)}`
    : `/api/personas/avatar/${filename}`;
}

// User-uploaded profile avatars. Migrated off local disk (db/avatars) to object
// storage so the VPS disk can be reclaimed; served from the CDN in prod.
export const USER_AVATAR_PREFIX = "user-avatars/";

export function userAvatarKey(filename: string): string {
  return `${USER_AVATAR_PREFIX}${filename}`;
}

export function userAvatarUrl(filename: string): string {
  // Same CDN-vs-proxy split as feed images / persona avatars. The proxy route
  // (app/routes/api/profile/avatar/$filename.ts) streams from object storage in
  // dev / no-CDN; prod points straight at cdn.rmhstudios.com.
  return CDN_BASE
    ? `${CDN_BASE}/${userAvatarKey(filename)}`
    : `/api/profile/avatar/${filename}`;
}

// Vibe-page gallery thumbnails. Rendered by the vibe-worker (Go) / the Node
// screenshot fallback, stored as WebP in object storage so the db/ volume can be
// reclaimed; served from the CDN in prod.
export const VIBE_THUMB_PREFIX = "vibe-thumbs/";

export function vibeThumbKey(slug: string): string {
  return `${VIBE_THUMB_PREFIX}${slug}.webp`;
}

export function vibeThumbUrl(slug: string, version: number | string): string {
  // CDN-vs-proxy split. The `?v=` cache-buster lets us serve immutably while a
  // re-render still busts the edge/browser cache.
  return CDN_BASE
    ? `${CDN_BASE}/${vibeThumbKey(slug)}?v=${version}`
    : `/api/vibe/thumb/${slug}?v=${version}`;
}

// Wide promotional store covers for games/apps/builds — custom aspect-ratio
// key-art generated by xAI (see scripts/generate-build-covers.ts), stored as
// WebP and served from the CDN. Keyed by build id + ratio so a new ratio is a
// new object (never overwrites an existing cover).
export const BUILD_COVER_PREFIX = "build-covers/";

export function buildCoverKey(id: string, ratio: string): string {
  return `${BUILD_COVER_PREFIX}${id}-${ratio}.webp`;
}

/**
 * Public URL for a build cover. Served straight from the CDN in prod; falls
 * back to the Node proxy route (which streams the object out of storage) when
 * no CDN origin is configured — so covers work on plain S3/R2 too.
 */
export function buildCoverUrl(id: string, ratio: string): string {
  return CDN_BASE
    ? `${CDN_BASE}/${buildCoverKey(id, ratio)}`
    : `/api/builds/cover/${id}-${ratio}.webp`;
}

/**
 * Extract the safe filename from a stored avatar URL, or null. Accepts every
 * form the app has produced over time:
 *  - the Node proxy path `/api/profile/avatar/<filename>` (dev / no CDN, and the
 *    legacy local-disk form), and
 *  - the public CDN URL `<CDN_BASE>/user-avatars/<filename>` (R2 + CDN).
 */
export function userAvatarFilename(url: string): string | null {
  const localPrefix = "/api/profile/avatar/";
  if (url.startsWith(localPrefix)) {
    const f = url.slice(localPrefix.length);
    return isSafeFilename(f) ? f : null;
  }
  if (CDN_BASE) {
    const cdnPrefix = `${CDN_BASE}/${USER_AVATAR_PREFIX}`;
    if (url.startsWith(cdnPrefix)) {
      const f = url.slice(cdnPrefix.length);
      return isSafeFilename(f) ? f : null;
    }
  }
  return null;
}

/**
 * Extract the safe filename from a stored feed-image URL, or null if it isn't
 * one. Accepts both forms the app produces:
 *  - the local Node proxy path `/api/feed/image/<filename>` (dev / no CDN), and
 *  - the public CDN URL `<CDN_BASE>/rmharks/<filename>` (R2 + cdn.rmhstudios.com).
 */
export function feedImageFilename(url: string): string | null {
  const localPrefix = "/api/feed/image/";
  if (url.startsWith(localPrefix)) {
    const f = url.slice(localPrefix.length);
    return isSafeFilename(f) ? f : null;
  }
  if (CDN_BASE) {
    const cdnPrefix = `${CDN_BASE}/${FEED_IMAGE_PREFIX}`;
    if (url.startsWith(cdnPrefix)) {
      const f = url.slice(cdnPrefix.length);
      return isSafeFilename(f) ? f : null;
    }
  }
  return null;
}

/** True if `url` is a valid feed-image URL (either supported form). */
export function isFeedImageUrl(url: string): boolean {
  return feedImageFilename(url) !== null;
}

/** True if a feed image URL's filename belongs to the given user (filename is `<userId>-<ts>-<rand>.<ext>`). */
export function ownsFeedImageUrl(url: string, userId: string): boolean {
  const filename = feedImageFilename(url);
  return filename !== null && filename.startsWith(`${userId}-`);
}
