import type { Word } from './types';

// ─── Word Database ──────────────────────────────────────────────────────────
// 200+ words with full tags for the Versecraft poetry puzzle system.
// Each word has syllable count, part of speech, tag weights (0-1),
// categories, rhyme groups, and stress patterns.

export const WORD_DATABASE: Word[] = [
  // ─── Nature / Light ────────────────────────────────────────────────────────
  { id: 'bloom', text: 'bloom', syllables: 1, partOfSpeech: 'noun', tags: { darkness: 0.1, brightness: 0.9, complexity: 0.2, nature: 0.95, urban: 0.0, abstract: 0.2, concrete: 0.9, emotionIntensity: 0.5, humor: 0.0, sincerity: 0.8 }, categories: ['nature', 'flowers', 'light'], rhymeGroup: 'oom', stressPattern: 'S', isSensory: true },
  { id: 'petal', text: 'petal', syllables: 2, partOfSpeech: 'noun', tags: { darkness: 0.0, brightness: 0.8, complexity: 0.2, nature: 0.95, urban: 0.0, abstract: 0.1, concrete: 1.0, emotionIntensity: 0.3, humor: 0.0, sincerity: 0.7 }, categories: ['nature', 'flowers'], rhymeGroup: 'etal', stressPattern: 'Su' },
  { id: 'willow', text: 'willow', syllables: 2, partOfSpeech: 'noun', tags: { darkness: 0.3, brightness: 0.5, complexity: 0.3, nature: 1.0, urban: 0.0, abstract: 0.2, concrete: 0.9, emotionIntensity: 0.4, humor: 0.0, sincerity: 0.8 }, categories: ['nature', 'solitude'], rhymeGroup: 'illo', stressPattern: 'Su', isMusical: true },
  { id: 'meadow', text: 'meadow', syllables: 2, partOfSpeech: 'noun', tags: { darkness: 0.0, brightness: 0.8, complexity: 0.1, nature: 1.0, urban: 0.0, abstract: 0.1, concrete: 1.0, emotionIntensity: 0.3, humor: 0.0, sincerity: 0.9 }, categories: ['nature', 'light'], rhymeGroup: 'edoh', stressPattern: 'Su' },
  { id: 'dawn', text: 'dawn', syllables: 1, partOfSpeech: 'noun', tags: { darkness: 0.1, brightness: 0.95, complexity: 0.2, nature: 0.7, urban: 0.1, abstract: 0.4, concrete: 0.7, emotionIntensity: 0.5, humor: 0.0, sincerity: 0.9 }, categories: ['light', 'nature', 'warmth'], rhymeGroup: 'awn', stressPattern: 'S' },
  { id: 'ember', text: 'ember', syllables: 2, partOfSpeech: 'noun', tags: { darkness: 0.4, brightness: 0.6, complexity: 0.3, nature: 0.5, urban: 0.1, abstract: 0.3, concrete: 0.8, emotionIntensity: 0.6, humor: 0.0, sincerity: 0.7 }, categories: ['warmth', 'light', 'night'], rhymeGroup: 'ember', stressPattern: 'Su', isSensory: true },
  { id: 'sunlight', text: 'sunlight', syllables: 2, partOfSpeech: 'noun', tags: { darkness: 0.0, brightness: 1.0, complexity: 0.1, nature: 0.8, urban: 0.2, abstract: 0.2, concrete: 0.9, emotionIntensity: 0.4, humor: 0.0, sincerity: 0.8 }, categories: ['light', 'warmth', 'nature'], rhymeGroup: 'ight', stressPattern: 'Su' },
  { id: 'river', text: 'river', syllables: 2, partOfSpeech: 'noun', tags: { darkness: 0.2, brightness: 0.6, complexity: 0.3, nature: 1.0, urban: 0.1, abstract: 0.3, concrete: 0.9, emotionIntensity: 0.4, humor: 0.0, sincerity: 0.8 }, categories: ['nature', 'solitude'], rhymeGroup: 'iver', stressPattern: 'Su', isMusical: true },
  { id: 'garden', text: 'garden', syllables: 2, partOfSpeech: 'noun', tags: { darkness: 0.1, brightness: 0.7, complexity: 0.2, nature: 0.95, urban: 0.2, abstract: 0.1, concrete: 1.0, emotionIntensity: 0.3, humor: 0.0, sincerity: 0.7 }, categories: ['nature', 'flowers'], rhymeGroup: 'arden', stressPattern: 'Su' },
  { id: 'feather', text: 'feather', syllables: 2, partOfSpeech: 'noun', tags: { darkness: 0.1, brightness: 0.7, complexity: 0.2, nature: 0.8, urban: 0.0, abstract: 0.3, concrete: 0.9, emotionIntensity: 0.3, humor: 0.0, sincerity: 0.6 }, categories: ['nature', 'light'], rhymeGroup: 'eather', stressPattern: 'Su', isSensory: true },
  { id: 'blossom', text: 'blossom', syllables: 2, partOfSpeech: 'noun', tags: { darkness: 0.0, brightness: 0.9, complexity: 0.2, nature: 1.0, urban: 0.0, abstract: 0.2, concrete: 0.9, emotionIntensity: 0.5, humor: 0.0, sincerity: 0.8 }, categories: ['nature', 'flowers', 'light'], rhymeGroup: 'ossom', stressPattern: 'Su' },
  { id: 'rain', text: 'rain', syllables: 1, partOfSpeech: 'noun', tags: { darkness: 0.3, brightness: 0.4, complexity: 0.1, nature: 0.9, urban: 0.3, abstract: 0.3, concrete: 0.8, emotionIntensity: 0.5, humor: 0.0, sincerity: 0.7 }, categories: ['nature', 'solitude'], rhymeGroup: 'ain', stressPattern: 'S', isSensory: true },
  { id: 'stone', text: 'stone', syllables: 1, partOfSpeech: 'noun', tags: { darkness: 0.3, brightness: 0.3, complexity: 0.2, nature: 0.7, urban: 0.3, abstract: 0.2, concrete: 1.0, emotionIntensity: 0.2, humor: 0.0, sincerity: 0.6 }, categories: ['nature', 'solitude'], rhymeGroup: 'one', stressPattern: 'S' },
  { id: 'moss', text: 'moss', syllables: 1, partOfSpeech: 'noun', tags: { darkness: 0.3, brightness: 0.4, complexity: 0.2, nature: 1.0, urban: 0.0, abstract: 0.1, concrete: 1.0, emotionIntensity: 0.2, humor: 0.0, sincerity: 0.7 }, categories: ['nature'], rhymeGroup: 'oss', stressPattern: 'S', isSensory: true },
  { id: 'breeze', text: 'breeze', syllables: 1, partOfSpeech: 'noun', tags: { darkness: 0.0, brightness: 0.7, complexity: 0.1, nature: 0.8, urban: 0.2, abstract: 0.3, concrete: 0.7, emotionIntensity: 0.3, humor: 0.0, sincerity: 0.7 }, categories: ['nature', 'light'], rhymeGroup: 'eeze', stressPattern: 'S', isSensory: true },
  { id: 'thorn', text: 'thorn', syllables: 1, partOfSpeech: 'noun', tags: { darkness: 0.5, brightness: 0.2, complexity: 0.3, nature: 0.9, urban: 0.0, abstract: 0.2, concrete: 1.0, emotionIntensity: 0.5, humor: 0.0, sincerity: 0.6 }, categories: ['nature', 'night'], rhymeGroup: 'orn', stressPattern: 'S' },
  { id: 'root', text: 'root', syllables: 1, partOfSpeech: 'noun', tags: { darkness: 0.3, brightness: 0.3, complexity: 0.3, nature: 0.9, urban: 0.0, abstract: 0.4, concrete: 0.8, emotionIntensity: 0.3, humor: 0.0, sincerity: 0.7 }, categories: ['nature'], rhymeGroup: 'oot', stressPattern: 'S' },
  { id: 'horizon', text: 'horizon', syllables: 3, partOfSpeech: 'noun', tags: { darkness: 0.2, brightness: 0.7, complexity: 0.4, nature: 0.7, urban: 0.1, abstract: 0.5, concrete: 0.6, emotionIntensity: 0.5, humor: 0.0, sincerity: 0.8 }, categories: ['nature', 'light'], rhymeGroup: 'izon', stressPattern: 'uSu' },
  { id: 'dew', text: 'dew', syllables: 1, partOfSpeech: 'noun', tags: { darkness: 0.0, brightness: 0.8, complexity: 0.1, nature: 1.0, urban: 0.0, abstract: 0.2, concrete: 0.9, emotionIntensity: 0.3, humor: 0.0, sincerity: 0.8 }, categories: ['nature', 'light'], rhymeGroup: 'ew', stressPattern: 'S', isSensory: true },
  { id: 'leaf', text: 'leaf', syllables: 1, partOfSpeech: 'noun', tags: { darkness: 0.1, brightness: 0.6, complexity: 0.1, nature: 1.0, urban: 0.0, abstract: 0.1, concrete: 1.0, emotionIntensity: 0.2, humor: 0.0, sincerity: 0.7 }, categories: ['nature'], rhymeGroup: 'eaf', stressPattern: 'S' },

  // ─── Darkness / Night ──────────────────────────────────────────────────────
  { id: 'shadow', text: 'shadow', syllables: 2, partOfSpeech: 'noun', tags: { darkness: 0.9, brightness: 0.1, complexity: 0.4, nature: 0.3, urban: 0.3, abstract: 0.5, concrete: 0.6, emotionIntensity: 0.5, humor: 0.0, sincerity: 0.6 }, categories: ['night', 'solitude'], rhymeGroup: 'adow', stressPattern: 'Su' },
  { id: 'midnight', text: 'midnight', syllables: 2, partOfSpeech: 'noun', tags: { darkness: 1.0, brightness: 0.0, complexity: 0.3, nature: 0.4, urban: 0.3, abstract: 0.4, concrete: 0.7, emotionIntensity: 0.5, humor: 0.0, sincerity: 0.7 }, categories: ['night'], rhymeGroup: 'ight', stressPattern: 'Su' },
  { id: 'ash', text: 'ash', syllables: 1, partOfSpeech: 'noun', tags: { darkness: 0.8, brightness: 0.1, complexity: 0.2, nature: 0.4, urban: 0.3, abstract: 0.3, concrete: 0.9, emotionIntensity: 0.5, humor: 0.0, sincerity: 0.6 }, categories: ['night', 'warmth'], rhymeGroup: 'ash', stressPattern: 'S' },
  { id: 'void', text: 'void', syllables: 1, partOfSpeech: 'noun', tags: { darkness: 1.0, brightness: 0.0, complexity: 0.5, nature: 0.1, urban: 0.2, abstract: 0.9, concrete: 0.2, emotionIntensity: 0.7, humor: 0.0, sincerity: 0.5 }, categories: ['night', 'abstract'], rhymeGroup: 'oid', stressPattern: 'S', isProfound: true },
  { id: 'gloom', text: 'gloom', syllables: 1, partOfSpeech: 'noun', tags: { darkness: 0.9, brightness: 0.0, complexity: 0.3, nature: 0.2, urban: 0.3, abstract: 0.5, concrete: 0.5, emotionIntensity: 0.6, humor: 0.0, sincerity: 0.6 }, categories: ['night', 'solitude'], rhymeGroup: 'oom', stressPattern: 'S' },
  { id: 'phantom', text: 'phantom', syllables: 2, partOfSpeech: 'noun', tags: { darkness: 0.9, brightness: 0.0, complexity: 0.5, nature: 0.1, urban: 0.2, abstract: 0.7, concrete: 0.4, emotionIntensity: 0.6, humor: 0.0, sincerity: 0.4 }, categories: ['night', 'surreal'], rhymeGroup: 'antom', stressPattern: 'Su' },
  { id: 'dusk', text: 'dusk', syllables: 1, partOfSpeech: 'noun', tags: { darkness: 0.7, brightness: 0.2, complexity: 0.2, nature: 0.6, urban: 0.2, abstract: 0.3, concrete: 0.7, emotionIntensity: 0.4, humor: 0.0, sincerity: 0.7 }, categories: ['night', 'nature'], rhymeGroup: 'usk', stressPattern: 'S', isMusical: true },
  { id: 'fog', text: 'fog', syllables: 1, partOfSpeech: 'noun', tags: { darkness: 0.6, brightness: 0.2, complexity: 0.3, nature: 0.7, urban: 0.3, abstract: 0.4, concrete: 0.7, emotionIntensity: 0.4, humor: 0.0, sincerity: 0.6 }, categories: ['night', 'nature', 'solitude'], rhymeGroup: 'og', stressPattern: 'S', isSensory: true },
  { id: 'eclipse', text: 'eclipse', syllables: 2, partOfSpeech: 'noun', tags: { darkness: 0.8, brightness: 0.2, complexity: 0.5, nature: 0.6, urban: 0.0, abstract: 0.5, concrete: 0.6, emotionIntensity: 0.7, humor: 0.0, sincerity: 0.6 }, categories: ['night', 'nature', 'abstract'], rhymeGroup: 'ipse', stressPattern: 'uS', isProfound: true },
  { id: 'ruin', text: 'ruin', syllables: 2, partOfSpeech: 'noun', tags: { darkness: 0.8, brightness: 0.1, complexity: 0.4, nature: 0.3, urban: 0.5, abstract: 0.4, concrete: 0.7, emotionIntensity: 0.7, humor: 0.0, sincerity: 0.6 }, categories: ['night', 'urban'], rhymeGroup: 'uin', stressPattern: 'Su' },
  { id: 'veil', text: 'veil', syllables: 1, partOfSpeech: 'noun', tags: { darkness: 0.5, brightness: 0.3, complexity: 0.4, nature: 0.1, urban: 0.2, abstract: 0.6, concrete: 0.5, emotionIntensity: 0.4, humor: 0.0, sincerity: 0.5 }, categories: ['night', 'abstract'], rhymeGroup: 'ail', stressPattern: 'S' },
  { id: 'cinder', text: 'cinder', syllables: 2, partOfSpeech: 'noun', tags: { darkness: 0.7, brightness: 0.2, complexity: 0.3, nature: 0.3, urban: 0.3, abstract: 0.2, concrete: 0.9, emotionIntensity: 0.4, humor: 0.0, sincerity: 0.6 }, categories: ['night', 'warmth'], rhymeGroup: 'inder', stressPattern: 'Su' },

  // ─── Emotion / Feeling ─────────────────────────────────────────────────────
  { id: 'tenderness', text: 'tenderness', syllables: 3, partOfSpeech: 'noun', tags: { darkness: 0.1, brightness: 0.7, complexity: 0.4, nature: 0.1, urban: 0.1, abstract: 0.7, concrete: 0.3, emotionIntensity: 0.8, humor: 0.0, sincerity: 0.95 }, categories: ['emotion', 'warmth'], rhymeGroup: 'ess', stressPattern: 'Suu', isProfound: true },
  { id: 'longing', text: 'longing', syllables: 2, partOfSpeech: 'noun', tags: { darkness: 0.4, brightness: 0.3, complexity: 0.4, nature: 0.1, urban: 0.1, abstract: 0.8, concrete: 0.2, emotionIntensity: 0.8, humor: 0.0, sincerity: 0.9 }, categories: ['emotion', 'solitude'], rhymeGroup: 'onging', stressPattern: 'Su', isProfound: true },
  { id: 'ache', text: 'ache', syllables: 1, partOfSpeech: 'noun', tags: { darkness: 0.5, brightness: 0.2, complexity: 0.3, nature: 0.0, urban: 0.1, abstract: 0.5, concrete: 0.5, emotionIntensity: 0.8, humor: 0.0, sincerity: 0.8 }, categories: ['emotion'], rhymeGroup: 'ake', stressPattern: 'S', isSensory: true },
  { id: 'joy', text: 'joy', syllables: 1, partOfSpeech: 'noun', tags: { darkness: 0.0, brightness: 0.95, complexity: 0.1, nature: 0.1, urban: 0.1, abstract: 0.5, concrete: 0.5, emotionIntensity: 0.9, humor: 0.1, sincerity: 0.9 }, categories: ['emotion', 'light', 'warmth'], rhymeGroup: 'oy', stressPattern: 'S' },
  { id: 'sorrow', text: 'sorrow', syllables: 2, partOfSpeech: 'noun', tags: { darkness: 0.7, brightness: 0.1, complexity: 0.3, nature: 0.1, urban: 0.1, abstract: 0.6, concrete: 0.4, emotionIntensity: 0.9, humor: 0.0, sincerity: 0.9 }, categories: ['emotion', 'night'], rhymeGroup: 'orrow', stressPattern: 'Su', isProfound: true },
  { id: 'bliss', text: 'bliss', syllables: 1, partOfSpeech: 'noun', tags: { darkness: 0.0, brightness: 0.9, complexity: 0.2, nature: 0.1, urban: 0.0, abstract: 0.6, concrete: 0.4, emotionIntensity: 0.9, humor: 0.0, sincerity: 0.9 }, categories: ['emotion', 'light', 'warmth'], rhymeGroup: 'iss', stressPattern: 'S' },
  { id: 'fury', text: 'fury', syllables: 2, partOfSpeech: 'noun', tags: { darkness: 0.6, brightness: 0.3, complexity: 0.3, nature: 0.1, urban: 0.2, abstract: 0.5, concrete: 0.5, emotionIntensity: 1.0, humor: 0.0, sincerity: 0.7 }, categories: ['emotion', 'power'], rhymeGroup: 'ury', stressPattern: 'Su' },
  { id: 'grief', text: 'grief', syllables: 1, partOfSpeech: 'noun', tags: { darkness: 0.8, brightness: 0.0, complexity: 0.4, nature: 0.0, urban: 0.1, abstract: 0.6, concrete: 0.4, emotionIntensity: 1.0, humor: 0.0, sincerity: 0.95 }, categories: ['emotion', 'night'], rhymeGroup: 'eef', stressPattern: 'S', isProfound: true },
  { id: 'wonder', text: 'wonder', syllables: 2, partOfSpeech: 'noun', tags: { darkness: 0.1, brightness: 0.7, complexity: 0.3, nature: 0.3, urban: 0.1, abstract: 0.6, concrete: 0.4, emotionIntensity: 0.6, humor: 0.0, sincerity: 0.8 }, categories: ['emotion', 'light'], rhymeGroup: 'under', stressPattern: 'Su' },
  { id: 'hope', text: 'hope', syllables: 1, partOfSpeech: 'noun', tags: { darkness: 0.0, brightness: 0.8, complexity: 0.2, nature: 0.1, urban: 0.1, abstract: 0.7, concrete: 0.3, emotionIntensity: 0.7, humor: 0.0, sincerity: 0.9 }, categories: ['emotion', 'light'], rhymeGroup: 'ope', stressPattern: 'S' },
  { id: 'desire', text: 'desire', syllables: 2, partOfSpeech: 'noun', tags: { darkness: 0.3, brightness: 0.5, complexity: 0.4, nature: 0.0, urban: 0.2, abstract: 0.7, concrete: 0.3, emotionIntensity: 0.9, humor: 0.0, sincerity: 0.8 }, categories: ['emotion', 'warmth'], rhymeGroup: 'ire', stressPattern: 'uS' },
  { id: 'serenity', text: 'serenity', syllables: 4, partOfSpeech: 'noun', tags: { darkness: 0.1, brightness: 0.7, complexity: 0.4, nature: 0.4, urban: 0.1, abstract: 0.7, concrete: 0.3, emotionIntensity: 0.4, humor: 0.0, sincerity: 0.9 }, categories: ['emotion', 'light', 'solitude'], rhymeGroup: 'ity', stressPattern: 'uSuu', isProfound: true },
  { id: 'fear', text: 'fear', syllables: 1, partOfSpeech: 'noun', tags: { darkness: 0.7, brightness: 0.1, complexity: 0.2, nature: 0.0, urban: 0.2, abstract: 0.5, concrete: 0.5, emotionIntensity: 0.9, humor: 0.0, sincerity: 0.7 }, categories: ['emotion', 'night'], rhymeGroup: 'ear', stressPattern: 'S' },
  { id: 'grace', text: 'grace', syllables: 1, partOfSpeech: 'noun', tags: { darkness: 0.0, brightness: 0.8, complexity: 0.3, nature: 0.2, urban: 0.1, abstract: 0.6, concrete: 0.4, emotionIntensity: 0.5, humor: 0.0, sincerity: 0.9 }, categories: ['emotion', 'light'], rhymeGroup: 'ace', stressPattern: 'S', isProfound: true },

  // ─── Abstract / Philosophical ──────────────────────────────────────────────
  { id: 'infinity', text: 'infinity', syllables: 4, partOfSpeech: 'noun', tags: { darkness: 0.3, brightness: 0.5, complexity: 0.8, nature: 0.2, urban: 0.0, abstract: 1.0, concrete: 0.0, emotionIntensity: 0.6, humor: 0.0, sincerity: 0.7 }, categories: ['abstract', 'surreal'], rhymeGroup: 'ity', stressPattern: 'uSuu', isProfound: true },
  { id: 'eternity', text: 'eternity', syllables: 4, partOfSpeech: 'noun', tags: { darkness: 0.3, brightness: 0.5, complexity: 0.7, nature: 0.1, urban: 0.0, abstract: 1.0, concrete: 0.0, emotionIntensity: 0.7, humor: 0.0, sincerity: 0.8 }, categories: ['abstract'], rhymeGroup: 'ity', stressPattern: 'uSuu', isProfound: true },
  { id: 'truth', text: 'truth', syllables: 1, partOfSpeech: 'noun', tags: { darkness: 0.2, brightness: 0.6, complexity: 0.5, nature: 0.0, urban: 0.1, abstract: 0.9, concrete: 0.1, emotionIntensity: 0.5, humor: 0.0, sincerity: 1.0 }, categories: ['abstract', 'literary'], rhymeGroup: 'ooth', stressPattern: 'S', isProfound: true },
  { id: 'silence', text: 'silence', syllables: 2, partOfSpeech: 'noun', tags: { darkness: 0.4, brightness: 0.3, complexity: 0.4, nature: 0.3, urban: 0.2, abstract: 0.6, concrete: 0.4, emotionIntensity: 0.4, humor: 0.0, sincerity: 0.8 }, categories: ['abstract', 'solitude'], rhymeGroup: 'ence', stressPattern: 'Su', isProfound: true },
  { id: 'paradox', text: 'paradox', syllables: 3, partOfSpeech: 'noun', tags: { darkness: 0.4, brightness: 0.3, complexity: 0.9, nature: 0.0, urban: 0.2, abstract: 0.9, concrete: 0.1, emotionIntensity: 0.4, humor: 0.3, sincerity: 0.5 }, categories: ['abstract', 'literary'], rhymeGroup: 'ox', stressPattern: 'SuS', isWeird: true },
  { id: 'entropy', text: 'entropy', syllables: 3, partOfSpeech: 'noun', tags: { darkness: 0.6, brightness: 0.1, complexity: 0.9, nature: 0.2, urban: 0.2, abstract: 0.9, concrete: 0.1, emotionIntensity: 0.5, humor: 0.0, sincerity: 0.6 }, categories: ['abstract'], rhymeGroup: 'opy', stressPattern: 'Suu', isProfound: true },
  { id: 'echo', text: 'echo', syllables: 2, partOfSpeech: 'noun', tags: { darkness: 0.4, brightness: 0.3, complexity: 0.4, nature: 0.3, urban: 0.3, abstract: 0.6, concrete: 0.5, emotionIntensity: 0.4, humor: 0.0, sincerity: 0.6 }, categories: ['abstract', 'solitude'], rhymeGroup: 'echo', stressPattern: 'Su', isSensory: true },
  { id: 'memory', text: 'memory', syllables: 3, partOfSpeech: 'noun', tags: { darkness: 0.3, brightness: 0.4, complexity: 0.5, nature: 0.1, urban: 0.1, abstract: 0.8, concrete: 0.2, emotionIntensity: 0.6, humor: 0.0, sincerity: 0.8 }, categories: ['abstract', 'emotion'], rhymeGroup: 'ory', stressPattern: 'Suu', isProfound: true },
  { id: 'destiny', text: 'destiny', syllables: 3, partOfSpeech: 'noun', tags: { darkness: 0.3, brightness: 0.5, complexity: 0.5, nature: 0.0, urban: 0.1, abstract: 0.9, concrete: 0.1, emotionIntensity: 0.6, humor: 0.0, sincerity: 0.7 }, categories: ['abstract'], rhymeGroup: 'iny', stressPattern: 'Suu' },
  { id: 'chaos', text: 'chaos', syllables: 2, partOfSpeech: 'noun', tags: { darkness: 0.6, brightness: 0.2, complexity: 0.7, nature: 0.2, urban: 0.3, abstract: 0.8, concrete: 0.2, emotionIntensity: 0.7, humor: 0.1, sincerity: 0.5 }, categories: ['abstract', 'surreal'], rhymeGroup: 'aos', stressPattern: 'Su', isWeird: true },
  { id: 'dream', text: 'dream', syllables: 1, partOfSpeech: 'noun', tags: { darkness: 0.2, brightness: 0.6, complexity: 0.4, nature: 0.2, urban: 0.1, abstract: 0.8, concrete: 0.2, emotionIntensity: 0.6, humor: 0.0, sincerity: 0.8 }, categories: ['abstract', 'surreal', 'light'], rhymeGroup: 'eam', stressPattern: 'S' },
  { id: 'riddle', text: 'riddle', syllables: 2, partOfSpeech: 'noun', tags: { darkness: 0.3, brightness: 0.3, complexity: 0.7, nature: 0.0, urban: 0.1, abstract: 0.7, concrete: 0.3, emotionIntensity: 0.3, humor: 0.3, sincerity: 0.4 }, categories: ['abstract', 'literary'], rhymeGroup: 'iddle', stressPattern: 'Su' },

  // ─── Surreal / Weird ───────────────────────────────────────────────────────
  { id: 'kaleidoscope', text: 'kaleidoscope', syllables: 4, partOfSpeech: 'noun', tags: { darkness: 0.1, brightness: 0.7, complexity: 0.8, nature: 0.1, urban: 0.2, abstract: 0.7, concrete: 0.5, emotionIntensity: 0.5, humor: 0.1, sincerity: 0.4 }, categories: ['surreal', 'light'], rhymeGroup: 'ope', stressPattern: 'uSuS', isWeird: true, isSensory: true },
  { id: 'labyrinth', text: 'labyrinth', syllables: 3, partOfSpeech: 'noun', tags: { darkness: 0.5, brightness: 0.2, complexity: 0.9, nature: 0.1, urban: 0.3, abstract: 0.6, concrete: 0.5, emotionIntensity: 0.5, humor: 0.0, sincerity: 0.5 }, categories: ['surreal', 'abstract'], rhymeGroup: 'inth', stressPattern: 'Suu', isWeird: true },
  { id: 'mirage', text: 'mirage', syllables: 2, partOfSpeech: 'noun', tags: { darkness: 0.3, brightness: 0.5, complexity: 0.6, nature: 0.4, urban: 0.1, abstract: 0.7, concrete: 0.3, emotionIntensity: 0.4, humor: 0.0, sincerity: 0.3 }, categories: ['surreal', 'abstract'], rhymeGroup: 'ahge', stressPattern: 'uS', isWeird: true },
  { id: 'clockwork', text: 'clockwork', syllables: 2, partOfSpeech: 'noun', tags: { darkness: 0.3, brightness: 0.3, complexity: 0.7, nature: 0.0, urban: 0.6, abstract: 0.4, concrete: 0.7, emotionIntensity: 0.3, humor: 0.1, sincerity: 0.4 }, categories: ['surreal', 'urban'], rhymeGroup: 'ork', stressPattern: 'Su', isWeird: true },
  { id: 'prism', text: 'prism', syllables: 2, partOfSpeech: 'noun', tags: { darkness: 0.1, brightness: 0.8, complexity: 0.6, nature: 0.2, urban: 0.2, abstract: 0.5, concrete: 0.6, emotionIntensity: 0.3, humor: 0.0, sincerity: 0.5 }, categories: ['surreal', 'light'], rhymeGroup: 'ism', stressPattern: 'Su', isSensory: true },
  { id: 'specter', text: 'specter', syllables: 2, partOfSpeech: 'noun', tags: { darkness: 0.9, brightness: 0.0, complexity: 0.5, nature: 0.1, urban: 0.2, abstract: 0.7, concrete: 0.3, emotionIntensity: 0.6, humor: 0.0, sincerity: 0.4 }, categories: ['surreal', 'night'], rhymeGroup: 'ecter', stressPattern: 'Su', isWeird: true },
  { id: 'alchemy', text: 'alchemy', syllables: 3, partOfSpeech: 'noun', tags: { darkness: 0.4, brightness: 0.4, complexity: 0.8, nature: 0.1, urban: 0.2, abstract: 0.7, concrete: 0.3, emotionIntensity: 0.4, humor: 0.0, sincerity: 0.5 }, categories: ['surreal', 'literary'], rhymeGroup: 'emy', stressPattern: 'Suu', isWeird: true },
  { id: 'nebula', text: 'nebula', syllables: 3, partOfSpeech: 'noun', tags: { darkness: 0.4, brightness: 0.6, complexity: 0.6, nature: 0.5, urban: 0.0, abstract: 0.7, concrete: 0.4, emotionIntensity: 0.4, humor: 0.0, sincerity: 0.6 }, categories: ['surreal', 'nature'], rhymeGroup: 'ula', stressPattern: 'Suu', isWeird: true },

  // ─── Urban / Modern ────────────────────────────────────────────────────────
  { id: 'algorithm', text: 'algorithm', syllables: 4, partOfSpeech: 'noun', tags: { darkness: 0.2, brightness: 0.3, complexity: 0.9, nature: 0.0, urban: 0.9, abstract: 0.7, concrete: 0.3, emotionIntensity: 0.1, humor: 0.1, sincerity: 0.4 }, categories: ['urban', 'abstract'], rhymeGroup: 'ithm', stressPattern: 'SuuS', isWeird: true },
  { id: 'neon', text: 'neon', syllables: 2, partOfSpeech: 'noun', tags: { darkness: 0.3, brightness: 0.8, complexity: 0.3, nature: 0.0, urban: 0.9, abstract: 0.2, concrete: 0.8, emotionIntensity: 0.4, humor: 0.0, sincerity: 0.3 }, categories: ['urban', 'light'], rhymeGroup: 'eon', stressPattern: 'Su', isSensory: true },
  { id: 'static', text: 'static', syllables: 2, partOfSpeech: 'noun', tags: { darkness: 0.4, brightness: 0.3, complexity: 0.4, nature: 0.0, urban: 0.8, abstract: 0.5, concrete: 0.5, emotionIntensity: 0.3, humor: 0.0, sincerity: 0.4 }, categories: ['urban'], rhymeGroup: 'atic', stressPattern: 'Su', isSensory: true },
  { id: 'chrome', text: 'chrome', syllables: 1, partOfSpeech: 'noun', tags: { darkness: 0.2, brightness: 0.6, complexity: 0.3, nature: 0.0, urban: 0.9, abstract: 0.2, concrete: 0.9, emotionIntensity: 0.2, humor: 0.0, sincerity: 0.3 }, categories: ['urban'], rhymeGroup: 'ome', stressPattern: 'S' },
  { id: 'concrete', text: 'concrete', syllables: 2, partOfSpeech: 'noun', tags: { darkness: 0.4, brightness: 0.2, complexity: 0.2, nature: 0.0, urban: 1.0, abstract: 0.1, concrete: 1.0, emotionIntensity: 0.2, humor: 0.0, sincerity: 0.5 }, categories: ['urban'], rhymeGroup: 'eet', stressPattern: 'Su' },
  { id: 'wire', text: 'wire', syllables: 1, partOfSpeech: 'noun', tags: { darkness: 0.3, brightness: 0.3, complexity: 0.3, nature: 0.0, urban: 0.9, abstract: 0.2, concrete: 0.9, emotionIntensity: 0.2, humor: 0.0, sincerity: 0.4 }, categories: ['urban'], rhymeGroup: 'ire', stressPattern: 'S' },
  { id: 'skyline', text: 'skyline', syllables: 2, partOfSpeech: 'noun', tags: { darkness: 0.2, brightness: 0.6, complexity: 0.3, nature: 0.3, urban: 0.8, abstract: 0.3, concrete: 0.7, emotionIntensity: 0.4, humor: 0.0, sincerity: 0.5 }, categories: ['urban', 'light'], rhymeGroup: 'ine', stressPattern: 'Su' },
  { id: 'frequency', text: 'frequency', syllables: 3, partOfSpeech: 'noun', tags: { darkness: 0.2, brightness: 0.3, complexity: 0.7, nature: 0.0, urban: 0.7, abstract: 0.7, concrete: 0.3, emotionIntensity: 0.2, humor: 0.0, sincerity: 0.4 }, categories: ['urban', 'abstract'], rhymeGroup: 'ency', stressPattern: 'Suu', isWeird: true },

  // ─── Power / Spoken Word ───────────────────────────────────────────────────
  { id: 'shatter', text: 'shatter', syllables: 2, partOfSpeech: 'verb', tags: { darkness: 0.5, brightness: 0.3, complexity: 0.3, nature: 0.1, urban: 0.3, abstract: 0.3, concrete: 0.8, emotionIntensity: 0.8, humor: 0.0, sincerity: 0.7 }, categories: ['power', 'emotion'], rhymeGroup: 'atter', stressPattern: 'Su', isSensory: true },
  { id: 'ignite', text: 'ignite', syllables: 2, partOfSpeech: 'verb', tags: { darkness: 0.2, brightness: 0.7, complexity: 0.3, nature: 0.2, urban: 0.2, abstract: 0.4, concrete: 0.7, emotionIntensity: 0.8, humor: 0.0, sincerity: 0.7 }, categories: ['power', 'warmth', 'light'], rhymeGroup: 'ight', stressPattern: 'uS' },
  { id: 'roar', text: 'roar', syllables: 1, partOfSpeech: 'verb', tags: { darkness: 0.3, brightness: 0.4, complexity: 0.1, nature: 0.4, urban: 0.2, abstract: 0.3, concrete: 0.7, emotionIntensity: 0.9, humor: 0.0, sincerity: 0.8 }, categories: ['power'], rhymeGroup: 'oar', stressPattern: 'S', isSensory: true },
  { id: 'thunder', text: 'thunder', syllables: 2, partOfSpeech: 'noun', tags: { darkness: 0.5, brightness: 0.4, complexity: 0.3, nature: 0.7, urban: 0.1, abstract: 0.3, concrete: 0.8, emotionIntensity: 0.8, humor: 0.0, sincerity: 0.7 }, categories: ['power', 'nature'], rhymeGroup: 'under', stressPattern: 'Su', isSensory: true },
  { id: 'blaze', text: 'blaze', syllables: 1, partOfSpeech: 'noun', tags: { darkness: 0.2, brightness: 0.8, complexity: 0.2, nature: 0.3, urban: 0.2, abstract: 0.3, concrete: 0.8, emotionIntensity: 0.8, humor: 0.0, sincerity: 0.7 }, categories: ['power', 'warmth', 'light'], rhymeGroup: 'aze', stressPattern: 'S', isSensory: true },
  { id: 'conquer', text: 'conquer', syllables: 2, partOfSpeech: 'verb', tags: { darkness: 0.4, brightness: 0.5, complexity: 0.4, nature: 0.0, urban: 0.3, abstract: 0.5, concrete: 0.5, emotionIntensity: 0.7, humor: 0.0, sincerity: 0.6 }, categories: ['power'], rhymeGroup: 'onquer', stressPattern: 'Su' },
  { id: 'fierce', text: 'fierce', syllables: 1, partOfSpeech: 'adjective', tags: { darkness: 0.4, brightness: 0.4, complexity: 0.3, nature: 0.3, urban: 0.2, abstract: 0.4, concrete: 0.6, emotionIntensity: 0.9, humor: 0.0, sincerity: 0.7 }, categories: ['power', 'emotion'], rhymeGroup: 'erce', stressPattern: 'S' },
  { id: 'unyielding', text: 'unyielding', syllables: 3, partOfSpeech: 'adjective', tags: { darkness: 0.3, brightness: 0.4, complexity: 0.5, nature: 0.1, urban: 0.2, abstract: 0.5, concrete: 0.5, emotionIntensity: 0.7, humor: 0.0, sincerity: 0.8 }, categories: ['power'], rhymeGroup: 'elding', stressPattern: 'uSu' },
  { id: 'revolt', text: 'revolt', syllables: 2, partOfSpeech: 'noun', tags: { darkness: 0.5, brightness: 0.3, complexity: 0.5, nature: 0.0, urban: 0.6, abstract: 0.5, concrete: 0.5, emotionIntensity: 0.8, humor: 0.0, sincerity: 0.7 }, categories: ['power', 'urban'], rhymeGroup: 'olt', stressPattern: 'uS' },

  // ─── Sensory ───────────────────────────────────────────────────────────────
  { id: 'velvet', text: 'velvet', syllables: 2, partOfSpeech: 'noun', tags: { darkness: 0.3, brightness: 0.4, complexity: 0.3, nature: 0.1, urban: 0.3, abstract: 0.2, concrete: 0.9, emotionIntensity: 0.4, humor: 0.0, sincerity: 0.6 }, categories: ['sensory', 'warmth'], rhymeGroup: 'elvet', stressPattern: 'Su', isSensory: true },
  { id: 'whisper', text: 'whisper', syllables: 2, partOfSpeech: 'noun', tags: { darkness: 0.3, brightness: 0.4, complexity: 0.3, nature: 0.2, urban: 0.1, abstract: 0.4, concrete: 0.6, emotionIntensity: 0.5, humor: 0.0, sincerity: 0.7 }, categories: ['sensory', 'solitude'], rhymeGroup: 'isper', stressPattern: 'Su', isSensory: true, isMusical: true },
  { id: 'crimson', text: 'crimson', syllables: 2, partOfSpeech: 'adjective', tags: { darkness: 0.5, brightness: 0.5, complexity: 0.3, nature: 0.3, urban: 0.2, abstract: 0.2, concrete: 0.9, emotionIntensity: 0.6, humor: 0.0, sincerity: 0.6 }, categories: ['sensory', 'warmth'], rhymeGroup: 'imson', stressPattern: 'Su', isSensory: true },
  { id: 'honey', text: 'honey', syllables: 2, partOfSpeech: 'noun', tags: { darkness: 0.0, brightness: 0.8, complexity: 0.1, nature: 0.7, urban: 0.1, abstract: 0.2, concrete: 0.9, emotionIntensity: 0.5, humor: 0.0, sincerity: 0.8 }, categories: ['sensory', 'warmth', 'nature'], rhymeGroup: 'oney', stressPattern: 'Su', isSensory: true },
  { id: 'silk', text: 'silk', syllables: 1, partOfSpeech: 'noun', tags: { darkness: 0.1, brightness: 0.6, complexity: 0.2, nature: 0.3, urban: 0.3, abstract: 0.2, concrete: 0.9, emotionIntensity: 0.3, humor: 0.0, sincerity: 0.6 }, categories: ['sensory'], rhymeGroup: 'ilk', stressPattern: 'S', isSensory: true },
  { id: 'amber', text: 'amber', syllables: 2, partOfSpeech: 'noun', tags: { darkness: 0.2, brightness: 0.7, complexity: 0.2, nature: 0.5, urban: 0.2, abstract: 0.2, concrete: 0.9, emotionIntensity: 0.3, humor: 0.0, sincerity: 0.7 }, categories: ['sensory', 'warmth', 'light'], rhymeGroup: 'amber', stressPattern: 'Su', isSensory: true },
  { id: 'ivory', text: 'ivory', syllables: 3, partOfSpeech: 'noun', tags: { darkness: 0.1, brightness: 0.8, complexity: 0.3, nature: 0.2, urban: 0.2, abstract: 0.2, concrete: 0.9, emotionIntensity: 0.3, humor: 0.0, sincerity: 0.6 }, categories: ['sensory', 'light'], rhymeGroup: 'ory', stressPattern: 'Suu', isSensory: true },
  { id: 'frost', text: 'frost', syllables: 1, partOfSpeech: 'noun', tags: { darkness: 0.3, brightness: 0.6, complexity: 0.2, nature: 0.9, urban: 0.1, abstract: 0.2, concrete: 0.9, emotionIntensity: 0.3, humor: 0.0, sincerity: 0.6 }, categories: ['sensory', 'nature', 'solitude'], rhymeGroup: 'ost', stressPattern: 'S', isSensory: true },
  { id: 'azure', text: 'azure', syllables: 2, partOfSpeech: 'adjective', tags: { darkness: 0.1, brightness: 0.7, complexity: 0.4, nature: 0.5, urban: 0.1, abstract: 0.3, concrete: 0.7, emotionIntensity: 0.3, humor: 0.0, sincerity: 0.6 }, categories: ['sensory', 'nature', 'light'], rhymeGroup: 'ure', stressPattern: 'Su', isSensory: true },

  // ─── Literary / Formal ─────────────────────────────────────────────────────
  { id: 'sonnet', text: 'sonnet', syllables: 2, partOfSpeech: 'noun', tags: { darkness: 0.1, brightness: 0.5, complexity: 0.7, nature: 0.1, urban: 0.2, abstract: 0.6, concrete: 0.4, emotionIntensity: 0.4, humor: 0.0, sincerity: 0.7 }, categories: ['literary'], rhymeGroup: 'onet', stressPattern: 'Su' },
  { id: 'verse', text: 'verse', syllables: 1, partOfSpeech: 'noun', tags: { darkness: 0.1, brightness: 0.5, complexity: 0.5, nature: 0.1, urban: 0.1, abstract: 0.5, concrete: 0.5, emotionIntensity: 0.4, humor: 0.0, sincerity: 0.7 }, categories: ['literary'], rhymeGroup: 'erse', stressPattern: 'S' },
  { id: 'quill', text: 'quill', syllables: 1, partOfSpeech: 'noun', tags: { darkness: 0.2, brightness: 0.4, complexity: 0.4, nature: 0.2, urban: 0.2, abstract: 0.3, concrete: 0.8, emotionIntensity: 0.3, humor: 0.0, sincerity: 0.7 }, categories: ['literary'], rhymeGroup: 'ill', stressPattern: 'S' },
  { id: 'metaphor', text: 'metaphor', syllables: 3, partOfSpeech: 'noun', tags: { darkness: 0.2, brightness: 0.4, complexity: 0.8, nature: 0.0, urban: 0.1, abstract: 0.9, concrete: 0.1, emotionIntensity: 0.4, humor: 0.0, sincerity: 0.6 }, categories: ['literary', 'abstract'], rhymeGroup: 'or', stressPattern: 'SuS' },
  { id: 'rhythm', text: 'rhythm', syllables: 2, partOfSpeech: 'noun', tags: { darkness: 0.1, brightness: 0.5, complexity: 0.5, nature: 0.2, urban: 0.3, abstract: 0.5, concrete: 0.5, emotionIntensity: 0.4, humor: 0.0, sincerity: 0.6 }, categories: ['literary'], rhymeGroup: 'ithm', stressPattern: 'Su', isMusical: true },
  { id: 'elegy', text: 'elegy', syllables: 3, partOfSpeech: 'noun', tags: { darkness: 0.6, brightness: 0.2, complexity: 0.7, nature: 0.1, urban: 0.1, abstract: 0.6, concrete: 0.4, emotionIntensity: 0.7, humor: 0.0, sincerity: 0.9 }, categories: ['literary', 'night'], rhymeGroup: 'egy', stressPattern: 'Suu', isProfound: true },
  { id: 'muse', text: 'muse', syllables: 1, partOfSpeech: 'noun', tags: { darkness: 0.1, brightness: 0.6, complexity: 0.5, nature: 0.1, urban: 0.1, abstract: 0.7, concrete: 0.3, emotionIntensity: 0.5, humor: 0.0, sincerity: 0.7 }, categories: ['literary', 'abstract'], rhymeGroup: 'oose', stressPattern: 'S', isProfound: true },
  { id: 'refrain', text: 'refrain', syllables: 2, partOfSpeech: 'noun', tags: { darkness: 0.2, brightness: 0.4, complexity: 0.5, nature: 0.0, urban: 0.1, abstract: 0.5, concrete: 0.5, emotionIntensity: 0.4, humor: 0.0, sincerity: 0.6 }, categories: ['literary'], rhymeGroup: 'ain', stressPattern: 'uS', isMusical: true },
  { id: 'stanza', text: 'stanza', syllables: 2, partOfSpeech: 'noun', tags: { darkness: 0.1, brightness: 0.4, complexity: 0.6, nature: 0.0, urban: 0.1, abstract: 0.5, concrete: 0.5, emotionIntensity: 0.3, humor: 0.0, sincerity: 0.6 }, categories: ['literary'], rhymeGroup: 'anza', stressPattern: 'Su' },

  // ─── Verbs: Motion / Action ────────────────────────────────────────────────
  { id: 'wander', text: 'wander', syllables: 2, partOfSpeech: 'verb', tags: { darkness: 0.2, brightness: 0.4, complexity: 0.3, nature: 0.4, urban: 0.3, abstract: 0.4, concrete: 0.6, emotionIntensity: 0.3, humor: 0.0, sincerity: 0.6 }, categories: ['solitude', 'nature'], rhymeGroup: 'ander', stressPattern: 'Su' },
  { id: 'drift', text: 'drift', syllables: 1, partOfSpeech: 'verb', tags: { darkness: 0.3, brightness: 0.4, complexity: 0.3, nature: 0.5, urban: 0.2, abstract: 0.5, concrete: 0.5, emotionIntensity: 0.3, humor: 0.0, sincerity: 0.6 }, categories: ['solitude', 'nature'], rhymeGroup: 'ift', stressPattern: 'S' },
  { id: 'soar', text: 'soar', syllables: 1, partOfSpeech: 'verb', tags: { darkness: 0.0, brightness: 0.8, complexity: 0.2, nature: 0.6, urban: 0.1, abstract: 0.4, concrete: 0.6, emotionIntensity: 0.6, humor: 0.0, sincerity: 0.7 }, categories: ['light', 'nature', 'power'], rhymeGroup: 'oar', stressPattern: 'S' },
  { id: 'collapse', text: 'collapse', syllables: 2, partOfSpeech: 'verb', tags: { darkness: 0.7, brightness: 0.1, complexity: 0.4, nature: 0.1, urban: 0.4, abstract: 0.4, concrete: 0.6, emotionIntensity: 0.8, humor: 0.0, sincerity: 0.6 }, categories: ['night', 'emotion'], rhymeGroup: 'apse', stressPattern: 'uS' },
  { id: 'bloom_v', text: 'bloom', syllables: 1, partOfSpeech: 'verb', tags: { darkness: 0.0, brightness: 0.9, complexity: 0.2, nature: 0.9, urban: 0.0, abstract: 0.3, concrete: 0.7, emotionIntensity: 0.5, humor: 0.0, sincerity: 0.8 }, categories: ['nature', 'light', 'flowers'], rhymeGroup: 'oom', stressPattern: 'S' },
  { id: 'tremble', text: 'tremble', syllables: 2, partOfSpeech: 'verb', tags: { darkness: 0.4, brightness: 0.2, complexity: 0.3, nature: 0.1, urban: 0.1, abstract: 0.3, concrete: 0.7, emotionIntensity: 0.7, humor: 0.0, sincerity: 0.7 }, categories: ['emotion', 'sensory'], rhymeGroup: 'emble', stressPattern: 'Su', isSensory: true },
  { id: 'dissolve', text: 'dissolve', syllables: 2, partOfSpeech: 'verb', tags: { darkness: 0.4, brightness: 0.3, complexity: 0.4, nature: 0.2, urban: 0.2, abstract: 0.6, concrete: 0.4, emotionIntensity: 0.5, humor: 0.0, sincerity: 0.6 }, categories: ['abstract', 'night'], rhymeGroup: 'olve', stressPattern: 'uS' },
  { id: 'linger', text: 'linger', syllables: 2, partOfSpeech: 'verb', tags: { darkness: 0.3, brightness: 0.3, complexity: 0.3, nature: 0.1, urban: 0.1, abstract: 0.5, concrete: 0.5, emotionIntensity: 0.4, humor: 0.0, sincerity: 0.7 }, categories: ['solitude', 'emotion'], rhymeGroup: 'inger', stressPattern: 'Su' },
  { id: 'unravel', text: 'unravel', syllables: 3, partOfSpeech: 'verb', tags: { darkness: 0.4, brightness: 0.3, complexity: 0.5, nature: 0.0, urban: 0.2, abstract: 0.6, concrete: 0.4, emotionIntensity: 0.6, humor: 0.0, sincerity: 0.6 }, categories: ['abstract', 'emotion'], rhymeGroup: 'avel', stressPattern: 'uSu' },
  { id: 'fracture', text: 'fracture', syllables: 2, partOfSpeech: 'verb', tags: { darkness: 0.6, brightness: 0.2, complexity: 0.4, nature: 0.1, urban: 0.3, abstract: 0.4, concrete: 0.7, emotionIntensity: 0.7, humor: 0.0, sincerity: 0.6 }, categories: ['power', 'night'], rhymeGroup: 'acture', stressPattern: 'Su' },
  { id: 'shimmer', text: 'shimmer', syllables: 2, partOfSpeech: 'verb', tags: { darkness: 0.1, brightness: 0.8, complexity: 0.2, nature: 0.4, urban: 0.2, abstract: 0.3, concrete: 0.7, emotionIntensity: 0.3, humor: 0.0, sincerity: 0.6 }, categories: ['light', 'sensory'], rhymeGroup: 'immer', stressPattern: 'Su', isSensory: true },
  { id: 'yearn', text: 'yearn', syllables: 1, partOfSpeech: 'verb', tags: { darkness: 0.3, brightness: 0.4, complexity: 0.3, nature: 0.0, urban: 0.1, abstract: 0.6, concrete: 0.4, emotionIntensity: 0.8, humor: 0.0, sincerity: 0.9 }, categories: ['emotion'], rhymeGroup: 'earn', stressPattern: 'S', isProfound: true },
  { id: 'embrace', text: 'embrace', syllables: 2, partOfSpeech: 'verb', tags: { darkness: 0.1, brightness: 0.6, complexity: 0.2, nature: 0.0, urban: 0.1, abstract: 0.4, concrete: 0.6, emotionIntensity: 0.7, humor: 0.0, sincerity: 0.9 }, categories: ['emotion', 'warmth'], rhymeGroup: 'ace', stressPattern: 'uS' },
  { id: 'erode', text: 'erode', syllables: 2, partOfSpeech: 'verb', tags: { darkness: 0.5, brightness: 0.2, complexity: 0.4, nature: 0.5, urban: 0.2, abstract: 0.5, concrete: 0.5, emotionIntensity: 0.4, humor: 0.0, sincerity: 0.6 }, categories: ['nature', 'night'], rhymeGroup: 'ode', stressPattern: 'uS' },

  // ─── Adjectives ────────────────────────────────────────────────────────────
  { id: 'fragile', text: 'fragile', syllables: 2, partOfSpeech: 'adjective', tags: { darkness: 0.3, brightness: 0.4, complexity: 0.3, nature: 0.2, urban: 0.1, abstract: 0.4, concrete: 0.6, emotionIntensity: 0.5, humor: 0.0, sincerity: 0.7 }, categories: ['emotion', 'sensory'], rhymeGroup: 'ile', stressPattern: 'Su' },
  { id: 'eternal', text: 'eternal', syllables: 3, partOfSpeech: 'adjective', tags: { darkness: 0.3, brightness: 0.5, complexity: 0.5, nature: 0.2, urban: 0.0, abstract: 0.9, concrete: 0.1, emotionIntensity: 0.6, humor: 0.0, sincerity: 0.8 }, categories: ['abstract'], rhymeGroup: 'ernal', stressPattern: 'uSu', isProfound: true },
  { id: 'luminous', text: 'luminous', syllables: 3, partOfSpeech: 'adjective', tags: { darkness: 0.0, brightness: 1.0, complexity: 0.4, nature: 0.3, urban: 0.2, abstract: 0.4, concrete: 0.6, emotionIntensity: 0.5, humor: 0.0, sincerity: 0.7 }, categories: ['light', 'sensory'], rhymeGroup: 'ous', stressPattern: 'Suu', isSensory: true },
  { id: 'hollow', text: 'hollow', syllables: 2, partOfSpeech: 'adjective', tags: { darkness: 0.7, brightness: 0.1, complexity: 0.3, nature: 0.2, urban: 0.2, abstract: 0.5, concrete: 0.5, emotionIntensity: 0.5, humor: 0.0, sincerity: 0.6 }, categories: ['night', 'solitude'], rhymeGroup: 'ollow', stressPattern: 'Su' },
  { id: 'gentle', text: 'gentle', syllables: 2, partOfSpeech: 'adjective', tags: { darkness: 0.0, brightness: 0.6, complexity: 0.1, nature: 0.3, urban: 0.1, abstract: 0.3, concrete: 0.7, emotionIntensity: 0.4, humor: 0.0, sincerity: 0.9 }, categories: ['emotion', 'warmth'], rhymeGroup: 'entle', stressPattern: 'Su' },
  { id: 'wild', text: 'wild', syllables: 1, partOfSpeech: 'adjective', tags: { darkness: 0.3, brightness: 0.5, complexity: 0.2, nature: 0.8, urban: 0.0, abstract: 0.3, concrete: 0.7, emotionIntensity: 0.6, humor: 0.0, sincerity: 0.7 }, categories: ['nature', 'power'], rhymeGroup: 'ild', stressPattern: 'S' },
  { id: 'bittersweet', text: 'bittersweet', syllables: 3, partOfSpeech: 'adjective', tags: { darkness: 0.4, brightness: 0.4, complexity: 0.5, nature: 0.2, urban: 0.1, abstract: 0.6, concrete: 0.4, emotionIntensity: 0.7, humor: 0.0, sincerity: 0.8 }, categories: ['emotion'], rhymeGroup: 'eet', stressPattern: 'SuS', isProfound: true },
  { id: 'serene', text: 'serene', syllables: 2, partOfSpeech: 'adjective', tags: { darkness: 0.1, brightness: 0.7, complexity: 0.3, nature: 0.5, urban: 0.0, abstract: 0.4, concrete: 0.6, emotionIntensity: 0.3, humor: 0.0, sincerity: 0.9 }, categories: ['light', 'nature', 'solitude'], rhymeGroup: 'een', stressPattern: 'uS' },
  { id: 'radiant', text: 'radiant', syllables: 3, partOfSpeech: 'adjective', tags: { darkness: 0.0, brightness: 1.0, complexity: 0.3, nature: 0.3, urban: 0.1, abstract: 0.3, concrete: 0.7, emotionIntensity: 0.6, humor: 0.0, sincerity: 0.8 }, categories: ['light', 'warmth'], rhymeGroup: 'ant', stressPattern: 'Suu' },
  { id: 'ancient', text: 'ancient', syllables: 2, partOfSpeech: 'adjective', tags: { darkness: 0.4, brightness: 0.3, complexity: 0.5, nature: 0.3, urban: 0.2, abstract: 0.6, concrete: 0.4, emotionIntensity: 0.4, humor: 0.0, sincerity: 0.7 }, categories: ['abstract', 'literary'], rhymeGroup: 'ent', stressPattern: 'Su' },
  { id: 'sacred', text: 'sacred', syllables: 2, partOfSpeech: 'adjective', tags: { darkness: 0.2, brightness: 0.6, complexity: 0.5, nature: 0.2, urban: 0.1, abstract: 0.7, concrete: 0.3, emotionIntensity: 0.6, humor: 0.0, sincerity: 0.9 }, categories: ['abstract', 'emotion'], rhymeGroup: 'ed', stressPattern: 'Su', isProfound: true },
  { id: 'shattered', text: 'shattered', syllables: 2, partOfSpeech: 'adjective', tags: { darkness: 0.7, brightness: 0.1, complexity: 0.3, nature: 0.0, urban: 0.3, abstract: 0.4, concrete: 0.6, emotionIntensity: 0.8, humor: 0.0, sincerity: 0.7 }, categories: ['emotion', 'night', 'power'], rhymeGroup: 'ered', stressPattern: 'Su' },
  { id: 'fleeting', text: 'fleeting', syllables: 2, partOfSpeech: 'adjective', tags: { darkness: 0.3, brightness: 0.4, complexity: 0.3, nature: 0.2, urban: 0.1, abstract: 0.6, concrete: 0.4, emotionIntensity: 0.5, humor: 0.0, sincerity: 0.7 }, categories: ['abstract', 'emotion'], rhymeGroup: 'eeting', stressPattern: 'Su' },
  { id: 'vivid', text: 'vivid', syllables: 2, partOfSpeech: 'adjective', tags: { darkness: 0.1, brightness: 0.8, complexity: 0.3, nature: 0.3, urban: 0.2, abstract: 0.3, concrete: 0.7, emotionIntensity: 0.5, humor: 0.0, sincerity: 0.6 }, categories: ['sensory', 'light'], rhymeGroup: 'ivid', stressPattern: 'Su', isSensory: true },
  { id: 'raw', text: 'raw', syllables: 1, partOfSpeech: 'adjective', tags: { darkness: 0.4, brightness: 0.3, complexity: 0.2, nature: 0.2, urban: 0.3, abstract: 0.3, concrete: 0.7, emotionIntensity: 0.7, humor: 0.0, sincerity: 0.8 }, categories: ['power', 'emotion'], rhymeGroup: 'aw', stressPattern: 'S' },
  { id: 'golden', text: 'golden', syllables: 2, partOfSpeech: 'adjective', tags: { darkness: 0.0, brightness: 0.9, complexity: 0.2, nature: 0.3, urban: 0.2, abstract: 0.3, concrete: 0.7, emotionIntensity: 0.4, humor: 0.0, sincerity: 0.7 }, categories: ['light', 'warmth', 'sensory'], rhymeGroup: 'olden', stressPattern: 'Su', isSensory: true },
  { id: 'silent', text: 'silent', syllables: 2, partOfSpeech: 'adjective', tags: { darkness: 0.4, brightness: 0.3, complexity: 0.2, nature: 0.3, urban: 0.2, abstract: 0.4, concrete: 0.6, emotionIntensity: 0.3, humor: 0.0, sincerity: 0.7 }, categories: ['solitude'], rhymeGroup: 'ent', stressPattern: 'Su' },
  { id: 'vast', text: 'vast', syllables: 1, partOfSpeech: 'adjective', tags: { darkness: 0.3, brightness: 0.4, complexity: 0.3, nature: 0.5, urban: 0.1, abstract: 0.5, concrete: 0.5, emotionIntensity: 0.5, humor: 0.0, sincerity: 0.7 }, categories: ['nature', 'abstract'], rhymeGroup: 'ast', stressPattern: 'S' },

  // ─── Humor / Quirky ────────────────────────────────────────────────────────
  { id: 'peculiar', text: 'peculiar', syllables: 4, partOfSpeech: 'adjective', tags: { darkness: 0.2, brightness: 0.4, complexity: 0.5, nature: 0.1, urban: 0.3, abstract: 0.5, concrete: 0.5, emotionIntensity: 0.3, humor: 0.6, sincerity: 0.4 }, categories: ['surreal', 'literary'], rhymeGroup: 'iar', stressPattern: 'uSuu', isWeird: true },
  { id: 'whimsy', text: 'whimsy', syllables: 2, partOfSpeech: 'noun', tags: { darkness: 0.0, brightness: 0.7, complexity: 0.4, nature: 0.2, urban: 0.1, abstract: 0.6, concrete: 0.4, emotionIntensity: 0.4, humor: 0.8, sincerity: 0.5 }, categories: ['surreal'], rhymeGroup: 'imsy', stressPattern: 'Su', isWeird: true },
  { id: 'ruckus', text: 'ruckus', syllables: 2, partOfSpeech: 'noun', tags: { darkness: 0.2, brightness: 0.4, complexity: 0.2, nature: 0.1, urban: 0.6, abstract: 0.3, concrete: 0.7, emotionIntensity: 0.5, humor: 0.7, sincerity: 0.4 }, categories: ['urban', 'power'], rhymeGroup: 'uckus', stressPattern: 'Su' },
  { id: 'bamboozle', text: 'bamboozle', syllables: 3, partOfSpeech: 'verb', tags: { darkness: 0.1, brightness: 0.4, complexity: 0.4, nature: 0.0, urban: 0.4, abstract: 0.5, concrete: 0.5, emotionIntensity: 0.4, humor: 0.9, sincerity: 0.2 }, categories: ['surreal'], rhymeGroup: 'oozle', stressPattern: 'uSu', isWeird: true },
  { id: 'wobble', text: 'wobble', syllables: 2, partOfSpeech: 'verb', tags: { darkness: 0.1, brightness: 0.4, complexity: 0.2, nature: 0.1, urban: 0.3, abstract: 0.2, concrete: 0.8, emotionIntensity: 0.2, humor: 0.7, sincerity: 0.4 }, categories: ['sensory'], rhymeGroup: 'obble', stressPattern: 'Su' },
  { id: 'absurd', text: 'absurd', syllables: 2, partOfSpeech: 'adjective', tags: { darkness: 0.2, brightness: 0.3, complexity: 0.5, nature: 0.0, urban: 0.3, abstract: 0.7, concrete: 0.3, emotionIntensity: 0.3, humor: 0.8, sincerity: 0.3 }, categories: ['surreal', 'literary'], rhymeGroup: 'urd', stressPattern: 'uS', isWeird: true },

  // ─── Connective / Small Words ──────────────────────────────────────────────
  { id: 'beneath', text: 'beneath', syllables: 2, partOfSpeech: 'preposition', tags: { darkness: 0.3, brightness: 0.3, complexity: 0.2, nature: 0.2, urban: 0.2, abstract: 0.3, concrete: 0.7, emotionIntensity: 0.2, humor: 0.0, sincerity: 0.5 }, categories: [], rhymeGroup: 'eeth', stressPattern: 'uS' },
  { id: 'between', text: 'between', syllables: 2, partOfSpeech: 'preposition', tags: { darkness: 0.2, brightness: 0.3, complexity: 0.3, nature: 0.1, urban: 0.2, abstract: 0.5, concrete: 0.5, emotionIntensity: 0.2, humor: 0.0, sincerity: 0.5 }, categories: [], rhymeGroup: 'een', stressPattern: 'uS' },
  { id: 'through', text: 'through', syllables: 1, partOfSpeech: 'preposition', tags: { darkness: 0.2, brightness: 0.3, complexity: 0.2, nature: 0.1, urban: 0.2, abstract: 0.4, concrete: 0.6, emotionIntensity: 0.2, humor: 0.0, sincerity: 0.5 }, categories: [], rhymeGroup: 'oo', stressPattern: 'S' },
  { id: 'beyond', text: 'beyond', syllables: 2, partOfSpeech: 'preposition', tags: { darkness: 0.3, brightness: 0.4, complexity: 0.3, nature: 0.2, urban: 0.1, abstract: 0.6, concrete: 0.4, emotionIntensity: 0.3, humor: 0.0, sincerity: 0.6 }, categories: ['abstract'], rhymeGroup: 'ond', stressPattern: 'uS' },
  { id: 'within', text: 'within', syllables: 2, partOfSpeech: 'preposition', tags: { darkness: 0.2, brightness: 0.3, complexity: 0.3, nature: 0.0, urban: 0.1, abstract: 0.5, concrete: 0.5, emotionIntensity: 0.3, humor: 0.0, sincerity: 0.6 }, categories: [], rhymeGroup: 'in', stressPattern: 'uS' },
  { id: 'among', text: 'among', syllables: 2, partOfSpeech: 'preposition', tags: { darkness: 0.2, brightness: 0.3, complexity: 0.2, nature: 0.1, urban: 0.2, abstract: 0.4, concrete: 0.6, emotionIntensity: 0.2, humor: 0.0, sincerity: 0.5 }, categories: [], rhymeGroup: 'ong', stressPattern: 'uS' },

  // ─── More Nature ───────────────────────────────────────────────────────────
  { id: 'ocean', text: 'ocean', syllables: 2, partOfSpeech: 'noun', tags: { darkness: 0.3, brightness: 0.5, complexity: 0.3, nature: 1.0, urban: 0.0, abstract: 0.3, concrete: 0.8, emotionIntensity: 0.5, humor: 0.0, sincerity: 0.8 }, categories: ['nature'], rhymeGroup: 'an', stressPattern: 'Su' },
  { id: 'mountain', text: 'mountain', syllables: 2, partOfSpeech: 'noun', tags: { darkness: 0.2, brightness: 0.5, complexity: 0.3, nature: 1.0, urban: 0.0, abstract: 0.2, concrete: 1.0, emotionIntensity: 0.4, humor: 0.0, sincerity: 0.7 }, categories: ['nature'], rhymeGroup: 'ain', stressPattern: 'Su' },
  { id: 'starlight', text: 'starlight', syllables: 2, partOfSpeech: 'noun', tags: { darkness: 0.4, brightness: 0.8, complexity: 0.3, nature: 0.8, urban: 0.0, abstract: 0.4, concrete: 0.7, emotionIntensity: 0.5, humor: 0.0, sincerity: 0.8 }, categories: ['nature', 'night', 'light'], rhymeGroup: 'ight', stressPattern: 'Su', isMusical: true },
  { id: 'seed', text: 'seed', syllables: 1, partOfSpeech: 'noun', tags: { darkness: 0.1, brightness: 0.5, complexity: 0.2, nature: 0.9, urban: 0.0, abstract: 0.3, concrete: 0.8, emotionIntensity: 0.3, humor: 0.0, sincerity: 0.7 }, categories: ['nature', 'flowers'], rhymeGroup: 'eed', stressPattern: 'S' },
  { id: 'storm', text: 'storm', syllables: 1, partOfSpeech: 'noun', tags: { darkness: 0.6, brightness: 0.2, complexity: 0.3, nature: 0.8, urban: 0.2, abstract: 0.3, concrete: 0.8, emotionIntensity: 0.7, humor: 0.0, sincerity: 0.7 }, categories: ['nature', 'power', 'night'], rhymeGroup: 'orm', stressPattern: 'S', isSensory: true },
  { id: 'tide', text: 'tide', syllables: 1, partOfSpeech: 'noun', tags: { darkness: 0.2, brightness: 0.5, complexity: 0.3, nature: 0.9, urban: 0.0, abstract: 0.4, concrete: 0.7, emotionIntensity: 0.4, humor: 0.0, sincerity: 0.7 }, categories: ['nature'], rhymeGroup: 'ide', stressPattern: 'S' },
  { id: 'vine', text: 'vine', syllables: 1, partOfSpeech: 'noun', tags: { darkness: 0.2, brightness: 0.5, complexity: 0.2, nature: 1.0, urban: 0.0, abstract: 0.1, concrete: 1.0, emotionIntensity: 0.2, humor: 0.0, sincerity: 0.6 }, categories: ['nature', 'flowers'], rhymeGroup: 'ine', stressPattern: 'S' },
  { id: 'flame', text: 'flame', syllables: 1, partOfSpeech: 'noun', tags: { darkness: 0.3, brightness: 0.8, complexity: 0.2, nature: 0.4, urban: 0.2, abstract: 0.3, concrete: 0.8, emotionIntensity: 0.7, humor: 0.0, sincerity: 0.7 }, categories: ['warmth', 'light', 'power'], rhymeGroup: 'ame', stressPattern: 'S', isSensory: true },
  { id: 'moonlight', text: 'moonlight', syllables: 2, partOfSpeech: 'noun', tags: { darkness: 0.5, brightness: 0.6, complexity: 0.3, nature: 0.8, urban: 0.1, abstract: 0.4, concrete: 0.7, emotionIntensity: 0.5, humor: 0.0, sincerity: 0.8 }, categories: ['night', 'nature', 'light'], rhymeGroup: 'ight', stressPattern: 'Su', isMusical: true },

  // ─── More Verbs ────────────────────────────────────────────────────────────
  { id: 'weave', text: 'weave', syllables: 1, partOfSpeech: 'verb', tags: { darkness: 0.1, brightness: 0.4, complexity: 0.4, nature: 0.3, urban: 0.2, abstract: 0.4, concrete: 0.6, emotionIntensity: 0.3, humor: 0.0, sincerity: 0.6 }, categories: ['literary'], rhymeGroup: 'eave', stressPattern: 'S' },
  { id: 'cradle', text: 'cradle', syllables: 2, partOfSpeech: 'verb', tags: { darkness: 0.1, brightness: 0.5, complexity: 0.3, nature: 0.1, urban: 0.1, abstract: 0.4, concrete: 0.6, emotionIntensity: 0.5, humor: 0.0, sincerity: 0.8 }, categories: ['warmth', 'emotion'], rhymeGroup: 'adle', stressPattern: 'Su' },
  { id: 'devour', text: 'devour', syllables: 2, partOfSpeech: 'verb', tags: { darkness: 0.5, brightness: 0.2, complexity: 0.4, nature: 0.3, urban: 0.2, abstract: 0.4, concrete: 0.6, emotionIntensity: 0.8, humor: 0.0, sincerity: 0.6 }, categories: ['power', 'sensory'], rhymeGroup: 'our', stressPattern: 'uS' },
  { id: 'surrender', text: 'surrender', syllables: 3, partOfSpeech: 'verb', tags: { darkness: 0.4, brightness: 0.3, complexity: 0.4, nature: 0.0, urban: 0.2, abstract: 0.5, concrete: 0.5, emotionIntensity: 0.7, humor: 0.0, sincerity: 0.8 }, categories: ['emotion'], rhymeGroup: 'ender', stressPattern: 'uSu' },
  { id: 'illuminate', text: 'illuminate', syllables: 4, partOfSpeech: 'verb', tags: { darkness: 0.0, brightness: 1.0, complexity: 0.5, nature: 0.2, urban: 0.2, abstract: 0.5, concrete: 0.5, emotionIntensity: 0.5, humor: 0.0, sincerity: 0.7 }, categories: ['light', 'abstract'], rhymeGroup: 'ate', stressPattern: 'uSuu' },
  { id: 'haunt', text: 'haunt', syllables: 1, partOfSpeech: 'verb', tags: { darkness: 0.8, brightness: 0.1, complexity: 0.4, nature: 0.1, urban: 0.3, abstract: 0.5, concrete: 0.5, emotionIntensity: 0.7, humor: 0.0, sincerity: 0.6 }, categories: ['night', 'emotion'], rhymeGroup: 'aunt', stressPattern: 'S' },
  { id: 'forgive', text: 'forgive', syllables: 2, partOfSpeech: 'verb', tags: { darkness: 0.2, brightness: 0.6, complexity: 0.4, nature: 0.0, urban: 0.1, abstract: 0.6, concrete: 0.4, emotionIntensity: 0.7, humor: 0.0, sincerity: 0.9 }, categories: ['emotion', 'warmth'], rhymeGroup: 'ive', stressPattern: 'uS', isProfound: true },
  { id: 'awaken', text: 'awaken', syllables: 3, partOfSpeech: 'verb', tags: { darkness: 0.1, brightness: 0.7, complexity: 0.3, nature: 0.2, urban: 0.1, abstract: 0.5, concrete: 0.5, emotionIntensity: 0.5, humor: 0.0, sincerity: 0.7 }, categories: ['light', 'abstract'], rhymeGroup: 'aken', stressPattern: 'uSu' },
  { id: 'shatter_v', text: 'shatter', syllables: 2, partOfSpeech: 'verb', tags: { darkness: 0.5, brightness: 0.3, complexity: 0.3, nature: 0.1, urban: 0.3, abstract: 0.3, concrete: 0.8, emotionIntensity: 0.8, humor: 0.0, sincerity: 0.7 }, categories: ['power', 'emotion'], rhymeGroup: 'atter', stressPattern: 'Su', isSensory: true },

  // ─── More Abstract / Emotion ───────────────────────────────────────────────
  { id: 'solace', text: 'solace', syllables: 2, partOfSpeech: 'noun', tags: { darkness: 0.2, brightness: 0.5, complexity: 0.4, nature: 0.1, urban: 0.1, abstract: 0.6, concrete: 0.4, emotionIntensity: 0.6, humor: 0.0, sincerity: 0.9 }, categories: ['emotion', 'solitude'], rhymeGroup: 'ace', stressPattern: 'Su', isProfound: true },
  { id: 'remnant', text: 'remnant', syllables: 2, partOfSpeech: 'noun', tags: { darkness: 0.5, brightness: 0.2, complexity: 0.4, nature: 0.1, urban: 0.3, abstract: 0.4, concrete: 0.6, emotionIntensity: 0.4, humor: 0.0, sincerity: 0.6 }, categories: ['abstract', 'night'], rhymeGroup: 'ant', stressPattern: 'Su' },
  { id: 'reverence', text: 'reverence', syllables: 3, partOfSpeech: 'noun', tags: { darkness: 0.1, brightness: 0.5, complexity: 0.5, nature: 0.1, urban: 0.1, abstract: 0.7, concrete: 0.3, emotionIntensity: 0.6, humor: 0.0, sincerity: 0.95 }, categories: ['emotion', 'literary'], rhymeGroup: 'ence', stressPattern: 'Suu', isProfound: true },
  { id: 'pulse', text: 'pulse', syllables: 1, partOfSpeech: 'noun', tags: { darkness: 0.3, brightness: 0.4, complexity: 0.3, nature: 0.3, urban: 0.3, abstract: 0.4, concrete: 0.7, emotionIntensity: 0.5, humor: 0.0, sincerity: 0.6 }, categories: ['sensory', 'power'], rhymeGroup: 'ulse', stressPattern: 'S', isSensory: true },
  { id: 'tempest', text: 'tempest', syllables: 2, partOfSpeech: 'noun', tags: { darkness: 0.5, brightness: 0.3, complexity: 0.4, nature: 0.6, urban: 0.1, abstract: 0.4, concrete: 0.6, emotionIntensity: 0.8, humor: 0.0, sincerity: 0.7 }, categories: ['nature', 'power', 'literary'], rhymeGroup: 'est', stressPattern: 'Su' },
  { id: 'wound', text: 'wound', syllables: 1, partOfSpeech: 'noun', tags: { darkness: 0.6, brightness: 0.1, complexity: 0.3, nature: 0.0, urban: 0.2, abstract: 0.4, concrete: 0.6, emotionIntensity: 0.8, humor: 0.0, sincerity: 0.7 }, categories: ['emotion', 'night'], rhymeGroup: 'oond', stressPattern: 'S' },
  { id: 'sanctuary', text: 'sanctuary', syllables: 4, partOfSpeech: 'noun', tags: { darkness: 0.1, brightness: 0.6, complexity: 0.5, nature: 0.3, urban: 0.2, abstract: 0.5, concrete: 0.5, emotionIntensity: 0.5, humor: 0.0, sincerity: 0.8 }, categories: ['warmth', 'solitude'], rhymeGroup: 'ary', stressPattern: 'Suuu' },
  { id: 'abyss', text: 'abyss', syllables: 2, partOfSpeech: 'noun', tags: { darkness: 1.0, brightness: 0.0, complexity: 0.5, nature: 0.3, urban: 0.1, abstract: 0.7, concrete: 0.4, emotionIntensity: 0.7, humor: 0.0, sincerity: 0.6 }, categories: ['night', 'abstract'], rhymeGroup: 'iss', stressPattern: 'uS', isProfound: true },
  { id: 'lullaby', text: 'lullaby', syllables: 3, partOfSpeech: 'noun', tags: { darkness: 0.2, brightness: 0.5, complexity: 0.3, nature: 0.1, urban: 0.1, abstract: 0.4, concrete: 0.6, emotionIntensity: 0.5, humor: 0.0, sincerity: 0.8 }, categories: ['warmth', 'solitude'], rhymeGroup: 'y', stressPattern: 'SuS', isMusical: true },
  { id: 'requiem', text: 'requiem', syllables: 3, partOfSpeech: 'noun', tags: { darkness: 0.7, brightness: 0.2, complexity: 0.7, nature: 0.0, urban: 0.1, abstract: 0.6, concrete: 0.4, emotionIntensity: 0.8, humor: 0.0, sincerity: 0.9 }, categories: ['literary', 'night', 'emotion'], rhymeGroup: 'em', stressPattern: 'Suu', isProfound: true, isMusical: true },
  { id: 'reverie', text: 'reverie', syllables: 3, partOfSpeech: 'noun', tags: { darkness: 0.2, brightness: 0.5, complexity: 0.5, nature: 0.2, urban: 0.0, abstract: 0.7, concrete: 0.3, emotionIntensity: 0.4, humor: 0.0, sincerity: 0.7 }, categories: ['surreal', 'abstract'], rhymeGroup: 'ee', stressPattern: 'Suu', isMusical: true },
  { id: 'obsidian', text: 'obsidian', syllables: 4, partOfSpeech: 'noun', tags: { darkness: 0.9, brightness: 0.1, complexity: 0.5, nature: 0.5, urban: 0.1, abstract: 0.3, concrete: 0.8, emotionIntensity: 0.4, humor: 0.0, sincerity: 0.6 }, categories: ['night', 'nature', 'sensory'], rhymeGroup: 'ian', stressPattern: 'uSuu', isSensory: true },
  { id: 'gossamer', text: 'gossamer', syllables: 3, partOfSpeech: 'noun', tags: { darkness: 0.1, brightness: 0.7, complexity: 0.5, nature: 0.5, urban: 0.0, abstract: 0.4, concrete: 0.6, emotionIntensity: 0.3, humor: 0.0, sincerity: 0.6 }, categories: ['nature', 'sensory', 'light'], rhymeGroup: 'amer', stressPattern: 'Suu', isSensory: true, isRare: true },
  { id: 'zephyr', text: 'zephyr', syllables: 2, partOfSpeech: 'noun', tags: { darkness: 0.1, brightness: 0.6, complexity: 0.5, nature: 0.8, urban: 0.0, abstract: 0.4, concrete: 0.6, emotionIntensity: 0.3, humor: 0.0, sincerity: 0.6 }, categories: ['nature', 'light'], rhymeGroup: 'er', stressPattern: 'Su', isRare: true, isMusical: true },
  { id: 'aurora', text: 'aurora', syllables: 3, partOfSpeech: 'noun', tags: { darkness: 0.2, brightness: 0.9, complexity: 0.5, nature: 0.7, urban: 0.0, abstract: 0.4, concrete: 0.7, emotionIntensity: 0.5, humor: 0.0, sincerity: 0.7 }, categories: ['nature', 'light'], rhymeGroup: 'ora', stressPattern: 'uSu', isSensory: true },

  // ─── More Adjectives / Adverbs ─────────────────────────────────────────────
  { id: 'quietly', text: 'quietly', syllables: 3, partOfSpeech: 'adverb', tags: { darkness: 0.3, brightness: 0.3, complexity: 0.2, nature: 0.2, urban: 0.1, abstract: 0.4, concrete: 0.6, emotionIntensity: 0.3, humor: 0.0, sincerity: 0.7 }, categories: ['solitude'], rhymeGroup: 'ly', stressPattern: 'Suu' },
  { id: 'fiercely', text: 'fiercely', syllables: 2, partOfSpeech: 'adverb', tags: { darkness: 0.3, brightness: 0.4, complexity: 0.3, nature: 0.2, urban: 0.2, abstract: 0.3, concrete: 0.7, emotionIntensity: 0.8, humor: 0.0, sincerity: 0.7 }, categories: ['power'], rhymeGroup: 'ly', stressPattern: 'Su' },
  { id: 'softly', text: 'softly', syllables: 2, partOfSpeech: 'adverb', tags: { darkness: 0.1, brightness: 0.5, complexity: 0.1, nature: 0.2, urban: 0.1, abstract: 0.3, concrete: 0.7, emotionIntensity: 0.3, humor: 0.0, sincerity: 0.8 }, categories: ['warmth', 'solitude'], rhymeGroup: 'ly', stressPattern: 'Su' },
  { id: 'slowly', text: 'slowly', syllables: 2, partOfSpeech: 'adverb', tags: { darkness: 0.2, brightness: 0.3, complexity: 0.1, nature: 0.2, urban: 0.1, abstract: 0.3, concrete: 0.7, emotionIntensity: 0.3, humor: 0.0, sincerity: 0.6 }, categories: [], rhymeGroup: 'ly', stressPattern: 'Su' },
  { id: 'deeply', text: 'deeply', syllables: 2, partOfSpeech: 'adverb', tags: { darkness: 0.3, brightness: 0.3, complexity: 0.3, nature: 0.1, urban: 0.1, abstract: 0.5, concrete: 0.5, emotionIntensity: 0.6, humor: 0.0, sincerity: 0.8 }, categories: ['emotion', 'abstract'], rhymeGroup: 'ly', stressPattern: 'Su' },

  // ─── Extra Nouns to Hit 200+ ───────────────────────────────────────────────
  { id: 'candle', text: 'candle', syllables: 2, partOfSpeech: 'noun', tags: { darkness: 0.3, brightness: 0.6, complexity: 0.1, nature: 0.1, urban: 0.3, abstract: 0.2, concrete: 0.9, emotionIntensity: 0.3, humor: 0.0, sincerity: 0.7 }, categories: ['warmth', 'light'], rhymeGroup: 'andle', stressPattern: 'Su', isSensory: true },
  { id: 'mirror', text: 'mirror', syllables: 2, partOfSpeech: 'noun', tags: { darkness: 0.3, brightness: 0.5, complexity: 0.4, nature: 0.0, urban: 0.4, abstract: 0.5, concrete: 0.6, emotionIntensity: 0.4, humor: 0.0, sincerity: 0.5 }, categories: ['abstract', 'surreal'], rhymeGroup: 'irror', stressPattern: 'Su' },
  { id: 'ink', text: 'ink', syllables: 1, partOfSpeech: 'noun', tags: { darkness: 0.6, brightness: 0.2, complexity: 0.3, nature: 0.0, urban: 0.4, abstract: 0.3, concrete: 0.9, emotionIntensity: 0.3, humor: 0.0, sincerity: 0.6 }, categories: ['literary', 'night'], rhymeGroup: 'ink', stressPattern: 'S' },
  { id: 'oath', text: 'oath', syllables: 1, partOfSpeech: 'noun', tags: { darkness: 0.3, brightness: 0.4, complexity: 0.4, nature: 0.0, urban: 0.2, abstract: 0.6, concrete: 0.4, emotionIntensity: 0.6, humor: 0.0, sincerity: 0.9 }, categories: ['literary', 'emotion'], rhymeGroup: 'oath', stressPattern: 'S', isProfound: true },
  { id: 'scar', text: 'scar', syllables: 1, partOfSpeech: 'noun', tags: { darkness: 0.6, brightness: 0.1, complexity: 0.3, nature: 0.0, urban: 0.3, abstract: 0.4, concrete: 0.7, emotionIntensity: 0.7, humor: 0.0, sincerity: 0.7 }, categories: ['emotion', 'night'], rhymeGroup: 'ar', stressPattern: 'S' },
  { id: 'crown', text: 'crown', syllables: 1, partOfSpeech: 'noun', tags: { darkness: 0.2, brightness: 0.6, complexity: 0.4, nature: 0.0, urban: 0.4, abstract: 0.4, concrete: 0.7, emotionIntensity: 0.5, humor: 0.0, sincerity: 0.5 }, categories: ['power', 'literary'], rhymeGroup: 'own', stressPattern: 'S' },
  { id: 'lantern', text: 'lantern', syllables: 2, partOfSpeech: 'noun', tags: { darkness: 0.3, brightness: 0.7, complexity: 0.2, nature: 0.2, urban: 0.3, abstract: 0.2, concrete: 0.9, emotionIntensity: 0.3, humor: 0.0, sincerity: 0.7 }, categories: ['light', 'warmth'], rhymeGroup: 'ern', stressPattern: 'Su', isSensory: true },
  { id: 'compass', text: 'compass', syllables: 2, partOfSpeech: 'noun', tags: { darkness: 0.1, brightness: 0.4, complexity: 0.4, nature: 0.2, urban: 0.3, abstract: 0.4, concrete: 0.7, emotionIntensity: 0.3, humor: 0.0, sincerity: 0.6 }, categories: ['abstract'], rhymeGroup: 'ass', stressPattern: 'Su' },
  { id: 'threshold', text: 'threshold', syllables: 2, partOfSpeech: 'noun', tags: { darkness: 0.3, brightness: 0.4, complexity: 0.5, nature: 0.1, urban: 0.3, abstract: 0.6, concrete: 0.5, emotionIntensity: 0.4, humor: 0.0, sincerity: 0.6 }, categories: ['abstract', 'literary'], rhymeGroup: 'old', stressPattern: 'Su', isProfound: true },
  { id: 'dust', text: 'dust', syllables: 1, partOfSpeech: 'noun', tags: { darkness: 0.5, brightness: 0.2, complexity: 0.2, nature: 0.3, urban: 0.4, abstract: 0.3, concrete: 0.8, emotionIntensity: 0.3, humor: 0.0, sincerity: 0.6 }, categories: ['nature', 'night'], rhymeGroup: 'ust', stressPattern: 'S' },
  { id: 'crystal', text: 'crystal', syllables: 2, partOfSpeech: 'noun', tags: { darkness: 0.1, brightness: 0.8, complexity: 0.4, nature: 0.5, urban: 0.2, abstract: 0.3, concrete: 0.8, emotionIntensity: 0.3, humor: 0.0, sincerity: 0.6 }, categories: ['nature', 'light', 'sensory'], rhymeGroup: 'al', stressPattern: 'Su', isSensory: true },
  { id: 'harbor', text: 'harbor', syllables: 2, partOfSpeech: 'noun', tags: { darkness: 0.2, brightness: 0.4, complexity: 0.3, nature: 0.5, urban: 0.4, abstract: 0.3, concrete: 0.7, emotionIntensity: 0.4, humor: 0.0, sincerity: 0.7 }, categories: ['nature', 'warmth', 'solitude'], rhymeGroup: 'or', stressPattern: 'Su' },
  { id: 'music', text: 'music', syllables: 2, partOfSpeech: 'noun', tags: { darkness: 0.1, brightness: 0.6, complexity: 0.3, nature: 0.1, urban: 0.3, abstract: 0.5, concrete: 0.5, emotionIntensity: 0.6, humor: 0.0, sincerity: 0.7 }, categories: ['sensory', 'warmth'], rhymeGroup: 'ic', stressPattern: 'Su', isMusical: true, isSensory: true },
  { id: 'ashes', text: 'ashes', syllables: 2, partOfSpeech: 'noun', tags: { darkness: 0.7, brightness: 0.1, complexity: 0.3, nature: 0.2, urban: 0.3, abstract: 0.4, concrete: 0.7, emotionIntensity: 0.5, humor: 0.0, sincerity: 0.6 }, categories: ['night', 'warmth'], rhymeGroup: 'ashes', stressPattern: 'Su' },
  { id: 'cathedral', text: 'cathedral', syllables: 3, partOfSpeech: 'noun', tags: { darkness: 0.3, brightness: 0.5, complexity: 0.6, nature: 0.1, urban: 0.5, abstract: 0.4, concrete: 0.7, emotionIntensity: 0.5, humor: 0.0, sincerity: 0.7 }, categories: ['urban', 'literary'], rhymeGroup: 'al', stressPattern: 'uSu' },
  { id: 'constellation', text: 'constellation', syllables: 4, partOfSpeech: 'noun', tags: { darkness: 0.3, brightness: 0.7, complexity: 0.6, nature: 0.7, urban: 0.0, abstract: 0.5, concrete: 0.6, emotionIntensity: 0.5, humor: 0.0, sincerity: 0.7 }, categories: ['nature', 'night', 'light'], rhymeGroup: 'ation', stressPattern: 'SuuSu', isRare: true },
];

// ─── Lookup Map ──────────────────────────────────────────────────────────────

const WORD_MAP = new Map<string, Word>();
for (const word of WORD_DATABASE) {
  WORD_MAP.set(word.id, word);
}

// ─── Public API ──────────────────────────────────────────────────────────────

/**
 * Get a pool of words for a puzzle, optionally biased toward given categories.
 * Returns `count` words, mixing category matches with random picks.
 */
export function getWordPool(count: number, preferredCategories: string[] = []): Word[] {
  // Separate words into category matches and others
  const categoryMatches: Word[] = [];
  const others: Word[] = [];

  for (const word of WORD_DATABASE) {
    if (preferredCategories.some(cat => word.categories.includes(cat))) {
      categoryMatches.push(word);
    } else {
      others.push(word);
    }
  }

  // Shuffle both pools
  shuffle(categoryMatches);
  shuffle(others);

  // Take ~60% from category matches, rest from others
  const categoryCount = Math.min(Math.ceil(count * 0.6), categoryMatches.length);
  const otherCount = Math.min(count - categoryCount, others.length);

  const result = [
    ...categoryMatches.slice(0, categoryCount),
    ...others.slice(0, otherCount),
  ];

  // If we still need more, fill from whichever pool has leftovers
  while (result.length < count) {
    if (result.length < categoryMatches.length) {
      result.push(categoryMatches[result.length]);
    } else if (others.length > otherCount) {
      result.push(others[otherCount + (result.length - count)]);
    } else {
      break;
    }
  }

  // Final shuffle so category words aren't all grouped together
  shuffle(result);
  return result.slice(0, count);
}

/**
 * Look up Word objects by their IDs.
 */
export function getWordsByIds(ids: string[]): Word[] {
  const result: Word[] = [];
  for (const id of ids) {
    const word = WORD_MAP.get(id);
    if (word) result.push(word);
  }
  return result;
}

/**
 * Fisher-Yates shuffle (in-place).
 */
function shuffle<T>(arr: T[]): T[] {
  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [arr[i], arr[j]] = [arr[j], arr[i]];
  }
  return arr;
}
