{{- if .Values.data.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "rmhstudios.fullname" . }}-data
  labels:
    {{- include "rmhstudios.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce   # MULTI-NODE SEAM: ReadWriteMany for multi-node
  storageClassName: {{ .Values.data.storageClass | quote }}
  resources:
    requests:
      storage: {{ .Values.data.size | quote }}
{{- end }}
