'use client';

import { useEffect, useRef, useState } from 'react';
import { ImagePlus, Loader2, Sparkles, Star, Wand2, X } from 'lucide-react';
import { toast } from 'sonner';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';

interface ImageUploaderProps {
  value: string[];
  /** Subset of `value` that was AI-generated. */
  aiImages: string[];
  onChange: (images: string[], aiImages: string[]) => void;
  max?: number;
}

/** Upload endpoint accepts up to 4 files per request. */
const CHUNK = 4;

/**
 * Multi-photo manager for a listing. Photos can be uploaded (posted to the
 * shared /api/rmharks/image endpoint) or generated with AI (xAI, via
 * /api/homes/ai-image) from a text prompt. The first image is the cover;
 * AI-generated photos are tagged so the listing shows a "Generated by AI"
 * disclaimer on them.
 */
export function ImageUploader({ value, aiImages, onChange, max = 8 }: ImageUploaderProps) {
  const [uploading, setUploading] = useState(false);
  const [aiOpen, setAiOpen] = useState(false);
  const [aiAvailable, setAiAvailable] = useState(false);
  const [aiPrompt, setAiPrompt] = useState('');
  const [generating, setGenerating] = useState(false);
  const inputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    let cancelled = false;
    fetch('/api/homes/ai-image')
      .then((r) => (r.ok ? r.json() : { available: false }))
      .then((d) => {
        if (!cancelled) setAiAvailable(Boolean(d.available));
      })
      .catch(() => {});
    return () => {
      cancelled = true;
    };
  }, []);

  const atMax = value.length >= max;

  async function handleFiles(fileList: FileList | null) {
    if (!fileList || fileList.length === 0) return;
    const remaining = max - value.length;
    if (remaining <= 0) {
      toast.error(`You can add up to ${max} photos.`);
      return;
    }
    const files = Array.from(fileList).slice(0, remaining);
    setUploading(true);
    try {
      const collected: string[] = [];
      for (let i = 0; i < files.length; i += CHUNK) {
        const form = new FormData();
        for (const f of files.slice(i, i + CHUNK)) form.append('images', f);
        const res = await fetch('/api/rmharks/image', { method: 'POST', body: form });
        if (!res.ok) {
          const data = await res.json().catch(() => ({}));
          throw new Error(data.error || 'Upload failed');
        }
        const data = await res.json();
        collected.push(...(data.urls ?? []));
      }
      onChange([...value, ...collected].slice(0, max), aiImages);
    } catch (err) {
      toast.error(err instanceof Error ? err.message : 'Upload failed');
    } finally {
      setUploading(false);
      if (inputRef.current) inputRef.current.value = '';
    }
  }

  async function generate() {
    const prompt = aiPrompt.trim();
    if (prompt.length < 3) {
      toast.error('Describe the photo you want to generate.');
      return;
    }
    if (atMax) {
      toast.error(`You can add up to ${max} photos.`);
      return;
    }
    setGenerating(true);
    try {
      const res = await fetch('/api/homes/ai-image', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ prompt }),
      });
      const data = await res.json().catch(() => ({}));
      if (!res.ok || !data.url) throw new Error(data.error || 'Could not generate an image.');
      onChange([...value, data.url].slice(0, max), [...aiImages, data.url]);
      setAiPrompt('');
      toast.success('Image generated');
    } catch (err) {
      toast.error(err instanceof Error ? err.message : 'Could not generate an image.');
    } finally {
      setGenerating(false);
    }
  }

  function remove(url: string) {
    onChange(
      value.filter((u) => u !== url),
      aiImages.filter((u) => u !== url),
    );
  }

  function makeCover(url: string) {
    onChange([url, ...value.filter((u) => u !== url)], aiImages);
  }

  return (
    <div>
      <div className="grid grid-cols-3 gap-2 sm:grid-cols-4">
        {value.map((url, i) => {
          const isAi = aiImages.includes(url);
          return (
            <div
              key={url}
              className="group relative aspect-square overflow-hidden rounded-site-sm border border-site-border bg-site-bg"
            >
              <img src={url} alt="" className="h-full w-full object-cover" />
              {i === 0 && (
                <span className="absolute left-1 top-1 inline-flex items-center gap-1 rounded-full bg-black/60 px-1.5 py-0.5 text-[10px] font-medium text-white">
                  <Star className="h-3 w-3 fill-current" /> Cover
                </span>
              )}
              {isAi && (
                <span className="absolute bottom-1 left-1 inline-flex items-center gap-1 rounded-full bg-site-accent/90 px-1.5 py-0.5 text-[10px] font-semibold text-site-accent-fg">
                  <Sparkles className="h-3 w-3" /> AI
                </span>
              )}
              <div className="absolute inset-0 flex items-start justify-end gap-1 p-1 opacity-0 transition-opacity group-hover:opacity-100">
                {i !== 0 && (
                  <button
                    type="button"
                    onClick={() => makeCover(url)}
                    aria-label="Make cover photo"
                    className="grid h-7 w-7 place-items-center rounded-full bg-black/60 text-white hover:bg-black/80"
                  >
                    <Star className="h-3.5 w-3.5" />
                  </button>
                )}
                <button
                  type="button"
                  onClick={() => remove(url)}
                  aria-label="Remove photo"
                  className="grid h-7 w-7 place-items-center rounded-full bg-black/60 text-white hover:bg-black/80"
                >
                  <X className="h-3.5 w-3.5" />
                </button>
              </div>
            </div>
          );
        })}

        {!atMax && (
          <button
            type="button"
            onClick={() => inputRef.current?.click()}
            disabled={uploading}
            className="flex aspect-square flex-col items-center justify-center gap-1 rounded-site-sm border border-dashed border-site-border text-site-text-muted transition-colors hover:border-site-accent/50 hover:text-site-text disabled:opacity-50"
          >
            {uploading ? (
              <Loader2 className="h-5 w-5 animate-spin" />
            ) : (
              <>
                <ImagePlus className="h-5 w-5" />
                <span className="text-xs">Upload</span>
              </>
            )}
          </button>
        )}
      </div>

      <input
        ref={inputRef}
        type="file"
        accept="image/png,image/jpeg,image/webp,image/gif"
        multiple
        className="hidden"
        onChange={(e) => handleFiles(e.target.files)}
      />

      <div className="mt-2 flex flex-wrap items-center gap-x-3 gap-y-1">
        <p className="text-xs text-site-text-muted">
          Up to {max} photos. The first is the cover — hover to set cover or remove.
        </p>
        {aiAvailable && (
          <button
            type="button"
            onClick={() => setAiOpen((v) => !v)}
            className="inline-flex items-center gap-1 text-xs font-medium text-site-accent hover:underline"
          >
            <Wand2 className="h-3.5 w-3.5" />
            {aiOpen ? 'Hide AI generator' : 'Generate with AI'}
          </button>
        )}
      </div>

      {aiAvailable && aiOpen && (
        <div className="mt-2 rounded-site border border-site-border bg-site-surface p-3">
          <label
            htmlFor="ai-prompt"
            className="mb-1.5 flex items-center gap-1.5 text-sm font-medium text-site-text"
          >
            <Sparkles className="h-4 w-4 text-site-accent" /> Generate a photo with AI
          </label>
          <Textarea
            id="ai-prompt"
            value={aiPrompt}
            maxLength={500}
            onChange={(e) => setAiPrompt(e.target.value)}
            placeholder="e.g. bright modern living room with hardwood floors and large windows"
            className="min-h-16"
            disabled={generating || atMax}
          />
          <div className="mt-2 flex items-center gap-2">
            <Button type="button" size="sm" onClick={generate} loading={generating} disabled={atMax}>
              {!generating && <Sparkles className="h-4 w-4" />}
              Generate
            </Button>
            <span className="text-xs text-site-text-muted">
              AI photos are labeled “Generated by AI” on your listing.
            </span>
          </div>
        </div>
      )}
    </div>
  );
}
