/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoidBreakerRouteImport } from './routes/void-breaker'
import { Route as VersecraftRouteImport } from './routes/versecraft'
import { Route as Velum2099RouteImport } from './routes/velum2099'
import { Route as TempleOfJoyRouteImport } from './routes/temple-of-joy'
import { Route as SynapseStormRouteImport } from './routes/synapse-storm'
import { Route as SliceItRouteImport } from './routes/slice-it'
import { Route as SecretRouteImport } from './routes/secret'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as RmhtypeRouteImport } from './routes/rmhtype'
import { Route as RmhtubeRouteImport } from './routes/rmhtube'
import { Route as RmhstudyRouteImport } from './routes/rmhstudy'
import { Route as RmhmusicRouteImport } from './routes/rmhmusic'
import { Route as RmhboxRouteImport } from './routes/rmhbox'
import { Route as NeonDriftwayRouteImport } from './routes/neon-driftway'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LightsOutRouteImport } from './routes/lights-out'
import { Route as LaundrySortRouteImport } from './routes/laundry-sort'
import { Route as KowloonKnockoutRouteImport } from './routes/kowloon-knockout'
import { Route as ForestExplorerRouteImport } from './routes/forest-explorer'
import { Route as AltairRouteImport } from './routes/altair'
import { Route as BuildsRouteRouteImport } from './routes/builds/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VersecraftIndexRouteImport } from './routes/versecraft/index'
import { Route as UserBuildsIndexRouteImport } from './routes/user-builds/index'
import { Route as TempleOfJoyIndexRouteImport } from './routes/temple-of-joy/index'
import { Route as SliceItIndexRouteImport } from './routes/slice-it/index'
import { Route as SecretIndexRouteImport } from './routes/secret/index'
import { Route as RmhtypeIndexRouteImport } from './routes/rmhtype/index'
import { Route as RmhtubeIndexRouteImport } from './routes/rmhtube/index'
import { Route as RmhstudyIndexRouteImport } from './routes/rmhstudy/index'
import { Route as RmhmusicIndexRouteImport } from './routes/rmhmusic/index'
import { Route as RmhcodeIndexRouteImport } from './routes/rmhcode/index'
import { Route as RmhboxIndexRouteImport } from './routes/rmhbox/index'
import { Route as ResearchIndexRouteImport } from './routes/research/index'
import { Route as NewsIndexRouteImport } from './routes/news/index'
import { Route as MessagesIndexRouteImport } from './routes/messages/index'
import { Route as KowloonKnockoutIndexRouteImport } from './routes/kowloon-knockout/index'
import { Route as ForestExplorerIndexRouteImport } from './routes/forest-explorer/index'
import { Route as BuildsIndexRouteImport } from './routes/builds/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as AltairIndexRouteImport } from './routes/altair/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as UserBuildsSubmitRouteImport } from './routes/user-builds/submit'
import { Route as UserBuildsManageRouteImport } from './routes/user-builds/manage'
import { Route as UserBuildsSlugRouteImport } from './routes/user-builds/$slug'
import { Route as SecretWeatherRouteImport } from './routes/secret/weather'
import { Route as SecretVegaRouteImport } from './routes/secret/vega'
import { Route as SecretSlidesRouteImport } from './routes/secret/slides'
import { Route as SecretSignalForgeRouteImport } from './routes/secret/signal-forge'
import { Route as SecretSheetsRouteImport } from './routes/secret/sheets'
import { Route as SecretNotesRouteImport } from './routes/secret/notes'
import { Route as SecretJobsRouteImport } from './routes/secret/jobs'
import { Route as SecretHouseAlwaysWinsRouteImport } from './routes/secret/house-always-wins'
import { Route as SecretEatsRouteImport } from './routes/secret/eats'
import { Route as SecretDreamRiftRouteImport } from './routes/secret/dream-rift'
import { Route as SecretDocsRouteImport } from './routes/secret/docs'
import { Route as SecretCursedLogicRouteImport } from './routes/secret/cursed-logic'
import { Route as RmhtypeSoloRouteImport } from './routes/rmhtype/solo'
import { Route as RmhtypeMultiplayerRouteImport } from './routes/rmhtype/multiplayer'
import { Route as RmhtypeRoomIdRouteImport } from './routes/rmhtype/$roomId'
import { Route as RmhtubeRoomIdRouteImport } from './routes/rmhtube/$roomId'
import { Route as RmhstudyRoomIdRouteImport } from './routes/rmhstudy/$roomId'
import { Route as RmhmusicPlayerRouteImport } from './routes/rmhmusic/player'
import { Route as RmhmusicRoomIdRouteImport } from './routes/rmhmusic/$roomId'
import { Route as RmhcodeAuthRouteImport } from './routes/rmhcode/auth'
import { Route as RmhboxLobbyIdRouteImport } from './routes/rmhbox/$lobbyId'
import { Route as ResearchCallRouteImport } from './routes/research/call'
import { Route as ResearchSlugRouteImport } from './routes/research/$slug'
import { Route as ProfileIdRouteImport } from './routes/profile/$id'
import { Route as NewsSlugRouteImport } from './routes/news/$slug'
import { Route as MessagesConversationIdRouteImport } from './routes/messages/$conversationId'
import { Route as ForestExplorerStoryRouteImport } from './routes/forest-explorer/story'
import { Route as ForestExplorerExploreRouteImport } from './routes/forest-explorer/explore'
import { Route as BuildsGamesRouteImport } from './routes/builds/games'
import { Route as BuildsAppsRouteImport } from './routes/builds/apps'
import { Route as BuildsSlugRouteImport } from './routes/builds/$slug'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as AltairMultiplayerRouteImport } from './routes/altair/multiplayer'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminUserBuildsRouteImport } from './routes/admin/user-builds'
import { Route as SecretWeatherIndexRouteImport } from './routes/secret/weather/index'
import { Route as SecretSlidesIndexRouteImport } from './routes/secret/slides/index'
import { Route as SecretSheetsIndexRouteImport } from './routes/secret/sheets/index'
import { Route as SecretNotesIndexRouteImport } from './routes/secret/notes/index'
import { Route as SecretJobsIndexRouteImport } from './routes/secret/jobs/index'
import { Route as SecretDocsIndexRouteImport } from './routes/secret/docs/index'
import { Route as SecretCursedLogicIndexRouteImport } from './routes/secret/cursed-logic/index'
import { Route as RmhboxMinigamesIndexRouteImport } from './routes/rmhbox/minigames/index'
import { Route as AltairMultiplayerIndexRouteImport } from './routes/altair/multiplayer/index'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminUserBuildsIndexRouteImport } from './routes/admin/user-builds/index'
import { Route as AdminCuratedBuildsIndexRouteImport } from './routes/admin/curated-builds/index'
import { Route as AdminBlogIndexRouteImport } from './routes/admin/blog/index'
import { Route as SecretJobsApplicationsRouteImport } from './routes/secret/jobs/applications'
import { Route as SecretJobsIdRouteImport } from './routes/secret/jobs/$id'
import { Route as AltairMultiplayerLobbyIdRouteImport } from './routes/altair/multiplayer/$lobbyId'
import { Route as AdminBlogNewRouteImport } from './routes/admin/blog/new'
import { Route as UseridPostPostidRouteImport } from './routes/$userid/post/$postid'
import { Route as SecretJobsAssessmentIdRouteImport } from './routes/secret/jobs/assessment/$id'
import { Route as RmhboxMinigamesMinigameIdHistoryRouteImport } from './routes/rmhbox/minigames/$minigameId/history'
import { Route as AdminCuratedBuildsIdEditRouteImport } from './routes/admin/curated-builds/$id/edit'
import { Route as AdminBlogSlugEditRouteImport } from './routes/admin/blog/$slug/edit'

const VoidBreakerRoute = VoidBreakerRouteImport.update({
  id: '/void-breaker',
  path: '/void-breaker',
  getParentRoute: () => rootRouteImport,
} as any)
const VersecraftRoute = VersecraftRouteImport.update({
  id: '/versecraft',
  path: '/versecraft',
  getParentRoute: () => rootRouteImport,
} as any)
const Velum2099Route = Velum2099RouteImport.update({
  id: '/velum2099',
  path: '/velum2099',
  getParentRoute: () => rootRouteImport,
} as any)
const TempleOfJoyRoute = TempleOfJoyRouteImport.update({
  id: '/temple-of-joy',
  path: '/temple-of-joy',
  getParentRoute: () => rootRouteImport,
} as any)
const SynapseStormRoute = SynapseStormRouteImport.update({
  id: '/synapse-storm',
  path: '/synapse-storm',
  getParentRoute: () => rootRouteImport,
} as any)
const SliceItRoute = SliceItRouteImport.update({
  id: '/slice-it',
  path: '/slice-it',
  getParentRoute: () => rootRouteImport,
} as any)
const SecretRoute = SecretRouteImport.update({
  id: '/secret',
  path: '/secret',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const RmhtypeRoute = RmhtypeRouteImport.update({
  id: '/rmhtype',
  path: '/rmhtype',
  getParentRoute: () => rootRouteImport,
} as any)
const RmhtubeRoute = RmhtubeRouteImport.update({
  id: '/rmhtube',
  path: '/rmhtube',
  getParentRoute: () => rootRouteImport,
} as any)
const RmhstudyRoute = RmhstudyRouteImport.update({
  id: '/rmhstudy',
  path: '/rmhstudy',
  getParentRoute: () => rootRouteImport,
} as any)
const RmhmusicRoute = RmhmusicRouteImport.update({
  id: '/rmhmusic',
  path: '/rmhmusic',
  getParentRoute: () => rootRouteImport,
} as any)
const RmhboxRoute = RmhboxRouteImport.update({
  id: '/rmhbox',
  path: '/rmhbox',
  getParentRoute: () => rootRouteImport,
} as any)
const NeonDriftwayRoute = NeonDriftwayRouteImport.update({
  id: '/neon-driftway',
  path: '/neon-driftway',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LightsOutRoute = LightsOutRouteImport.update({
  id: '/lights-out',
  path: '/lights-out',
  getParentRoute: () => rootRouteImport,
} as any)
const LaundrySortRoute = LaundrySortRouteImport.update({
  id: '/laundry-sort',
  path: '/laundry-sort',
  getParentRoute: () => rootRouteImport,
} as any)
const KowloonKnockoutRoute = KowloonKnockoutRouteImport.update({
  id: '/kowloon-knockout',
  path: '/kowloon-knockout',
  getParentRoute: () => rootRouteImport,
} as any)
const ForestExplorerRoute = ForestExplorerRouteImport.update({
  id: '/forest-explorer',
  path: '/forest-explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const AltairRoute = AltairRouteImport.update({
  id: '/altair',
  path: '/altair',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildsRouteRoute = BuildsRouteRouteImport.update({
  id: '/builds',
  path: '/builds',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VersecraftIndexRoute = VersecraftIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VersecraftRoute,
} as any)
const UserBuildsIndexRoute = UserBuildsIndexRouteImport.update({
  id: '/user-builds/',
  path: '/user-builds/',
  getParentRoute: () => rootRouteImport,
} as any)
const TempleOfJoyIndexRoute = TempleOfJoyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TempleOfJoyRoute,
} as any)
const SliceItIndexRoute = SliceItIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SliceItRoute,
} as any)
const SecretIndexRoute = SecretIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SecretRoute,
} as any)
const RmhtypeIndexRoute = RmhtypeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RmhtypeRoute,
} as any)
const RmhtubeIndexRoute = RmhtubeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RmhtubeRoute,
} as any)
const RmhstudyIndexRoute = RmhstudyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RmhstudyRoute,
} as any)
const RmhmusicIndexRoute = RmhmusicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RmhmusicRoute,
} as any)
const RmhcodeIndexRoute = RmhcodeIndexRouteImport.update({
  id: '/rmhcode/',
  path: '/rmhcode/',
  getParentRoute: () => rootRouteImport,
} as any)
const RmhboxIndexRoute = RmhboxIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RmhboxRoute,
} as any)
const ResearchIndexRoute = ResearchIndexRouteImport.update({
  id: '/research/',
  path: '/research/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesIndexRoute = MessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => rootRouteImport,
} as any)
const KowloonKnockoutIndexRoute = KowloonKnockoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KowloonKnockoutRoute,
} as any)
const ForestExplorerIndexRoute = ForestExplorerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ForestExplorerRoute,
} as any)
const BuildsIndexRoute = BuildsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BuildsRouteRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AltairIndexRoute = AltairIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AltairRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const UserBuildsSubmitRoute = UserBuildsSubmitRouteImport.update({
  id: '/user-builds/submit',
  path: '/user-builds/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const UserBuildsManageRoute = UserBuildsManageRouteImport.update({
  id: '/user-builds/manage',
  path: '/user-builds/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const UserBuildsSlugRoute = UserBuildsSlugRouteImport.update({
  id: '/user-builds/$slug',
  path: '/user-builds/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SecretWeatherRoute = SecretWeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => SecretRoute,
} as any)
const SecretVegaRoute = SecretVegaRouteImport.update({
  id: '/vega',
  path: '/vega',
  getParentRoute: () => SecretRoute,
} as any)
const SecretSlidesRoute = SecretSlidesRouteImport.update({
  id: '/slides',
  path: '/slides',
  getParentRoute: () => SecretRoute,
} as any)
const SecretSignalForgeRoute = SecretSignalForgeRouteImport.update({
  id: '/signal-forge',
  path: '/signal-forge',
  getParentRoute: () => SecretRoute,
} as any)
const SecretSheetsRoute = SecretSheetsRouteImport.update({
  id: '/sheets',
  path: '/sheets',
  getParentRoute: () => SecretRoute,
} as any)
const SecretNotesRoute = SecretNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => SecretRoute,
} as any)
const SecretJobsRoute = SecretJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => SecretRoute,
} as any)
const SecretHouseAlwaysWinsRoute = SecretHouseAlwaysWinsRouteImport.update({
  id: '/house-always-wins',
  path: '/house-always-wins',
  getParentRoute: () => SecretRoute,
} as any)
const SecretEatsRoute = SecretEatsRouteImport.update({
  id: '/eats',
  path: '/eats',
  getParentRoute: () => SecretRoute,
} as any)
const SecretDreamRiftRoute = SecretDreamRiftRouteImport.update({
  id: '/dream-rift',
  path: '/dream-rift',
  getParentRoute: () => SecretRoute,
} as any)
const SecretDocsRoute = SecretDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => SecretRoute,
} as any)
const SecretCursedLogicRoute = SecretCursedLogicRouteImport.update({
  id: '/cursed-logic',
  path: '/cursed-logic',
  getParentRoute: () => SecretRoute,
} as any)
const RmhtypeSoloRoute = RmhtypeSoloRouteImport.update({
  id: '/solo',
  path: '/solo',
  getParentRoute: () => RmhtypeRoute,
} as any)
const RmhtypeMultiplayerRoute = RmhtypeMultiplayerRouteImport.update({
  id: '/multiplayer',
  path: '/multiplayer',
  getParentRoute: () => RmhtypeRoute,
} as any)
const RmhtypeRoomIdRoute = RmhtypeRoomIdRouteImport.update({
  id: '/$roomId',
  path: '/$roomId',
  getParentRoute: () => RmhtypeRoute,
} as any)
const RmhtubeRoomIdRoute = RmhtubeRoomIdRouteImport.update({
  id: '/$roomId',
  path: '/$roomId',
  getParentRoute: () => RmhtubeRoute,
} as any)
const RmhstudyRoomIdRoute = RmhstudyRoomIdRouteImport.update({
  id: '/$roomId',
  path: '/$roomId',
  getParentRoute: () => RmhstudyRoute,
} as any)
const RmhmusicPlayerRoute = RmhmusicPlayerRouteImport.update({
  id: '/player',
  path: '/player',
  getParentRoute: () => RmhmusicRoute,
} as any)
const RmhmusicRoomIdRoute = RmhmusicRoomIdRouteImport.update({
  id: '/$roomId',
  path: '/$roomId',
  getParentRoute: () => RmhmusicRoute,
} as any)
const RmhcodeAuthRoute = RmhcodeAuthRouteImport.update({
  id: '/rmhcode/auth',
  path: '/rmhcode/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const RmhboxLobbyIdRoute = RmhboxLobbyIdRouteImport.update({
  id: '/$lobbyId',
  path: '/$lobbyId',
  getParentRoute: () => RmhboxRoute,
} as any)
const ResearchCallRoute = ResearchCallRouteImport.update({
  id: '/research/call',
  path: '/research/call',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchSlugRoute = ResearchSlugRouteImport.update({
  id: '/research/$slug',
  path: '/research/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIdRoute = ProfileIdRouteImport.update({
  id: '/profile/$id',
  path: '/profile/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/news/$slug',
  path: '/news/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesConversationIdRoute = MessagesConversationIdRouteImport.update({
  id: '/messages/$conversationId',
  path: '/messages/$conversationId',
  getParentRoute: () => rootRouteImport,
} as any)
const ForestExplorerStoryRoute = ForestExplorerStoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => ForestExplorerRoute,
} as any)
const ForestExplorerExploreRoute = ForestExplorerExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => ForestExplorerRoute,
} as any)
const BuildsGamesRoute = BuildsGamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => BuildsRouteRoute,
} as any)
const BuildsAppsRoute = BuildsAppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => BuildsRouteRoute,
} as any)
const BuildsSlugRoute = BuildsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BuildsRouteRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AltairMultiplayerRoute = AltairMultiplayerRouteImport.update({
  id: '/multiplayer',
  path: '/multiplayer',
  getParentRoute: () => AltairRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUserBuildsRoute = AdminUserBuildsRouteImport.update({
  id: '/user-builds',
  path: '/user-builds',
  getParentRoute: () => AdminRouteRoute,
} as any)
const SecretWeatherIndexRoute = SecretWeatherIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SecretWeatherRoute,
} as any)
const SecretSlidesIndexRoute = SecretSlidesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SecretSlidesRoute,
} as any)
const SecretSheetsIndexRoute = SecretSheetsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SecretSheetsRoute,
} as any)
const SecretNotesIndexRoute = SecretNotesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SecretNotesRoute,
} as any)
const SecretJobsIndexRoute = SecretJobsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SecretJobsRoute,
} as any)
const SecretDocsIndexRoute = SecretDocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SecretDocsRoute,
} as any)
const SecretCursedLogicIndexRoute = SecretCursedLogicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SecretCursedLogicRoute,
} as any)
const RmhboxMinigamesIndexRoute = RmhboxMinigamesIndexRouteImport.update({
  id: '/minigames/',
  path: '/minigames/',
  getParentRoute: () => RmhboxRoute,
} as any)
const AltairMultiplayerIndexRoute = AltairMultiplayerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AltairMultiplayerRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminUsersRoute,
} as any)
const AdminUserBuildsIndexRoute = AdminUserBuildsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminUserBuildsRoute,
} as any)
const AdminCuratedBuildsIndexRoute = AdminCuratedBuildsIndexRouteImport.update({
  id: '/curated-builds/',
  path: '/curated-builds/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBlogIndexRoute = AdminBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const SecretJobsApplicationsRoute = SecretJobsApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => SecretJobsRoute,
} as any)
const SecretJobsIdRoute = SecretJobsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SecretJobsRoute,
} as any)
const AltairMultiplayerLobbyIdRoute =
  AltairMultiplayerLobbyIdRouteImport.update({
    id: '/$lobbyId',
    path: '/$lobbyId',
    getParentRoute: () => AltairMultiplayerRoute,
  } as any)
const AdminBlogNewRoute = AdminBlogNewRouteImport.update({
  id: '/blog/new',
  path: '/blog/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const UseridPostPostidRoute = UseridPostPostidRouteImport.update({
  id: '/$userid/post/$postid',
  path: '/$userid/post/$postid',
  getParentRoute: () => rootRouteImport,
} as any)
const SecretJobsAssessmentIdRoute = SecretJobsAssessmentIdRouteImport.update({
  id: '/assessment/$id',
  path: '/assessment/$id',
  getParentRoute: () => SecretJobsRoute,
} as any)
const RmhboxMinigamesMinigameIdHistoryRoute =
  RmhboxMinigamesMinigameIdHistoryRouteImport.update({
    id: '/minigames/$minigameId/history',
    path: '/minigames/$minigameId/history',
    getParentRoute: () => RmhboxRoute,
  } as any)
const AdminCuratedBuildsIdEditRoute =
  AdminCuratedBuildsIdEditRouteImport.update({
    id: '/curated-builds/$id/edit',
    path: '/curated-builds/$id/edit',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminBlogSlugEditRoute = AdminBlogSlugEditRouteImport.update({
  id: '/blog/$slug/edit',
  path: '/blog/$slug/edit',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/builds': typeof BuildsRouteRouteWithChildren
  '/altair': typeof AltairRouteWithChildren
  '/forest-explorer': typeof ForestExplorerRouteWithChildren
  '/kowloon-knockout': typeof KowloonKnockoutRouteWithChildren
  '/laundry-sort': typeof LaundrySortRoute
  '/lights-out': typeof LightsOutRoute
  '/login': typeof LoginRoute
  '/neon-driftway': typeof NeonDriftwayRoute
  '/rmhbox': typeof RmhboxRouteWithChildren
  '/rmhmusic': typeof RmhmusicRouteWithChildren
  '/rmhstudy': typeof RmhstudyRouteWithChildren
  '/rmhtube': typeof RmhtubeRouteWithChildren
  '/rmhtype': typeof RmhtypeRouteWithChildren
  '/roadmap': typeof RoadmapRoute
  '/secret': typeof SecretRouteWithChildren
  '/slice-it': typeof SliceItRouteWithChildren
  '/synapse-storm': typeof SynapseStormRoute
  '/temple-of-joy': typeof TempleOfJoyRouteWithChildren
  '/velum2099': typeof Velum2099Route
  '/versecraft': typeof VersecraftRouteWithChildren
  '/void-breaker': typeof VoidBreakerRoute
  '/admin/user-builds': typeof AdminUserBuildsRouteWithChildren
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/altair/multiplayer': typeof AltairMultiplayerRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/builds/$slug': typeof BuildsSlugRoute
  '/builds/apps': typeof BuildsAppsRoute
  '/builds/games': typeof BuildsGamesRoute
  '/forest-explorer/explore': typeof ForestExplorerExploreRoute
  '/forest-explorer/story': typeof ForestExplorerStoryRoute
  '/messages/$conversationId': typeof MessagesConversationIdRoute
  '/news/$slug': typeof NewsSlugRoute
  '/profile/$id': typeof ProfileIdRoute
  '/research/$slug': typeof ResearchSlugRoute
  '/research/call': typeof ResearchCallRoute
  '/rmhbox/$lobbyId': typeof RmhboxLobbyIdRoute
  '/rmhcode/auth': typeof RmhcodeAuthRoute
  '/rmhmusic/$roomId': typeof RmhmusicRoomIdRoute
  '/rmhmusic/player': typeof RmhmusicPlayerRoute
  '/rmhstudy/$roomId': typeof RmhstudyRoomIdRoute
  '/rmhtube/$roomId': typeof RmhtubeRoomIdRoute
  '/rmhtype/$roomId': typeof RmhtypeRoomIdRoute
  '/rmhtype/multiplayer': typeof RmhtypeMultiplayerRoute
  '/rmhtype/solo': typeof RmhtypeSoloRoute
  '/secret/cursed-logic': typeof SecretCursedLogicRouteWithChildren
  '/secret/docs': typeof SecretDocsRouteWithChildren
  '/secret/dream-rift': typeof SecretDreamRiftRoute
  '/secret/eats': typeof SecretEatsRoute
  '/secret/house-always-wins': typeof SecretHouseAlwaysWinsRoute
  '/secret/jobs': typeof SecretJobsRouteWithChildren
  '/secret/notes': typeof SecretNotesRouteWithChildren
  '/secret/sheets': typeof SecretSheetsRouteWithChildren
  '/secret/signal-forge': typeof SecretSignalForgeRoute
  '/secret/slides': typeof SecretSlidesRouteWithChildren
  '/secret/vega': typeof SecretVegaRoute
  '/secret/weather': typeof SecretWeatherRouteWithChildren
  '/user-builds/$slug': typeof UserBuildsSlugRoute
  '/user-builds/manage': typeof UserBuildsManageRoute
  '/user-builds/submit': typeof UserBuildsSubmitRoute
  '/admin/': typeof AdminIndexRoute
  '/altair/': typeof AltairIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/builds/': typeof BuildsIndexRoute
  '/forest-explorer/': typeof ForestExplorerIndexRoute
  '/kowloon-knockout/': typeof KowloonKnockoutIndexRoute
  '/messages/': typeof MessagesIndexRoute
  '/news/': typeof NewsIndexRoute
  '/research/': typeof ResearchIndexRoute
  '/rmhbox/': typeof RmhboxIndexRoute
  '/rmhcode/': typeof RmhcodeIndexRoute
  '/rmhmusic/': typeof RmhmusicIndexRoute
  '/rmhstudy/': typeof RmhstudyIndexRoute
  '/rmhtube/': typeof RmhtubeIndexRoute
  '/rmhtype/': typeof RmhtypeIndexRoute
  '/secret/': typeof SecretIndexRoute
  '/slice-it/': typeof SliceItIndexRoute
  '/temple-of-joy/': typeof TempleOfJoyIndexRoute
  '/user-builds/': typeof UserBuildsIndexRoute
  '/versecraft/': typeof VersecraftIndexRoute
  '/$userid/post/$postid': typeof UseridPostPostidRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/altair/multiplayer/$lobbyId': typeof AltairMultiplayerLobbyIdRoute
  '/secret/jobs/$id': typeof SecretJobsIdRoute
  '/secret/jobs/applications': typeof SecretJobsApplicationsRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/admin/curated-builds/': typeof AdminCuratedBuildsIndexRoute
  '/admin/user-builds/': typeof AdminUserBuildsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/altair/multiplayer/': typeof AltairMultiplayerIndexRoute
  '/rmhbox/minigames/': typeof RmhboxMinigamesIndexRoute
  '/secret/cursed-logic/': typeof SecretCursedLogicIndexRoute
  '/secret/docs/': typeof SecretDocsIndexRoute
  '/secret/jobs/': typeof SecretJobsIndexRoute
  '/secret/notes/': typeof SecretNotesIndexRoute
  '/secret/sheets/': typeof SecretSheetsIndexRoute
  '/secret/slides/': typeof SecretSlidesIndexRoute
  '/secret/weather/': typeof SecretWeatherIndexRoute
  '/admin/blog/$slug/edit': typeof AdminBlogSlugEditRoute
  '/admin/curated-builds/$id/edit': typeof AdminCuratedBuildsIdEditRoute
  '/rmhbox/minigames/$minigameId/history': typeof RmhboxMinigamesMinigameIdHistoryRoute
  '/secret/jobs/assessment/$id': typeof SecretJobsAssessmentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/laundry-sort': typeof LaundrySortRoute
  '/lights-out': typeof LightsOutRoute
  '/login': typeof LoginRoute
  '/neon-driftway': typeof NeonDriftwayRoute
  '/roadmap': typeof RoadmapRoute
  '/synapse-storm': typeof SynapseStormRoute
  '/velum2099': typeof Velum2099Route
  '/void-breaker': typeof VoidBreakerRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/builds/$slug': typeof BuildsSlugRoute
  '/builds/apps': typeof BuildsAppsRoute
  '/builds/games': typeof BuildsGamesRoute
  '/forest-explorer/explore': typeof ForestExplorerExploreRoute
  '/forest-explorer/story': typeof ForestExplorerStoryRoute
  '/messages/$conversationId': typeof MessagesConversationIdRoute
  '/news/$slug': typeof NewsSlugRoute
  '/profile/$id': typeof ProfileIdRoute
  '/research/$slug': typeof ResearchSlugRoute
  '/research/call': typeof ResearchCallRoute
  '/rmhbox/$lobbyId': typeof RmhboxLobbyIdRoute
  '/rmhcode/auth': typeof RmhcodeAuthRoute
  '/rmhmusic/$roomId': typeof RmhmusicRoomIdRoute
  '/rmhmusic/player': typeof RmhmusicPlayerRoute
  '/rmhstudy/$roomId': typeof RmhstudyRoomIdRoute
  '/rmhtube/$roomId': typeof RmhtubeRoomIdRoute
  '/rmhtype/$roomId': typeof RmhtypeRoomIdRoute
  '/rmhtype/multiplayer': typeof RmhtypeMultiplayerRoute
  '/rmhtype/solo': typeof RmhtypeSoloRoute
  '/secret/dream-rift': typeof SecretDreamRiftRoute
  '/secret/eats': typeof SecretEatsRoute
  '/secret/house-always-wins': typeof SecretHouseAlwaysWinsRoute
  '/secret/signal-forge': typeof SecretSignalForgeRoute
  '/secret/vega': typeof SecretVegaRoute
  '/user-builds/$slug': typeof UserBuildsSlugRoute
  '/user-builds/manage': typeof UserBuildsManageRoute
  '/user-builds/submit': typeof UserBuildsSubmitRoute
  '/admin': typeof AdminIndexRoute
  '/altair': typeof AltairIndexRoute
  '/blog': typeof BlogIndexRoute
  '/builds': typeof BuildsIndexRoute
  '/forest-explorer': typeof ForestExplorerIndexRoute
  '/kowloon-knockout': typeof KowloonKnockoutIndexRoute
  '/messages': typeof MessagesIndexRoute
  '/news': typeof NewsIndexRoute
  '/research': typeof ResearchIndexRoute
  '/rmhbox': typeof RmhboxIndexRoute
  '/rmhcode': typeof RmhcodeIndexRoute
  '/rmhmusic': typeof RmhmusicIndexRoute
  '/rmhstudy': typeof RmhstudyIndexRoute
  '/rmhtube': typeof RmhtubeIndexRoute
  '/rmhtype': typeof RmhtypeIndexRoute
  '/secret': typeof SecretIndexRoute
  '/slice-it': typeof SliceItIndexRoute
  '/temple-of-joy': typeof TempleOfJoyIndexRoute
  '/user-builds': typeof UserBuildsIndexRoute
  '/versecraft': typeof VersecraftIndexRoute
  '/$userid/post/$postid': typeof UseridPostPostidRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/altair/multiplayer/$lobbyId': typeof AltairMultiplayerLobbyIdRoute
  '/secret/jobs/$id': typeof SecretJobsIdRoute
  '/secret/jobs/applications': typeof SecretJobsApplicationsRoute
  '/admin/blog': typeof AdminBlogIndexRoute
  '/admin/curated-builds': typeof AdminCuratedBuildsIndexRoute
  '/admin/user-builds': typeof AdminUserBuildsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/altair/multiplayer': typeof AltairMultiplayerIndexRoute
  '/rmhbox/minigames': typeof RmhboxMinigamesIndexRoute
  '/secret/cursed-logic': typeof SecretCursedLogicIndexRoute
  '/secret/docs': typeof SecretDocsIndexRoute
  '/secret/jobs': typeof SecretJobsIndexRoute
  '/secret/notes': typeof SecretNotesIndexRoute
  '/secret/sheets': typeof SecretSheetsIndexRoute
  '/secret/slides': typeof SecretSlidesIndexRoute
  '/secret/weather': typeof SecretWeatherIndexRoute
  '/admin/blog/$slug/edit': typeof AdminBlogSlugEditRoute
  '/admin/curated-builds/$id/edit': typeof AdminCuratedBuildsIdEditRoute
  '/rmhbox/minigames/$minigameId/history': typeof RmhboxMinigamesMinigameIdHistoryRoute
  '/secret/jobs/assessment/$id': typeof SecretJobsAssessmentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/builds': typeof BuildsRouteRouteWithChildren
  '/altair': typeof AltairRouteWithChildren
  '/forest-explorer': typeof ForestExplorerRouteWithChildren
  '/kowloon-knockout': typeof KowloonKnockoutRouteWithChildren
  '/laundry-sort': typeof LaundrySortRoute
  '/lights-out': typeof LightsOutRoute
  '/login': typeof LoginRoute
  '/neon-driftway': typeof NeonDriftwayRoute
  '/rmhbox': typeof RmhboxRouteWithChildren
  '/rmhmusic': typeof RmhmusicRouteWithChildren
  '/rmhstudy': typeof RmhstudyRouteWithChildren
  '/rmhtube': typeof RmhtubeRouteWithChildren
  '/rmhtype': typeof RmhtypeRouteWithChildren
  '/roadmap': typeof RoadmapRoute
  '/secret': typeof SecretRouteWithChildren
  '/slice-it': typeof SliceItRouteWithChildren
  '/synapse-storm': typeof SynapseStormRoute
  '/temple-of-joy': typeof TempleOfJoyRouteWithChildren
  '/velum2099': typeof Velum2099Route
  '/versecraft': typeof VersecraftRouteWithChildren
  '/void-breaker': typeof VoidBreakerRoute
  '/admin/user-builds': typeof AdminUserBuildsRouteWithChildren
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/altair/multiplayer': typeof AltairMultiplayerRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/builds/$slug': typeof BuildsSlugRoute
  '/builds/apps': typeof BuildsAppsRoute
  '/builds/games': typeof BuildsGamesRoute
  '/forest-explorer/explore': typeof ForestExplorerExploreRoute
  '/forest-explorer/story': typeof ForestExplorerStoryRoute
  '/messages/$conversationId': typeof MessagesConversationIdRoute
  '/news/$slug': typeof NewsSlugRoute
  '/profile/$id': typeof ProfileIdRoute
  '/research/$slug': typeof ResearchSlugRoute
  '/research/call': typeof ResearchCallRoute
  '/rmhbox/$lobbyId': typeof RmhboxLobbyIdRoute
  '/rmhcode/auth': typeof RmhcodeAuthRoute
  '/rmhmusic/$roomId': typeof RmhmusicRoomIdRoute
  '/rmhmusic/player': typeof RmhmusicPlayerRoute
  '/rmhstudy/$roomId': typeof RmhstudyRoomIdRoute
  '/rmhtube/$roomId': typeof RmhtubeRoomIdRoute
  '/rmhtype/$roomId': typeof RmhtypeRoomIdRoute
  '/rmhtype/multiplayer': typeof RmhtypeMultiplayerRoute
  '/rmhtype/solo': typeof RmhtypeSoloRoute
  '/secret/cursed-logic': typeof SecretCursedLogicRouteWithChildren
  '/secret/docs': typeof SecretDocsRouteWithChildren
  '/secret/dream-rift': typeof SecretDreamRiftRoute
  '/secret/eats': typeof SecretEatsRoute
  '/secret/house-always-wins': typeof SecretHouseAlwaysWinsRoute
  '/secret/jobs': typeof SecretJobsRouteWithChildren
  '/secret/notes': typeof SecretNotesRouteWithChildren
  '/secret/sheets': typeof SecretSheetsRouteWithChildren
  '/secret/signal-forge': typeof SecretSignalForgeRoute
  '/secret/slides': typeof SecretSlidesRouteWithChildren
  '/secret/vega': typeof SecretVegaRoute
  '/secret/weather': typeof SecretWeatherRouteWithChildren
  '/user-builds/$slug': typeof UserBuildsSlugRoute
  '/user-builds/manage': typeof UserBuildsManageRoute
  '/user-builds/submit': typeof UserBuildsSubmitRoute
  '/admin/': typeof AdminIndexRoute
  '/altair/': typeof AltairIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/builds/': typeof BuildsIndexRoute
  '/forest-explorer/': typeof ForestExplorerIndexRoute
  '/kowloon-knockout/': typeof KowloonKnockoutIndexRoute
  '/messages/': typeof MessagesIndexRoute
  '/news/': typeof NewsIndexRoute
  '/research/': typeof ResearchIndexRoute
  '/rmhbox/': typeof RmhboxIndexRoute
  '/rmhcode/': typeof RmhcodeIndexRoute
  '/rmhmusic/': typeof RmhmusicIndexRoute
  '/rmhstudy/': typeof RmhstudyIndexRoute
  '/rmhtube/': typeof RmhtubeIndexRoute
  '/rmhtype/': typeof RmhtypeIndexRoute
  '/secret/': typeof SecretIndexRoute
  '/slice-it/': typeof SliceItIndexRoute
  '/temple-of-joy/': typeof TempleOfJoyIndexRoute
  '/user-builds/': typeof UserBuildsIndexRoute
  '/versecraft/': typeof VersecraftIndexRoute
  '/$userid/post/$postid': typeof UseridPostPostidRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/altair/multiplayer/$lobbyId': typeof AltairMultiplayerLobbyIdRoute
  '/secret/jobs/$id': typeof SecretJobsIdRoute
  '/secret/jobs/applications': typeof SecretJobsApplicationsRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/admin/curated-builds/': typeof AdminCuratedBuildsIndexRoute
  '/admin/user-builds/': typeof AdminUserBuildsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/altair/multiplayer/': typeof AltairMultiplayerIndexRoute
  '/rmhbox/minigames/': typeof RmhboxMinigamesIndexRoute
  '/secret/cursed-logic/': typeof SecretCursedLogicIndexRoute
  '/secret/docs/': typeof SecretDocsIndexRoute
  '/secret/jobs/': typeof SecretJobsIndexRoute
  '/secret/notes/': typeof SecretNotesIndexRoute
  '/secret/sheets/': typeof SecretSheetsIndexRoute
  '/secret/slides/': typeof SecretSlidesIndexRoute
  '/secret/weather/': typeof SecretWeatherIndexRoute
  '/admin/blog/$slug/edit': typeof AdminBlogSlugEditRoute
  '/admin/curated-builds/$id/edit': typeof AdminCuratedBuildsIdEditRoute
  '/rmhbox/minigames/$minigameId/history': typeof RmhboxMinigamesMinigameIdHistoryRoute
  '/secret/jobs/assessment/$id': typeof SecretJobsAssessmentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/builds'
    | '/altair'
    | '/forest-explorer'
    | '/kowloon-knockout'
    | '/laundry-sort'
    | '/lights-out'
    | '/login'
    | '/neon-driftway'
    | '/rmhbox'
    | '/rmhmusic'
    | '/rmhstudy'
    | '/rmhtube'
    | '/rmhtype'
    | '/roadmap'
    | '/secret'
    | '/slice-it'
    | '/synapse-storm'
    | '/temple-of-joy'
    | '/velum2099'
    | '/versecraft'
    | '/void-breaker'
    | '/admin/user-builds'
    | '/admin/users'
    | '/altair/multiplayer'
    | '/blog/$slug'
    | '/builds/$slug'
    | '/builds/apps'
    | '/builds/games'
    | '/forest-explorer/explore'
    | '/forest-explorer/story'
    | '/messages/$conversationId'
    | '/news/$slug'
    | '/profile/$id'
    | '/research/$slug'
    | '/research/call'
    | '/rmhbox/$lobbyId'
    | '/rmhcode/auth'
    | '/rmhmusic/$roomId'
    | '/rmhmusic/player'
    | '/rmhstudy/$roomId'
    | '/rmhtube/$roomId'
    | '/rmhtype/$roomId'
    | '/rmhtype/multiplayer'
    | '/rmhtype/solo'
    | '/secret/cursed-logic'
    | '/secret/docs'
    | '/secret/dream-rift'
    | '/secret/eats'
    | '/secret/house-always-wins'
    | '/secret/jobs'
    | '/secret/notes'
    | '/secret/sheets'
    | '/secret/signal-forge'
    | '/secret/slides'
    | '/secret/vega'
    | '/secret/weather'
    | '/user-builds/$slug'
    | '/user-builds/manage'
    | '/user-builds/submit'
    | '/admin/'
    | '/altair/'
    | '/blog/'
    | '/builds/'
    | '/forest-explorer/'
    | '/kowloon-knockout/'
    | '/messages/'
    | '/news/'
    | '/research/'
    | '/rmhbox/'
    | '/rmhcode/'
    | '/rmhmusic/'
    | '/rmhstudy/'
    | '/rmhtube/'
    | '/rmhtype/'
    | '/secret/'
    | '/slice-it/'
    | '/temple-of-joy/'
    | '/user-builds/'
    | '/versecraft/'
    | '/$userid/post/$postid'
    | '/admin/blog/new'
    | '/altair/multiplayer/$lobbyId'
    | '/secret/jobs/$id'
    | '/secret/jobs/applications'
    | '/admin/blog/'
    | '/admin/curated-builds/'
    | '/admin/user-builds/'
    | '/admin/users/'
    | '/altair/multiplayer/'
    | '/rmhbox/minigames/'
    | '/secret/cursed-logic/'
    | '/secret/docs/'
    | '/secret/jobs/'
    | '/secret/notes/'
    | '/secret/sheets/'
    | '/secret/slides/'
    | '/secret/weather/'
    | '/admin/blog/$slug/edit'
    | '/admin/curated-builds/$id/edit'
    | '/rmhbox/minigames/$minigameId/history'
    | '/secret/jobs/assessment/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/laundry-sort'
    | '/lights-out'
    | '/login'
    | '/neon-driftway'
    | '/roadmap'
    | '/synapse-storm'
    | '/velum2099'
    | '/void-breaker'
    | '/blog/$slug'
    | '/builds/$slug'
    | '/builds/apps'
    | '/builds/games'
    | '/forest-explorer/explore'
    | '/forest-explorer/story'
    | '/messages/$conversationId'
    | '/news/$slug'
    | '/profile/$id'
    | '/research/$slug'
    | '/research/call'
    | '/rmhbox/$lobbyId'
    | '/rmhcode/auth'
    | '/rmhmusic/$roomId'
    | '/rmhmusic/player'
    | '/rmhstudy/$roomId'
    | '/rmhtube/$roomId'
    | '/rmhtype/$roomId'
    | '/rmhtype/multiplayer'
    | '/rmhtype/solo'
    | '/secret/dream-rift'
    | '/secret/eats'
    | '/secret/house-always-wins'
    | '/secret/signal-forge'
    | '/secret/vega'
    | '/user-builds/$slug'
    | '/user-builds/manage'
    | '/user-builds/submit'
    | '/admin'
    | '/altair'
    | '/blog'
    | '/builds'
    | '/forest-explorer'
    | '/kowloon-knockout'
    | '/messages'
    | '/news'
    | '/research'
    | '/rmhbox'
    | '/rmhcode'
    | '/rmhmusic'
    | '/rmhstudy'
    | '/rmhtube'
    | '/rmhtype'
    | '/secret'
    | '/slice-it'
    | '/temple-of-joy'
    | '/user-builds'
    | '/versecraft'
    | '/$userid/post/$postid'
    | '/admin/blog/new'
    | '/altair/multiplayer/$lobbyId'
    | '/secret/jobs/$id'
    | '/secret/jobs/applications'
    | '/admin/blog'
    | '/admin/curated-builds'
    | '/admin/user-builds'
    | '/admin/users'
    | '/altair/multiplayer'
    | '/rmhbox/minigames'
    | '/secret/cursed-logic'
    | '/secret/docs'
    | '/secret/jobs'
    | '/secret/notes'
    | '/secret/sheets'
    | '/secret/slides'
    | '/secret/weather'
    | '/admin/blog/$slug/edit'
    | '/admin/curated-builds/$id/edit'
    | '/rmhbox/minigames/$minigameId/history'
    | '/secret/jobs/assessment/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/builds'
    | '/altair'
    | '/forest-explorer'
    | '/kowloon-knockout'
    | '/laundry-sort'
    | '/lights-out'
    | '/login'
    | '/neon-driftway'
    | '/rmhbox'
    | '/rmhmusic'
    | '/rmhstudy'
    | '/rmhtube'
    | '/rmhtype'
    | '/roadmap'
    | '/secret'
    | '/slice-it'
    | '/synapse-storm'
    | '/temple-of-joy'
    | '/velum2099'
    | '/versecraft'
    | '/void-breaker'
    | '/admin/user-builds'
    | '/admin/users'
    | '/altair/multiplayer'
    | '/blog/$slug'
    | '/builds/$slug'
    | '/builds/apps'
    | '/builds/games'
    | '/forest-explorer/explore'
    | '/forest-explorer/story'
    | '/messages/$conversationId'
    | '/news/$slug'
    | '/profile/$id'
    | '/research/$slug'
    | '/research/call'
    | '/rmhbox/$lobbyId'
    | '/rmhcode/auth'
    | '/rmhmusic/$roomId'
    | '/rmhmusic/player'
    | '/rmhstudy/$roomId'
    | '/rmhtube/$roomId'
    | '/rmhtype/$roomId'
    | '/rmhtype/multiplayer'
    | '/rmhtype/solo'
    | '/secret/cursed-logic'
    | '/secret/docs'
    | '/secret/dream-rift'
    | '/secret/eats'
    | '/secret/house-always-wins'
    | '/secret/jobs'
    | '/secret/notes'
    | '/secret/sheets'
    | '/secret/signal-forge'
    | '/secret/slides'
    | '/secret/vega'
    | '/secret/weather'
    | '/user-builds/$slug'
    | '/user-builds/manage'
    | '/user-builds/submit'
    | '/admin/'
    | '/altair/'
    | '/blog/'
    | '/builds/'
    | '/forest-explorer/'
    | '/kowloon-knockout/'
    | '/messages/'
    | '/news/'
    | '/research/'
    | '/rmhbox/'
    | '/rmhcode/'
    | '/rmhmusic/'
    | '/rmhstudy/'
    | '/rmhtube/'
    | '/rmhtype/'
    | '/secret/'
    | '/slice-it/'
    | '/temple-of-joy/'
    | '/user-builds/'
    | '/versecraft/'
    | '/$userid/post/$postid'
    | '/admin/blog/new'
    | '/altair/multiplayer/$lobbyId'
    | '/secret/jobs/$id'
    | '/secret/jobs/applications'
    | '/admin/blog/'
    | '/admin/curated-builds/'
    | '/admin/user-builds/'
    | '/admin/users/'
    | '/altair/multiplayer/'
    | '/rmhbox/minigames/'
    | '/secret/cursed-logic/'
    | '/secret/docs/'
    | '/secret/jobs/'
    | '/secret/notes/'
    | '/secret/sheets/'
    | '/secret/slides/'
    | '/secret/weather/'
    | '/admin/blog/$slug/edit'
    | '/admin/curated-builds/$id/edit'
    | '/rmhbox/minigames/$minigameId/history'
    | '/secret/jobs/assessment/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  BuildsRouteRoute: typeof BuildsRouteRouteWithChildren
  AltairRoute: typeof AltairRouteWithChildren
  ForestExplorerRoute: typeof ForestExplorerRouteWithChildren
  KowloonKnockoutRoute: typeof KowloonKnockoutRouteWithChildren
  LaundrySortRoute: typeof LaundrySortRoute
  LightsOutRoute: typeof LightsOutRoute
  LoginRoute: typeof LoginRoute
  NeonDriftwayRoute: typeof NeonDriftwayRoute
  RmhboxRoute: typeof RmhboxRouteWithChildren
  RmhmusicRoute: typeof RmhmusicRouteWithChildren
  RmhstudyRoute: typeof RmhstudyRouteWithChildren
  RmhtubeRoute: typeof RmhtubeRouteWithChildren
  RmhtypeRoute: typeof RmhtypeRouteWithChildren
  RoadmapRoute: typeof RoadmapRoute
  SecretRoute: typeof SecretRouteWithChildren
  SliceItRoute: typeof SliceItRouteWithChildren
  SynapseStormRoute: typeof SynapseStormRoute
  TempleOfJoyRoute: typeof TempleOfJoyRouteWithChildren
  Velum2099Route: typeof Velum2099Route
  VersecraftRoute: typeof VersecraftRouteWithChildren
  VoidBreakerRoute: typeof VoidBreakerRoute
  BlogSlugRoute: typeof BlogSlugRoute
  MessagesConversationIdRoute: typeof MessagesConversationIdRoute
  NewsSlugRoute: typeof NewsSlugRoute
  ProfileIdRoute: typeof ProfileIdRoute
  ResearchSlugRoute: typeof ResearchSlugRoute
  ResearchCallRoute: typeof ResearchCallRoute
  RmhcodeAuthRoute: typeof RmhcodeAuthRoute
  UserBuildsSlugRoute: typeof UserBuildsSlugRoute
  UserBuildsManageRoute: typeof UserBuildsManageRoute
  UserBuildsSubmitRoute: typeof UserBuildsSubmitRoute
  BlogIndexRoute: typeof BlogIndexRoute
  MessagesIndexRoute: typeof MessagesIndexRoute
  NewsIndexRoute: typeof NewsIndexRoute
  ResearchIndexRoute: typeof ResearchIndexRoute
  RmhcodeIndexRoute: typeof RmhcodeIndexRoute
  UserBuildsIndexRoute: typeof UserBuildsIndexRoute
  UseridPostPostidRoute: typeof UseridPostPostidRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/void-breaker': {
      id: '/void-breaker'
      path: '/void-breaker'
      fullPath: '/void-breaker'
      preLoaderRoute: typeof VoidBreakerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/versecraft': {
      id: '/versecraft'
      path: '/versecraft'
      fullPath: '/versecraft'
      preLoaderRoute: typeof VersecraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/velum2099': {
      id: '/velum2099'
      path: '/velum2099'
      fullPath: '/velum2099'
      preLoaderRoute: typeof Velum2099RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/temple-of-joy': {
      id: '/temple-of-joy'
      path: '/temple-of-joy'
      fullPath: '/temple-of-joy'
      preLoaderRoute: typeof TempleOfJoyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/synapse-storm': {
      id: '/synapse-storm'
      path: '/synapse-storm'
      fullPath: '/synapse-storm'
      preLoaderRoute: typeof SynapseStormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slice-it': {
      id: '/slice-it'
      path: '/slice-it'
      fullPath: '/slice-it'
      preLoaderRoute: typeof SliceItRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/secret': {
      id: '/secret'
      path: '/secret'
      fullPath: '/secret'
      preLoaderRoute: typeof SecretRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rmhtype': {
      id: '/rmhtype'
      path: '/rmhtype'
      fullPath: '/rmhtype'
      preLoaderRoute: typeof RmhtypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rmhtube': {
      id: '/rmhtube'
      path: '/rmhtube'
      fullPath: '/rmhtube'
      preLoaderRoute: typeof RmhtubeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rmhstudy': {
      id: '/rmhstudy'
      path: '/rmhstudy'
      fullPath: '/rmhstudy'
      preLoaderRoute: typeof RmhstudyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rmhmusic': {
      id: '/rmhmusic'
      path: '/rmhmusic'
      fullPath: '/rmhmusic'
      preLoaderRoute: typeof RmhmusicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rmhbox': {
      id: '/rmhbox'
      path: '/rmhbox'
      fullPath: '/rmhbox'
      preLoaderRoute: typeof RmhboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/neon-driftway': {
      id: '/neon-driftway'
      path: '/neon-driftway'
      fullPath: '/neon-driftway'
      preLoaderRoute: typeof NeonDriftwayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lights-out': {
      id: '/lights-out'
      path: '/lights-out'
      fullPath: '/lights-out'
      preLoaderRoute: typeof LightsOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laundry-sort': {
      id: '/laundry-sort'
      path: '/laundry-sort'
      fullPath: '/laundry-sort'
      preLoaderRoute: typeof LaundrySortRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kowloon-knockout': {
      id: '/kowloon-knockout'
      path: '/kowloon-knockout'
      fullPath: '/kowloon-knockout'
      preLoaderRoute: typeof KowloonKnockoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forest-explorer': {
      id: '/forest-explorer'
      path: '/forest-explorer'
      fullPath: '/forest-explorer'
      preLoaderRoute: typeof ForestExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/altair': {
      id: '/altair'
      path: '/altair'
      fullPath: '/altair'
      preLoaderRoute: typeof AltairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builds': {
      id: '/builds'
      path: '/builds'
      fullPath: '/builds'
      preLoaderRoute: typeof BuildsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/versecraft/': {
      id: '/versecraft/'
      path: '/'
      fullPath: '/versecraft/'
      preLoaderRoute: typeof VersecraftIndexRouteImport
      parentRoute: typeof VersecraftRoute
    }
    '/user-builds/': {
      id: '/user-builds/'
      path: '/user-builds'
      fullPath: '/user-builds/'
      preLoaderRoute: typeof UserBuildsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/temple-of-joy/': {
      id: '/temple-of-joy/'
      path: '/'
      fullPath: '/temple-of-joy/'
      preLoaderRoute: typeof TempleOfJoyIndexRouteImport
      parentRoute: typeof TempleOfJoyRoute
    }
    '/slice-it/': {
      id: '/slice-it/'
      path: '/'
      fullPath: '/slice-it/'
      preLoaderRoute: typeof SliceItIndexRouteImport
      parentRoute: typeof SliceItRoute
    }
    '/secret/': {
      id: '/secret/'
      path: '/'
      fullPath: '/secret/'
      preLoaderRoute: typeof SecretIndexRouteImport
      parentRoute: typeof SecretRoute
    }
    '/rmhtype/': {
      id: '/rmhtype/'
      path: '/'
      fullPath: '/rmhtype/'
      preLoaderRoute: typeof RmhtypeIndexRouteImport
      parentRoute: typeof RmhtypeRoute
    }
    '/rmhtube/': {
      id: '/rmhtube/'
      path: '/'
      fullPath: '/rmhtube/'
      preLoaderRoute: typeof RmhtubeIndexRouteImport
      parentRoute: typeof RmhtubeRoute
    }
    '/rmhstudy/': {
      id: '/rmhstudy/'
      path: '/'
      fullPath: '/rmhstudy/'
      preLoaderRoute: typeof RmhstudyIndexRouteImport
      parentRoute: typeof RmhstudyRoute
    }
    '/rmhmusic/': {
      id: '/rmhmusic/'
      path: '/'
      fullPath: '/rmhmusic/'
      preLoaderRoute: typeof RmhmusicIndexRouteImport
      parentRoute: typeof RmhmusicRoute
    }
    '/rmhcode/': {
      id: '/rmhcode/'
      path: '/rmhcode'
      fullPath: '/rmhcode/'
      preLoaderRoute: typeof RmhcodeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rmhbox/': {
      id: '/rmhbox/'
      path: '/'
      fullPath: '/rmhbox/'
      preLoaderRoute: typeof RmhboxIndexRouteImport
      parentRoute: typeof RmhboxRoute
    }
    '/research/': {
      id: '/research/'
      path: '/research'
      fullPath: '/research/'
      preLoaderRoute: typeof ResearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/': {
      id: '/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof MessagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kowloon-knockout/': {
      id: '/kowloon-knockout/'
      path: '/'
      fullPath: '/kowloon-knockout/'
      preLoaderRoute: typeof KowloonKnockoutIndexRouteImport
      parentRoute: typeof KowloonKnockoutRoute
    }
    '/forest-explorer/': {
      id: '/forest-explorer/'
      path: '/'
      fullPath: '/forest-explorer/'
      preLoaderRoute: typeof ForestExplorerIndexRouteImport
      parentRoute: typeof ForestExplorerRoute
    }
    '/builds/': {
      id: '/builds/'
      path: '/'
      fullPath: '/builds/'
      preLoaderRoute: typeof BuildsIndexRouteImport
      parentRoute: typeof BuildsRouteRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/altair/': {
      id: '/altair/'
      path: '/'
      fullPath: '/altair/'
      preLoaderRoute: typeof AltairIndexRouteImport
      parentRoute: typeof AltairRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/user-builds/submit': {
      id: '/user-builds/submit'
      path: '/user-builds/submit'
      fullPath: '/user-builds/submit'
      preLoaderRoute: typeof UserBuildsSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user-builds/manage': {
      id: '/user-builds/manage'
      path: '/user-builds/manage'
      fullPath: '/user-builds/manage'
      preLoaderRoute: typeof UserBuildsManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user-builds/$slug': {
      id: '/user-builds/$slug'
      path: '/user-builds/$slug'
      fullPath: '/user-builds/$slug'
      preLoaderRoute: typeof UserBuildsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/secret/weather': {
      id: '/secret/weather'
      path: '/weather'
      fullPath: '/secret/weather'
      preLoaderRoute: typeof SecretWeatherRouteImport
      parentRoute: typeof SecretRoute
    }
    '/secret/vega': {
      id: '/secret/vega'
      path: '/vega'
      fullPath: '/secret/vega'
      preLoaderRoute: typeof SecretVegaRouteImport
      parentRoute: typeof SecretRoute
    }
    '/secret/slides': {
      id: '/secret/slides'
      path: '/slides'
      fullPath: '/secret/slides'
      preLoaderRoute: typeof SecretSlidesRouteImport
      parentRoute: typeof SecretRoute
    }
    '/secret/signal-forge': {
      id: '/secret/signal-forge'
      path: '/signal-forge'
      fullPath: '/secret/signal-forge'
      preLoaderRoute: typeof SecretSignalForgeRouteImport
      parentRoute: typeof SecretRoute
    }
    '/secret/sheets': {
      id: '/secret/sheets'
      path: '/sheets'
      fullPath: '/secret/sheets'
      preLoaderRoute: typeof SecretSheetsRouteImport
      parentRoute: typeof SecretRoute
    }
    '/secret/notes': {
      id: '/secret/notes'
      path: '/notes'
      fullPath: '/secret/notes'
      preLoaderRoute: typeof SecretNotesRouteImport
      parentRoute: typeof SecretRoute
    }
    '/secret/jobs': {
      id: '/secret/jobs'
      path: '/jobs'
      fullPath: '/secret/jobs'
      preLoaderRoute: typeof SecretJobsRouteImport
      parentRoute: typeof SecretRoute
    }
    '/secret/house-always-wins': {
      id: '/secret/house-always-wins'
      path: '/house-always-wins'
      fullPath: '/secret/house-always-wins'
      preLoaderRoute: typeof SecretHouseAlwaysWinsRouteImport
      parentRoute: typeof SecretRoute
    }
    '/secret/eats': {
      id: '/secret/eats'
      path: '/eats'
      fullPath: '/secret/eats'
      preLoaderRoute: typeof SecretEatsRouteImport
      parentRoute: typeof SecretRoute
    }
    '/secret/dream-rift': {
      id: '/secret/dream-rift'
      path: '/dream-rift'
      fullPath: '/secret/dream-rift'
      preLoaderRoute: typeof SecretDreamRiftRouteImport
      parentRoute: typeof SecretRoute
    }
    '/secret/docs': {
      id: '/secret/docs'
      path: '/docs'
      fullPath: '/secret/docs'
      preLoaderRoute: typeof SecretDocsRouteImport
      parentRoute: typeof SecretRoute
    }
    '/secret/cursed-logic': {
      id: '/secret/cursed-logic'
      path: '/cursed-logic'
      fullPath: '/secret/cursed-logic'
      preLoaderRoute: typeof SecretCursedLogicRouteImport
      parentRoute: typeof SecretRoute
    }
    '/rmhtype/solo': {
      id: '/rmhtype/solo'
      path: '/solo'
      fullPath: '/rmhtype/solo'
      preLoaderRoute: typeof RmhtypeSoloRouteImport
      parentRoute: typeof RmhtypeRoute
    }
    '/rmhtype/multiplayer': {
      id: '/rmhtype/multiplayer'
      path: '/multiplayer'
      fullPath: '/rmhtype/multiplayer'
      preLoaderRoute: typeof RmhtypeMultiplayerRouteImport
      parentRoute: typeof RmhtypeRoute
    }
    '/rmhtype/$roomId': {
      id: '/rmhtype/$roomId'
      path: '/$roomId'
      fullPath: '/rmhtype/$roomId'
      preLoaderRoute: typeof RmhtypeRoomIdRouteImport
      parentRoute: typeof RmhtypeRoute
    }
    '/rmhtube/$roomId': {
      id: '/rmhtube/$roomId'
      path: '/$roomId'
      fullPath: '/rmhtube/$roomId'
      preLoaderRoute: typeof RmhtubeRoomIdRouteImport
      parentRoute: typeof RmhtubeRoute
    }
    '/rmhstudy/$roomId': {
      id: '/rmhstudy/$roomId'
      path: '/$roomId'
      fullPath: '/rmhstudy/$roomId'
      preLoaderRoute: typeof RmhstudyRoomIdRouteImport
      parentRoute: typeof RmhstudyRoute
    }
    '/rmhmusic/player': {
      id: '/rmhmusic/player'
      path: '/player'
      fullPath: '/rmhmusic/player'
      preLoaderRoute: typeof RmhmusicPlayerRouteImport
      parentRoute: typeof RmhmusicRoute
    }
    '/rmhmusic/$roomId': {
      id: '/rmhmusic/$roomId'
      path: '/$roomId'
      fullPath: '/rmhmusic/$roomId'
      preLoaderRoute: typeof RmhmusicRoomIdRouteImport
      parentRoute: typeof RmhmusicRoute
    }
    '/rmhcode/auth': {
      id: '/rmhcode/auth'
      path: '/rmhcode/auth'
      fullPath: '/rmhcode/auth'
      preLoaderRoute: typeof RmhcodeAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rmhbox/$lobbyId': {
      id: '/rmhbox/$lobbyId'
      path: '/$lobbyId'
      fullPath: '/rmhbox/$lobbyId'
      preLoaderRoute: typeof RmhboxLobbyIdRouteImport
      parentRoute: typeof RmhboxRoute
    }
    '/research/call': {
      id: '/research/call'
      path: '/research/call'
      fullPath: '/research/call'
      preLoaderRoute: typeof ResearchCallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/$slug': {
      id: '/research/$slug'
      path: '/research/$slug'
      fullPath: '/research/$slug'
      preLoaderRoute: typeof ResearchSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$id': {
      id: '/profile/$id'
      path: '/profile/$id'
      fullPath: '/profile/$id'
      preLoaderRoute: typeof ProfileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/news/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/$conversationId': {
      id: '/messages/$conversationId'
      path: '/messages/$conversationId'
      fullPath: '/messages/$conversationId'
      preLoaderRoute: typeof MessagesConversationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forest-explorer/story': {
      id: '/forest-explorer/story'
      path: '/story'
      fullPath: '/forest-explorer/story'
      preLoaderRoute: typeof ForestExplorerStoryRouteImport
      parentRoute: typeof ForestExplorerRoute
    }
    '/forest-explorer/explore': {
      id: '/forest-explorer/explore'
      path: '/explore'
      fullPath: '/forest-explorer/explore'
      preLoaderRoute: typeof ForestExplorerExploreRouteImport
      parentRoute: typeof ForestExplorerRoute
    }
    '/builds/games': {
      id: '/builds/games'
      path: '/games'
      fullPath: '/builds/games'
      preLoaderRoute: typeof BuildsGamesRouteImport
      parentRoute: typeof BuildsRouteRoute
    }
    '/builds/apps': {
      id: '/builds/apps'
      path: '/apps'
      fullPath: '/builds/apps'
      preLoaderRoute: typeof BuildsAppsRouteImport
      parentRoute: typeof BuildsRouteRoute
    }
    '/builds/$slug': {
      id: '/builds/$slug'
      path: '/$slug'
      fullPath: '/builds/$slug'
      preLoaderRoute: typeof BuildsSlugRouteImport
      parentRoute: typeof BuildsRouteRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/altair/multiplayer': {
      id: '/altair/multiplayer'
      path: '/multiplayer'
      fullPath: '/altair/multiplayer'
      preLoaderRoute: typeof AltairMultiplayerRouteImport
      parentRoute: typeof AltairRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/user-builds': {
      id: '/admin/user-builds'
      path: '/user-builds'
      fullPath: '/admin/user-builds'
      preLoaderRoute: typeof AdminUserBuildsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/secret/weather/': {
      id: '/secret/weather/'
      path: '/'
      fullPath: '/secret/weather/'
      preLoaderRoute: typeof SecretWeatherIndexRouteImport
      parentRoute: typeof SecretWeatherRoute
    }
    '/secret/slides/': {
      id: '/secret/slides/'
      path: '/'
      fullPath: '/secret/slides/'
      preLoaderRoute: typeof SecretSlidesIndexRouteImport
      parentRoute: typeof SecretSlidesRoute
    }
    '/secret/sheets/': {
      id: '/secret/sheets/'
      path: '/'
      fullPath: '/secret/sheets/'
      preLoaderRoute: typeof SecretSheetsIndexRouteImport
      parentRoute: typeof SecretSheetsRoute
    }
    '/secret/notes/': {
      id: '/secret/notes/'
      path: '/'
      fullPath: '/secret/notes/'
      preLoaderRoute: typeof SecretNotesIndexRouteImport
      parentRoute: typeof SecretNotesRoute
    }
    '/secret/jobs/': {
      id: '/secret/jobs/'
      path: '/'
      fullPath: '/secret/jobs/'
      preLoaderRoute: typeof SecretJobsIndexRouteImport
      parentRoute: typeof SecretJobsRoute
    }
    '/secret/docs/': {
      id: '/secret/docs/'
      path: '/'
      fullPath: '/secret/docs/'
      preLoaderRoute: typeof SecretDocsIndexRouteImport
      parentRoute: typeof SecretDocsRoute
    }
    '/secret/cursed-logic/': {
      id: '/secret/cursed-logic/'
      path: '/'
      fullPath: '/secret/cursed-logic/'
      preLoaderRoute: typeof SecretCursedLogicIndexRouteImport
      parentRoute: typeof SecretCursedLogicRoute
    }
    '/rmhbox/minigames/': {
      id: '/rmhbox/minigames/'
      path: '/minigames'
      fullPath: '/rmhbox/minigames/'
      preLoaderRoute: typeof RmhboxMinigamesIndexRouteImport
      parentRoute: typeof RmhboxRoute
    }
    '/altair/multiplayer/': {
      id: '/altair/multiplayer/'
      path: '/'
      fullPath: '/altair/multiplayer/'
      preLoaderRoute: typeof AltairMultiplayerIndexRouteImport
      parentRoute: typeof AltairMultiplayerRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminUsersRoute
    }
    '/admin/user-builds/': {
      id: '/admin/user-builds/'
      path: '/'
      fullPath: '/admin/user-builds/'
      preLoaderRoute: typeof AdminUserBuildsIndexRouteImport
      parentRoute: typeof AdminUserBuildsRoute
    }
    '/admin/curated-builds/': {
      id: '/admin/curated-builds/'
      path: '/curated-builds'
      fullPath: '/admin/curated-builds/'
      preLoaderRoute: typeof AdminCuratedBuildsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/blog/': {
      id: '/admin/blog/'
      path: '/blog'
      fullPath: '/admin/blog/'
      preLoaderRoute: typeof AdminBlogIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/secret/jobs/applications': {
      id: '/secret/jobs/applications'
      path: '/applications'
      fullPath: '/secret/jobs/applications'
      preLoaderRoute: typeof SecretJobsApplicationsRouteImport
      parentRoute: typeof SecretJobsRoute
    }
    '/secret/jobs/$id': {
      id: '/secret/jobs/$id'
      path: '/$id'
      fullPath: '/secret/jobs/$id'
      preLoaderRoute: typeof SecretJobsIdRouteImport
      parentRoute: typeof SecretJobsRoute
    }
    '/altair/multiplayer/$lobbyId': {
      id: '/altair/multiplayer/$lobbyId'
      path: '/$lobbyId'
      fullPath: '/altair/multiplayer/$lobbyId'
      preLoaderRoute: typeof AltairMultiplayerLobbyIdRouteImport
      parentRoute: typeof AltairMultiplayerRoute
    }
    '/admin/blog/new': {
      id: '/admin/blog/new'
      path: '/blog/new'
      fullPath: '/admin/blog/new'
      preLoaderRoute: typeof AdminBlogNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/$userid/post/$postid': {
      id: '/$userid/post/$postid'
      path: '/$userid/post/$postid'
      fullPath: '/$userid/post/$postid'
      preLoaderRoute: typeof UseridPostPostidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/secret/jobs/assessment/$id': {
      id: '/secret/jobs/assessment/$id'
      path: '/assessment/$id'
      fullPath: '/secret/jobs/assessment/$id'
      preLoaderRoute: typeof SecretJobsAssessmentIdRouteImport
      parentRoute: typeof SecretJobsRoute
    }
    '/rmhbox/minigames/$minigameId/history': {
      id: '/rmhbox/minigames/$minigameId/history'
      path: '/minigames/$minigameId/history'
      fullPath: '/rmhbox/minigames/$minigameId/history'
      preLoaderRoute: typeof RmhboxMinigamesMinigameIdHistoryRouteImport
      parentRoute: typeof RmhboxRoute
    }
    '/admin/curated-builds/$id/edit': {
      id: '/admin/curated-builds/$id/edit'
      path: '/curated-builds/$id/edit'
      fullPath: '/admin/curated-builds/$id/edit'
      preLoaderRoute: typeof AdminCuratedBuildsIdEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/blog/$slug/edit': {
      id: '/admin/blog/$slug/edit'
      path: '/blog/$slug/edit'
      fullPath: '/admin/blog/$slug/edit'
      preLoaderRoute: typeof AdminBlogSlugEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminUserBuildsRouteChildren {
  AdminUserBuildsIndexRoute: typeof AdminUserBuildsIndexRoute
}

const AdminUserBuildsRouteChildren: AdminUserBuildsRouteChildren = {
  AdminUserBuildsIndexRoute: AdminUserBuildsIndexRoute,
}

const AdminUserBuildsRouteWithChildren = AdminUserBuildsRoute._addFileChildren(
  AdminUserBuildsRouteChildren,
)

interface AdminUsersRouteChildren {
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminUsersRouteChildren: AdminUsersRouteChildren = {
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminUsersRouteWithChildren = AdminUsersRoute._addFileChildren(
  AdminUsersRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminUserBuildsRoute: typeof AdminUserBuildsRouteWithChildren
  AdminUsersRoute: typeof AdminUsersRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBlogNewRoute: typeof AdminBlogNewRoute
  AdminBlogIndexRoute: typeof AdminBlogIndexRoute
  AdminCuratedBuildsIndexRoute: typeof AdminCuratedBuildsIndexRoute
  AdminBlogSlugEditRoute: typeof AdminBlogSlugEditRoute
  AdminCuratedBuildsIdEditRoute: typeof AdminCuratedBuildsIdEditRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminUserBuildsRoute: AdminUserBuildsRouteWithChildren,
  AdminUsersRoute: AdminUsersRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  AdminBlogNewRoute: AdminBlogNewRoute,
  AdminBlogIndexRoute: AdminBlogIndexRoute,
  AdminCuratedBuildsIndexRoute: AdminCuratedBuildsIndexRoute,
  AdminBlogSlugEditRoute: AdminBlogSlugEditRoute,
  AdminCuratedBuildsIdEditRoute: AdminCuratedBuildsIdEditRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface BuildsRouteRouteChildren {
  BuildsSlugRoute: typeof BuildsSlugRoute
  BuildsAppsRoute: typeof BuildsAppsRoute
  BuildsGamesRoute: typeof BuildsGamesRoute
  BuildsIndexRoute: typeof BuildsIndexRoute
}

const BuildsRouteRouteChildren: BuildsRouteRouteChildren = {
  BuildsSlugRoute: BuildsSlugRoute,
  BuildsAppsRoute: BuildsAppsRoute,
  BuildsGamesRoute: BuildsGamesRoute,
  BuildsIndexRoute: BuildsIndexRoute,
}

const BuildsRouteRouteWithChildren = BuildsRouteRoute._addFileChildren(
  BuildsRouteRouteChildren,
)

interface AltairMultiplayerRouteChildren {
  AltairMultiplayerLobbyIdRoute: typeof AltairMultiplayerLobbyIdRoute
  AltairMultiplayerIndexRoute: typeof AltairMultiplayerIndexRoute
}

const AltairMultiplayerRouteChildren: AltairMultiplayerRouteChildren = {
  AltairMultiplayerLobbyIdRoute: AltairMultiplayerLobbyIdRoute,
  AltairMultiplayerIndexRoute: AltairMultiplayerIndexRoute,
}

const AltairMultiplayerRouteWithChildren =
  AltairMultiplayerRoute._addFileChildren(AltairMultiplayerRouteChildren)

interface AltairRouteChildren {
  AltairMultiplayerRoute: typeof AltairMultiplayerRouteWithChildren
  AltairIndexRoute: typeof AltairIndexRoute
}

const AltairRouteChildren: AltairRouteChildren = {
  AltairMultiplayerRoute: AltairMultiplayerRouteWithChildren,
  AltairIndexRoute: AltairIndexRoute,
}

const AltairRouteWithChildren =
  AltairRoute._addFileChildren(AltairRouteChildren)

interface ForestExplorerRouteChildren {
  ForestExplorerExploreRoute: typeof ForestExplorerExploreRoute
  ForestExplorerStoryRoute: typeof ForestExplorerStoryRoute
  ForestExplorerIndexRoute: typeof ForestExplorerIndexRoute
}

const ForestExplorerRouteChildren: ForestExplorerRouteChildren = {
  ForestExplorerExploreRoute: ForestExplorerExploreRoute,
  ForestExplorerStoryRoute: ForestExplorerStoryRoute,
  ForestExplorerIndexRoute: ForestExplorerIndexRoute,
}

const ForestExplorerRouteWithChildren = ForestExplorerRoute._addFileChildren(
  ForestExplorerRouteChildren,
)

interface KowloonKnockoutRouteChildren {
  KowloonKnockoutIndexRoute: typeof KowloonKnockoutIndexRoute
}

const KowloonKnockoutRouteChildren: KowloonKnockoutRouteChildren = {
  KowloonKnockoutIndexRoute: KowloonKnockoutIndexRoute,
}

const KowloonKnockoutRouteWithChildren = KowloonKnockoutRoute._addFileChildren(
  KowloonKnockoutRouteChildren,
)

interface RmhboxRouteChildren {
  RmhboxLobbyIdRoute: typeof RmhboxLobbyIdRoute
  RmhboxIndexRoute: typeof RmhboxIndexRoute
  RmhboxMinigamesIndexRoute: typeof RmhboxMinigamesIndexRoute
  RmhboxMinigamesMinigameIdHistoryRoute: typeof RmhboxMinigamesMinigameIdHistoryRoute
}

const RmhboxRouteChildren: RmhboxRouteChildren = {
  RmhboxLobbyIdRoute: RmhboxLobbyIdRoute,
  RmhboxIndexRoute: RmhboxIndexRoute,
  RmhboxMinigamesIndexRoute: RmhboxMinigamesIndexRoute,
  RmhboxMinigamesMinigameIdHistoryRoute: RmhboxMinigamesMinigameIdHistoryRoute,
}

const RmhboxRouteWithChildren =
  RmhboxRoute._addFileChildren(RmhboxRouteChildren)

interface RmhmusicRouteChildren {
  RmhmusicRoomIdRoute: typeof RmhmusicRoomIdRoute
  RmhmusicPlayerRoute: typeof RmhmusicPlayerRoute
  RmhmusicIndexRoute: typeof RmhmusicIndexRoute
}

const RmhmusicRouteChildren: RmhmusicRouteChildren = {
  RmhmusicRoomIdRoute: RmhmusicRoomIdRoute,
  RmhmusicPlayerRoute: RmhmusicPlayerRoute,
  RmhmusicIndexRoute: RmhmusicIndexRoute,
}

const RmhmusicRouteWithChildren = RmhmusicRoute._addFileChildren(
  RmhmusicRouteChildren,
)

interface RmhstudyRouteChildren {
  RmhstudyRoomIdRoute: typeof RmhstudyRoomIdRoute
  RmhstudyIndexRoute: typeof RmhstudyIndexRoute
}

const RmhstudyRouteChildren: RmhstudyRouteChildren = {
  RmhstudyRoomIdRoute: RmhstudyRoomIdRoute,
  RmhstudyIndexRoute: RmhstudyIndexRoute,
}

const RmhstudyRouteWithChildren = RmhstudyRoute._addFileChildren(
  RmhstudyRouteChildren,
)

interface RmhtubeRouteChildren {
  RmhtubeRoomIdRoute: typeof RmhtubeRoomIdRoute
  RmhtubeIndexRoute: typeof RmhtubeIndexRoute
}

const RmhtubeRouteChildren: RmhtubeRouteChildren = {
  RmhtubeRoomIdRoute: RmhtubeRoomIdRoute,
  RmhtubeIndexRoute: RmhtubeIndexRoute,
}

const RmhtubeRouteWithChildren =
  RmhtubeRoute._addFileChildren(RmhtubeRouteChildren)

interface RmhtypeRouteChildren {
  RmhtypeRoomIdRoute: typeof RmhtypeRoomIdRoute
  RmhtypeMultiplayerRoute: typeof RmhtypeMultiplayerRoute
  RmhtypeSoloRoute: typeof RmhtypeSoloRoute
  RmhtypeIndexRoute: typeof RmhtypeIndexRoute
}

const RmhtypeRouteChildren: RmhtypeRouteChildren = {
  RmhtypeRoomIdRoute: RmhtypeRoomIdRoute,
  RmhtypeMultiplayerRoute: RmhtypeMultiplayerRoute,
  RmhtypeSoloRoute: RmhtypeSoloRoute,
  RmhtypeIndexRoute: RmhtypeIndexRoute,
}

const RmhtypeRouteWithChildren =
  RmhtypeRoute._addFileChildren(RmhtypeRouteChildren)

interface SecretCursedLogicRouteChildren {
  SecretCursedLogicIndexRoute: typeof SecretCursedLogicIndexRoute
}

const SecretCursedLogicRouteChildren: SecretCursedLogicRouteChildren = {
  SecretCursedLogicIndexRoute: SecretCursedLogicIndexRoute,
}

const SecretCursedLogicRouteWithChildren =
  SecretCursedLogicRoute._addFileChildren(SecretCursedLogicRouteChildren)

interface SecretDocsRouteChildren {
  SecretDocsIndexRoute: typeof SecretDocsIndexRoute
}

const SecretDocsRouteChildren: SecretDocsRouteChildren = {
  SecretDocsIndexRoute: SecretDocsIndexRoute,
}

const SecretDocsRouteWithChildren = SecretDocsRoute._addFileChildren(
  SecretDocsRouteChildren,
)

interface SecretJobsRouteChildren {
  SecretJobsIdRoute: typeof SecretJobsIdRoute
  SecretJobsApplicationsRoute: typeof SecretJobsApplicationsRoute
  SecretJobsIndexRoute: typeof SecretJobsIndexRoute
  SecretJobsAssessmentIdRoute: typeof SecretJobsAssessmentIdRoute
}

const SecretJobsRouteChildren: SecretJobsRouteChildren = {
  SecretJobsIdRoute: SecretJobsIdRoute,
  SecretJobsApplicationsRoute: SecretJobsApplicationsRoute,
  SecretJobsIndexRoute: SecretJobsIndexRoute,
  SecretJobsAssessmentIdRoute: SecretJobsAssessmentIdRoute,
}

const SecretJobsRouteWithChildren = SecretJobsRoute._addFileChildren(
  SecretJobsRouteChildren,
)

interface SecretNotesRouteChildren {
  SecretNotesIndexRoute: typeof SecretNotesIndexRoute
}

const SecretNotesRouteChildren: SecretNotesRouteChildren = {
  SecretNotesIndexRoute: SecretNotesIndexRoute,
}

const SecretNotesRouteWithChildren = SecretNotesRoute._addFileChildren(
  SecretNotesRouteChildren,
)

interface SecretSheetsRouteChildren {
  SecretSheetsIndexRoute: typeof SecretSheetsIndexRoute
}

const SecretSheetsRouteChildren: SecretSheetsRouteChildren = {
  SecretSheetsIndexRoute: SecretSheetsIndexRoute,
}

const SecretSheetsRouteWithChildren = SecretSheetsRoute._addFileChildren(
  SecretSheetsRouteChildren,
)

interface SecretSlidesRouteChildren {
  SecretSlidesIndexRoute: typeof SecretSlidesIndexRoute
}

const SecretSlidesRouteChildren: SecretSlidesRouteChildren = {
  SecretSlidesIndexRoute: SecretSlidesIndexRoute,
}

const SecretSlidesRouteWithChildren = SecretSlidesRoute._addFileChildren(
  SecretSlidesRouteChildren,
)

interface SecretWeatherRouteChildren {
  SecretWeatherIndexRoute: typeof SecretWeatherIndexRoute
}

const SecretWeatherRouteChildren: SecretWeatherRouteChildren = {
  SecretWeatherIndexRoute: SecretWeatherIndexRoute,
}

const SecretWeatherRouteWithChildren = SecretWeatherRoute._addFileChildren(
  SecretWeatherRouteChildren,
)

interface SecretRouteChildren {
  SecretCursedLogicRoute: typeof SecretCursedLogicRouteWithChildren
  SecretDocsRoute: typeof SecretDocsRouteWithChildren
  SecretDreamRiftRoute: typeof SecretDreamRiftRoute
  SecretEatsRoute: typeof SecretEatsRoute
  SecretHouseAlwaysWinsRoute: typeof SecretHouseAlwaysWinsRoute
  SecretJobsRoute: typeof SecretJobsRouteWithChildren
  SecretNotesRoute: typeof SecretNotesRouteWithChildren
  SecretSheetsRoute: typeof SecretSheetsRouteWithChildren
  SecretSignalForgeRoute: typeof SecretSignalForgeRoute
  SecretSlidesRoute: typeof SecretSlidesRouteWithChildren
  SecretVegaRoute: typeof SecretVegaRoute
  SecretWeatherRoute: typeof SecretWeatherRouteWithChildren
  SecretIndexRoute: typeof SecretIndexRoute
}

const SecretRouteChildren: SecretRouteChildren = {
  SecretCursedLogicRoute: SecretCursedLogicRouteWithChildren,
  SecretDocsRoute: SecretDocsRouteWithChildren,
  SecretDreamRiftRoute: SecretDreamRiftRoute,
  SecretEatsRoute: SecretEatsRoute,
  SecretHouseAlwaysWinsRoute: SecretHouseAlwaysWinsRoute,
  SecretJobsRoute: SecretJobsRouteWithChildren,
  SecretNotesRoute: SecretNotesRouteWithChildren,
  SecretSheetsRoute: SecretSheetsRouteWithChildren,
  SecretSignalForgeRoute: SecretSignalForgeRoute,
  SecretSlidesRoute: SecretSlidesRouteWithChildren,
  SecretVegaRoute: SecretVegaRoute,
  SecretWeatherRoute: SecretWeatherRouteWithChildren,
  SecretIndexRoute: SecretIndexRoute,
}

const SecretRouteWithChildren =
  SecretRoute._addFileChildren(SecretRouteChildren)

interface SliceItRouteChildren {
  SliceItIndexRoute: typeof SliceItIndexRoute
}

const SliceItRouteChildren: SliceItRouteChildren = {
  SliceItIndexRoute: SliceItIndexRoute,
}

const SliceItRouteWithChildren =
  SliceItRoute._addFileChildren(SliceItRouteChildren)

interface TempleOfJoyRouteChildren {
  TempleOfJoyIndexRoute: typeof TempleOfJoyIndexRoute
}

const TempleOfJoyRouteChildren: TempleOfJoyRouteChildren = {
  TempleOfJoyIndexRoute: TempleOfJoyIndexRoute,
}

const TempleOfJoyRouteWithChildren = TempleOfJoyRoute._addFileChildren(
  TempleOfJoyRouteChildren,
)

interface VersecraftRouteChildren {
  VersecraftIndexRoute: typeof VersecraftIndexRoute
}

const VersecraftRouteChildren: VersecraftRouteChildren = {
  VersecraftIndexRoute: VersecraftIndexRoute,
}

const VersecraftRouteWithChildren = VersecraftRoute._addFileChildren(
  VersecraftRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  BuildsRouteRoute: BuildsRouteRouteWithChildren,
  AltairRoute: AltairRouteWithChildren,
  ForestExplorerRoute: ForestExplorerRouteWithChildren,
  KowloonKnockoutRoute: KowloonKnockoutRouteWithChildren,
  LaundrySortRoute: LaundrySortRoute,
  LightsOutRoute: LightsOutRoute,
  LoginRoute: LoginRoute,
  NeonDriftwayRoute: NeonDriftwayRoute,
  RmhboxRoute: RmhboxRouteWithChildren,
  RmhmusicRoute: RmhmusicRouteWithChildren,
  RmhstudyRoute: RmhstudyRouteWithChildren,
  RmhtubeRoute: RmhtubeRouteWithChildren,
  RmhtypeRoute: RmhtypeRouteWithChildren,
  RoadmapRoute: RoadmapRoute,
  SecretRoute: SecretRouteWithChildren,
  SliceItRoute: SliceItRouteWithChildren,
  SynapseStormRoute: SynapseStormRoute,
  TempleOfJoyRoute: TempleOfJoyRouteWithChildren,
  Velum2099Route: Velum2099Route,
  VersecraftRoute: VersecraftRouteWithChildren,
  VoidBreakerRoute: VoidBreakerRoute,
  BlogSlugRoute: BlogSlugRoute,
  MessagesConversationIdRoute: MessagesConversationIdRoute,
  NewsSlugRoute: NewsSlugRoute,
  ProfileIdRoute: ProfileIdRoute,
  ResearchSlugRoute: ResearchSlugRoute,
  ResearchCallRoute: ResearchCallRoute,
  RmhcodeAuthRoute: RmhcodeAuthRoute,
  UserBuildsSlugRoute: UserBuildsSlugRoute,
  UserBuildsManageRoute: UserBuildsManageRoute,
  UserBuildsSubmitRoute: UserBuildsSubmitRoute,
  BlogIndexRoute: BlogIndexRoute,
  MessagesIndexRoute: MessagesIndexRoute,
  NewsIndexRoute: NewsIndexRoute,
  ResearchIndexRoute: ResearchIndexRoute,
  RmhcodeIndexRoute: RmhcodeIndexRoute,
  UserBuildsIndexRoute: UserBuildsIndexRoute,
  UseridPostPostidRoute: UseridPostPostidRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
