/**
 * Isleworks — the building catalogue.
 *
 * Static data, one entry per thing you can place. This is the single source of
 * truth the palette, the simulation, the save format and the 3D models all read
 * from; nothing else in the game hard-codes a building's numbers.
 *
 * Two rules were followed while tuning, and both are load-bearing:
 *
 *  1. **Every category has a distinct failure mode.** Residential fails on land
 *     value, commercial on customers, industrial on pollution it inflicts on
 *     everyone else, utilities on capacity, civic on radius. A player who spams
 *     one category stalls for a reason they can see.
 *  2. **Cost is roughly 10–14 months of the thing's own contribution.** So a
 *     building always pays back, but only if the surrounding city keeps it
 *     working — which is where the interesting decisions live.
 *
 * `unlockPopulation` gates the palette. It reads `peakPopulation`, so a bad
 * month never takes a building away again.
 */

import type { BuildingCategory, BuildingDefinition } from './types';

export const STARTING_MONEY = 6500;
export const CITY_HALL_ID = 'city-hall';

const defs: BuildingDefinition[] = [
  /* ── Transport ─────────────────────────────────────────────────────────── */
  {
    id: 'road',
    name: 'Road',
    category: 'transport',
    description: 'The spine of everything. Buildings need to touch a road that reaches city hall.',
    cost: 14,
    upkeep: 0.2,
    unlockPopulation: 0,
    footprint: { width: 1, height: 1 },
    requiresRoad: false,
    requiresPower: false,
    requiresWater: false,
    noise: 3,
    effectRadius: 1,
    modelId: 'road',
    iconId: 'Route',
  },
  {
    id: 'bus-stop',
    name: 'Bus Stop',
    category: 'transport',
    description: 'Takes cars off the nearby roads. Cheap, small radius, surprisingly effective.',
    cost: 180,
    upkeep: 4,
    unlockPopulation: 30,
    footprint: { width: 1, height: 1 },
    requiresRoad: true,
    requiresPower: true,
    requiresWater: false,
    powerConsumption: 2,
    happinessBonus: 2,
    effectRadius: 4,
    modelId: 'bus-stop',
    iconId: 'Bus',
  },
  {
    id: 'transit-hub',
    name: 'Transit Hub',
    category: 'transport',
    description: 'Halves congestion across a wide radius and pulls visitors into nearby shops.',
    cost: 2400,
    upkeep: 42,
    unlockPopulation: 220,
    footprint: { width: 2, height: 2 },
    requiresRoad: true,
    requiresPower: true,
    requiresWater: true,
    powerConsumption: 26,
    waterConsumption: 10,
    jobs: 16,
    noise: 6,
    happinessBonus: 6,
    landValueBonus: 5,
    effectRadius: 8,
    modelId: 'transit-hub',
    iconId: 'TrainFront',
  },
  {
    id: 'ferry-dock',
    name: 'Ferry Dock',
    category: 'transport',
    description: 'Must touch water. Brings trade income scaled by how pretty the coast is.',
    cost: 1100,
    upkeep: 20,
    unlockPopulation: 120,
    footprint: { width: 2, height: 1 },
    requiresRoad: true,
    requiresPower: true,
    requiresWater: false,
    requiresShore: true,
    powerConsumption: 10,
    jobs: 8,
    happinessBonus: 3,
    landValueBonus: 6,
    effectRadius: 5,
    modelId: 'ferry-dock',
    iconId: 'Ship',
  },

  /* ── Residential ───────────────────────────────────────────────────────── */
  {
    id: 'cottage',
    name: 'Cottage',
    category: 'residential',
    description: 'A starter home. Undemanding, and content almost anywhere that is quiet.',
    cost: 150,
    upkeep: 1.5,
    unlockPopulation: 0,
    footprint: { width: 1, height: 1 },
    requiresRoad: true,
    requiresPower: true,
    requiresWater: true,
    housing: 4,
    powerConsumption: 3,
    waterConsumption: 3,
    modelId: 'cottage',
    iconId: 'Home',
    upgradeChain: ['duplex'],
  },
  {
    id: 'duplex',
    name: 'Duplex',
    category: 'residential',
    description: 'Two families, one roof. Wants a little land value before anyone moves in.',
    cost: 280,
    upkeep: 3,
    unlockPopulation: 25,
    footprint: { width: 1, height: 1 },
    requiresRoad: true,
    requiresPower: true,
    requiresWater: true,
    housing: 9,
    powerConsumption: 6,
    waterConsumption: 6,
    modelId: 'duplex',
    iconId: 'Hotel',
  },
  {
    id: 'rowhouses',
    name: 'Rowhouses',
    category: 'residential',
    description: 'Dense but low. The efficient middle of the housing ladder.',
    cost: 620,
    upkeep: 7,
    unlockPopulation: 70,
    footprint: { width: 2, height: 1 },
    requiresRoad: true,
    requiresPower: true,
    requiresWater: true,
    housing: 22,
    powerConsumption: 13,
    waterConsumption: 13,
    modelId: 'rowhouses',
    iconId: 'Building',
  },
  {
    id: 'apartments',
    name: 'Apartments',
    category: 'residential',
    description: 'Real density. Needs services nearby or the block empties out again.',
    cost: 1400,
    upkeep: 17,
    unlockPopulation: 150,
    footprint: { width: 2, height: 2 },
    requiresRoad: true,
    requiresPower: true,
    requiresWater: true,
    housing: 52,
    powerConsumption: 30,
    waterConsumption: 30,
    noise: 3,
    modelId: 'apartments',
    iconId: 'Building2',
  },
  {
    id: 'residential-tower',
    name: 'Residential Tower',
    category: 'residential',
    description: 'Houses a neighbourhood on four tiles — and drinks power like one.',
    cost: 3600,
    upkeep: 46,
    unlockPopulation: 400,
    footprint: { width: 2, height: 2 },
    requiresRoad: true,
    requiresPower: true,
    requiresWater: true,
    housing: 120,
    powerConsumption: 74,
    waterConsumption: 70,
    noise: 5,
    modelId: 'residential-tower',
    iconId: 'Building2',
  },
  {
    id: 'condominium',
    name: 'Condominium',
    category: 'residential',
    description: 'Only fills up where land value is high. Pays double the tax when it does.',
    cost: 5200,
    upkeep: 58,
    unlockPopulation: 700,
    footprint: { width: 2, height: 2 },
    requiresRoad: true,
    requiresPower: true,
    requiresWater: true,
    housing: 84,
    powerConsumption: 60,
    waterConsumption: 56,
    landValueBonus: 6,
    effectRadius: 3,
    modelId: 'condominium',
    iconId: 'Hotel',
  },

  /* ── Commercial ────────────────────────────────────────────────────────── */
  {
    id: 'corner-store',
    name: 'Corner Store',
    category: 'commercial',
    description: 'A handful of jobs and a reason to walk down the street.',
    cost: 240,
    upkeep: 4,
    unlockPopulation: 12,
    footprint: { width: 1, height: 1 },
    requiresRoad: true,
    requiresPower: true,
    requiresWater: true,
    jobs: 4,
    powerConsumption: 5,
    waterConsumption: 3,
    happinessBonus: 2,
    effectRadius: 4,
    modelId: 'corner-store',
    iconId: 'Store',
  },
  {
    id: 'cafe',
    name: 'Café',
    category: 'commercial',
    description: 'Small earner, large mood. Land value rises for a few tiles around it.',
    cost: 340,
    upkeep: 6,
    unlockPopulation: 35,
    footprint: { width: 1, height: 1 },
    requiresRoad: true,
    requiresPower: true,
    requiresWater: true,
    jobs: 5,
    powerConsumption: 6,
    waterConsumption: 4,
    happinessBonus: 4,
    landValueBonus: 4,
    effectRadius: 4,
    modelId: 'cafe',
    iconId: 'Coffee',
  },
  {
    id: 'grocery',
    name: 'Grocery',
    category: 'commercial',
    description: 'The workhorse shop. Feeds a whole district and hires from it too.',
    cost: 760,
    upkeep: 12,
    unlockPopulation: 90,
    footprint: { width: 2, height: 1 },
    requiresRoad: true,
    requiresPower: true,
    requiresWater: true,
    jobs: 14,
    powerConsumption: 16,
    waterConsumption: 9,
    happinessBonus: 3,
    effectRadius: 6,
    modelId: 'grocery',
    iconId: 'ShoppingCart',
  },
  {
    id: 'office-block',
    name: 'Office Block',
    category: 'commercial',
    description: 'Clean jobs at density. Wants low noise and a road that is not gridlocked.',
    cost: 1800,
    upkeep: 24,
    unlockPopulation: 180,
    footprint: { width: 2, height: 2 },
    requiresRoad: true,
    requiresPower: true,
    requiresWater: true,
    jobs: 42,
    powerConsumption: 38,
    waterConsumption: 18,
    landValueBonus: 3,
    effectRadius: 4,
    modelId: 'office-block',
    iconId: 'Briefcase',
  },
  {
    id: 'shopping-centre',
    name: 'Shopping Centre',
    category: 'commercial',
    description: 'Draws customers from far away. Also draws every car in the district.',
    cost: 3200,
    upkeep: 44,
    unlockPopulation: 320,
    footprint: { width: 3, height: 2 },
    requiresRoad: true,
    requiresPower: true,
    requiresWater: true,
    jobs: 74,
    powerConsumption: 66,
    waterConsumption: 32,
    noise: 8,
    happinessBonus: 5,
    effectRadius: 8,
    modelId: 'shopping-centre',
    iconId: 'ShoppingBag',
  },
  {
    id: 'business-tower',
    name: 'Business Tower',
    category: 'commercial',
    description: 'The city’s biggest employer. Only worth it where land value already is.',
    cost: 6400,
    upkeep: 88,
    unlockPopulation: 600,
    footprint: { width: 2, height: 2 },
    requiresRoad: true,
    requiresPower: true,
    requiresWater: true,
    jobs: 120,
    powerConsumption: 112,
    waterConsumption: 48,
    landValueBonus: 8,
    effectRadius: 5,
    modelId: 'business-tower',
    iconId: 'Building2',
  },

  /* ── Industrial ────────────────────────────────────────────────────────── */
  {
    id: 'workshop',
    name: 'Workshop',
    category: 'industrial',
    description: 'Early jobs that do not need a degree. Keep it a few tiles from the houses.',
    cost: 300,
    upkeep: 5,
    unlockPopulation: 10,
    footprint: { width: 1, height: 1 },
    requiresRoad: true,
    requiresPower: true,
    requiresWater: true,
    jobs: 7,
    powerConsumption: 8,
    waterConsumption: 5,
    pollution: 6,
    noise: 5,
    effectRadius: 3,
    modelId: 'workshop',
    iconId: 'Hammer',
  },
  {
    id: 'warehouse',
    name: 'Warehouse',
    category: 'industrial',
    description: 'Low pollution, low glamour. Boosts every industrial building around it.',
    cost: 900,
    upkeep: 12,
    unlockPopulation: 110,
    footprint: { width: 2, height: 2 },
    requiresRoad: true,
    requiresPower: true,
    requiresWater: false,
    jobs: 16,
    powerConsumption: 14,
    pollution: 4,
    noise: 6,
    effectRadius: 5,
    modelId: 'warehouse',
    iconId: 'Warehouse',
  },
  {
    id: 'factory',
    name: 'Factory',
    category: 'industrial',
    description: 'The money engine of a young city, and the reason it needs parks.',
    cost: 1900,
    upkeep: 26,
    unlockPopulation: 140,
    footprint: { width: 2, height: 2 },
    requiresRoad: true,
    requiresPower: true,
    requiresWater: true,
    jobs: 38,
    powerConsumption: 46,
    waterConsumption: 26,
    pollution: 22,
    noise: 12,
    effectRadius: 6,
    modelId: 'factory',
    iconId: 'Factory',
  },
  {
    id: 'recycling-plant',
    name: 'Recycling Plant',
    category: 'industrial',
    description: 'Runs the pollution back out of the neighbourhood instead of into it.',
    cost: 2600,
    upkeep: 34,
    unlockPopulation: 260,
    footprint: { width: 2, height: 2 },
    requiresRoad: true,
    requiresPower: true,
    requiresWater: true,
    jobs: 26,
    powerConsumption: 40,
    waterConsumption: 22,
    pollution: -16,
    noise: 7,
    effectRadius: 7,
    modelId: 'recycling-plant',
    iconId: 'Recycle',
  },
  {
    id: 'fabrication-lab',
    name: 'Fabrication Lab',
    category: 'industrial',
    description: 'Clean industry. Needs an educated city — efficiency scales with schooling.',
    cost: 4200,
    upkeep: 54,
    unlockPopulation: 480,
    footprint: { width: 2, height: 2 },
    requiresRoad: true,
    requiresPower: true,
    requiresWater: true,
    jobs: 56,
    powerConsumption: 78,
    waterConsumption: 30,
    pollution: 5,
    noise: 4,
    landValueBonus: 2,
    effectRadius: 4,
    modelId: 'fabrication-lab',
    iconId: 'Cpu',
  },

  /* ── Civic ─────────────────────────────────────────────────────────────── */
  {
    id: CITY_HALL_ID,
    name: 'City Hall',
    category: 'civic',
    description: 'Where the island begins. Every road network is measured from here.',
    cost: 0,
    upkeep: 5,
    unlockPopulation: 0,
    unique: true,
    footprint: { width: 2, height: 2 },
    requiresRoad: false,
    requiresPower: false,
    requiresWater: false,
    jobs: 8,
    happinessBonus: 4,
    landValueBonus: 6,
    effectRadius: 6,
    modelId: 'city-hall',
    iconId: 'Landmark',
  },
  {
    id: 'clinic',
    name: 'Clinic',
    category: 'civic',
    description: 'Basic health cover for a few streets. The first civic building most cities need.',
    cost: 640,
    upkeep: 11,
    unlockPopulation: 40,
    footprint: { width: 1, height: 1 },
    requiresRoad: true,
    requiresPower: true,
    requiresWater: true,
    jobs: 8,
    powerConsumption: 10,
    waterConsumption: 8,
    service: 'health',
    serviceCapacity: 90,
    happinessBonus: 3,
    effectRadius: 6,
    modelId: 'clinic',
    iconId: 'Stethoscope',
  },
  {
    id: 'hospital',
    name: 'Hospital',
    category: 'civic',
    description: 'Covers most of an island. Expensive to run, and worth it past a few hundred.',
    cost: 3800,
    upkeep: 62,
    unlockPopulation: 300,
    footprint: { width: 3, height: 2 },
    requiresRoad: true,
    requiresPower: true,
    requiresWater: true,
    jobs: 46,
    powerConsumption: 58,
    waterConsumption: 44,
    service: 'health',
    serviceCapacity: 620,
    happinessBonus: 5,
    landValueBonus: 2,
    effectRadius: 11,
    modelId: 'hospital',
    iconId: 'Cross',
  },
  {
    id: 'fire-station',
    name: 'Fire Station',
    category: 'civic',
    description: 'Keeps buildings in repair. Without cover, condition decays and output with it.',
    cost: 900,
    upkeep: 14,
    unlockPopulation: 60,
    footprint: { width: 2, height: 1 },
    requiresRoad: true,
    requiresPower: true,
    requiresWater: true,
    jobs: 12,
    powerConsumption: 10,
    waterConsumption: 10,
    service: 'fire',
    serviceCapacity: 320,
    noise: 3,
    effectRadius: 8,
    modelId: 'fire-station',
    iconId: 'Flame',
  },
  {
    id: 'police-station',
    name: 'Police Station',
    category: 'civic',
    description: 'Safety cover. Low land value plus no cover is how a district starts emptying.',
    cost: 1000,
    upkeep: 16,
    unlockPopulation: 80,
    footprint: { width: 2, height: 1 },
    requiresRoad: true,
    requiresPower: true,
    requiresWater: true,
    jobs: 14,
    powerConsumption: 12,
    waterConsumption: 8,
    service: 'safety',
    serviceCapacity: 340,
    happinessBonus: 2,
    effectRadius: 8,
    modelId: 'police-station',
    iconId: 'Shield',
  },
  {
    id: 'school',
    name: 'School',
    category: 'civic',
    description: 'Education raises land value, unlocks clean industry, and keeps families here.',
    cost: 1600,
    upkeep: 22,
    unlockPopulation: 120,
    footprint: { width: 2, height: 2 },
    requiresRoad: true,
    requiresPower: true,
    requiresWater: true,
    jobs: 22,
    powerConsumption: 22,
    waterConsumption: 18,
    service: 'education',
    serviceCapacity: 300,
    happinessBonus: 4,
    landValueBonus: 3,
    effectRadius: 9,
    modelId: 'school',
    iconId: 'School',
  },
  {
    id: 'university',
    name: 'University',
    category: 'civic',
    description: 'The whole island gets smarter. Fabrication labs run at full tilt near one.',
    cost: 6800,
    upkeep: 92,
    unlockPopulation: 520,
    footprint: { width: 3, height: 3 },
    requiresRoad: true,
    requiresPower: true,
    requiresWater: true,
    jobs: 78,
    powerConsumption: 84,
    waterConsumption: 60,
    service: 'education',
    serviceCapacity: 900,
    happinessBonus: 6,
    landValueBonus: 7,
    effectRadius: 14,
    modelId: 'university',
    iconId: 'GraduationCap',
  },

  /* ── Recreation ────────────────────────────────────────────────────────── */
  {
    id: 'pocket-park',
    name: 'Pocket Park',
    category: 'recreation',
    description: 'Cheap, tiny, and the fastest way to lift a street out of the doldrums.',
    cost: 120,
    upkeep: 2,
    unlockPopulation: 0,
    footprint: { width: 1, height: 1 },
    requiresRoad: false,
    requiresPower: false,
    requiresWater: true,
    waterConsumption: 2,
    pollution: -4,
    service: 'leisure',
    serviceCapacity: 60,
    happinessBonus: 3,
    landValueBonus: 5,
    effectRadius: 3,
    modelId: 'pocket-park',
    iconId: 'Trees',
  },
  {
    id: 'playground',
    name: 'Playground',
    category: 'recreation',
    description: 'Families notice. Pairs well with anywhere you have put a lot of housing.',
    cost: 240,
    upkeep: 4,
    unlockPopulation: 30,
    footprint: { width: 1, height: 1 },
    requiresRoad: false,
    requiresPower: false,
    requiresWater: true,
    waterConsumption: 2,
    pollution: -2,
    service: 'leisure',
    serviceCapacity: 110,
    happinessBonus: 5,
    landValueBonus: 4,
    effectRadius: 4,
    modelId: 'playground',
    iconId: 'Baby',
  },
  {
    id: 'sports-court',
    name: 'Sports Court',
    category: 'recreation',
    description: 'A little noisy, a lot popular. Best a tile or two off the housing.',
    cost: 520,
    upkeep: 8,
    unlockPopulation: 80,
    footprint: { width: 2, height: 1 },
    requiresRoad: true,
    requiresPower: true,
    requiresWater: true,
    powerConsumption: 6,
    waterConsumption: 5,
    noise: 5,
    service: 'leisure',
    serviceCapacity: 220,
    happinessBonus: 6,
    landValueBonus: 3,
    effectRadius: 6,
    modelId: 'sports-court',
    iconId: 'Dumbbell',
  },
  {
    id: 'plaza',
    name: 'Plaza',
    category: 'recreation',
    description: 'A fountain, some benches, and a noticeable jump in what the land is worth.',
    cost: 900,
    upkeep: 12,
    unlockPopulation: 140,
    footprint: { width: 2, height: 2 },
    requiresRoad: true,
    requiresPower: true,
    requiresWater: true,
    powerConsumption: 6,
    waterConsumption: 8,
    pollution: -4,
    service: 'leisure',
    serviceCapacity: 260,
    happinessBonus: 6,
    landValueBonus: 9,
    effectRadius: 6,
    modelId: 'plaza',
    iconId: 'Sparkles',
  },
  {
    id: 'botanical-garden',
    name: 'Botanical Garden',
    category: 'recreation',
    description: 'Scrubs pollution over a wide radius and makes the whole district desirable.',
    cost: 2200,
    upkeep: 26,
    unlockPopulation: 240,
    footprint: { width: 2, height: 2 },
    requiresRoad: true,
    requiresPower: true,
    requiresWater: true,
    powerConsumption: 10,
    waterConsumption: 24,
    pollution: -20,
    service: 'leisure',
    serviceCapacity: 380,
    happinessBonus: 7,
    landValueBonus: 10,
    effectRadius: 8,
    modelId: 'botanical-garden',
    iconId: 'Flower2',
  },
  {
    id: 'museum',
    name: 'Museum',
    category: 'recreation',
    description: 'Visitors pay to come. Trade income scales with how happy the city is.',
    cost: 3400,
    upkeep: 44,
    unlockPopulation: 380,
    footprint: { width: 2, height: 2 },
    requiresRoad: true,
    requiresPower: true,
    requiresWater: true,
    jobs: 20,
    powerConsumption: 30,
    waterConsumption: 14,
    service: 'leisure',
    serviceCapacity: 420,
    happinessBonus: 8,
    landValueBonus: 12,
    effectRadius: 9,
    modelId: 'museum',
    iconId: 'Palette',
  },
  {
    id: 'observatory',
    name: 'Observatory',
    category: 'recreation',
    description: 'The landmark. One per island is plenty — it lifts land value everywhere.',
    cost: 7500,
    upkeep: 70,
    unlockPopulation: 750,
    footprint: { width: 2, height: 2 },
    requiresRoad: true,
    requiresPower: true,
    requiresWater: true,
    jobs: 24,
    powerConsumption: 48,
    waterConsumption: 16,
    service: 'leisure',
    serviceCapacity: 600,
    happinessBonus: 10,
    landValueBonus: 16,
    effectRadius: 14,
    modelId: 'observatory',
    iconId: 'Telescope',
  },

  /* ── Utility ───────────────────────────────────────────────────────────── */
  {
    id: 'wind-turbine',
    name: 'Wind Turbine',
    category: 'utility',
    description: 'Clean, quiet-ish, and cheap enough to dot around the edges of the island.',
    cost: 420,
    upkeep: 4,
    unlockPopulation: 0,
    footprint: { width: 1, height: 1 },
    requiresRoad: false,
    requiresPower: false,
    requiresWater: false,
    powerGeneration: 34,
    noise: 4,
    effectRadius: 2,
    modelId: 'wind-turbine',
    iconId: 'Wind',
  },
  {
    id: 'solar-array',
    name: 'Solar Array',
    category: 'utility',
    description: 'Silent and clean. Output dips at night, so pair it with storage.',
    cost: 1500,
    upkeep: 14,
    unlockPopulation: 100,
    footprint: { width: 2, height: 2 },
    requiresRoad: false,
    requiresPower: false,
    requiresWater: false,
    powerGeneration: 96,
    modelId: 'solar-array',
    iconId: 'Sun',
  },
  {
    id: 'gas-plant',
    name: 'Gas Plant',
    category: 'utility',
    description: 'Enormous, steady output. Everything downwind of it pays for the privilege.',
    cost: 2800,
    upkeep: 36,
    unlockPopulation: 180,
    footprint: { width: 2, height: 2 },
    requiresRoad: true,
    requiresPower: false,
    requiresWater: true,
    waterConsumption: 20,
    powerGeneration: 320,
    jobs: 14,
    pollution: 28,
    noise: 12,
    effectRadius: 7,
    modelId: 'gas-plant',
    iconId: 'Zap',
  },
  {
    id: 'battery-bank',
    name: 'Battery Bank',
    category: 'utility',
    description: 'Buffers the grid. Covers the night-time solar dip and blunts demand spikes.',
    cost: 1200,
    upkeep: 10,
    unlockPopulation: 160,
    footprint: { width: 1, height: 1 },
    requiresRoad: false,
    requiresPower: false,
    requiresWater: false,
    powerGeneration: 40,
    modelId: 'battery-bank',
    iconId: 'BatteryCharging',
  },
  {
    id: 'water-tower',
    name: 'Water Tower',
    category: 'utility',
    description: 'Starter water. Goes anywhere, holds enough for a couple of streets.',
    cost: 400,
    upkeep: 4,
    unlockPopulation: 0,
    footprint: { width: 1, height: 1 },
    requiresRoad: false,
    requiresPower: true,
    requiresWater: false,
    powerConsumption: 5,
    waterGeneration: 46,
    modelId: 'water-tower',
    iconId: 'Droplet',
  },
  {
    id: 'pumping-station',
    name: 'Pumping Station',
    category: 'utility',
    description: 'Must touch the sea. Supplies a whole district for the price of one coastal tile.',
    cost: 1600,
    upkeep: 16,
    unlockPopulation: 90,
    footprint: { width: 2, height: 1 },
    requiresRoad: true,
    requiresPower: true,
    requiresWater: false,
    requiresShore: true,
    powerConsumption: 24,
    waterGeneration: 220,
    jobs: 6,
    noise: 4,
    effectRadius: 3,
    modelId: 'pumping-station',
    iconId: 'Droplets',
  },
  {
    id: 'sewage-works',
    name: 'Sewage Works',
    category: 'utility',
    description: 'Raises the ceiling on how much water the city can actually use.',
    cost: 2000,
    upkeep: 30,
    unlockPopulation: 200,
    footprint: { width: 2, height: 2 },
    requiresRoad: true,
    requiresPower: true,
    requiresWater: false,
    powerConsumption: 30,
    waterGeneration: 140,
    jobs: 10,
    pollution: 14,
    noise: 6,
    effectRadius: 5,
    modelId: 'sewage-works',
    iconId: 'Waves',
  },
  {
    id: 'waste-depot',
    name: 'Waste Depot',
    category: 'utility',
    description: 'Hauls the city’s rubbish away. Cuts pollution everywhere, smells locally.',
    cost: 1400,
    upkeep: 24,
    unlockPopulation: 150,
    footprint: { width: 2, height: 1 },
    requiresRoad: true,
    requiresPower: true,
    requiresWater: false,
    powerConsumption: 16,
    jobs: 12,
    pollution: 8,
    noise: 7,
    effectRadius: 4,
    modelId: 'waste-depot',
    iconId: 'Trash2',
  },

  /* ── Decoration ────────────────────────────────────────────────────────── */
  {
    id: 'tree-cluster',
    name: 'Tree Cluster',
    category: 'decoration',
    description: 'Three trees. Quietly cleans the air and softens whatever is next to it.',
    cost: 45,
    upkeep: 0.4,
    unlockPopulation: 0,
    footprint: { width: 1, height: 1 },
    requiresRoad: false,
    requiresPower: false,
    requiresWater: false,
    pollution: -3,
    landValueBonus: 3,
    effectRadius: 2,
    modelId: 'tree-cluster',
    iconId: 'TreePine',
  },
  {
    id: 'flowerbed',
    name: 'Flowerbed',
    category: 'decoration',
    description: 'The cheapest land value in the game, one tile at a time.',
    cost: 30,
    upkeep: 0.3,
    unlockPopulation: 0,
    footprint: { width: 1, height: 1 },
    requiresRoad: false,
    requiresPower: false,
    requiresWater: false,
    landValueBonus: 2,
    happinessBonus: 1,
    effectRadius: 2,
    modelId: 'flowerbed',
    iconId: 'Flower2',
  },
  {
    id: 'fountain',
    name: 'Fountain',
    category: 'decoration',
    description: 'A centrepiece. Worth more surrounded by paving than hidden behind a factory.',
    cost: 260,
    upkeep: 3,
    unlockPopulation: 40,
    footprint: { width: 1, height: 1 },
    requiresRoad: false,
    requiresPower: true,
    requiresWater: true,
    powerConsumption: 2,
    waterConsumption: 4,
    landValueBonus: 6,
    happinessBonus: 2,
    effectRadius: 3,
    modelId: 'fountain',
    iconId: 'Sparkles',
  },
  {
    id: 'lamp-post',
    name: 'Lamp Post',
    category: 'decoration',
    description: 'Lights the street after dark and makes the neighbours feel safer.',
    cost: 40,
    upkeep: 0.6,
    unlockPopulation: 20,
    footprint: { width: 1, height: 1 },
    requiresRoad: false,
    requiresPower: true,
    requiresWater: false,
    powerConsumption: 1,
    landValueBonus: 1,
    happinessBonus: 1,
    effectRadius: 2,
    modelId: 'lamp-post',
    iconId: 'Lamp',
  },
  {
    id: 'statue',
    name: 'Statue',
    category: 'decoration',
    description: 'Nobody remembers who it is. Everybody agrees the square looks better.',
    cost: 480,
    upkeep: 4,
    unlockPopulation: 100,
    footprint: { width: 1, height: 1 },
    requiresRoad: false,
    requiresPower: false,
    requiresWater: false,
    landValueBonus: 8,
    happinessBonus: 2,
    effectRadius: 4,
    modelId: 'statue',
    iconId: 'Gem',
  },
];

export const BUILDINGS: readonly BuildingDefinition[] = defs;

const BY_ID = new Map(defs.map((d) => [d.id, d]));

export function getDefinition(id: string): BuildingDefinition {
  const def = BY_ID.get(id);
  if (!def) throw new Error(`Isleworks: unknown building definition "${id}"`);
  return def;
}

export function tryGetDefinition(id: string): BuildingDefinition | undefined {
  return BY_ID.get(id);
}

export const CATEGORY_ORDER: BuildingCategory[] = [
  'transport',
  'residential',
  'commercial',
  'industrial',
  'civic',
  'recreation',
  'utility',
  'decoration',
];

export const CATEGORY_LABELS: Record<BuildingCategory, string> = {
  transport: 'Transport',
  residential: 'Homes',
  commercial: 'Shops',
  industrial: 'Industry',
  civic: 'Services',
  recreation: 'Leisure',
  utility: 'Utilities',
  decoration: 'Decor',
};

/** Palette contents for a category, hiding anything the city has not unlocked. */
export function unlockedIn(
  category: BuildingCategory,
  peakPopulation: number,
): BuildingDefinition[] {
  return defs.filter(
    (d) => d.category === category && !d.unique && d.unlockPopulation <= peakPopulation,
  );
}

/** The next thing that unlocks, for the "coming up" hint in the palette. */
export function nextUnlock(peakPopulation: number): BuildingDefinition | undefined {
  return defs
    .filter((d) => !d.unique && d.unlockPopulation > peakPopulation)
    .sort((a, b) => a.unlockPopulation - b.unlockPopulation)[0];
}
