/**
 * The Dunesday watch list — every MCU film and Disney+ series, plus the Dune
 * films, that a marathon before Avengers: Doomsday and Dune: Part Three (both
 * 18 December 2026) could include.
 *
 * Runtimes are in minutes. Films are the theatrical cut. A series carries its
 * total runtime and its episode count, and the scheduler splits it at episode
 * boundaries, so a 9-episode show can spread over several nights. Anything
 * marked `approx` is an estimate (a recent release, or a series whose episode
 * lengths vary) — the page says so and lets the viewer correct it, which is
 * why the runtimes here are a default rather than a fact the UI depends on.
 *
 * `chrono` is the in-universe position used by "Story order". It follows the
 * order Disney+ publishes for the timeline, which is itself a judgement call
 * for the multiverse-era shows; ties don't matter because no two share a value.
 *
 * Titles are proper nouns and stay in English in every locale, the same way
 * the library's book titles do.
 */

/** `extra` is a title the viewer added themselves (an X-Men film, a Sony one…). */
export type Franchise = 'mcu' | 'dune' | 'extra';
export type TitleKind = 'film' | 'series' | 'special';

export interface WatchTitle {
  id: string;
  title: string;
  franchise: Franchise;
  kind: TitleKind;
  /** ISO release date (US). */
  released: string;
  /** Total runtime in minutes. */
  minutes: number;
  /** Episode count for a series; absent for films and specials. */
  episodes?: number;
  /** In-universe position for "Story order". */
  chrono: number;
  /** MCU phase (1–6), or 0 for Dune. */
  phase: number;
  /** Part of the short "essentials" track for the two December releases. */
  essential: boolean;
  animated?: boolean;
  /** The runtime is an estimate the viewer may want to correct. */
  approx?: boolean;
  /** One line shown under the title — what it sets up for December. */
  hook: string;
}

export const DUNESDAY = '2026-12-18';

export const TITLES: WatchTitle[] = [
  // ── Phase 1 ─────────────────────────────────────────────────────────────
  {
    id: 'iron-man',
    title: 'Iron Man',
    franchise: 'mcu',
    kind: 'film',
    released: '2008-05-02',
    minutes: 126,
    chrono: 3,
    phase: 1,
    essential: true,
    hook: 'Where it all starts: Tony Stark builds the suit.',
  },
  {
    id: 'incredible-hulk',
    title: 'The Incredible Hulk',
    franchise: 'mcu',
    kind: 'film',
    released: '2008-06-13',
    minutes: 112,
    chrono: 5,
    phase: 1,
    essential: false,
    hook: 'Bruce Banner on the run; introduces Thunderbolt Ross.',
  },
  {
    id: 'iron-man-2',
    title: 'Iron Man 2',
    franchise: 'mcu',
    kind: 'film',
    released: '2010-05-07',
    minutes: 124,
    chrono: 4,
    phase: 1,
    essential: false,
    hook: 'Black Widow arrives and S.H.I.E.L.D. steps forward.',
  },
  {
    id: 'thor',
    title: 'Thor',
    franchise: 'mcu',
    kind: 'film',
    released: '2011-05-06',
    minutes: 115,
    chrono: 6,
    phase: 1,
    essential: false,
    hook: 'Asgard, Loki, and the God of Thunder.',
  },
  {
    id: 'cap-first-avenger',
    title: 'Captain America: The First Avenger',
    franchise: 'mcu',
    kind: 'film',
    released: '2011-07-22',
    minutes: 124,
    chrono: 1,
    phase: 1,
    essential: true,
    hook: 'Steve Rogers, Bucky, and the Tesseract in WWII.',
  },
  {
    id: 'avengers',
    title: 'The Avengers',
    franchise: 'mcu',
    kind: 'film',
    released: '2012-05-04',
    minutes: 143,
    chrono: 7,
    phase: 1,
    essential: true,
    hook: 'The team assembles for the first time.',
  },
  // ── Phase 2 ─────────────────────────────────────────────────────────────
  {
    id: 'iron-man-3',
    title: 'Iron Man 3',
    franchise: 'mcu',
    kind: 'film',
    released: '2013-05-03',
    minutes: 130,
    chrono: 9,
    phase: 2,
    essential: false,
    hook: 'Tony after New York, and the Mandarin.',
  },
  {
    id: 'thor-dark-world',
    title: 'Thor: The Dark World',
    franchise: 'mcu',
    kind: 'film',
    released: '2013-11-08',
    minutes: 112,
    chrono: 8,
    phase: 2,
    essential: false,
    hook: 'The Aether — an Infinity Stone.',
  },
  {
    id: 'cap-winter-soldier',
    title: 'Captain America: The Winter Soldier',
    franchise: 'mcu',
    kind: 'film',
    released: '2014-04-04',
    minutes: 136,
    chrono: 10,
    phase: 2,
    essential: true,
    hook: 'Bucky returns and S.H.I.E.L.D. falls.',
  },
  {
    id: 'gotg',
    title: 'Guardians of the Galaxy',
    franchise: 'mcu',
    kind: 'film',
    released: '2014-08-01',
    minutes: 121,
    chrono: 11,
    phase: 2,
    essential: true,
    hook: 'The cosmic side of the MCU, with Thanos in the wings.',
  },
  {
    id: 'age-of-ultron',
    title: 'Avengers: Age of Ultron',
    franchise: 'mcu',
    kind: 'film',
    released: '2015-05-01',
    minutes: 141,
    chrono: 13,
    phase: 2,
    essential: true,
    hook: 'Ultron, Vision and Wanda Maximoff.',
  },
  {
    id: 'ant-man',
    title: 'Ant-Man',
    franchise: 'mcu',
    kind: 'film',
    released: '2015-07-17',
    minutes: 117,
    chrono: 14,
    phase: 2,
    essential: false,
    hook: 'Scott Lang and the Quantum Realm.',
  },
  // ── Phase 3 ─────────────────────────────────────────────────────────────
  {
    id: 'civil-war',
    title: 'Captain America: Civil War',
    franchise: 'mcu',
    kind: 'film',
    released: '2016-05-06',
    minutes: 147,
    chrono: 15,
    phase: 3,
    essential: true,
    hook: 'The Avengers split; Black Panther and Spider-Man debut.',
  },
  {
    id: 'doctor-strange',
    title: 'Doctor Strange',
    franchise: 'mcu',
    kind: 'film',
    released: '2016-11-04',
    minutes: 115,
    chrono: 19,
    phase: 3,
    essential: false,
    hook: 'Magic, the Time Stone and the multiverse idea.',
  },
  {
    id: 'gotg-2',
    title: 'Guardians of the Galaxy Vol. 2',
    franchise: 'mcu',
    kind: 'film',
    released: '2017-05-05',
    minutes: 136,
    chrono: 12,
    phase: 3,
    essential: false,
    hook: "Peter Quill's father.",
  },
  {
    id: 'spider-man-homecoming',
    title: 'Spider-Man: Homecoming',
    franchise: 'mcu',
    kind: 'film',
    released: '2017-07-07',
    minutes: 133,
    chrono: 18,
    phase: 3,
    essential: false,
    hook: 'Peter Parker under Tony Stark’s wing.',
  },
  {
    id: 'thor-ragnarok',
    title: 'Thor: Ragnarok',
    franchise: 'mcu',
    kind: 'film',
    released: '2017-11-03',
    minutes: 130,
    chrono: 20,
    phase: 3,
    essential: true,
    hook: 'Asgard falls; Thor and Hulk team up.',
  },
  {
    id: 'black-panther',
    title: 'Black Panther',
    franchise: 'mcu',
    kind: 'film',
    released: '2018-02-16',
    minutes: 134,
    chrono: 17,
    phase: 3,
    essential: false,
    hook: 'Wakanda opens to the world.',
  },
  {
    id: 'infinity-war',
    title: 'Avengers: Infinity War',
    franchise: 'mcu',
    kind: 'film',
    released: '2018-04-27',
    minutes: 149,
    chrono: 22,
    phase: 3,
    essential: true,
    hook: 'Thanos and the snap.',
  },
  {
    id: 'ant-man-wasp',
    title: 'Ant-Man and the Wasp',
    franchise: 'mcu',
    kind: 'film',
    released: '2018-07-06',
    minutes: 118,
    chrono: 21,
    phase: 3,
    essential: false,
    hook: 'The Quantum Realm that makes time travel possible.',
  },
  {
    id: 'captain-marvel',
    title: 'Captain Marvel',
    franchise: 'mcu',
    kind: 'film',
    released: '2019-03-08',
    minutes: 123,
    chrono: 2,
    phase: 3,
    essential: false,
    hook: 'Carol Danvers in the 1990s; the Skrulls.',
  },
  {
    id: 'endgame',
    title: 'Avengers: Endgame',
    franchise: 'mcu',
    kind: 'film',
    released: '2019-04-26',
    minutes: 181,
    chrono: 23,
    phase: 3,
    essential: true,
    hook: 'The time heist and the end of the Infinity Saga.',
  },
  {
    id: 'far-from-home',
    title: 'Spider-Man: Far From Home',
    franchise: 'mcu',
    kind: 'film',
    released: '2019-07-02',
    minutes: 129,
    chrono: 30,
    phase: 3,
    essential: false,
    hook: 'Life after Endgame; Peter’s identity revealed.',
  },
  // ── Phase 4 ─────────────────────────────────────────────────────────────
  {
    id: 'wandavision',
    title: 'WandaVision',
    franchise: 'mcu',
    kind: 'series',
    released: '2021-01-15',
    minutes: 350,
    episodes: 9,
    chrono: 26,
    phase: 4,
    essential: false,
    approx: true,
    hook: 'Wanda’s grief becomes a sitcom reality.',
  },
  {
    id: 'falcon-winter-soldier',
    title: 'The Falcon and the Winter Soldier',
    franchise: 'mcu',
    kind: 'series',
    released: '2021-03-19',
    minutes: 300,
    episodes: 6,
    chrono: 28,
    phase: 4,
    essential: true,
    approx: true,
    hook: 'Sam Wilson takes up the shield.',
  },
  {
    id: 'loki-1',
    title: 'Loki (Season 1)',
    franchise: 'mcu',
    kind: 'series',
    released: '2021-06-09',
    minutes: 285,
    episodes: 6,
    chrono: 24,
    phase: 4,
    essential: true,
    approx: true,
    hook: 'The TVA, variants, and the multiverse breaks open.',
  },
  {
    id: 'black-widow',
    title: 'Black Widow',
    franchise: 'mcu',
    kind: 'film',
    released: '2021-07-09',
    minutes: 134,
    chrono: 16,
    phase: 4,
    essential: false,
    hook: 'Natasha’s past; Yelena Belova and the Red Guardian.',
  },
  {
    id: 'what-if-1',
    title: 'What If...? (Season 1)',
    franchise: 'mcu',
    kind: 'series',
    released: '2021-08-11',
    minutes: 300,
    episodes: 9,
    chrono: 25,
    phase: 4,
    essential: false,
    animated: true,
    approx: true,
    hook: 'Animated alternate realities and the Watcher.',
  },
  {
    id: 'shang-chi',
    title: 'Shang-Chi and the Legend of the Ten Rings',
    franchise: 'mcu',
    kind: 'film',
    released: '2021-09-03',
    minutes: 132,
    chrono: 27,
    phase: 4,
    essential: false,
    hook: 'The Ten Rings and a hidden realm.',
  },
  {
    id: 'eternals',
    title: 'Eternals',
    franchise: 'mcu',
    kind: 'film',
    released: '2021-11-05',
    minutes: 156,
    chrono: 29,
    phase: 4,
    essential: false,
    hook: 'Ancient guardians and the Celestials.',
  },
  {
    id: 'hawkeye',
    title: 'Hawkeye',
    franchise: 'mcu',
    kind: 'series',
    released: '2021-11-24',
    minutes: 300,
    episodes: 6,
    chrono: 32,
    phase: 4,
    essential: false,
    approx: true,
    hook: 'Clint Barton meets Kate Bishop at Christmas.',
  },
  {
    id: 'no-way-home',
    title: 'Spider-Man: No Way Home',
    franchise: 'mcu',
    kind: 'film',
    released: '2021-12-17',
    minutes: 148,
    chrono: 31,
    phase: 4,
    essential: true,
    hook: 'The multiverse spell that erases Peter Parker.',
  },
  {
    id: 'moon-knight',
    title: 'Moon Knight',
    franchise: 'mcu',
    kind: 'series',
    released: '2022-03-30',
    minutes: 280,
    episodes: 6,
    chrono: 33,
    phase: 4,
    essential: false,
    approx: true,
    hook: 'Marc Spector and the Egyptian gods.',
  },
  {
    id: 'multiverse-of-madness',
    title: 'Doctor Strange in the Multiverse of Madness',
    franchise: 'mcu',
    kind: 'film',
    released: '2022-05-06',
    minutes: 126,
    chrono: 34,
    phase: 4,
    essential: true,
    hook: 'Incursions — when universes collide.',
  },
  {
    id: 'ms-marvel',
    title: 'Ms. Marvel',
    franchise: 'mcu',
    kind: 'series',
    released: '2022-06-08',
    minutes: 280,
    episodes: 6,
    chrono: 35,
    phase: 4,
    essential: false,
    approx: true,
    hook: 'Kamala Khan, who leads into The Marvels.',
  },
  {
    id: 'love-and-thunder',
    title: 'Thor: Love and Thunder',
    franchise: 'mcu',
    kind: 'film',
    released: '2022-07-08',
    minutes: 119,
    chrono: 36,
    phase: 4,
    essential: false,
    hook: 'Gorr the God Butcher and Mighty Thor.',
  },
  {
    id: 'she-hulk',
    title: 'She-Hulk: Attorney at Law',
    franchise: 'mcu',
    kind: 'series',
    released: '2022-08-18',
    minutes: 300,
    episodes: 9,
    chrono: 38,
    phase: 4,
    essential: false,
    approx: true,
    hook: 'Jennifer Walters, fourth-wall breaks and Daredevil.',
  },
  {
    id: 'werewolf-by-night',
    title: 'Werewolf by Night',
    franchise: 'mcu',
    kind: 'special',
    released: '2022-10-07',
    minutes: 53,
    chrono: 37,
    phase: 4,
    essential: false,
    hook: 'A black-and-white monster-hunt special.',
  },
  {
    id: 'wakanda-forever',
    title: 'Black Panther: Wakanda Forever',
    franchise: 'mcu',
    kind: 'film',
    released: '2022-11-11',
    minutes: 161,
    chrono: 39,
    phase: 4,
    essential: false,
    hook: 'Wakanda mourns; Namor and Talokan.',
  },
  {
    id: 'gotg-holiday',
    title: 'The Guardians of the Galaxy Holiday Special',
    franchise: 'mcu',
    kind: 'special',
    released: '2022-11-25',
    minutes: 44,
    chrono: 41,
    phase: 4,
    essential: false,
    hook: 'Kevin Bacon, kidnapped for Christmas.',
  },
  // ── Phase 5 ─────────────────────────────────────────────────────────────
  {
    id: 'quantumania',
    title: 'Ant-Man and the Wasp: Quantumania',
    franchise: 'mcu',
    kind: 'film',
    released: '2023-02-17',
    minutes: 125,
    chrono: 42,
    phase: 5,
    essential: false,
    hook: 'Deep in the Quantum Realm.',
  },
  {
    id: 'gotg-3',
    title: 'Guardians of the Galaxy Vol. 3',
    franchise: 'mcu',
    kind: 'film',
    released: '2023-05-05',
    minutes: 150,
    chrono: 43,
    phase: 5,
    essential: false,
    hook: 'Rocket’s origin and the team’s farewell.',
  },
  {
    id: 'secret-invasion',
    title: 'Secret Invasion',
    franchise: 'mcu',
    kind: 'series',
    released: '2023-06-21',
    minutes: 300,
    episodes: 6,
    chrono: 44,
    phase: 5,
    essential: false,
    approx: true,
    hook: 'Nick Fury and the Skrull infiltration.',
  },
  {
    id: 'loki-2',
    title: 'Loki (Season 2)',
    franchise: 'mcu',
    kind: 'series',
    released: '2023-10-05',
    minutes: 300,
    episodes: 6,
    chrono: 46,
    phase: 5,
    essential: true,
    approx: true,
    hook: 'Loki takes the throne at the end of time.',
  },
  {
    id: 'the-marvels',
    title: 'The Marvels',
    franchise: 'mcu',
    kind: 'film',
    released: '2023-11-10',
    minutes: 105,
    chrono: 45,
    phase: 5,
    essential: false,
    hook: 'Carol, Monica and Kamala swap places.',
  },
  {
    id: 'what-if-2',
    title: 'What If...? (Season 2)',
    franchise: 'mcu',
    kind: 'series',
    released: '2023-12-22',
    minutes: 300,
    episodes: 9,
    chrono: 47,
    phase: 5,
    essential: false,
    animated: true,
    approx: true,
    hook: 'More realities, and Kahhori.',
  },
  {
    id: 'echo',
    title: 'Echo',
    franchise: 'mcu',
    kind: 'series',
    released: '2024-01-09',
    minutes: 220,
    episodes: 5,
    chrono: 40,
    phase: 5,
    essential: false,
    approx: true,
    hook: 'Maya Lopez goes home; Kingpin follows.',
  },
  {
    id: 'deadpool-wolverine',
    title: 'Deadpool & Wolverine',
    franchise: 'mcu',
    kind: 'film',
    released: '2024-07-26',
    minutes: 128,
    chrono: 48,
    phase: 5,
    essential: true,
    hook: 'The TVA, the Void and the Fox universe.',
  },
  {
    id: 'agatha',
    title: 'Agatha All Along',
    franchise: 'mcu',
    kind: 'series',
    released: '2024-09-18',
    minutes: 330,
    episodes: 9,
    chrono: 49,
    phase: 5,
    essential: false,
    approx: true,
    hook: 'The Witches’ Road.',
  },
  {
    id: 'what-if-3',
    title: 'What If...? (Season 3)',
    franchise: 'mcu',
    kind: 'series',
    released: '2024-12-22',
    minutes: 260,
    episodes: 8,
    chrono: 50,
    phase: 5,
    essential: false,
    animated: true,
    approx: true,
    hook: 'The Watcher’s final season.',
  },
  {
    id: 'friendly-neighborhood',
    title: 'Your Friendly Neighborhood Spider-Man',
    franchise: 'mcu',
    kind: 'series',
    released: '2025-01-29',
    minutes: 240,
    episodes: 10,
    chrono: 51,
    phase: 5,
    essential: false,
    animated: true,
    approx: true,
    hook: 'An animated Peter Parker’s first year.',
  },
  {
    id: 'brave-new-world',
    title: 'Captain America: Brave New World',
    franchise: 'mcu',
    kind: 'film',
    released: '2025-02-14',
    minutes: 118,
    chrono: 53,
    phase: 5,
    essential: true,
    hook: 'Sam Wilson as Captain America; President Ross.',
  },
  {
    id: 'daredevil-ba-1',
    title: 'Daredevil: Born Again (Season 1)',
    franchise: 'mcu',
    kind: 'series',
    released: '2025-03-04',
    minutes: 450,
    episodes: 9,
    chrono: 52,
    phase: 5,
    essential: false,
    approx: true,
    hook: 'Matt Murdock against Mayor Fisk.',
  },
  {
    id: 'thunderbolts',
    title: 'Thunderbolts*',
    franchise: 'mcu',
    kind: 'film',
    released: '2025-05-02',
    minutes: 127,
    chrono: 54,
    phase: 5,
    essential: true,
    hook: 'Yelena’s misfits become the New Avengers.',
  },
  {
    id: 'ironheart',
    title: 'Ironheart',
    franchise: 'mcu',
    kind: 'series',
    released: '2025-06-24',
    minutes: 270,
    episodes: 6,
    chrono: 55,
    phase: 5,
    essential: false,
    approx: true,
    hook: 'Riri Williams mixes tech and magic.',
  },
  // ── Phase 6 ─────────────────────────────────────────────────────────────
  {
    id: 'fantastic-four',
    title: 'The Fantastic Four: First Steps',
    franchise: 'mcu',
    kind: 'film',
    released: '2025-07-25',
    minutes: 115,
    chrono: 61,
    phase: 6,
    essential: true,
    hook: 'Marvel’s First Family, and Galactus.',
  },
  {
    id: 'eyes-of-wakanda',
    title: 'Eyes of Wakanda',
    franchise: 'mcu',
    kind: 'series',
    released: '2025-08-06',
    minutes: 120,
    episodes: 4,
    chrono: 56,
    phase: 6,
    essential: false,
    animated: true,
    approx: true,
    hook: 'Wakandan agents across history.',
  },
  {
    id: 'marvel-zombies',
    title: 'Marvel Zombies',
    franchise: 'mcu',
    kind: 'series',
    released: '2025-09-24',
    minutes: 160,
    episodes: 4,
    chrono: 57,
    phase: 6,
    essential: false,
    animated: true,
    approx: true,
    hook: 'An animated undead apocalypse.',
  },
  {
    id: 'wonder-man',
    title: 'Wonder Man',
    franchise: 'mcu',
    kind: 'series',
    released: '2026-01-27',
    minutes: 240,
    episodes: 8,
    chrono: 58,
    phase: 6,
    essential: false,
    approx: true,
    hook: 'Simon Williams goes to Hollywood.',
  },
  {
    id: 'daredevil-ba-2',
    title: 'Daredevil: Born Again (Season 2)',
    franchise: 'mcu',
    kind: 'series',
    released: '2026-03-24',
    minutes: 400,
    episodes: 8,
    chrono: 59,
    phase: 6,
    essential: false,
    approx: true,
    hook: 'Fisk’s New York pushes back.',
  },
  {
    id: 'brand-new-day',
    title: 'Spider-Man: Brand New Day',
    franchise: 'mcu',
    kind: 'film',
    released: '2026-07-31',
    minutes: 135,
    chrono: 60,
    phase: 6,
    essential: true,
    approx: true,
    hook: 'Peter Parker, forgotten, starts over.',
  },
  // ── Dune ────────────────────────────────────────────────────────────────
  {
    id: 'dune-1984',
    title: 'Dune (1984)',
    franchise: 'dune',
    kind: 'film',
    released: '1984-12-14',
    minutes: 137,
    chrono: 102,
    phase: 0,
    essential: false,
    hook: 'David Lynch’s cult adaptation — optional.',
  },
  {
    id: 'dune-prophecy',
    title: 'Dune: Prophecy (Season 1)',
    franchise: 'dune',
    kind: 'series',
    released: '2024-11-17',
    minutes: 360,
    episodes: 6,
    chrono: 101,
    phase: 0,
    essential: false,
    approx: true,
    hook: 'The Bene Gesserit, 10,000 years earlier.',
  },
  {
    id: 'dune-2021',
    title: 'Dune: Part One',
    franchise: 'dune',
    kind: 'film',
    released: '2021-10-22',
    minutes: 155,
    chrono: 103,
    phase: 0,
    essential: true,
    hook: 'House Atreides arrives on Arrakis.',
  },
  {
    id: 'dune-part-two',
    title: 'Dune: Part Two',
    franchise: 'dune',
    kind: 'film',
    released: '2024-03-01',
    minutes: 166,
    chrono: 104,
    phase: 0,
    essential: true,
    hook: 'Paul joins the Fremen and rises.',
  },
];

export const TITLE_BY_ID: ReadonlyMap<string, WatchTitle> = new Map(TITLES.map((t) => [t.id, t]));

/** The two films the whole page is counting down to. */
export const FINALES = [
  { id: 'doomsday', title: 'Avengers: Doomsday', franchise: 'mcu' as const },
  { id: 'dune-part-three', title: 'Dune: Part Three', franchise: 'dune' as const },
];

/** Default selection: every film and live-action series, no animation, no Lynch. */
export function defaultIncluded(title: WatchTitle): boolean {
  if (title.animated) return false;
  if (title.id === 'dune-1984' || title.id === 'dune-prophecy') return false;
  return true;
}
