import { staticCardFor, staticCardImage } from '@/lib/og/static-cards';

export const SITE_URL = 'https://rmhstudios.com';

/**
 * The card every route falls back to, generated by `scripts/gen-og-cards.tsx`
 * in the site's own design language.
 *
 * There used to be two site-wide defaults — this one and a 1.8MB `/og.png` at
 * 1536×1024 that `__root.tsx` set by hand — so the same link could unfurl two
 * different ways depending on which head won. There is now one, at the 1200×630
 * every consumer expects.
 */
export const DEFAULT_OG_IMAGE = '/images/og/default.png';
export const OG_IMAGE_WIDTH = 1200;
export const OG_IMAGE_HEIGHT = 630;

/**
 * Path of the dynamically-rendered card for a given kind of page.
 *
 * Every card route lives under `/api/og/<kind>/<id>` and renders through
 * `lib/og/`. Going through this helper rather than writing the path inline is
 * what keeps a route from quietly pointing at a card endpoint that no longer
 * exists — and makes the set of things that HAVE a real card greppable.
 */
export function ogCardPath(
  kind: 'post' | 'profile' | 'replay' | 'moment' | 'game' | 'blog' | 'job',
  id: string,
): string {
  return `/api/og/${kind}/${encodeURIComponent(id)}`;
}

/** Absolute-ise a site-relative asset path; pass absolute URLs through. */
export function absoluteUrl(pathOrUrl: string): string {
  if (/^https?:\/\//i.test(pathOrUrl)) return pathOrUrl;
  return `${SITE_URL}${pathOrUrl.startsWith('/') ? '' : '/'}${pathOrUrl}`;
}

interface SeoConfig {
  title: string;
  description: string;
  path: string;
  /** Site-relative path or absolute URL. Falls back to the default card. */
  image?: string;
  /**
   * What the image shows, for anyone whose reader announces it. Defaults to a
   * description of the card rather than being left off — an `og:image` with no
   * `alt` is an image with no text alternative in every client that surfaces one.
   */
  imageAlt?: string;
  type?: string;
  /** Set when the card is NOT a 1200×630 render — e.g. a game's own key art. */
  imageSize?: { width: number; height: number } | null;
}

/**
 * Build a full meta array with OG + Twitter Card tags for use in route `head()`.
 *
 * Beyond the tags themselves, this exists so three things are true everywhere
 * and can't be forgotten per route:
 *
 * - **`og:image` is absolute.** A relative one is ignored by most crawlers, and
 *   several routes were emitting them (a shared build previewed as nothing at
 *   all).
 * - **The dimensions are declared.** Without `og:image:width`/`height`, Discord
 *   and Slack lay out a placeholder before the fetch resolves and reflow the
 *   embed when it lands; with them the large-image card is chosen immediately.
 * - **`twitter:card` matches the image.** `summary_large_image` with a 400px
 *   avatar renders as a blurry crop — so the size, not the route, decides.
 */
export function buildMeta({
  title,
  description,
  path,
  image,
  imageAlt,
  type = 'website',
  imageSize,
}: SeoConfig) {
  const url = `${SITE_URL}${path}`;
  // A route that names no image gets its section's card — `/library/…` shares
  // the library card, `/terms` the legal one — and only falls through to the
  // site-wide default when the path matches no section at all. That mapping is
  // data (`lib/og/static-cards.ts`), so adding a section card is one entry
  // rather than an edit to every route under it.
  const section = image ? null : staticCardFor(path);
  const ogImage = absoluteUrl(image || (section ? staticCardImage(section) : DEFAULT_OG_IMAGE));
  // A supplied image is a 1200×630 card unless the caller says otherwise.
  const size = imageSize === undefined ? { width: OG_IMAGE_WIDTH, height: OG_IMAGE_HEIGHT } : imageSize;
  const isLarge = !size || size.width >= 600;

  return [
    { title },
    { name: 'description', content: description },
    { property: 'og:title', content: title },
    { property: 'og:description', content: description },
    { property: 'og:type', content: type },
    { property: 'og:url', content: url },
    { property: 'og:image', content: ogImage },
    ...(size
      ? [
          { property: 'og:image:width', content: String(size.width) },
          { property: 'og:image:height', content: String(size.height) },
        ]
      : []),
    { property: 'og:image:alt', content: imageAlt ?? title },
    { property: 'og:site_name', content: 'RMH Studios' },
    { property: 'og:locale', content: 'en_US' },
    { name: 'twitter:card', content: isLarge ? 'summary_large_image' : 'summary' },
    { name: 'twitter:title', content: title },
    { name: 'twitter:description', content: description },
    { name: 'twitter:image', content: ogImage },
    { name: 'twitter:image:alt', content: imageAlt ?? title },
  ];
}

/**
 * Build a canonical link for use in route head().
 */
export function buildCanonical(path: string) {
  return { rel: 'canonical', href: `${SITE_URL}${path}` };
}
