/**
 * RMHHomes — AI listing-image generation (server only).
 *
 * Lets a poster generate a listing photo from a text prompt with xAI (Grok
 * image API), the same client + shared daily image budget + object-storage
 * pipeline the persona-avatar and feed-image generators use. The generated
 * image is stored as a normal feed image (owned by the poster, so it renders
 * and validates exactly like an uploaded photo) and its URL is returned. The
 * caller records the URL in the listing's `aiImages` so the UI can show a
 * "Generated by AI" disclaimer on it.
 *
 * Returns a discriminated result rather than throwing so the API can surface a
 * friendly message; the poster can always fall back to uploading a real photo.
 */

import OpenAI from 'openai';
import { tryConsumeImageBudget } from '@/lib/rmhark-ai/image-budget.server';
import { validateImageBuffer } from '@/lib/slice-it/upload-validation';
import { optimizeImage } from '@/lib/image-optimize';
import { putObject } from '@/lib/storage/s3.server';
import { feedImageKey, feedImageUrl, withImageDimensions } from '@/lib/storage/keys';

// xAI is OpenAI-SDK compatible; point the base URL at their endpoint.
const xai = new OpenAI({
  apiKey: process.env.XAI_API_KEY || '',
  baseURL: 'https://api.x.ai/v1',
  maxRetries: 1,
});

const XAI_IMAGE_MODEL = process.env.XAI_IMAGE_MODEL || 'grok-imagine-image';

// Listings render 4:3; generate at that aspect so cards/detail don't crop oddly.
const IMAGE_WIDTH = 1024;
const IMAGE_HEIGHT = 768;

export type GenerateResult = { url: string } | { error: string };

/** True when a key is set and the image kill switch is not engaged. */
export function isListingImageAIConfigured(): boolean {
  return Boolean(process.env.XAI_API_KEY) && process.env.XAI_IMAGE_ENABLED !== 'false';
}

/**
 * Generate a listing photo from `prompt` for `userId`, store it, and return its
 * URL. On any failure returns `{ error }` (never throws) so posting still works.
 */
export async function generateListingImage(
  userId: string,
  prompt: string,
): Promise<GenerateResult> {
  if (!isListingImageAIConfigured()) {
    return {
      error: 'AI image generation is unavailable right now. You can upload a photo instead.',
    };
  }
  const clean = prompt.trim().replace(/\s+/g, ' ').slice(0, 500);
  if (clean.length < 3) {
    return { error: 'Describe the photo you want to generate (a few words is enough).' };
  }

  // Reserve budget right before the paid call (shared global daily cap with the
  // feed + avatar generators). Not refunded on failure — a hard spend ceiling.
  if (!(await tryConsumeImageBudget())) {
    return {
      error: 'The daily AI-image limit has been reached. Try again later or upload a photo.',
    };
  }

  try {
    const framed =
      `Professional real-estate listing photograph. ${clean}. ` +
      `Realistic, natural lighting, wide-angle interior or exterior as appropriate, ` +
      `no people, no text, no watermark, no logos.`;

    const res = await xai.images.generate({ model: XAI_IMAGE_MODEL, prompt: framed, n: 1 });
    const src = res.data?.[0]?.url;
    if (!src) return { error: 'Could not generate an image. Try a different description.' };

    const fetched = await fetch(src);
    if (!fetched.ok) return { error: 'Could not generate an image. Please try again.' };
    const raw = Buffer.from(await fetched.arrayBuffer());

    const validation = validateImageBuffer(raw);
    if (!validation.ok) return { error: 'The generated image was invalid. Please try again.' };

    const { buffer, contentType, width, height } = await optimizeImage(raw, {
      width: IMAGE_WIDTH,
      height: IMAGE_HEIGHT,
      format: 'webp',
      quality: 82,
    });

    // Name it like an uploaded feed image (`<userId>-…`) so ownership + serving
    // work identically to a manual upload.
    const filename = withImageDimensions(
      `${userId}-${Date.now()}-${Math.round(Math.random() * 1e9)}.webp`,
      width,
      height,
    );
    await putObject(feedImageKey(filename), buffer, contentType);
    return { url: feedImageUrl(filename) };
  } catch (err) {
    console.error('generateListingImage failed:', err);
    return { error: 'Could not generate an image. Please try again.' };
  }
}
