// Package doctrine implements the Doctrine Engine background worker: a
// long-lived scheduler that ports the three jobs from
// server/doctrine-worker/index.ts (puzzle generation, Sahur activation
// checks, and weekly reputation decay).
//
// The deterministic pieces (the mulberry32 PRNG, the string-hash seeding,
// the difficulty-by-weekday map, and the puzzle mode set) are replicated
// EXACTLY from the Node source so puzzles generated by the Go worker match
// those the Node worker would have produced for the same date.
package doctrine

import "math"

// Modes is the ordered set of regular puzzle modes generated daily. It mirrors
// the `MODES` tuple in the Node worker. SAHUR_SPECIAL is intentionally NOT in
// this list — it is generated separately, exactly as in the source.
var Modes = []string{"ALIBI", "SPECTRUM", "OUTCAST", "CHAINLINK", "IMPOSTOR"}

// SahurSpecialMode is the extra special mode generated each day.
const SahurSpecialMode = "SAHUR_SPECIAL"

// Mulberry32 returns a deterministic PRNG seeded by `seed`, producing the same
// float64 sequence in [0,1) as the Node `mulberry32` implementation.
//
// The Node source uses 32-bit integer arithmetic via `| 0`, `Math.imul`, and
// `>>> 0`. We replicate that bit-for-bit with int32/uint32 conversions:
//
//	let s = seed | 0;
//	s = (s + 0x6D2B79F5) | 0;
//	let t = Math.imul(s ^ (s >>> 15), 1 | s);
//	t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
//	return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
func Mulberry32(seed int) func() float64 {
	// `seed | 0` truncates to a signed 32-bit int.
	s := int32(seed)
	return func() float64 {
		// s = (s + 0x6D2B79F5) | 0  — wrapping 32-bit add.
		s = s + int32(0x6D2B79F5)

		// In JS, `>>>` is an UNSIGNED shift and `Math.imul` is signed 32-bit
		// multiply. We do unsigned shifts on the uint32 view and let int32
		// multiplication wrap to mimic Math.imul.
		us := uint32(s)

		// t = Math.imul(s ^ (s >>> 15), 1 | s)
		t := imul(int32(us^(us>>15)), int32(uint32(1)|us))

		// t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t
		ut := uint32(t)
		t = (t + imul(int32(ut^(ut>>7)), int32(uint32(61)|ut))) ^ t

		// return ((t ^ (t >>> 14)) >>> 0) / 4294967296
		ut = uint32(t)
		return float64(ut^(ut>>14)) / 4294967296.0
	}
}

// imul reproduces JavaScript's Math.imul: a signed 32-bit integer multiply
// where the result wraps modulo 2^32.
func imul(a, b int32) int32 {
	return int32(uint32(a) * uint32(b))
}

// GetSeedForDate reproduces the Node `getSeedForDate(date, mode)`: it hashes
// the string `"<date>:<mode>:doctrine"` with the classic 32-bit
// `(hash << 5) - hash + c` rolling hash, then returns Math.abs(hash).
//
// IMPORTANT: callers pass `mode` lowercased to match the Node call sites
// (`mode.toLowerCase()` / the literal `'sahur_special'`).
func GetSeedForDate(date, mode string) int {
	var hash int32
	input := date + ":" + mode + ":doctrine"
	for i := 0; i < len(input); i++ {
		// charCodeAt over the ASCII date/mode strings == the byte value.
		// `(hash << 5) - hash + c | 0` with 32-bit wrapping.
		hash = (hash<<5 - hash + int32(input[i]))
	}
	// Math.abs(hash). Note: math.MinInt32 has no positive int32, but JS
	// Math.abs would promote it to a float; in practice the hash never hits
	// that exact value for these inputs. We use int math and guard anyway.
	if hash < 0 {
		return int(-int64(hash))
	}
	return int(hash)
}

// DifficultyForWeekday maps a UTC weekday (0=Sunday..6=Saturday, matching
// JS Date.getUTCDay) to a puzzle difficulty, replicating the Node
// difficultyMap with a default of 3.
func DifficultyForWeekday(weekday int) int {
	switch weekday {
	case 1:
		return 1
	case 2:
		return 2
	case 3:
		return 3
	case 4:
		return 3
	case 5:
		return 4
	case 6:
		return 4
	case 0:
		return 5
	default:
		return 3
	}
}

// SahurDifficulty derives the SAHUR_SPECIAL difficulty from the base
// difficulty: Math.min(5, difficulty + 1).
func SahurDifficulty(base int) int {
	return int(math.Min(5, float64(base+1)))
}
