// AUTO-GENERATED by scripts/gen-i18n-resources.ts (do not edit by hand).
// Core English namespaces only — the namespaces any route may render (site
// chrome, nav, the feed, shared UI). Statically bundled into the client entry so
// first paint / hydration has the strings it needs WITHOUT shipping the full
// catalog on every page; the rest is backfilled from resources.en.ts on the
// client after init (see lib/i18n/instances.ts). Kept in sync with
// CORE_NAMESPACES in lib/i18n/config.ts (plus c-ui).
import enCommon from "@/locales/en/common.json";
import enNav from "@/locales/en/nav.json";
import enSite from "@/locales/en/site.json";
import enPages from "@/locales/en/pages.json";
import enShared from "@/locales/en/shared.json";
import enFeed from "@/locales/en/feed.json";
import enBuilds from "@/locales/en/builds.json";
import enLibrary from "@/locales/en/library.json";
import enRideshare from "@/locales/en/rideshare.json";
import enGroups from "@/locales/en/groups.json";
import enUserBuilds from "@/locales/en/user-builds.json";
import enV from "@/locales/en/v.json";
import enCUi from "@/locales/en/c-ui.json";

const enCoreResources = {
  "common": enCommon,
  "nav": enNav,
  "site": enSite,
  "pages": enPages,
  "shared": enShared,
  "feed": enFeed,
  "builds": enBuilds,
  "library": enLibrary,
  "rideshare": enRideshare,
  "groups": enGroups,
  "user-builds": enUserBuilds,
  "v": enV,
  "c-ui": enCUi,
} as const;

export default enCoreResources;
