// AUTO-GENERATED by scripts/gen-i18n-resources.ts (do not edit by hand).
// Per-language i18n bundle for "ja". Only the namespaces translated for
// this locale are bundled; any other namespace falls back to English at runtime.
import jaBuilds from "@/locales/ja/builds.json";
import jaCommon from "@/locales/ja/common.json";
import jaFeed from "@/locales/ja/feed.json";
import jaGroups from "@/locales/ja/groups.json";
import jaLibrary from "@/locales/ja/library.json";
import jaNav from "@/locales/ja/nav.json";
import jaPages from "@/locales/ja/pages.json";
import jaRideshare from "@/locales/ja/rideshare.json";
import jaShared from "@/locales/ja/shared.json";
import jaSite from "@/locales/ja/site.json";
import jaUserBuilds from "@/locales/ja/user-builds.json";
import jaV from "@/locales/ja/v.json";

const jaResources = {
  "builds": jaBuilds,
  "common": jaCommon,
  "feed": jaFeed,
  "groups": jaGroups,
  "library": jaLibrary,
  "nav": jaNav,
  "pages": jaPages,
  "rideshare": jaRideshare,
  "shared": jaShared,
  "site": jaSite,
  "user-builds": jaUserBuilds,
  "v": jaV,
} as const;

export default jaResources;
