// AUTO-GENERATED by scripts (do not edit by hand). Per-language i18n bundle
// for "en". Split out of the old monolithic resources.ts so each language
// ships as its own chunk — only the active language is loaded on the client.
import enAdmin from "@/locales/en/admin.json";
import enBuilds from "@/locales/en/builds.json";
import enCAdmin from "@/locales/en/c-admin.json";
import enCAltair from "@/locales/en/c-altair.json";
import enCBlog from "@/locales/en/c-blog.json";
import enCBuilds from "@/locales/en/c-builds.json";
import enCCursedLogic from "@/locales/en/c-cursed-logic.json";
import enCDailyPuzzles from "@/locales/en/c-daily-puzzles.json";
import enCDoctrine from "@/locales/en/c-doctrine.json";
import enCDreamRift from "@/locales/en/c-dream-rift.json";
import enCEconomy from "@/locales/en/c-economy.json";
import enCForestExplorer from "@/locales/en/c-forest-explorer.json";
import enCGame from "@/locales/en/c-game.json";
import enCHouseAlwaysWins from "@/locales/en/c-house-always-wins.json";
import enCKowloonKnockout from "@/locales/en/c-kowloon-knockout.json";
import enCLaundrySort from "@/locales/en/c-laundry-sort.json";
import enCLibrary from "@/locales/en/c-library.json";
import enCLightsOut from "@/locales/en/c-lights-out.json";
import enCLockdown from "@/locales/en/c-lockdown.json";
import enCModeration from "@/locales/en/c-moderation.json";
import enCNeonDriftway from "@/locales/en/c-neon-driftway.json";
import enCNews from "@/locales/en/c-news.json";
import enCRideshare from "@/locales/en/c-rideshare.json";
import enCRmhCapital from "@/locales/en/c-rmh-capital.json";
import enCRmhPmc from "@/locales/en/c-rmh-pmc.json";
import enCRmhbox from "@/locales/en/c-rmhbox.json";
import enCRmhcalculator from "@/locales/en/c-rmhcalculator.json";
import enCRmhcode from "@/locales/en/c-rmhcode.json";
import enCRmhcoins from "@/locales/en/c-rmhcoins.json";
import enCRmhmusic from "@/locales/en/c-rmhmusic.json";
import enCRmhstudy from "@/locales/en/c-rmhstudy.json";
import enCRmhtech from "@/locales/en/c-rmhtech.json";
import enCRmhtube from "@/locales/en/c-rmhtube.json";
import enCRmhtype from "@/locales/en/c-rmhtype.json";
import enCRmhvibe from "@/locales/en/c-rmhvibe.json";
import enCRoadmap from "@/locales/en/c-roadmap.json";
import enCSignalForge from "@/locales/en/c-signal-forge.json";
import enCStudio from "@/locales/en/c-studio.json";
import enCSynapseStorm from "@/locales/en/c-synapse-storm.json";
import enCTempleOfJoy from "@/locales/en/c-temple-of-joy.json";
import enCUi from "@/locales/en/c-ui.json";
import enCUserBuilds from "@/locales/en/c-user-builds.json";
import enCVega from "@/locales/en/c-vega.json";
import enCVelum2099 from "@/locales/en/c-velum2099.json";
import enCVersecraft from "@/locales/en/c-versecraft.json";
import enCVoidBreaker from "@/locales/en/c-void-breaker.json";
import enCommon from "@/locales/en/common.json";
import enFeed from "@/locales/en/feed.json";
import enGroups from "@/locales/en/groups.json";
import enLibrary from "@/locales/en/library.json";
import enNav from "@/locales/en/nav.json";
import enPages from "@/locales/en/pages.json";
import enRAltair from "@/locales/en/r-altair.json";
import enRDiscord from "@/locales/en/r-discord.json";
import enRForestExplorer from "@/locales/en/r-forest-explorer.json";
import enRKowloonKnockout from "@/locales/en/r-kowloon-knockout.json";
import enRRmhbox from "@/locales/en/r-rmhbox.json";
import enRRmhcode from "@/locales/en/r-rmhcode.json";
import enRSecret from "@/locales/en/r-secret.json";
import enRSliceIt from "@/locales/en/r-slice-it.json";
import enRStrategies from "@/locales/en/r-strategies.json";
import enRStudio from "@/locales/en/r-studio.json";
import enRideshare from "@/locales/en/rideshare.json";
import enShared from "@/locales/en/shared.json";
import enSite from "@/locales/en/site.json";
import enUserBuilds from "@/locales/en/user-builds.json";
import enV from "@/locales/en/v.json";

const enResources = {
  "admin": enAdmin,
  "builds": enBuilds,
  "c-admin": enCAdmin,
  "c-altair": enCAltair,
  "c-blog": enCBlog,
  "c-builds": enCBuilds,
  "c-cursed-logic": enCCursedLogic,
  "c-daily-puzzles": enCDailyPuzzles,
  "c-doctrine": enCDoctrine,
  "c-dream-rift": enCDreamRift,
  "c-economy": enCEconomy,
  "c-forest-explorer": enCForestExplorer,
  "c-game": enCGame,
  "c-house-always-wins": enCHouseAlwaysWins,
  "c-kowloon-knockout": enCKowloonKnockout,
  "c-laundry-sort": enCLaundrySort,
  "c-library": enCLibrary,
  "c-lights-out": enCLightsOut,
  "c-lockdown": enCLockdown,
  "c-moderation": enCModeration,
  "c-neon-driftway": enCNeonDriftway,
  "c-news": enCNews,
  "c-rideshare": enCRideshare,
  "c-rmh-capital": enCRmhCapital,
  "c-rmh-pmc": enCRmhPmc,
  "c-rmhbox": enCRmhbox,
  "c-rmhcalculator": enCRmhcalculator,
  "c-rmhcode": enCRmhcode,
  "c-rmhcoins": enCRmhcoins,
  "c-rmhmusic": enCRmhmusic,
  "c-rmhstudy": enCRmhstudy,
  "c-rmhtech": enCRmhtech,
  "c-rmhtube": enCRmhtube,
  "c-rmhtype": enCRmhtype,
  "c-rmhvibe": enCRmhvibe,
  "c-roadmap": enCRoadmap,
  "c-signal-forge": enCSignalForge,
  "c-studio": enCStudio,
  "c-synapse-storm": enCSynapseStorm,
  "c-temple-of-joy": enCTempleOfJoy,
  "c-ui": enCUi,
  "c-user-builds": enCUserBuilds,
  "c-vega": enCVega,
  "c-velum2099": enCVelum2099,
  "c-versecraft": enCVersecraft,
  "c-void-breaker": enCVoidBreaker,
  "common": enCommon,
  "feed": enFeed,
  "groups": enGroups,
  "library": enLibrary,
  "nav": enNav,
  "pages": enPages,
  "r-altair": enRAltair,
  "r-discord": enRDiscord,
  "r-forest-explorer": enRForestExplorer,
  "r-kowloon-knockout": enRKowloonKnockout,
  "r-rmhbox": enRRmhbox,
  "r-rmhcode": enRRmhcode,
  "r-secret": enRSecret,
  "r-slice-it": enRSliceIt,
  "r-strategies": enRStrategies,
  "r-studio": enRStudio,
  "rideshare": enRideshare,
  "shared": enShared,
  "site": enSite,
  "user-builds": enUserBuilds,
  "v": enV,
} as const;

export default enResources;
