// AUTO-GENERATED by scripts/gen-i18n-resources.ts (do not edit by hand).
// Per-language i18n bundle for "es". Only the namespaces translated for
// this locale are bundled; any other namespace falls back to English at runtime.
import esBuilds from "@/locales/es/builds.json";
import esCommon from "@/locales/es/common.json";
import esFeed from "@/locales/es/feed.json";
import esGroups from "@/locales/es/groups.json";
import esLibrary from "@/locales/es/library.json";
import esNav from "@/locales/es/nav.json";
import esPages from "@/locales/es/pages.json";
import esRideshare from "@/locales/es/rideshare.json";
import esShared from "@/locales/es/shared.json";
import esSite from "@/locales/es/site.json";
import esUserBuilds from "@/locales/es/user-builds.json";
import esV from "@/locales/es/v.json";

const esResources = {
  "builds": esBuilds,
  "common": esCommon,
  "feed": esFeed,
  "groups": esGroups,
  "library": esLibrary,
  "nav": esNav,
  "pages": esPages,
  "rideshare": esRideshare,
  "shared": esShared,
  "site": esSite,
  "user-builds": esUserBuilds,
  "v": esV,
} as const;

export default esResources;
