// AUTO-GENERATED by scripts/gen-i18n-resources.ts (do not edit by hand).
// Per-language i18n bundle for "bn". Only the namespaces translated for
// this locale are bundled; any other namespace falls back to English at runtime.
import bnAdmin from "@/locales/bn/admin.json";
import bnBuilds from "@/locales/bn/builds.json";
import bnCAdmin from "@/locales/bn/c-admin.json";
import bnCAltair from "@/locales/bn/c-altair.json";
import bnCBlog from "@/locales/bn/c-blog.json";
import bnCBuilds from "@/locales/bn/c-builds.json";
import bnCCursedLogic from "@/locales/bn/c-cursed-logic.json";
import bnCDailyPuzzles from "@/locales/bn/c-daily-puzzles.json";
import bnCDoctrine from "@/locales/bn/c-doctrine.json";
import bnCDreamRift from "@/locales/bn/c-dream-rift.json";
import bnCEconomy from "@/locales/bn/c-economy.json";
import bnCForestExplorer from "@/locales/bn/c-forest-explorer.json";
import bnCGame from "@/locales/bn/c-game.json";
import bnCHouseAlwaysWins from "@/locales/bn/c-house-always-wins.json";
import bnCKowloonKnockout from "@/locales/bn/c-kowloon-knockout.json";
import bnCLaundrySort from "@/locales/bn/c-laundry-sort.json";
import bnCLibrary from "@/locales/bn/c-library.json";
import bnCLightsOut from "@/locales/bn/c-lights-out.json";
import bnCLockdown from "@/locales/bn/c-lockdown.json";
import bnCModeration from "@/locales/bn/c-moderation.json";
import bnCNeonDriftway from "@/locales/bn/c-neon-driftway.json";
import bnCNews from "@/locales/bn/c-news.json";
import bnCRideshare from "@/locales/bn/c-rideshare.json";
import bnCRmhCapital from "@/locales/bn/c-rmh-capital.json";
import bnCRmhPmc from "@/locales/bn/c-rmh-pmc.json";
import bnCRmhbox from "@/locales/bn/c-rmhbox.json";
import bnCRmhcode from "@/locales/bn/c-rmhcode.json";
import bnCRmhcoins from "@/locales/bn/c-rmhcoins.json";
import bnCRmhmusic from "@/locales/bn/c-rmhmusic.json";
import bnCRmhstudy from "@/locales/bn/c-rmhstudy.json";
import bnCRmhtech from "@/locales/bn/c-rmhtech.json";
import bnCRmhtube from "@/locales/bn/c-rmhtube.json";
import bnCRmhtype from "@/locales/bn/c-rmhtype.json";
import bnCRmhvibe from "@/locales/bn/c-rmhvibe.json";
import bnCRoadmap from "@/locales/bn/c-roadmap.json";
import bnCSignalForge from "@/locales/bn/c-signal-forge.json";
import bnCStudio from "@/locales/bn/c-studio.json";
import bnCSynapseStorm from "@/locales/bn/c-synapse-storm.json";
import bnCTempleOfJoy from "@/locales/bn/c-temple-of-joy.json";
import bnCUi from "@/locales/bn/c-ui.json";
import bnCUserBuilds from "@/locales/bn/c-user-builds.json";
import bnCVega from "@/locales/bn/c-vega.json";
import bnCVersecraft from "@/locales/bn/c-versecraft.json";
import bnCVoidBreaker from "@/locales/bn/c-void-breaker.json";
import bnCommon from "@/locales/bn/common.json";
import bnFeed from "@/locales/bn/feed.json";
import bnGroups from "@/locales/bn/groups.json";
import bnLibrary from "@/locales/bn/library.json";
import bnNav from "@/locales/bn/nav.json";
import bnPages from "@/locales/bn/pages.json";
import bnRAltair from "@/locales/bn/r-altair.json";
import bnRDiscord from "@/locales/bn/r-discord.json";
import bnRForestExplorer from "@/locales/bn/r-forest-explorer.json";
import bnRRmhbox from "@/locales/bn/r-rmhbox.json";
import bnRRmhcode from "@/locales/bn/r-rmhcode.json";
import bnRSecret from "@/locales/bn/r-secret.json";
import bnRSliceIt from "@/locales/bn/r-slice-it.json";
import bnRStrategies from "@/locales/bn/r-strategies.json";
import bnRStudio from "@/locales/bn/r-studio.json";
import bnRideshare from "@/locales/bn/rideshare.json";
import bnShared from "@/locales/bn/shared.json";
import bnSite from "@/locales/bn/site.json";
import bnUserBuilds from "@/locales/bn/user-builds.json";
import bnV from "@/locales/bn/v.json";

const bnResources = {
  "admin": bnAdmin,
  "builds": bnBuilds,
  "c-admin": bnCAdmin,
  "c-altair": bnCAltair,
  "c-blog": bnCBlog,
  "c-builds": bnCBuilds,
  "c-cursed-logic": bnCCursedLogic,
  "c-daily-puzzles": bnCDailyPuzzles,
  "c-doctrine": bnCDoctrine,
  "c-dream-rift": bnCDreamRift,
  "c-economy": bnCEconomy,
  "c-forest-explorer": bnCForestExplorer,
  "c-game": bnCGame,
  "c-house-always-wins": bnCHouseAlwaysWins,
  "c-kowloon-knockout": bnCKowloonKnockout,
  "c-laundry-sort": bnCLaundrySort,
  "c-library": bnCLibrary,
  "c-lights-out": bnCLightsOut,
  "c-lockdown": bnCLockdown,
  "c-moderation": bnCModeration,
  "c-neon-driftway": bnCNeonDriftway,
  "c-news": bnCNews,
  "c-rideshare": bnCRideshare,
  "c-rmh-capital": bnCRmhCapital,
  "c-rmh-pmc": bnCRmhPmc,
  "c-rmhbox": bnCRmhbox,
  "c-rmhcode": bnCRmhcode,
  "c-rmhcoins": bnCRmhcoins,
  "c-rmhmusic": bnCRmhmusic,
  "c-rmhstudy": bnCRmhstudy,
  "c-rmhtech": bnCRmhtech,
  "c-rmhtube": bnCRmhtube,
  "c-rmhtype": bnCRmhtype,
  "c-rmhvibe": bnCRmhvibe,
  "c-roadmap": bnCRoadmap,
  "c-signal-forge": bnCSignalForge,
  "c-studio": bnCStudio,
  "c-synapse-storm": bnCSynapseStorm,
  "c-temple-of-joy": bnCTempleOfJoy,
  "c-ui": bnCUi,
  "c-user-builds": bnCUserBuilds,
  "c-vega": bnCVega,
  "c-versecraft": bnCVersecraft,
  "c-void-breaker": bnCVoidBreaker,
  "common": bnCommon,
  "feed": bnFeed,
  "groups": bnGroups,
  "library": bnLibrary,
  "nav": bnNav,
  "pages": bnPages,
  "r-altair": bnRAltair,
  "r-discord": bnRDiscord,
  "r-forest-explorer": bnRForestExplorer,
  "r-rmhbox": bnRRmhbox,
  "r-rmhcode": bnRRmhcode,
  "r-secret": bnRSecret,
  "r-slice-it": bnRSliceIt,
  "r-strategies": bnRStrategies,
  "r-studio": bnRStudio,
  "rideshare": bnRideshare,
  "shared": bnShared,
  "site": bnSite,
  "user-builds": bnUserBuilds,
  "v": bnV,
} as const;

export default bnResources;
