// AUTO-GENERATED by scripts/gen-i18n-resources.ts (do not edit by hand).
// Per-language i18n bundle for "fr". Only the namespaces translated for
// this locale are bundled; any other namespace falls back to English at runtime.
import frAdmin from "@/locales/fr/admin.json";
import frBuilds from "@/locales/fr/builds.json";
import frCAdmin from "@/locales/fr/c-admin.json";
import frCAltair from "@/locales/fr/c-altair.json";
import frCBlog from "@/locales/fr/c-blog.json";
import frCBuilds from "@/locales/fr/c-builds.json";
import frCCursedLogic from "@/locales/fr/c-cursed-logic.json";
import frCDailyPuzzles from "@/locales/fr/c-daily-puzzles.json";
import frCDoctrine from "@/locales/fr/c-doctrine.json";
import frCDreamRift from "@/locales/fr/c-dream-rift.json";
import frCEconomy from "@/locales/fr/c-economy.json";
import frCForestExplorer from "@/locales/fr/c-forest-explorer.json";
import frCGame from "@/locales/fr/c-game.json";
import frCHouseAlwaysWins from "@/locales/fr/c-house-always-wins.json";
import frCKowloonKnockout from "@/locales/fr/c-kowloon-knockout.json";
import frCLaundrySort from "@/locales/fr/c-laundry-sort.json";
import frCLibrary from "@/locales/fr/c-library.json";
import frCLightsOut from "@/locales/fr/c-lights-out.json";
import frCLockdown from "@/locales/fr/c-lockdown.json";
import frCModeration from "@/locales/fr/c-moderation.json";
import frCNeonDriftway from "@/locales/fr/c-neon-driftway.json";
import frCNews from "@/locales/fr/c-news.json";
import frCRideshare from "@/locales/fr/c-rideshare.json";
import frCRmhCapital from "@/locales/fr/c-rmh-capital.json";
import frCRmhPmc from "@/locales/fr/c-rmh-pmc.json";
import frCRmhbox from "@/locales/fr/c-rmhbox.json";
import frCRmhcode from "@/locales/fr/c-rmhcode.json";
import frCRmhcoins from "@/locales/fr/c-rmhcoins.json";
import frCRmhmusic from "@/locales/fr/c-rmhmusic.json";
import frCRmhstudy from "@/locales/fr/c-rmhstudy.json";
import frCRmhtech from "@/locales/fr/c-rmhtech.json";
import frCRmhtube from "@/locales/fr/c-rmhtube.json";
import frCRmhtype from "@/locales/fr/c-rmhtype.json";
import frCRmhvibe from "@/locales/fr/c-rmhvibe.json";
import frCRoadmap from "@/locales/fr/c-roadmap.json";
import frCSignalForge from "@/locales/fr/c-signal-forge.json";
import frCStudio from "@/locales/fr/c-studio.json";
import frCSynapseStorm from "@/locales/fr/c-synapse-storm.json";
import frCTempleOfJoy from "@/locales/fr/c-temple-of-joy.json";
import frCUi from "@/locales/fr/c-ui.json";
import frCUserBuilds from "@/locales/fr/c-user-builds.json";
import frCVega from "@/locales/fr/c-vega.json";
import frCVersecraft from "@/locales/fr/c-versecraft.json";
import frCVoidBreaker from "@/locales/fr/c-void-breaker.json";
import frCommon from "@/locales/fr/common.json";
import frFeed from "@/locales/fr/feed.json";
import frGroups from "@/locales/fr/groups.json";
import frLibrary from "@/locales/fr/library.json";
import frNav from "@/locales/fr/nav.json";
import frPages from "@/locales/fr/pages.json";
import frRAltair from "@/locales/fr/r-altair.json";
import frRDiscord from "@/locales/fr/r-discord.json";
import frRForestExplorer from "@/locales/fr/r-forest-explorer.json";
import frRRmhbox from "@/locales/fr/r-rmhbox.json";
import frRRmhcode from "@/locales/fr/r-rmhcode.json";
import frRSecret from "@/locales/fr/r-secret.json";
import frRSliceIt from "@/locales/fr/r-slice-it.json";
import frRStrategies from "@/locales/fr/r-strategies.json";
import frRStudio from "@/locales/fr/r-studio.json";
import frRideshare from "@/locales/fr/rideshare.json";
import frShared from "@/locales/fr/shared.json";
import frSite from "@/locales/fr/site.json";
import frUserBuilds from "@/locales/fr/user-builds.json";
import frV from "@/locales/fr/v.json";

const frResources = {
  "admin": frAdmin,
  "builds": frBuilds,
  "c-admin": frCAdmin,
  "c-altair": frCAltair,
  "c-blog": frCBlog,
  "c-builds": frCBuilds,
  "c-cursed-logic": frCCursedLogic,
  "c-daily-puzzles": frCDailyPuzzles,
  "c-doctrine": frCDoctrine,
  "c-dream-rift": frCDreamRift,
  "c-economy": frCEconomy,
  "c-forest-explorer": frCForestExplorer,
  "c-game": frCGame,
  "c-house-always-wins": frCHouseAlwaysWins,
  "c-kowloon-knockout": frCKowloonKnockout,
  "c-laundry-sort": frCLaundrySort,
  "c-library": frCLibrary,
  "c-lights-out": frCLightsOut,
  "c-lockdown": frCLockdown,
  "c-moderation": frCModeration,
  "c-neon-driftway": frCNeonDriftway,
  "c-news": frCNews,
  "c-rideshare": frCRideshare,
  "c-rmh-capital": frCRmhCapital,
  "c-rmh-pmc": frCRmhPmc,
  "c-rmhbox": frCRmhbox,
  "c-rmhcode": frCRmhcode,
  "c-rmhcoins": frCRmhcoins,
  "c-rmhmusic": frCRmhmusic,
  "c-rmhstudy": frCRmhstudy,
  "c-rmhtech": frCRmhtech,
  "c-rmhtube": frCRmhtube,
  "c-rmhtype": frCRmhtype,
  "c-rmhvibe": frCRmhvibe,
  "c-roadmap": frCRoadmap,
  "c-signal-forge": frCSignalForge,
  "c-studio": frCStudio,
  "c-synapse-storm": frCSynapseStorm,
  "c-temple-of-joy": frCTempleOfJoy,
  "c-ui": frCUi,
  "c-user-builds": frCUserBuilds,
  "c-vega": frCVega,
  "c-versecraft": frCVersecraft,
  "c-void-breaker": frCVoidBreaker,
  "common": frCommon,
  "feed": frFeed,
  "groups": frGroups,
  "library": frLibrary,
  "nav": frNav,
  "pages": frPages,
  "r-altair": frRAltair,
  "r-discord": frRDiscord,
  "r-forest-explorer": frRForestExplorer,
  "r-rmhbox": frRRmhbox,
  "r-rmhcode": frRRmhcode,
  "r-secret": frRSecret,
  "r-slice-it": frRSliceIt,
  "r-strategies": frRStrategies,
  "r-studio": frRStudio,
  "rideshare": frRideshare,
  "shared": frShared,
  "site": frSite,
  "user-builds": frUserBuilds,
  "v": frV,
} as const;

export default frResources;
