// AUTO-GENERATED by scripts/gen-i18n-resources.ts (do not edit by hand).
// Per-language i18n bundle for "ko". Only the namespaces translated for
// this locale are bundled; any other namespace falls back to English at runtime.
import koAdmin from "@/locales/ko/admin.json";
import koBuilds from "@/locales/ko/builds.json";
import koCAdmin from "@/locales/ko/c-admin.json";
import koCAltair from "@/locales/ko/c-altair.json";
import koCBlog from "@/locales/ko/c-blog.json";
import koCBuilds from "@/locales/ko/c-builds.json";
import koCCursedLogic from "@/locales/ko/c-cursed-logic.json";
import koCDailyPuzzles from "@/locales/ko/c-daily-puzzles.json";
import koCDoctrine from "@/locales/ko/c-doctrine.json";
import koCDreamRift from "@/locales/ko/c-dream-rift.json";
import koCEconomy from "@/locales/ko/c-economy.json";
import koCForestExplorer from "@/locales/ko/c-forest-explorer.json";
import koCGame from "@/locales/ko/c-game.json";
import koCHouseAlwaysWins from "@/locales/ko/c-house-always-wins.json";
import koCKowloonKnockout from "@/locales/ko/c-kowloon-knockout.json";
import koCLaundrySort from "@/locales/ko/c-laundry-sort.json";
import koCLibrary from "@/locales/ko/c-library.json";
import koCLightsOut from "@/locales/ko/c-lights-out.json";
import koCLockdown from "@/locales/ko/c-lockdown.json";
import koCModeration from "@/locales/ko/c-moderation.json";
import koCNeonDriftway from "@/locales/ko/c-neon-driftway.json";
import koCNews from "@/locales/ko/c-news.json";
import koCRideshare from "@/locales/ko/c-rideshare.json";
import koCRmhCapital from "@/locales/ko/c-rmh-capital.json";
import koCRmhPmc from "@/locales/ko/c-rmh-pmc.json";
import koCRmhbox from "@/locales/ko/c-rmhbox.json";
import koCRmhcode from "@/locales/ko/c-rmhcode.json";
import koCRmhcoins from "@/locales/ko/c-rmhcoins.json";
import koCRmhmusic from "@/locales/ko/c-rmhmusic.json";
import koCRmhstudy from "@/locales/ko/c-rmhstudy.json";
import koCRmhtech from "@/locales/ko/c-rmhtech.json";
import koCRmhtube from "@/locales/ko/c-rmhtube.json";
import koCRmhtype from "@/locales/ko/c-rmhtype.json";
import koCRmhvibe from "@/locales/ko/c-rmhvibe.json";
import koCRoadmap from "@/locales/ko/c-roadmap.json";
import koCSignalForge from "@/locales/ko/c-signal-forge.json";
import koCStudio from "@/locales/ko/c-studio.json";
import koCSynapseStorm from "@/locales/ko/c-synapse-storm.json";
import koCTempleOfJoy from "@/locales/ko/c-temple-of-joy.json";
import koCUi from "@/locales/ko/c-ui.json";
import koCUserBuilds from "@/locales/ko/c-user-builds.json";
import koCVega from "@/locales/ko/c-vega.json";
import koCVersecraft from "@/locales/ko/c-versecraft.json";
import koCVoidBreaker from "@/locales/ko/c-void-breaker.json";
import koCommon from "@/locales/ko/common.json";
import koFeed from "@/locales/ko/feed.json";
import koGroups from "@/locales/ko/groups.json";
import koLibrary from "@/locales/ko/library.json";
import koNav from "@/locales/ko/nav.json";
import koPages from "@/locales/ko/pages.json";
import koRAltair from "@/locales/ko/r-altair.json";
import koRDiscord from "@/locales/ko/r-discord.json";
import koRForestExplorer from "@/locales/ko/r-forest-explorer.json";
import koRRmhbox from "@/locales/ko/r-rmhbox.json";
import koRRmhcode from "@/locales/ko/r-rmhcode.json";
import koRSecret from "@/locales/ko/r-secret.json";
import koRSliceIt from "@/locales/ko/r-slice-it.json";
import koRStrategies from "@/locales/ko/r-strategies.json";
import koRStudio from "@/locales/ko/r-studio.json";
import koRideshare from "@/locales/ko/rideshare.json";
import koShared from "@/locales/ko/shared.json";
import koSite from "@/locales/ko/site.json";
import koUserBuilds from "@/locales/ko/user-builds.json";
import koV from "@/locales/ko/v.json";

const koResources = {
  "admin": koAdmin,
  "builds": koBuilds,
  "c-admin": koCAdmin,
  "c-altair": koCAltair,
  "c-blog": koCBlog,
  "c-builds": koCBuilds,
  "c-cursed-logic": koCCursedLogic,
  "c-daily-puzzles": koCDailyPuzzles,
  "c-doctrine": koCDoctrine,
  "c-dream-rift": koCDreamRift,
  "c-economy": koCEconomy,
  "c-forest-explorer": koCForestExplorer,
  "c-game": koCGame,
  "c-house-always-wins": koCHouseAlwaysWins,
  "c-kowloon-knockout": koCKowloonKnockout,
  "c-laundry-sort": koCLaundrySort,
  "c-library": koCLibrary,
  "c-lights-out": koCLightsOut,
  "c-lockdown": koCLockdown,
  "c-moderation": koCModeration,
  "c-neon-driftway": koCNeonDriftway,
  "c-news": koCNews,
  "c-rideshare": koCRideshare,
  "c-rmh-capital": koCRmhCapital,
  "c-rmh-pmc": koCRmhPmc,
  "c-rmhbox": koCRmhbox,
  "c-rmhcode": koCRmhcode,
  "c-rmhcoins": koCRmhcoins,
  "c-rmhmusic": koCRmhmusic,
  "c-rmhstudy": koCRmhstudy,
  "c-rmhtech": koCRmhtech,
  "c-rmhtube": koCRmhtube,
  "c-rmhtype": koCRmhtype,
  "c-rmhvibe": koCRmhvibe,
  "c-roadmap": koCRoadmap,
  "c-signal-forge": koCSignalForge,
  "c-studio": koCStudio,
  "c-synapse-storm": koCSynapseStorm,
  "c-temple-of-joy": koCTempleOfJoy,
  "c-ui": koCUi,
  "c-user-builds": koCUserBuilds,
  "c-vega": koCVega,
  "c-versecraft": koCVersecraft,
  "c-void-breaker": koCVoidBreaker,
  "common": koCommon,
  "feed": koFeed,
  "groups": koGroups,
  "library": koLibrary,
  "nav": koNav,
  "pages": koPages,
  "r-altair": koRAltair,
  "r-discord": koRDiscord,
  "r-forest-explorer": koRForestExplorer,
  "r-rmhbox": koRRmhbox,
  "r-rmhcode": koRRmhcode,
  "r-secret": koRSecret,
  "r-slice-it": koRSliceIt,
  "r-strategies": koRStrategies,
  "r-studio": koRStudio,
  "rideshare": koRideshare,
  "shared": koShared,
  "site": koSite,
  "user-builds": koUserBuilds,
  "v": koV,
} as const;

export default koResources;
