// AUTO-GENERATED by scripts/gen-i18n-resources.ts (do not edit by hand).
// Per-language i18n bundle for "pt". Only the namespaces translated for
// this locale are bundled; any other namespace falls back to English at runtime.
import ptBuilds from "@/locales/pt/builds.json";
import ptCommon from "@/locales/pt/common.json";
import ptFeed from "@/locales/pt/feed.json";
import ptGroups from "@/locales/pt/groups.json";
import ptLibrary from "@/locales/pt/library.json";
import ptNav from "@/locales/pt/nav.json";
import ptPages from "@/locales/pt/pages.json";
import ptRideshare from "@/locales/pt/rideshare.json";
import ptShared from "@/locales/pt/shared.json";
import ptSite from "@/locales/pt/site.json";
import ptUserBuilds from "@/locales/pt/user-builds.json";
import ptV from "@/locales/pt/v.json";

const ptResources = {
  "builds": ptBuilds,
  "common": ptCommon,
  "feed": ptFeed,
  "groups": ptGroups,
  "library": ptLibrary,
  "nav": ptNav,
  "pages": ptPages,
  "rideshare": ptRideshare,
  "shared": ptShared,
  "site": ptSite,
  "user-builds": ptUserBuilds,
  "v": ptV,
} as const;

export default ptResources;
