// AUTO-GENERATED by scripts (do not edit by hand). Per-language i18n bundle
// for "ar". Split out of the old monolithic resources.ts so each language
// ships as its own chunk — only the active language is loaded on the client.
import arSourcesAdmin from "@/locales/ar/.sources.admin.json";
import arSourcesBuilds from "@/locales/ar/.sources.builds.json";
import arSourcesCAdmin from "@/locales/ar/.sources.c-admin.json";
import arSourcesCAltair from "@/locales/ar/.sources.c-altair.json";
import arSourcesCBlog from "@/locales/ar/.sources.c-blog.json";
import arSourcesCBuilds from "@/locales/ar/.sources.c-builds.json";
import arSourcesCCursedLogic from "@/locales/ar/.sources.c-cursed-logic.json";
import arSourcesCDailyPuzzles from "@/locales/ar/.sources.c-daily-puzzles.json";
import arSourcesCDoctrine from "@/locales/ar/.sources.c-doctrine.json";
import arSourcesCDreamRift from "@/locales/ar/.sources.c-dream-rift.json";
import arSourcesCEconomy from "@/locales/ar/.sources.c-economy.json";
import arSourcesCForestExplorer from "@/locales/ar/.sources.c-forest-explorer.json";
import arSourcesCGame from "@/locales/ar/.sources.c-game.json";
import arSourcesCHouseAlwaysWins from "@/locales/ar/.sources.c-house-always-wins.json";
import arSourcesCKowloonKnockout from "@/locales/ar/.sources.c-kowloon-knockout.json";
import arSourcesCLaundrySort from "@/locales/ar/.sources.c-laundry-sort.json";
import arSourcesCLibrary from "@/locales/ar/.sources.c-library.json";
import arSourcesCLightsOut from "@/locales/ar/.sources.c-lights-out.json";
import arSourcesCLockdown from "@/locales/ar/.sources.c-lockdown.json";
import arSourcesCModeration from "@/locales/ar/.sources.c-moderation.json";
import arSourcesCNeonDriftway from "@/locales/ar/.sources.c-neon-driftway.json";
import arSourcesCNews from "@/locales/ar/.sources.c-news.json";
import arSourcesCRideshare from "@/locales/ar/.sources.c-rideshare.json";
import arSourcesCRmhCapital from "@/locales/ar/.sources.c-rmh-capital.json";
import arSourcesCRmhPmc from "@/locales/ar/.sources.c-rmh-pmc.json";
import arSourcesCRmhbox from "@/locales/ar/.sources.c-rmhbox.json";
import arSourcesCRmhcode from "@/locales/ar/.sources.c-rmhcode.json";
import arSourcesCRmhcoins from "@/locales/ar/.sources.c-rmhcoins.json";
import arSourcesCRmhmusic from "@/locales/ar/.sources.c-rmhmusic.json";
import arSourcesCRmhstudy from "@/locales/ar/.sources.c-rmhstudy.json";
import arSourcesCRmhtech from "@/locales/ar/.sources.c-rmhtech.json";
import arSourcesCRmhtube from "@/locales/ar/.sources.c-rmhtube.json";
import arSourcesCRmhtype from "@/locales/ar/.sources.c-rmhtype.json";
import arSourcesCRmhvibe from "@/locales/ar/.sources.c-rmhvibe.json";
import arSourcesCRoadmap from "@/locales/ar/.sources.c-roadmap.json";
import arSourcesCSignalForge from "@/locales/ar/.sources.c-signal-forge.json";
import arSourcesCStudio from "@/locales/ar/.sources.c-studio.json";
import arSourcesCSynapseStorm from "@/locales/ar/.sources.c-synapse-storm.json";
import arSourcesCTempleOfJoy from "@/locales/ar/.sources.c-temple-of-joy.json";
import arSourcesCUi from "@/locales/ar/.sources.c-ui.json";
import arSourcesCUserBuilds from "@/locales/ar/.sources.c-user-builds.json";
import arSourcesCVega from "@/locales/ar/.sources.c-vega.json";
import arSourcesCVersecraft from "@/locales/ar/.sources.c-versecraft.json";
import arSourcesCVoidBreaker from "@/locales/ar/.sources.c-void-breaker.json";
import arSourcesCommon from "@/locales/ar/.sources.common.json";
import arSourcesFeed from "@/locales/ar/.sources.feed.json";
import arSourcesGroups from "@/locales/ar/.sources.groups.json";
import arSourcesLibrary from "@/locales/ar/.sources.library.json";
import arSourcesNav from "@/locales/ar/.sources.nav.json";
import arSourcesPages from "@/locales/ar/.sources.pages.json";
import arSourcesRAltair from "@/locales/ar/.sources.r-altair.json";
import arSourcesRDiscord from "@/locales/ar/.sources.r-discord.json";
import arSourcesRForestExplorer from "@/locales/ar/.sources.r-forest-explorer.json";
import arSourcesRRmhbox from "@/locales/ar/.sources.r-rmhbox.json";
import arSourcesRRmhcode from "@/locales/ar/.sources.r-rmhcode.json";
import arSourcesRSecret from "@/locales/ar/.sources.r-secret.json";
import arSourcesRSliceIt from "@/locales/ar/.sources.r-slice-it.json";
import arSourcesRStrategies from "@/locales/ar/.sources.r-strategies.json";
import arSourcesRStudio from "@/locales/ar/.sources.r-studio.json";
import arSourcesRideshare from "@/locales/ar/.sources.rideshare.json";
import arSourcesShared from "@/locales/ar/.sources.shared.json";
import arSourcesSite from "@/locales/ar/.sources.site.json";
import arSourcesUserBuilds from "@/locales/ar/.sources.user-builds.json";
import arSourcesV from "@/locales/ar/.sources.v.json";
import arAdmin from "@/locales/ar/admin.json";
import arBuilds from "@/locales/ar/builds.json";
import arCAdmin from "@/locales/ar/c-admin.json";
import arCAltair from "@/locales/ar/c-altair.json";
import arCBlog from "@/locales/ar/c-blog.json";
import arCBuilds from "@/locales/ar/c-builds.json";
import arCCursedLogic from "@/locales/ar/c-cursed-logic.json";
import arCDailyPuzzles from "@/locales/ar/c-daily-puzzles.json";
import arCDoctrine from "@/locales/ar/c-doctrine.json";
import arCDreamRift from "@/locales/ar/c-dream-rift.json";
import arCEconomy from "@/locales/ar/c-economy.json";
import arCForestExplorer from "@/locales/ar/c-forest-explorer.json";
import arCGame from "@/locales/ar/c-game.json";
import arCHouseAlwaysWins from "@/locales/ar/c-house-always-wins.json";
import arCKowloonKnockout from "@/locales/ar/c-kowloon-knockout.json";
import arCLaundrySort from "@/locales/ar/c-laundry-sort.json";
import arCLibrary from "@/locales/ar/c-library.json";
import arCLightsOut from "@/locales/ar/c-lights-out.json";
import arCLockdown from "@/locales/ar/c-lockdown.json";
import arCModeration from "@/locales/ar/c-moderation.json";
import arCNeonDriftway from "@/locales/ar/c-neon-driftway.json";
import arCNews from "@/locales/ar/c-news.json";
import arCRideshare from "@/locales/ar/c-rideshare.json";
import arCRmhCapital from "@/locales/ar/c-rmh-capital.json";
import arCRmhPmc from "@/locales/ar/c-rmh-pmc.json";
import arCRmhbox from "@/locales/ar/c-rmhbox.json";
import arCRmhcode from "@/locales/ar/c-rmhcode.json";
import arCRmhcoins from "@/locales/ar/c-rmhcoins.json";
import arCRmhmusic from "@/locales/ar/c-rmhmusic.json";
import arCRmhstudy from "@/locales/ar/c-rmhstudy.json";
import arCRmhtech from "@/locales/ar/c-rmhtech.json";
import arCRmhtube from "@/locales/ar/c-rmhtube.json";
import arCRmhtype from "@/locales/ar/c-rmhtype.json";
import arCRmhvibe from "@/locales/ar/c-rmhvibe.json";
import arCRoadmap from "@/locales/ar/c-roadmap.json";
import arCSignalForge from "@/locales/ar/c-signal-forge.json";
import arCStudio from "@/locales/ar/c-studio.json";
import arCSynapseStorm from "@/locales/ar/c-synapse-storm.json";
import arCTempleOfJoy from "@/locales/ar/c-temple-of-joy.json";
import arCUi from "@/locales/ar/c-ui.json";
import arCUserBuilds from "@/locales/ar/c-user-builds.json";
import arCVega from "@/locales/ar/c-vega.json";
import arCVelum2099 from "@/locales/ar/c-velum2099.json";
import arCVersecraft from "@/locales/ar/c-versecraft.json";
import arCVoidBreaker from "@/locales/ar/c-void-breaker.json";
import arCommon from "@/locales/ar/common.json";
import arFeed from "@/locales/ar/feed.json";
import arGroups from "@/locales/ar/groups.json";
import arLibrary from "@/locales/ar/library.json";
import arNav from "@/locales/ar/nav.json";
import arPages from "@/locales/ar/pages.json";
import arRAltair from "@/locales/ar/r-altair.json";
import arRDiscord from "@/locales/ar/r-discord.json";
import arRForestExplorer from "@/locales/ar/r-forest-explorer.json";
import arRKowloonKnockout from "@/locales/ar/r-kowloon-knockout.json";
import arRRmhbox from "@/locales/ar/r-rmhbox.json";
import arRRmhcode from "@/locales/ar/r-rmhcode.json";
import arRSecret from "@/locales/ar/r-secret.json";
import arRSliceIt from "@/locales/ar/r-slice-it.json";
import arRStrategies from "@/locales/ar/r-strategies.json";
import arRStudio from "@/locales/ar/r-studio.json";
import arRideshare from "@/locales/ar/rideshare.json";
import arShared from "@/locales/ar/shared.json";
import arSite from "@/locales/ar/site.json";
import arUserBuilds from "@/locales/ar/user-builds.json";
import arV from "@/locales/ar/v.json";

const arResources = {
  ".sources.admin": arSourcesAdmin,
  ".sources.builds": arSourcesBuilds,
  ".sources.c-admin": arSourcesCAdmin,
  ".sources.c-altair": arSourcesCAltair,
  ".sources.c-blog": arSourcesCBlog,
  ".sources.c-builds": arSourcesCBuilds,
  ".sources.c-cursed-logic": arSourcesCCursedLogic,
  ".sources.c-daily-puzzles": arSourcesCDailyPuzzles,
  ".sources.c-doctrine": arSourcesCDoctrine,
  ".sources.c-dream-rift": arSourcesCDreamRift,
  ".sources.c-economy": arSourcesCEconomy,
  ".sources.c-forest-explorer": arSourcesCForestExplorer,
  ".sources.c-game": arSourcesCGame,
  ".sources.c-house-always-wins": arSourcesCHouseAlwaysWins,
  ".sources.c-kowloon-knockout": arSourcesCKowloonKnockout,
  ".sources.c-laundry-sort": arSourcesCLaundrySort,
  ".sources.c-library": arSourcesCLibrary,
  ".sources.c-lights-out": arSourcesCLightsOut,
  ".sources.c-lockdown": arSourcesCLockdown,
  ".sources.c-moderation": arSourcesCModeration,
  ".sources.c-neon-driftway": arSourcesCNeonDriftway,
  ".sources.c-news": arSourcesCNews,
  ".sources.c-rideshare": arSourcesCRideshare,
  ".sources.c-rmh-capital": arSourcesCRmhCapital,
  ".sources.c-rmh-pmc": arSourcesCRmhPmc,
  ".sources.c-rmhbox": arSourcesCRmhbox,
  ".sources.c-rmhcode": arSourcesCRmhcode,
  ".sources.c-rmhcoins": arSourcesCRmhcoins,
  ".sources.c-rmhmusic": arSourcesCRmhmusic,
  ".sources.c-rmhstudy": arSourcesCRmhstudy,
  ".sources.c-rmhtech": arSourcesCRmhtech,
  ".sources.c-rmhtube": arSourcesCRmhtube,
  ".sources.c-rmhtype": arSourcesCRmhtype,
  ".sources.c-rmhvibe": arSourcesCRmhvibe,
  ".sources.c-roadmap": arSourcesCRoadmap,
  ".sources.c-signal-forge": arSourcesCSignalForge,
  ".sources.c-studio": arSourcesCStudio,
  ".sources.c-synapse-storm": arSourcesCSynapseStorm,
  ".sources.c-temple-of-joy": arSourcesCTempleOfJoy,
  ".sources.c-ui": arSourcesCUi,
  ".sources.c-user-builds": arSourcesCUserBuilds,
  ".sources.c-vega": arSourcesCVega,
  ".sources.c-versecraft": arSourcesCVersecraft,
  ".sources.c-void-breaker": arSourcesCVoidBreaker,
  ".sources.common": arSourcesCommon,
  ".sources.feed": arSourcesFeed,
  ".sources.groups": arSourcesGroups,
  ".sources.library": arSourcesLibrary,
  ".sources.nav": arSourcesNav,
  ".sources.pages": arSourcesPages,
  ".sources.r-altair": arSourcesRAltair,
  ".sources.r-discord": arSourcesRDiscord,
  ".sources.r-forest-explorer": arSourcesRForestExplorer,
  ".sources.r-rmhbox": arSourcesRRmhbox,
  ".sources.r-rmhcode": arSourcesRRmhcode,
  ".sources.r-secret": arSourcesRSecret,
  ".sources.r-slice-it": arSourcesRSliceIt,
  ".sources.r-strategies": arSourcesRStrategies,
  ".sources.r-studio": arSourcesRStudio,
  ".sources.rideshare": arSourcesRideshare,
  ".sources.shared": arSourcesShared,
  ".sources.site": arSourcesSite,
  ".sources.user-builds": arSourcesUserBuilds,
  ".sources.v": arSourcesV,
  "admin": arAdmin,
  "builds": arBuilds,
  "c-admin": arCAdmin,
  "c-altair": arCAltair,
  "c-blog": arCBlog,
  "c-builds": arCBuilds,
  "c-cursed-logic": arCCursedLogic,
  "c-daily-puzzles": arCDailyPuzzles,
  "c-doctrine": arCDoctrine,
  "c-dream-rift": arCDreamRift,
  "c-economy": arCEconomy,
  "c-forest-explorer": arCForestExplorer,
  "c-game": arCGame,
  "c-house-always-wins": arCHouseAlwaysWins,
  "c-kowloon-knockout": arCKowloonKnockout,
  "c-laundry-sort": arCLaundrySort,
  "c-library": arCLibrary,
  "c-lights-out": arCLightsOut,
  "c-lockdown": arCLockdown,
  "c-moderation": arCModeration,
  "c-neon-driftway": arCNeonDriftway,
  "c-news": arCNews,
  "c-rideshare": arCRideshare,
  "c-rmh-capital": arCRmhCapital,
  "c-rmh-pmc": arCRmhPmc,
  "c-rmhbox": arCRmhbox,
  "c-rmhcode": arCRmhcode,
  "c-rmhcoins": arCRmhcoins,
  "c-rmhmusic": arCRmhmusic,
  "c-rmhstudy": arCRmhstudy,
  "c-rmhtech": arCRmhtech,
  "c-rmhtube": arCRmhtube,
  "c-rmhtype": arCRmhtype,
  "c-rmhvibe": arCRmhvibe,
  "c-roadmap": arCRoadmap,
  "c-signal-forge": arCSignalForge,
  "c-studio": arCStudio,
  "c-synapse-storm": arCSynapseStorm,
  "c-temple-of-joy": arCTempleOfJoy,
  "c-ui": arCUi,
  "c-user-builds": arCUserBuilds,
  "c-vega": arCVega,
  "c-velum2099": arCVelum2099,
  "c-versecraft": arCVersecraft,
  "c-void-breaker": arCVoidBreaker,
  "common": arCommon,
  "feed": arFeed,
  "groups": arGroups,
  "library": arLibrary,
  "nav": arNav,
  "pages": arPages,
  "r-altair": arRAltair,
  "r-discord": arRDiscord,
  "r-forest-explorer": arRForestExplorer,
  "r-kowloon-knockout": arRKowloonKnockout,
  "r-rmhbox": arRRmhbox,
  "r-rmhcode": arRRmhcode,
  "r-secret": arRSecret,
  "r-slice-it": arRSliceIt,
  "r-strategies": arRStrategies,
  "r-studio": arRStudio,
  "rideshare": arRideshare,
  "shared": arShared,
  "site": arSite,
  "user-builds": arUserBuilds,
  "v": arV,
} as const;

export default arResources;
