// AUTO-GENERATED by scripts/gen-i18n-resources.ts (do not edit by hand).
// Per-language i18n bundle for "vi". Only the namespaces translated for
// this locale are bundled; any other namespace falls back to English at runtime.
import viBuilds from "@/locales/vi/builds.json";
import viCommon from "@/locales/vi/common.json";
import viFeed from "@/locales/vi/feed.json";
import viGroups from "@/locales/vi/groups.json";
import viLibrary from "@/locales/vi/library.json";
import viNav from "@/locales/vi/nav.json";
import viPages from "@/locales/vi/pages.json";
import viRideshare from "@/locales/vi/rideshare.json";
import viShared from "@/locales/vi/shared.json";
import viSite from "@/locales/vi/site.json";
import viUserBuilds from "@/locales/vi/user-builds.json";
import viV from "@/locales/vi/v.json";

const viResources = {
  "builds": viBuilds,
  "common": viCommon,
  "feed": viFeed,
  "groups": viGroups,
  "library": viLibrary,
  "nav": viNav,
  "pages": viPages,
  "rideshare": viRideshare,
  "shared": viShared,
  "site": viSite,
  "user-builds": viUserBuilds,
  "v": viV,
} as const;

export default viResources;
