// AUTO-GENERATED by scripts/gen-i18n-resources.ts (do not edit by hand).
// Per-language i18n bundle for "fr". Only the namespaces translated for
// this locale are bundled; any other namespace falls back to English at runtime.
import frBuilds from "@/locales/fr/builds.json";
import frCommon from "@/locales/fr/common.json";
import frFeed from "@/locales/fr/feed.json";
import frGroups from "@/locales/fr/groups.json";
import frLibrary from "@/locales/fr/library.json";
import frNav from "@/locales/fr/nav.json";
import frPages from "@/locales/fr/pages.json";
import frRideshare from "@/locales/fr/rideshare.json";
import frShared from "@/locales/fr/shared.json";
import frSite from "@/locales/fr/site.json";
import frUserBuilds from "@/locales/fr/user-builds.json";
import frV from "@/locales/fr/v.json";

const frResources = {
  "builds": frBuilds,
  "common": frCommon,
  "feed": frFeed,
  "groups": frGroups,
  "library": frLibrary,
  "nav": frNav,
  "pages": frPages,
  "rideshare": frRideshare,
  "shared": frShared,
  "site": frSite,
  "user-builds": frUserBuilds,
  "v": frV,
} as const;

export default frResources;
