// AUTO-GENERATED by scripts/gen-i18n-resources.ts (do not edit by hand).
// Per-language i18n bundle for "sv". Only the namespaces translated for
// this locale are bundled; any other namespace falls back to English at runtime.


const svResources = {

} as const;

export default svResources;
