// AUTO-GENERATED by scripts/gen-i18n-resources.ts (do not edit by hand).
// Per-language i18n bundle for "ko". Only the namespaces translated for
// this locale are bundled; any other namespace falls back to English at runtime.
import koBuilds from "@/locales/ko/builds.json";
import koCommon from "@/locales/ko/common.json";
import koFeed from "@/locales/ko/feed.json";
import koGroups from "@/locales/ko/groups.json";
import koLibrary from "@/locales/ko/library.json";
import koNav from "@/locales/ko/nav.json";
import koPages from "@/locales/ko/pages.json";
import koRideshare from "@/locales/ko/rideshare.json";
import koShared from "@/locales/ko/shared.json";
import koSite from "@/locales/ko/site.json";
import koUserBuilds from "@/locales/ko/user-builds.json";
import koV from "@/locales/ko/v.json";

const koResources = {
  "builds": koBuilds,
  "common": koCommon,
  "feed": koFeed,
  "groups": koGroups,
  "library": koLibrary,
  "nav": koNav,
  "pages": koPages,
  "rideshare": koRideshare,
  "shared": koShared,
  "site": koSite,
  "user-builds": koUserBuilds,
  "v": koV,
} as const;

export default koResources;
