// AUTO-GENERATED by scripts/gen-i18n-resources.ts (do not edit by hand).
// Per-language i18n bundle for "zh". Only the namespaces translated for
// this locale are bundled; any other namespace falls back to English at runtime.
import zhAdmin from "@/locales/zh/admin.json";
import zhBuilds from "@/locales/zh/builds.json";
import zhCAdmin from "@/locales/zh/c-admin.json";
import zhCAltair from "@/locales/zh/c-altair.json";
import zhCBlog from "@/locales/zh/c-blog.json";
import zhCBuilds from "@/locales/zh/c-builds.json";
import zhCCursedLogic from "@/locales/zh/c-cursed-logic.json";
import zhCDailyPuzzles from "@/locales/zh/c-daily-puzzles.json";
import zhCDoctrine from "@/locales/zh/c-doctrine.json";
import zhCDreamRift from "@/locales/zh/c-dream-rift.json";
import zhCEconomy from "@/locales/zh/c-economy.json";
import zhCForestExplorer from "@/locales/zh/c-forest-explorer.json";
import zhCGame from "@/locales/zh/c-game.json";
import zhCHouseAlwaysWins from "@/locales/zh/c-house-always-wins.json";
import zhCKowloonKnockout from "@/locales/zh/c-kowloon-knockout.json";
import zhCLaundrySort from "@/locales/zh/c-laundry-sort.json";
import zhCLibrary from "@/locales/zh/c-library.json";
import zhCLightsOut from "@/locales/zh/c-lights-out.json";
import zhCLockdown from "@/locales/zh/c-lockdown.json";
import zhCModeration from "@/locales/zh/c-moderation.json";
import zhCNeonDriftway from "@/locales/zh/c-neon-driftway.json";
import zhCNews from "@/locales/zh/c-news.json";
import zhCRideshare from "@/locales/zh/c-rideshare.json";
import zhCRmhCapital from "@/locales/zh/c-rmh-capital.json";
import zhCRmhPmc from "@/locales/zh/c-rmh-pmc.json";
import zhCRmhbox from "@/locales/zh/c-rmhbox.json";
import zhCRmhcode from "@/locales/zh/c-rmhcode.json";
import zhCRmhcoins from "@/locales/zh/c-rmhcoins.json";
import zhCRmhmusic from "@/locales/zh/c-rmhmusic.json";
import zhCRmhstudy from "@/locales/zh/c-rmhstudy.json";
import zhCRmhtech from "@/locales/zh/c-rmhtech.json";
import zhCRmhtube from "@/locales/zh/c-rmhtube.json";
import zhCRmhtype from "@/locales/zh/c-rmhtype.json";
import zhCRmhvibe from "@/locales/zh/c-rmhvibe.json";
import zhCRoadmap from "@/locales/zh/c-roadmap.json";
import zhCSignalForge from "@/locales/zh/c-signal-forge.json";
import zhCStudio from "@/locales/zh/c-studio.json";
import zhCSynapseStorm from "@/locales/zh/c-synapse-storm.json";
import zhCTempleOfJoy from "@/locales/zh/c-temple-of-joy.json";
import zhCUi from "@/locales/zh/c-ui.json";
import zhCUserBuilds from "@/locales/zh/c-user-builds.json";
import zhCVega from "@/locales/zh/c-vega.json";
import zhCVelum2099 from "@/locales/zh/c-velum2099.json";
import zhCVersecraft from "@/locales/zh/c-versecraft.json";
import zhCVoidBreaker from "@/locales/zh/c-void-breaker.json";
import zhCommon from "@/locales/zh/common.json";
import zhFeed from "@/locales/zh/feed.json";
import zhGroups from "@/locales/zh/groups.json";
import zhLibrary from "@/locales/zh/library.json";
import zhNav from "@/locales/zh/nav.json";
import zhPages from "@/locales/zh/pages.json";
import zhRAltair from "@/locales/zh/r-altair.json";
import zhRDiscord from "@/locales/zh/r-discord.json";
import zhRForestExplorer from "@/locales/zh/r-forest-explorer.json";
import zhRKowloonKnockout from "@/locales/zh/r-kowloon-knockout.json";
import zhRRmhbox from "@/locales/zh/r-rmhbox.json";
import zhRRmhcode from "@/locales/zh/r-rmhcode.json";
import zhRSecret from "@/locales/zh/r-secret.json";
import zhRSliceIt from "@/locales/zh/r-slice-it.json";
import zhRStrategies from "@/locales/zh/r-strategies.json";
import zhRStudio from "@/locales/zh/r-studio.json";
import zhRideshare from "@/locales/zh/rideshare.json";
import zhShared from "@/locales/zh/shared.json";
import zhSite from "@/locales/zh/site.json";
import zhUserBuilds from "@/locales/zh/user-builds.json";
import zhV from "@/locales/zh/v.json";

const zhResources = {
  "admin": zhAdmin,
  "builds": zhBuilds,
  "c-admin": zhCAdmin,
  "c-altair": zhCAltair,
  "c-blog": zhCBlog,
  "c-builds": zhCBuilds,
  "c-cursed-logic": zhCCursedLogic,
  "c-daily-puzzles": zhCDailyPuzzles,
  "c-doctrine": zhCDoctrine,
  "c-dream-rift": zhCDreamRift,
  "c-economy": zhCEconomy,
  "c-forest-explorer": zhCForestExplorer,
  "c-game": zhCGame,
  "c-house-always-wins": zhCHouseAlwaysWins,
  "c-kowloon-knockout": zhCKowloonKnockout,
  "c-laundry-sort": zhCLaundrySort,
  "c-library": zhCLibrary,
  "c-lights-out": zhCLightsOut,
  "c-lockdown": zhCLockdown,
  "c-moderation": zhCModeration,
  "c-neon-driftway": zhCNeonDriftway,
  "c-news": zhCNews,
  "c-rideshare": zhCRideshare,
  "c-rmh-capital": zhCRmhCapital,
  "c-rmh-pmc": zhCRmhPmc,
  "c-rmhbox": zhCRmhbox,
  "c-rmhcode": zhCRmhcode,
  "c-rmhcoins": zhCRmhcoins,
  "c-rmhmusic": zhCRmhmusic,
  "c-rmhstudy": zhCRmhstudy,
  "c-rmhtech": zhCRmhtech,
  "c-rmhtube": zhCRmhtube,
  "c-rmhtype": zhCRmhtype,
  "c-rmhvibe": zhCRmhvibe,
  "c-roadmap": zhCRoadmap,
  "c-signal-forge": zhCSignalForge,
  "c-studio": zhCStudio,
  "c-synapse-storm": zhCSynapseStorm,
  "c-temple-of-joy": zhCTempleOfJoy,
  "c-ui": zhCUi,
  "c-user-builds": zhCUserBuilds,
  "c-vega": zhCVega,
  "c-velum2099": zhCVelum2099,
  "c-versecraft": zhCVersecraft,
  "c-void-breaker": zhCVoidBreaker,
  "common": zhCommon,
  "feed": zhFeed,
  "groups": zhGroups,
  "library": zhLibrary,
  "nav": zhNav,
  "pages": zhPages,
  "r-altair": zhRAltair,
  "r-discord": zhRDiscord,
  "r-forest-explorer": zhRForestExplorer,
  "r-kowloon-knockout": zhRKowloonKnockout,
  "r-rmhbox": zhRRmhbox,
  "r-rmhcode": zhRRmhcode,
  "r-secret": zhRSecret,
  "r-slice-it": zhRSliceIt,
  "r-strategies": zhRStrategies,
  "r-studio": zhRStudio,
  "rideshare": zhRideshare,
  "shared": zhShared,
  "site": zhSite,
  "user-builds": zhUserBuilds,
  "v": zhV,
} as const;

export default zhResources;
