// AUTO-GENERATED by scripts/gen-i18n-resources.ts (do not edit by hand).
// Per-language i18n bundle for "pl". Only the namespaces translated for
// this locale are bundled; any other namespace falls back to English at runtime.
import plAdmin from "@/locales/pl/admin.json";
import plBuilds from "@/locales/pl/builds.json";
import plCAdmin from "@/locales/pl/c-admin.json";
import plCAltair from "@/locales/pl/c-altair.json";
import plCBlog from "@/locales/pl/c-blog.json";
import plCBuilds from "@/locales/pl/c-builds.json";
import plCCursedLogic from "@/locales/pl/c-cursed-logic.json";
import plCDailyPuzzles from "@/locales/pl/c-daily-puzzles.json";
import plCDoctrine from "@/locales/pl/c-doctrine.json";
import plCDreamRift from "@/locales/pl/c-dream-rift.json";
import plCEconomy from "@/locales/pl/c-economy.json";
import plCForestExplorer from "@/locales/pl/c-forest-explorer.json";
import plCGame from "@/locales/pl/c-game.json";
import plCHouseAlwaysWins from "@/locales/pl/c-house-always-wins.json";
import plCKowloonKnockout from "@/locales/pl/c-kowloon-knockout.json";
import plCLaundrySort from "@/locales/pl/c-laundry-sort.json";
import plCLibrary from "@/locales/pl/c-library.json";
import plCLightsOut from "@/locales/pl/c-lights-out.json";
import plCLockdown from "@/locales/pl/c-lockdown.json";
import plCModeration from "@/locales/pl/c-moderation.json";
import plCNeonDriftway from "@/locales/pl/c-neon-driftway.json";
import plCNews from "@/locales/pl/c-news.json";
import plCRideshare from "@/locales/pl/c-rideshare.json";
import plCRmhCapital from "@/locales/pl/c-rmh-capital.json";
import plCRmhPmc from "@/locales/pl/c-rmh-pmc.json";
import plCRmhbox from "@/locales/pl/c-rmhbox.json";
import plCRmhcode from "@/locales/pl/c-rmhcode.json";
import plCRmhcoins from "@/locales/pl/c-rmhcoins.json";
import plCRmhmusic from "@/locales/pl/c-rmhmusic.json";
import plCRmhstudy from "@/locales/pl/c-rmhstudy.json";
import plCRmhtech from "@/locales/pl/c-rmhtech.json";
import plCRmhtube from "@/locales/pl/c-rmhtube.json";
import plCRmhtype from "@/locales/pl/c-rmhtype.json";
import plCRmhvibe from "@/locales/pl/c-rmhvibe.json";
import plCRoadmap from "@/locales/pl/c-roadmap.json";
import plCSignalForge from "@/locales/pl/c-signal-forge.json";
import plCStudio from "@/locales/pl/c-studio.json";
import plCSynapseStorm from "@/locales/pl/c-synapse-storm.json";
import plCTempleOfJoy from "@/locales/pl/c-temple-of-joy.json";
import plCUi from "@/locales/pl/c-ui.json";
import plCUserBuilds from "@/locales/pl/c-user-builds.json";
import plCVega from "@/locales/pl/c-vega.json";
import plCVersecraft from "@/locales/pl/c-versecraft.json";
import plCVoidBreaker from "@/locales/pl/c-void-breaker.json";
import plCommon from "@/locales/pl/common.json";
import plFeed from "@/locales/pl/feed.json";
import plGroups from "@/locales/pl/groups.json";
import plLibrary from "@/locales/pl/library.json";
import plNav from "@/locales/pl/nav.json";
import plPages from "@/locales/pl/pages.json";
import plRAltair from "@/locales/pl/r-altair.json";
import plRDiscord from "@/locales/pl/r-discord.json";
import plRForestExplorer from "@/locales/pl/r-forest-explorer.json";
import plRRmhbox from "@/locales/pl/r-rmhbox.json";
import plRRmhcode from "@/locales/pl/r-rmhcode.json";
import plRSecret from "@/locales/pl/r-secret.json";
import plRSliceIt from "@/locales/pl/r-slice-it.json";
import plRStrategies from "@/locales/pl/r-strategies.json";
import plRStudio from "@/locales/pl/r-studio.json";
import plRideshare from "@/locales/pl/rideshare.json";
import plShared from "@/locales/pl/shared.json";
import plSite from "@/locales/pl/site.json";
import plUserBuilds from "@/locales/pl/user-builds.json";
import plV from "@/locales/pl/v.json";

const plResources = {
  "admin": plAdmin,
  "builds": plBuilds,
  "c-admin": plCAdmin,
  "c-altair": plCAltair,
  "c-blog": plCBlog,
  "c-builds": plCBuilds,
  "c-cursed-logic": plCCursedLogic,
  "c-daily-puzzles": plCDailyPuzzles,
  "c-doctrine": plCDoctrine,
  "c-dream-rift": plCDreamRift,
  "c-economy": plCEconomy,
  "c-forest-explorer": plCForestExplorer,
  "c-game": plCGame,
  "c-house-always-wins": plCHouseAlwaysWins,
  "c-kowloon-knockout": plCKowloonKnockout,
  "c-laundry-sort": plCLaundrySort,
  "c-library": plCLibrary,
  "c-lights-out": plCLightsOut,
  "c-lockdown": plCLockdown,
  "c-moderation": plCModeration,
  "c-neon-driftway": plCNeonDriftway,
  "c-news": plCNews,
  "c-rideshare": plCRideshare,
  "c-rmh-capital": plCRmhCapital,
  "c-rmh-pmc": plCRmhPmc,
  "c-rmhbox": plCRmhbox,
  "c-rmhcode": plCRmhcode,
  "c-rmhcoins": plCRmhcoins,
  "c-rmhmusic": plCRmhmusic,
  "c-rmhstudy": plCRmhstudy,
  "c-rmhtech": plCRmhtech,
  "c-rmhtube": plCRmhtube,
  "c-rmhtype": plCRmhtype,
  "c-rmhvibe": plCRmhvibe,
  "c-roadmap": plCRoadmap,
  "c-signal-forge": plCSignalForge,
  "c-studio": plCStudio,
  "c-synapse-storm": plCSynapseStorm,
  "c-temple-of-joy": plCTempleOfJoy,
  "c-ui": plCUi,
  "c-user-builds": plCUserBuilds,
  "c-vega": plCVega,
  "c-versecraft": plCVersecraft,
  "c-void-breaker": plCVoidBreaker,
  "common": plCommon,
  "feed": plFeed,
  "groups": plGroups,
  "library": plLibrary,
  "nav": plNav,
  "pages": plPages,
  "r-altair": plRAltair,
  "r-discord": plRDiscord,
  "r-forest-explorer": plRForestExplorer,
  "r-rmhbox": plRRmhbox,
  "r-rmhcode": plRRmhcode,
  "r-secret": plRSecret,
  "r-slice-it": plRSliceIt,
  "r-strategies": plRStrategies,
  "r-studio": plRStudio,
  "rideshare": plRideshare,
  "shared": plShared,
  "site": plSite,
  "user-builds": plUserBuilds,
  "v": plV,
} as const;

export default plResources;
