// AUTO-GENERATED by scripts/gen-i18n-resources.ts (do not edit by hand).
// Per-language i18n bundle for "cs". Only the namespaces translated for
// this locale are bundled; any other namespace falls back to English at runtime.


const csResources = {

} as const;

export default csResources;
