// AUTO-GENERATED by scripts/gen-i18n-resources.ts (do not edit by hand).
// Per-language i18n bundle for "vi". Only the namespaces translated for
// this locale are bundled; any other namespace falls back to English at runtime.
import viAdmin from "@/locales/vi/admin.json";
import viBuilds from "@/locales/vi/builds.json";
import viCAdmin from "@/locales/vi/c-admin.json";
import viCAltair from "@/locales/vi/c-altair.json";
import viCBlog from "@/locales/vi/c-blog.json";
import viCBuilds from "@/locales/vi/c-builds.json";
import viCCursedLogic from "@/locales/vi/c-cursed-logic.json";
import viCDailyPuzzles from "@/locales/vi/c-daily-puzzles.json";
import viCDoctrine from "@/locales/vi/c-doctrine.json";
import viCDreamRift from "@/locales/vi/c-dream-rift.json";
import viCEconomy from "@/locales/vi/c-economy.json";
import viCForestExplorer from "@/locales/vi/c-forest-explorer.json";
import viCGame from "@/locales/vi/c-game.json";
import viCHouseAlwaysWins from "@/locales/vi/c-house-always-wins.json";
import viCKowloonKnockout from "@/locales/vi/c-kowloon-knockout.json";
import viCLaundrySort from "@/locales/vi/c-laundry-sort.json";
import viCLibrary from "@/locales/vi/c-library.json";
import viCLightsOut from "@/locales/vi/c-lights-out.json";
import viCLockdown from "@/locales/vi/c-lockdown.json";
import viCModeration from "@/locales/vi/c-moderation.json";
import viCNeonDriftway from "@/locales/vi/c-neon-driftway.json";
import viCNews from "@/locales/vi/c-news.json";
import viCRideshare from "@/locales/vi/c-rideshare.json";
import viCRmhCapital from "@/locales/vi/c-rmh-capital.json";
import viCRmhPmc from "@/locales/vi/c-rmh-pmc.json";
import viCRmhbox from "@/locales/vi/c-rmhbox.json";
import viCRmhcode from "@/locales/vi/c-rmhcode.json";
import viCRmhcoins from "@/locales/vi/c-rmhcoins.json";
import viCRmhmusic from "@/locales/vi/c-rmhmusic.json";
import viCRmhstudy from "@/locales/vi/c-rmhstudy.json";
import viCRmhtech from "@/locales/vi/c-rmhtech.json";
import viCRmhtube from "@/locales/vi/c-rmhtube.json";
import viCRmhtype from "@/locales/vi/c-rmhtype.json";
import viCRmhvibe from "@/locales/vi/c-rmhvibe.json";
import viCRoadmap from "@/locales/vi/c-roadmap.json";
import viCSignalForge from "@/locales/vi/c-signal-forge.json";
import viCStudio from "@/locales/vi/c-studio.json";
import viCSynapseStorm from "@/locales/vi/c-synapse-storm.json";
import viCTempleOfJoy from "@/locales/vi/c-temple-of-joy.json";
import viCUi from "@/locales/vi/c-ui.json";
import viCUserBuilds from "@/locales/vi/c-user-builds.json";
import viCVega from "@/locales/vi/c-vega.json";
import viCVersecraft from "@/locales/vi/c-versecraft.json";
import viCVoidBreaker from "@/locales/vi/c-void-breaker.json";
import viCommon from "@/locales/vi/common.json";
import viFeed from "@/locales/vi/feed.json";
import viGroups from "@/locales/vi/groups.json";
import viLibrary from "@/locales/vi/library.json";
import viNav from "@/locales/vi/nav.json";
import viPages from "@/locales/vi/pages.json";
import viRAltair from "@/locales/vi/r-altair.json";
import viRDiscord from "@/locales/vi/r-discord.json";
import viRForestExplorer from "@/locales/vi/r-forest-explorer.json";
import viRRmhbox from "@/locales/vi/r-rmhbox.json";
import viRRmhcode from "@/locales/vi/r-rmhcode.json";
import viRSecret from "@/locales/vi/r-secret.json";
import viRSliceIt from "@/locales/vi/r-slice-it.json";
import viRStrategies from "@/locales/vi/r-strategies.json";
import viRStudio from "@/locales/vi/r-studio.json";
import viRideshare from "@/locales/vi/rideshare.json";
import viShared from "@/locales/vi/shared.json";
import viSite from "@/locales/vi/site.json";
import viUserBuilds from "@/locales/vi/user-builds.json";
import viV from "@/locales/vi/v.json";

const viResources = {
  "admin": viAdmin,
  "builds": viBuilds,
  "c-admin": viCAdmin,
  "c-altair": viCAltair,
  "c-blog": viCBlog,
  "c-builds": viCBuilds,
  "c-cursed-logic": viCCursedLogic,
  "c-daily-puzzles": viCDailyPuzzles,
  "c-doctrine": viCDoctrine,
  "c-dream-rift": viCDreamRift,
  "c-economy": viCEconomy,
  "c-forest-explorer": viCForestExplorer,
  "c-game": viCGame,
  "c-house-always-wins": viCHouseAlwaysWins,
  "c-kowloon-knockout": viCKowloonKnockout,
  "c-laundry-sort": viCLaundrySort,
  "c-library": viCLibrary,
  "c-lights-out": viCLightsOut,
  "c-lockdown": viCLockdown,
  "c-moderation": viCModeration,
  "c-neon-driftway": viCNeonDriftway,
  "c-news": viCNews,
  "c-rideshare": viCRideshare,
  "c-rmh-capital": viCRmhCapital,
  "c-rmh-pmc": viCRmhPmc,
  "c-rmhbox": viCRmhbox,
  "c-rmhcode": viCRmhcode,
  "c-rmhcoins": viCRmhcoins,
  "c-rmhmusic": viCRmhmusic,
  "c-rmhstudy": viCRmhstudy,
  "c-rmhtech": viCRmhtech,
  "c-rmhtube": viCRmhtube,
  "c-rmhtype": viCRmhtype,
  "c-rmhvibe": viCRmhvibe,
  "c-roadmap": viCRoadmap,
  "c-signal-forge": viCSignalForge,
  "c-studio": viCStudio,
  "c-synapse-storm": viCSynapseStorm,
  "c-temple-of-joy": viCTempleOfJoy,
  "c-ui": viCUi,
  "c-user-builds": viCUserBuilds,
  "c-vega": viCVega,
  "c-versecraft": viCVersecraft,
  "c-void-breaker": viCVoidBreaker,
  "common": viCommon,
  "feed": viFeed,
  "groups": viGroups,
  "library": viLibrary,
  "nav": viNav,
  "pages": viPages,
  "r-altair": viRAltair,
  "r-discord": viRDiscord,
  "r-forest-explorer": viRForestExplorer,
  "r-rmhbox": viRRmhbox,
  "r-rmhcode": viRRmhcode,
  "r-secret": viRSecret,
  "r-slice-it": viRSliceIt,
  "r-strategies": viRStrategies,
  "r-studio": viRStudio,
  "rideshare": viRideshare,
  "shared": viShared,
  "site": viSite,
  "user-builds": viUserBuilds,
  "v": viV,
} as const;

export default viResources;
