// AUTO-GENERATED by scripts/gen-i18n-resources.ts (do not edit by hand).
// Per-language i18n bundle for "fa". Only the namespaces translated for
// this locale are bundled; any other namespace falls back to English at runtime.
import faAdmin from "@/locales/fa/admin.json";
import faBuilds from "@/locales/fa/builds.json";
import faCAdmin from "@/locales/fa/c-admin.json";
import faCAltair from "@/locales/fa/c-altair.json";
import faCBlog from "@/locales/fa/c-blog.json";
import faCBuilds from "@/locales/fa/c-builds.json";
import faCCursedLogic from "@/locales/fa/c-cursed-logic.json";
import faCDailyPuzzles from "@/locales/fa/c-daily-puzzles.json";
import faCDoctrine from "@/locales/fa/c-doctrine.json";
import faCDreamRift from "@/locales/fa/c-dream-rift.json";
import faCEconomy from "@/locales/fa/c-economy.json";
import faCForestExplorer from "@/locales/fa/c-forest-explorer.json";
import faCGame from "@/locales/fa/c-game.json";
import faCHouseAlwaysWins from "@/locales/fa/c-house-always-wins.json";
import faCKowloonKnockout from "@/locales/fa/c-kowloon-knockout.json";
import faCLaundrySort from "@/locales/fa/c-laundry-sort.json";
import faCLibrary from "@/locales/fa/c-library.json";
import faCLightsOut from "@/locales/fa/c-lights-out.json";
import faCLockdown from "@/locales/fa/c-lockdown.json";
import faCModeration from "@/locales/fa/c-moderation.json";
import faCNeonDriftway from "@/locales/fa/c-neon-driftway.json";
import faCNews from "@/locales/fa/c-news.json";
import faCRideshare from "@/locales/fa/c-rideshare.json";
import faCRmhCapital from "@/locales/fa/c-rmh-capital.json";
import faCRmhPmc from "@/locales/fa/c-rmh-pmc.json";
import faCRmhbox from "@/locales/fa/c-rmhbox.json";
import faCRmhcode from "@/locales/fa/c-rmhcode.json";
import faCRmhcoins from "@/locales/fa/c-rmhcoins.json";
import faCRmhmusic from "@/locales/fa/c-rmhmusic.json";
import faCRmhstudy from "@/locales/fa/c-rmhstudy.json";
import faCRmhtech from "@/locales/fa/c-rmhtech.json";
import faCRmhtube from "@/locales/fa/c-rmhtube.json";
import faCRmhtype from "@/locales/fa/c-rmhtype.json";
import faCRmhvibe from "@/locales/fa/c-rmhvibe.json";
import faCRoadmap from "@/locales/fa/c-roadmap.json";
import faCSignalForge from "@/locales/fa/c-signal-forge.json";
import faCStudio from "@/locales/fa/c-studio.json";
import faCSynapseStorm from "@/locales/fa/c-synapse-storm.json";
import faCTempleOfJoy from "@/locales/fa/c-temple-of-joy.json";
import faCUi from "@/locales/fa/c-ui.json";
import faCUserBuilds from "@/locales/fa/c-user-builds.json";
import faCVega from "@/locales/fa/c-vega.json";
import faCVersecraft from "@/locales/fa/c-versecraft.json";
import faCVoidBreaker from "@/locales/fa/c-void-breaker.json";
import faCommon from "@/locales/fa/common.json";
import faFeed from "@/locales/fa/feed.json";
import faGroups from "@/locales/fa/groups.json";
import faLibrary from "@/locales/fa/library.json";
import faNav from "@/locales/fa/nav.json";
import faPages from "@/locales/fa/pages.json";
import faRAltair from "@/locales/fa/r-altair.json";
import faRDiscord from "@/locales/fa/r-discord.json";
import faRForestExplorer from "@/locales/fa/r-forest-explorer.json";
import faRRmhbox from "@/locales/fa/r-rmhbox.json";
import faRRmhcode from "@/locales/fa/r-rmhcode.json";
import faRSecret from "@/locales/fa/r-secret.json";
import faRSliceIt from "@/locales/fa/r-slice-it.json";
import faRStrategies from "@/locales/fa/r-strategies.json";
import faRStudio from "@/locales/fa/r-studio.json";
import faRideshare from "@/locales/fa/rideshare.json";
import faShared from "@/locales/fa/shared.json";
import faSite from "@/locales/fa/site.json";
import faUserBuilds from "@/locales/fa/user-builds.json";
import faV from "@/locales/fa/v.json";

const faResources = {
  "admin": faAdmin,
  "builds": faBuilds,
  "c-admin": faCAdmin,
  "c-altair": faCAltair,
  "c-blog": faCBlog,
  "c-builds": faCBuilds,
  "c-cursed-logic": faCCursedLogic,
  "c-daily-puzzles": faCDailyPuzzles,
  "c-doctrine": faCDoctrine,
  "c-dream-rift": faCDreamRift,
  "c-economy": faCEconomy,
  "c-forest-explorer": faCForestExplorer,
  "c-game": faCGame,
  "c-house-always-wins": faCHouseAlwaysWins,
  "c-kowloon-knockout": faCKowloonKnockout,
  "c-laundry-sort": faCLaundrySort,
  "c-library": faCLibrary,
  "c-lights-out": faCLightsOut,
  "c-lockdown": faCLockdown,
  "c-moderation": faCModeration,
  "c-neon-driftway": faCNeonDriftway,
  "c-news": faCNews,
  "c-rideshare": faCRideshare,
  "c-rmh-capital": faCRmhCapital,
  "c-rmh-pmc": faCRmhPmc,
  "c-rmhbox": faCRmhbox,
  "c-rmhcode": faCRmhcode,
  "c-rmhcoins": faCRmhcoins,
  "c-rmhmusic": faCRmhmusic,
  "c-rmhstudy": faCRmhstudy,
  "c-rmhtech": faCRmhtech,
  "c-rmhtube": faCRmhtube,
  "c-rmhtype": faCRmhtype,
  "c-rmhvibe": faCRmhvibe,
  "c-roadmap": faCRoadmap,
  "c-signal-forge": faCSignalForge,
  "c-studio": faCStudio,
  "c-synapse-storm": faCSynapseStorm,
  "c-temple-of-joy": faCTempleOfJoy,
  "c-ui": faCUi,
  "c-user-builds": faCUserBuilds,
  "c-vega": faCVega,
  "c-versecraft": faCVersecraft,
  "c-void-breaker": faCVoidBreaker,
  "common": faCommon,
  "feed": faFeed,
  "groups": faGroups,
  "library": faLibrary,
  "nav": faNav,
  "pages": faPages,
  "r-altair": faRAltair,
  "r-discord": faRDiscord,
  "r-forest-explorer": faRForestExplorer,
  "r-rmhbox": faRRmhbox,
  "r-rmhcode": faRRmhcode,
  "r-secret": faRSecret,
  "r-slice-it": faRSliceIt,
  "r-strategies": faRStrategies,
  "r-studio": faRStudio,
  "rideshare": faRideshare,
  "shared": faShared,
  "site": faSite,
  "user-builds": faUserBuilds,
  "v": faV,
} as const;

export default faResources;
