// AUTO-GENERATED by scripts/gen-i18n-resources.ts (do not edit by hand).
// Per-language i18n bundle for "ja". Only the namespaces translated for
// this locale are bundled; any other namespace falls back to English at runtime.
import jaAdmin from "@/locales/ja/admin.json";
import jaBuilds from "@/locales/ja/builds.json";
import jaCAdmin from "@/locales/ja/c-admin.json";
import jaCAltair from "@/locales/ja/c-altair.json";
import jaCBlog from "@/locales/ja/c-blog.json";
import jaCBuilds from "@/locales/ja/c-builds.json";
import jaCCursedLogic from "@/locales/ja/c-cursed-logic.json";
import jaCDailyPuzzles from "@/locales/ja/c-daily-puzzles.json";
import jaCDoctrine from "@/locales/ja/c-doctrine.json";
import jaCDreamRift from "@/locales/ja/c-dream-rift.json";
import jaCEconomy from "@/locales/ja/c-economy.json";
import jaCForestExplorer from "@/locales/ja/c-forest-explorer.json";
import jaCGame from "@/locales/ja/c-game.json";
import jaCHouseAlwaysWins from "@/locales/ja/c-house-always-wins.json";
import jaCKowloonKnockout from "@/locales/ja/c-kowloon-knockout.json";
import jaCLaundrySort from "@/locales/ja/c-laundry-sort.json";
import jaCLibrary from "@/locales/ja/c-library.json";
import jaCLightsOut from "@/locales/ja/c-lights-out.json";
import jaCLockdown from "@/locales/ja/c-lockdown.json";
import jaCModeration from "@/locales/ja/c-moderation.json";
import jaCNeonDriftway from "@/locales/ja/c-neon-driftway.json";
import jaCNews from "@/locales/ja/c-news.json";
import jaCRideshare from "@/locales/ja/c-rideshare.json";
import jaCRmhCapital from "@/locales/ja/c-rmh-capital.json";
import jaCRmhPmc from "@/locales/ja/c-rmh-pmc.json";
import jaCRmhbox from "@/locales/ja/c-rmhbox.json";
import jaCRmhcode from "@/locales/ja/c-rmhcode.json";
import jaCRmhcoins from "@/locales/ja/c-rmhcoins.json";
import jaCRmhmusic from "@/locales/ja/c-rmhmusic.json";
import jaCRmhstudy from "@/locales/ja/c-rmhstudy.json";
import jaCRmhtech from "@/locales/ja/c-rmhtech.json";
import jaCRmhtube from "@/locales/ja/c-rmhtube.json";
import jaCRmhtype from "@/locales/ja/c-rmhtype.json";
import jaCRmhvibe from "@/locales/ja/c-rmhvibe.json";
import jaCRoadmap from "@/locales/ja/c-roadmap.json";
import jaCSignalForge from "@/locales/ja/c-signal-forge.json";
import jaCStudio from "@/locales/ja/c-studio.json";
import jaCSynapseStorm from "@/locales/ja/c-synapse-storm.json";
import jaCTempleOfJoy from "@/locales/ja/c-temple-of-joy.json";
import jaCUi from "@/locales/ja/c-ui.json";
import jaCUserBuilds from "@/locales/ja/c-user-builds.json";
import jaCVega from "@/locales/ja/c-vega.json";
import jaCVersecraft from "@/locales/ja/c-versecraft.json";
import jaCVoidBreaker from "@/locales/ja/c-void-breaker.json";
import jaCommon from "@/locales/ja/common.json";
import jaFeed from "@/locales/ja/feed.json";
import jaGroups from "@/locales/ja/groups.json";
import jaLibrary from "@/locales/ja/library.json";
import jaNav from "@/locales/ja/nav.json";
import jaPages from "@/locales/ja/pages.json";
import jaRAltair from "@/locales/ja/r-altair.json";
import jaRDiscord from "@/locales/ja/r-discord.json";
import jaRForestExplorer from "@/locales/ja/r-forest-explorer.json";
import jaRRmhbox from "@/locales/ja/r-rmhbox.json";
import jaRRmhcode from "@/locales/ja/r-rmhcode.json";
import jaRSecret from "@/locales/ja/r-secret.json";
import jaRSliceIt from "@/locales/ja/r-slice-it.json";
import jaRStrategies from "@/locales/ja/r-strategies.json";
import jaRStudio from "@/locales/ja/r-studio.json";
import jaRideshare from "@/locales/ja/rideshare.json";
import jaShared from "@/locales/ja/shared.json";
import jaSite from "@/locales/ja/site.json";
import jaUserBuilds from "@/locales/ja/user-builds.json";
import jaV from "@/locales/ja/v.json";

const jaResources = {
  "admin": jaAdmin,
  "builds": jaBuilds,
  "c-admin": jaCAdmin,
  "c-altair": jaCAltair,
  "c-blog": jaCBlog,
  "c-builds": jaCBuilds,
  "c-cursed-logic": jaCCursedLogic,
  "c-daily-puzzles": jaCDailyPuzzles,
  "c-doctrine": jaCDoctrine,
  "c-dream-rift": jaCDreamRift,
  "c-economy": jaCEconomy,
  "c-forest-explorer": jaCForestExplorer,
  "c-game": jaCGame,
  "c-house-always-wins": jaCHouseAlwaysWins,
  "c-kowloon-knockout": jaCKowloonKnockout,
  "c-laundry-sort": jaCLaundrySort,
  "c-library": jaCLibrary,
  "c-lights-out": jaCLightsOut,
  "c-lockdown": jaCLockdown,
  "c-moderation": jaCModeration,
  "c-neon-driftway": jaCNeonDriftway,
  "c-news": jaCNews,
  "c-rideshare": jaCRideshare,
  "c-rmh-capital": jaCRmhCapital,
  "c-rmh-pmc": jaCRmhPmc,
  "c-rmhbox": jaCRmhbox,
  "c-rmhcode": jaCRmhcode,
  "c-rmhcoins": jaCRmhcoins,
  "c-rmhmusic": jaCRmhmusic,
  "c-rmhstudy": jaCRmhstudy,
  "c-rmhtech": jaCRmhtech,
  "c-rmhtube": jaCRmhtube,
  "c-rmhtype": jaCRmhtype,
  "c-rmhvibe": jaCRmhvibe,
  "c-roadmap": jaCRoadmap,
  "c-signal-forge": jaCSignalForge,
  "c-studio": jaCStudio,
  "c-synapse-storm": jaCSynapseStorm,
  "c-temple-of-joy": jaCTempleOfJoy,
  "c-ui": jaCUi,
  "c-user-builds": jaCUserBuilds,
  "c-vega": jaCVega,
  "c-versecraft": jaCVersecraft,
  "c-void-breaker": jaCVoidBreaker,
  "common": jaCommon,
  "feed": jaFeed,
  "groups": jaGroups,
  "library": jaLibrary,
  "nav": jaNav,
  "pages": jaPages,
  "r-altair": jaRAltair,
  "r-discord": jaRDiscord,
  "r-forest-explorer": jaRForestExplorer,
  "r-rmhbox": jaRRmhbox,
  "r-rmhcode": jaRRmhcode,
  "r-secret": jaRSecret,
  "r-slice-it": jaRSliceIt,
  "r-strategies": jaRStrategies,
  "r-studio": jaRStudio,
  "rideshare": jaRideshare,
  "shared": jaShared,
  "site": jaSite,
  "user-builds": jaUserBuilds,
  "v": jaV,
} as const;

export default jaResources;
