// AUTO-GENERATED by scripts (do not edit by hand). Per-language i18n bundle
// for "zh". Split out of the old monolithic resources.ts so each language
// ships as its own chunk — only the active language is loaded on the client.
import zhSourcesAdmin from "@/locales/zh/.sources.admin.json";
import zhSourcesBuilds from "@/locales/zh/.sources.builds.json";
import zhSourcesCAdmin from "@/locales/zh/.sources.c-admin.json";
import zhSourcesCAltair from "@/locales/zh/.sources.c-altair.json";
import zhSourcesCBlog from "@/locales/zh/.sources.c-blog.json";
import zhSourcesCBuilds from "@/locales/zh/.sources.c-builds.json";
import zhSourcesCCursedLogic from "@/locales/zh/.sources.c-cursed-logic.json";
import zhSourcesCDailyPuzzles from "@/locales/zh/.sources.c-daily-puzzles.json";
import zhSourcesCDoctrine from "@/locales/zh/.sources.c-doctrine.json";
import zhSourcesCDreamRift from "@/locales/zh/.sources.c-dream-rift.json";
import zhSourcesCEconomy from "@/locales/zh/.sources.c-economy.json";
import zhSourcesCForestExplorer from "@/locales/zh/.sources.c-forest-explorer.json";
import zhSourcesCGame from "@/locales/zh/.sources.c-game.json";
import zhSourcesCHouseAlwaysWins from "@/locales/zh/.sources.c-house-always-wins.json";
import zhSourcesCKowloonKnockout from "@/locales/zh/.sources.c-kowloon-knockout.json";
import zhSourcesCLaundrySort from "@/locales/zh/.sources.c-laundry-sort.json";
import zhSourcesCLibrary from "@/locales/zh/.sources.c-library.json";
import zhSourcesCLightsOut from "@/locales/zh/.sources.c-lights-out.json";
import zhSourcesCLockdown from "@/locales/zh/.sources.c-lockdown.json";
import zhSourcesCModeration from "@/locales/zh/.sources.c-moderation.json";
import zhSourcesCNeonDriftway from "@/locales/zh/.sources.c-neon-driftway.json";
import zhSourcesCNews from "@/locales/zh/.sources.c-news.json";
import zhSourcesCRideshare from "@/locales/zh/.sources.c-rideshare.json";
import zhSourcesCRmhCapital from "@/locales/zh/.sources.c-rmh-capital.json";
import zhSourcesCRmhPmc from "@/locales/zh/.sources.c-rmh-pmc.json";
import zhSourcesCRmhbox from "@/locales/zh/.sources.c-rmhbox.json";
import zhSourcesCRmhcode from "@/locales/zh/.sources.c-rmhcode.json";
import zhSourcesCRmhcoins from "@/locales/zh/.sources.c-rmhcoins.json";
import zhSourcesCRmhmusic from "@/locales/zh/.sources.c-rmhmusic.json";
import zhSourcesCRmhstudy from "@/locales/zh/.sources.c-rmhstudy.json";
import zhSourcesCRmhtech from "@/locales/zh/.sources.c-rmhtech.json";
import zhSourcesCRmhtube from "@/locales/zh/.sources.c-rmhtube.json";
import zhSourcesCRmhtype from "@/locales/zh/.sources.c-rmhtype.json";
import zhSourcesCRmhvibe from "@/locales/zh/.sources.c-rmhvibe.json";
import zhSourcesCRoadmap from "@/locales/zh/.sources.c-roadmap.json";
import zhSourcesCSignalForge from "@/locales/zh/.sources.c-signal-forge.json";
import zhSourcesCStudio from "@/locales/zh/.sources.c-studio.json";
import zhSourcesCSynapseStorm from "@/locales/zh/.sources.c-synapse-storm.json";
import zhSourcesCTempleOfJoy from "@/locales/zh/.sources.c-temple-of-joy.json";
import zhSourcesCUi from "@/locales/zh/.sources.c-ui.json";
import zhSourcesCUserBuilds from "@/locales/zh/.sources.c-user-builds.json";
import zhSourcesCVega from "@/locales/zh/.sources.c-vega.json";
import zhSourcesCVersecraft from "@/locales/zh/.sources.c-versecraft.json";
import zhSourcesCVoidBreaker from "@/locales/zh/.sources.c-void-breaker.json";
import zhSourcesCommon from "@/locales/zh/.sources.common.json";
import zhSourcesFeed from "@/locales/zh/.sources.feed.json";
import zhSourcesGroups from "@/locales/zh/.sources.groups.json";
import zhSourcesLibrary from "@/locales/zh/.sources.library.json";
import zhSourcesNav from "@/locales/zh/.sources.nav.json";
import zhSourcesPages from "@/locales/zh/.sources.pages.json";
import zhSourcesRAltair from "@/locales/zh/.sources.r-altair.json";
import zhSourcesRDiscord from "@/locales/zh/.sources.r-discord.json";
import zhSourcesRForestExplorer from "@/locales/zh/.sources.r-forest-explorer.json";
import zhSourcesRRmhbox from "@/locales/zh/.sources.r-rmhbox.json";
import zhSourcesRRmhcode from "@/locales/zh/.sources.r-rmhcode.json";
import zhSourcesRSecret from "@/locales/zh/.sources.r-secret.json";
import zhSourcesRSliceIt from "@/locales/zh/.sources.r-slice-it.json";
import zhSourcesRStrategies from "@/locales/zh/.sources.r-strategies.json";
import zhSourcesRStudio from "@/locales/zh/.sources.r-studio.json";
import zhSourcesRideshare from "@/locales/zh/.sources.rideshare.json";
import zhSourcesShared from "@/locales/zh/.sources.shared.json";
import zhSourcesSite from "@/locales/zh/.sources.site.json";
import zhSourcesUserBuilds from "@/locales/zh/.sources.user-builds.json";
import zhSourcesV from "@/locales/zh/.sources.v.json";
import zhAdmin from "@/locales/zh/admin.json";
import zhBuilds from "@/locales/zh/builds.json";
import zhCAdmin from "@/locales/zh/c-admin.json";
import zhCAltair from "@/locales/zh/c-altair.json";
import zhCBlog from "@/locales/zh/c-blog.json";
import zhCBuilds from "@/locales/zh/c-builds.json";
import zhCCursedLogic from "@/locales/zh/c-cursed-logic.json";
import zhCDailyPuzzles from "@/locales/zh/c-daily-puzzles.json";
import zhCDoctrine from "@/locales/zh/c-doctrine.json";
import zhCDreamRift from "@/locales/zh/c-dream-rift.json";
import zhCEconomy from "@/locales/zh/c-economy.json";
import zhCForestExplorer from "@/locales/zh/c-forest-explorer.json";
import zhCGame from "@/locales/zh/c-game.json";
import zhCHouseAlwaysWins from "@/locales/zh/c-house-always-wins.json";
import zhCKowloonKnockout from "@/locales/zh/c-kowloon-knockout.json";
import zhCLaundrySort from "@/locales/zh/c-laundry-sort.json";
import zhCLibrary from "@/locales/zh/c-library.json";
import zhCLightsOut from "@/locales/zh/c-lights-out.json";
import zhCLockdown from "@/locales/zh/c-lockdown.json";
import zhCModeration from "@/locales/zh/c-moderation.json";
import zhCNeonDriftway from "@/locales/zh/c-neon-driftway.json";
import zhCNews from "@/locales/zh/c-news.json";
import zhCRideshare from "@/locales/zh/c-rideshare.json";
import zhCRmhCapital from "@/locales/zh/c-rmh-capital.json";
import zhCRmhPmc from "@/locales/zh/c-rmh-pmc.json";
import zhCRmhbox from "@/locales/zh/c-rmhbox.json";
import zhCRmhcode from "@/locales/zh/c-rmhcode.json";
import zhCRmhcoins from "@/locales/zh/c-rmhcoins.json";
import zhCRmhmusic from "@/locales/zh/c-rmhmusic.json";
import zhCRmhstudy from "@/locales/zh/c-rmhstudy.json";
import zhCRmhtech from "@/locales/zh/c-rmhtech.json";
import zhCRmhtube from "@/locales/zh/c-rmhtube.json";
import zhCRmhtype from "@/locales/zh/c-rmhtype.json";
import zhCRmhvibe from "@/locales/zh/c-rmhvibe.json";
import zhCRoadmap from "@/locales/zh/c-roadmap.json";
import zhCSignalForge from "@/locales/zh/c-signal-forge.json";
import zhCStudio from "@/locales/zh/c-studio.json";
import zhCSynapseStorm from "@/locales/zh/c-synapse-storm.json";
import zhCTempleOfJoy from "@/locales/zh/c-temple-of-joy.json";
import zhCUi from "@/locales/zh/c-ui.json";
import zhCUserBuilds from "@/locales/zh/c-user-builds.json";
import zhCVega from "@/locales/zh/c-vega.json";
import zhCVelum2099 from "@/locales/zh/c-velum2099.json";
import zhCVersecraft from "@/locales/zh/c-versecraft.json";
import zhCVoidBreaker from "@/locales/zh/c-void-breaker.json";
import zhCommon from "@/locales/zh/common.json";
import zhFeed from "@/locales/zh/feed.json";
import zhGroups from "@/locales/zh/groups.json";
import zhLibrary from "@/locales/zh/library.json";
import zhNav from "@/locales/zh/nav.json";
import zhPages from "@/locales/zh/pages.json";
import zhRAltair from "@/locales/zh/r-altair.json";
import zhRDiscord from "@/locales/zh/r-discord.json";
import zhRForestExplorer from "@/locales/zh/r-forest-explorer.json";
import zhRKowloonKnockout from "@/locales/zh/r-kowloon-knockout.json";
import zhRRmhbox from "@/locales/zh/r-rmhbox.json";
import zhRRmhcode from "@/locales/zh/r-rmhcode.json";
import zhRSecret from "@/locales/zh/r-secret.json";
import zhRSliceIt from "@/locales/zh/r-slice-it.json";
import zhRStrategies from "@/locales/zh/r-strategies.json";
import zhRStudio from "@/locales/zh/r-studio.json";
import zhRideshare from "@/locales/zh/rideshare.json";
import zhShared from "@/locales/zh/shared.json";
import zhSite from "@/locales/zh/site.json";
import zhUserBuilds from "@/locales/zh/user-builds.json";
import zhV from "@/locales/zh/v.json";

const zhResources = {
  ".sources.admin": zhSourcesAdmin,
  ".sources.builds": zhSourcesBuilds,
  ".sources.c-admin": zhSourcesCAdmin,
  ".sources.c-altair": zhSourcesCAltair,
  ".sources.c-blog": zhSourcesCBlog,
  ".sources.c-builds": zhSourcesCBuilds,
  ".sources.c-cursed-logic": zhSourcesCCursedLogic,
  ".sources.c-daily-puzzles": zhSourcesCDailyPuzzles,
  ".sources.c-doctrine": zhSourcesCDoctrine,
  ".sources.c-dream-rift": zhSourcesCDreamRift,
  ".sources.c-economy": zhSourcesCEconomy,
  ".sources.c-forest-explorer": zhSourcesCForestExplorer,
  ".sources.c-game": zhSourcesCGame,
  ".sources.c-house-always-wins": zhSourcesCHouseAlwaysWins,
  ".sources.c-kowloon-knockout": zhSourcesCKowloonKnockout,
  ".sources.c-laundry-sort": zhSourcesCLaundrySort,
  ".sources.c-library": zhSourcesCLibrary,
  ".sources.c-lights-out": zhSourcesCLightsOut,
  ".sources.c-lockdown": zhSourcesCLockdown,
  ".sources.c-moderation": zhSourcesCModeration,
  ".sources.c-neon-driftway": zhSourcesCNeonDriftway,
  ".sources.c-news": zhSourcesCNews,
  ".sources.c-rideshare": zhSourcesCRideshare,
  ".sources.c-rmh-capital": zhSourcesCRmhCapital,
  ".sources.c-rmh-pmc": zhSourcesCRmhPmc,
  ".sources.c-rmhbox": zhSourcesCRmhbox,
  ".sources.c-rmhcode": zhSourcesCRmhcode,
  ".sources.c-rmhcoins": zhSourcesCRmhcoins,
  ".sources.c-rmhmusic": zhSourcesCRmhmusic,
  ".sources.c-rmhstudy": zhSourcesCRmhstudy,
  ".sources.c-rmhtech": zhSourcesCRmhtech,
  ".sources.c-rmhtube": zhSourcesCRmhtube,
  ".sources.c-rmhtype": zhSourcesCRmhtype,
  ".sources.c-rmhvibe": zhSourcesCRmhvibe,
  ".sources.c-roadmap": zhSourcesCRoadmap,
  ".sources.c-signal-forge": zhSourcesCSignalForge,
  ".sources.c-studio": zhSourcesCStudio,
  ".sources.c-synapse-storm": zhSourcesCSynapseStorm,
  ".sources.c-temple-of-joy": zhSourcesCTempleOfJoy,
  ".sources.c-ui": zhSourcesCUi,
  ".sources.c-user-builds": zhSourcesCUserBuilds,
  ".sources.c-vega": zhSourcesCVega,
  ".sources.c-versecraft": zhSourcesCVersecraft,
  ".sources.c-void-breaker": zhSourcesCVoidBreaker,
  ".sources.common": zhSourcesCommon,
  ".sources.feed": zhSourcesFeed,
  ".sources.groups": zhSourcesGroups,
  ".sources.library": zhSourcesLibrary,
  ".sources.nav": zhSourcesNav,
  ".sources.pages": zhSourcesPages,
  ".sources.r-altair": zhSourcesRAltair,
  ".sources.r-discord": zhSourcesRDiscord,
  ".sources.r-forest-explorer": zhSourcesRForestExplorer,
  ".sources.r-rmhbox": zhSourcesRRmhbox,
  ".sources.r-rmhcode": zhSourcesRRmhcode,
  ".sources.r-secret": zhSourcesRSecret,
  ".sources.r-slice-it": zhSourcesRSliceIt,
  ".sources.r-strategies": zhSourcesRStrategies,
  ".sources.r-studio": zhSourcesRStudio,
  ".sources.rideshare": zhSourcesRideshare,
  ".sources.shared": zhSourcesShared,
  ".sources.site": zhSourcesSite,
  ".sources.user-builds": zhSourcesUserBuilds,
  ".sources.v": zhSourcesV,
  "admin": zhAdmin,
  "builds": zhBuilds,
  "c-admin": zhCAdmin,
  "c-altair": zhCAltair,
  "c-blog": zhCBlog,
  "c-builds": zhCBuilds,
  "c-cursed-logic": zhCCursedLogic,
  "c-daily-puzzles": zhCDailyPuzzles,
  "c-doctrine": zhCDoctrine,
  "c-dream-rift": zhCDreamRift,
  "c-economy": zhCEconomy,
  "c-forest-explorer": zhCForestExplorer,
  "c-game": zhCGame,
  "c-house-always-wins": zhCHouseAlwaysWins,
  "c-kowloon-knockout": zhCKowloonKnockout,
  "c-laundry-sort": zhCLaundrySort,
  "c-library": zhCLibrary,
  "c-lights-out": zhCLightsOut,
  "c-lockdown": zhCLockdown,
  "c-moderation": zhCModeration,
  "c-neon-driftway": zhCNeonDriftway,
  "c-news": zhCNews,
  "c-rideshare": zhCRideshare,
  "c-rmh-capital": zhCRmhCapital,
  "c-rmh-pmc": zhCRmhPmc,
  "c-rmhbox": zhCRmhbox,
  "c-rmhcode": zhCRmhcode,
  "c-rmhcoins": zhCRmhcoins,
  "c-rmhmusic": zhCRmhmusic,
  "c-rmhstudy": zhCRmhstudy,
  "c-rmhtech": zhCRmhtech,
  "c-rmhtube": zhCRmhtube,
  "c-rmhtype": zhCRmhtype,
  "c-rmhvibe": zhCRmhvibe,
  "c-roadmap": zhCRoadmap,
  "c-signal-forge": zhCSignalForge,
  "c-studio": zhCStudio,
  "c-synapse-storm": zhCSynapseStorm,
  "c-temple-of-joy": zhCTempleOfJoy,
  "c-ui": zhCUi,
  "c-user-builds": zhCUserBuilds,
  "c-vega": zhCVega,
  "c-velum2099": zhCVelum2099,
  "c-versecraft": zhCVersecraft,
  "c-void-breaker": zhCVoidBreaker,
  "common": zhCommon,
  "feed": zhFeed,
  "groups": zhGroups,
  "library": zhLibrary,
  "nav": zhNav,
  "pages": zhPages,
  "r-altair": zhRAltair,
  "r-discord": zhRDiscord,
  "r-forest-explorer": zhRForestExplorer,
  "r-kowloon-knockout": zhRKowloonKnockout,
  "r-rmhbox": zhRRmhbox,
  "r-rmhcode": zhRRmhcode,
  "r-secret": zhRSecret,
  "r-slice-it": zhRSliceIt,
  "r-strategies": zhRStrategies,
  "r-studio": zhRStudio,
  "rideshare": zhRideshare,
  "shared": zhShared,
  "site": zhSite,
  "user-builds": zhUserBuilds,
  "v": zhV,
} as const;

export default zhResources;
