// AUTO-GENERATED by scripts/gen-i18n-resources.ts (do not edit by hand).
// Per-language i18n bundle for "tr". Only the namespaces translated for
// this locale are bundled; any other namespace falls back to English at runtime.
import trBuilds from "@/locales/tr/builds.json";
import trCommon from "@/locales/tr/common.json";
import trFeed from "@/locales/tr/feed.json";
import trGroups from "@/locales/tr/groups.json";
import trLibrary from "@/locales/tr/library.json";
import trNav from "@/locales/tr/nav.json";
import trPages from "@/locales/tr/pages.json";
import trRideshare from "@/locales/tr/rideshare.json";
import trShared from "@/locales/tr/shared.json";
import trSite from "@/locales/tr/site.json";
import trUserBuilds from "@/locales/tr/user-builds.json";
import trV from "@/locales/tr/v.json";

const trResources = {
  "builds": trBuilds,
  "common": trCommon,
  "feed": trFeed,
  "groups": trGroups,
  "library": trLibrary,
  "nav": trNav,
  "pages": trPages,
  "rideshare": trRideshare,
  "shared": trShared,
  "site": trSite,
  "user-builds": trUserBuilds,
  "v": trV,
} as const;

export default trResources;
