import { describe, it, expect } from 'vitest';
import {
  CURRENT_RELEASE,
  storageKeyFor,
  itemNumber,
  gridClassFor,
  type WhatsNewItemId,
} from '@/lib/whats-new';

describe('whats-new release', () => {
  it('announces between two and four items', () => {
    // The layout is built for that range; more silently stacks badly.
    expect(CURRENT_RELEASE.items.length).toBeGreaterThanOrEqual(2);
    expect(CURRENT_RELEASE.items.length).toBeLessThanOrEqual(4);
  });

  it('announces each item once', () => {
    const ids = [...CURRENT_RELEASE.items];
    expect(ids.length).toBe(new Set(ids).size);
  });

  it('has a version label and a non-empty id', () => {
    expect(CURRENT_RELEASE.id.length).toBeGreaterThan(0);
    expect(CURRENT_RELEASE.version.length).toBeGreaterThan(0);
  });

  it('derives the storage key from the release id', () => {
    // The bug this prevents: shipping a new announcement under the previous
    // release's key, so nobody who saw the last one ever sees this one. It
    // fails silently and in the direction you don't notice.
    expect(storageKeyFor(CURRENT_RELEASE)).toContain(CURRENT_RELEASE.id);
    expect(storageKeyFor({ ...CURRENT_RELEASE, id: 'other' })).not.toBe(
      storageKeyFor(CURRENT_RELEASE),
    );
  });

  it('numbers cards from 01', () => {
    expect(itemNumber(0)).toBe('01');
    expect(itemNumber(9)).toBe('10');
  });

  it('emits grid classes Tailwind can actually see', () => {
    // A computed `sm:grid-cols-${n}` is never generated by the scanner, so the
    // cards stack. Every returned class must be a literal in the source.
    for (const count of [2, 3, 4]) {
      const cls = gridClassFor(count);
      expect(cls).toContain('grid-cols-1');
      expect(cls).toMatch(/sm:grid-cols-\d/);
    }
    expect(gridClassFor(2)).not.toBe(gridClassFor(3));
  });
});

describe('whats-new copy', () => {
  it('covers every announced item', async () => {
    const mod = await import('@/components/feed/WhatsNewModal');
    const releaseCopy = (mod as unknown as { releaseCopy?: unknown }).releaseCopy;
    // Only asserted when the component exports it; the point of the check is
    // that an announced id without copy would render an empty card.
    if (typeof releaseCopy !== 'function') return;
    const identity = ((_k: string, o: { defaultValue: string }) => o.defaultValue) as never;
    const copy = (
      releaseCopy as (t: never) => Record<WhatsNewItemId, { title: string; copy: string }>
    )(identity);
    for (const id of CURRENT_RELEASE.items) {
      expect({ id, ok: Boolean(copy[id]?.title && copy[id]?.copy) }).toEqual({ id, ok: true });
    }
  });
});
