import { createCanvas, loadImage } from '@napi-rs/canvas';
import { readFileSync, writeFileSync } from 'node:fs';
import { setCanvasFactory } from '../lib/dream-rift/render/surface';
import { World } from '../lib/dream-rift/sim/world';
import { Renderer, type HudView } from '../lib/dream-rift/render/renderer';
import { DIFFICULTY, PLAYFIELD_W, PLAYFIELD_H, CHAR_STATS, FPS } from '../lib/dream-rift/constants';
import { STAGES } from '../lib/dream-rift/data/stages';
import { stageTheme } from '../lib/dream-rift/render/palette';
import type { BossState, PlayerShip, BulletColorName, LoadedSpriteAssets, PlayerId, InputFrame } from '../lib/dream-rift/types';
setCanvasFactory((w,h)=>{const c=createCanvas(w,h);return {canvas:c,ctx:c.getContext('2d')};});
const m = JSON.parse(readFileSync('public/dream-rift/manifest.json','utf8'));
const assets: LoadedSpriteAssets = { players:{}, bosses:{} };
for (const id of Object.keys(m.sprites.players)) assets.players[id as PlayerId] = { image: await loadImage('public'+m.sprites.players[id].url) as unknown as HTMLImageElement, def: m.sprites.players[id] };
for (const k of Object.keys(m.sprites.bosses)) assets.bosses[k] = { image: await loadImage('public'+m.sprites.bosses[k].url) as unknown as HTMLImageElement, def: m.sprites.bosses[k] };
const stageIdx=2; const cssW=414, cssH=896, dpr=2;
const world = new World(DIFFICULTY.normal, 1003); world.localSlot=0;
const p: PlayerShip = { slot:0,userId:'u',name:'Aoi',charId:'qln',present:true,joined:true,x:PLAYFIELD_W/2,y:PLAYFIELD_H-70,lives:3,bombs:2,power:96,graze:1284,score:4127360,pointItems:30,hitboxR:CHAR_STATS.qln.hitboxR,invuln:999,deathbombWindow:0,bombActive:0,dead:false,respawnTimer:0,focus:true,firing:true,shotCd:0,spellMeter:0,isLocal:true,renderX:PLAYFIELD_W/2,renderY:PLAYFIELD_H-70,moveDir:0,deaths:1,spellsCaptured:2,animTime:30 };
world.players=[p]; world.themeColors=stageTheme(stageIdx).bulletColors as BulletColorName[];
const d=STAGES[stageIdx].boss, c=d.cards[1];
world.spawnBoss({ active:true,x:PLAYFIELD_W/2,y:104,targetX:PLAYFIELD_W/2+30,targetY:110,hp:d.baseHp*c.hp*0.62,phaseMaxHp:d.baseHp*c.hp,phaseIndex:1,phaseStartFrame:0,timeLeftFrames:28*FPS,themeIndex:d.themeIndex,cards:d.cards,defeated:false,introFrames:0,moveTimer:200,fireTimer:0,subTimer:0,hitFlash:0,name:d.name } as BossState);
const canvas = createCanvas(cssW*dpr, cssH*dpr);
const r = new Renderer(canvas as unknown as HTMLCanvasElement, stageIdx);
r.setStage(stageIdx, d.themeIndex); r.setSpriteAssets(assets); r.setBossSheet(d.bossSprite); r.resize(cssW*dpr, cssH*dpr, dpr);
const input: InputFrame = { up:false,down:false,left:false,right:false,shot:true,bomb:false,focus:true };
for (let i=0;i<240;i++){ world.setLocalInput(0, input); world.step(true); }
const hud: HudView = { stageIndex:stageIdx,stageName:STAGES[stageIdx].name,bossActive:true,bossName:d.name,bossHp:d.baseHp*c.hp*0.62,bossMaxHp:d.baseHp*c.hp,bossCards:d.cards.length,bossCardIndex:1,spellName:c.name,spellTimeLeft:24,hiScore:12480990,coop:false };
r.render(world, hud, 0);
writeFileSync(process.argv[2] || '/tmp/stacked.png', (canvas as unknown as {toBuffer:(m:string)=>Buffer}).toBuffer('image/png'));
console.log('wrote stacked frame', cssW+'x'+cssH);
