/**
 * Regenerate lib/i18n/resources.<locale>.ts for one or more locales from the
 * JSON catalogs present under locales/<locale>/.
 *
 * Only real namespace files are bundled; dot-prefixed pipeline artifacts
 * (.sources.*.json) are skipped. A locale only needs the namespaces it has been
 * translated for — anything missing falls back to English at runtime — so this
 * imports exactly the files on disk and can be re-run as more get translated.
 *
 * Usage: pnpm exec tsx scripts/gen-i18n-resources.ts es fr de ...
 */
import { existsSync, readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { LOCALES, CORE_NAMESPACES } from "../lib/i18n/config.ts";

const ROOT = process.cwd();

// Namespaces bundled into the en *entry* chunk (resources.en-core.ts). The rest
// of en is code-split and backfilled on the client (see lib/i18n/instances.ts).
// CORE_NAMESPACES + c-ui (used by shared UI primitives on every route).
const EN_CORE_NAMESPACES = [...CORE_NAMESPACES, "c-ui"] as const;

/** "user-builds" -> "UserBuilds", "c-rmh-pmc" -> "CRmhPmc". */
function pascal(ns: string): string {
  return ns
    .split(/[-_.]/)
    .filter(Boolean)
    .map((p) => p[0].toUpperCase() + p.slice(1))
    .join("");
}

/**
 * Emit lib/i18n/resources.en-core.ts — only the core en namespaces, statically
 * imported so the entry ships them for first paint without the full catalog.
 */
function genEnCore(): void {
  const dir = join(ROOT, "locales", "en");
  const namespaces = EN_CORE_NAMESPACES.filter((ns) =>
    existsSync(join(dir, `${ns}.json`)),
  );
  const varName = (ns: string) => `en${pascal(ns)}`;
  const imports = namespaces
    .map((ns) => `import ${varName(ns)} from "@/locales/en/${ns}.json";`)
    .join("\n");
  const entries = namespaces
    .map((ns) => `  ${JSON.stringify(ns)}: ${varName(ns)},`)
    .join("\n");

  const content = `// AUTO-GENERATED by scripts/gen-i18n-resources.ts (do not edit by hand).
// Core English namespaces only — the namespaces any route may render (site
// chrome, nav, the feed, shared UI). Statically bundled into the client entry so
// first paint / hydration has the strings it needs WITHOUT shipping the full
// catalog on every page; the rest is backfilled from resources.en.ts on the
// client after init (see lib/i18n/instances.ts). Kept in sync with
// CORE_NAMESPACES in lib/i18n/config.ts (plus c-ui).
${imports}

const enCoreResources = {
${entries}
} as const;

export default enCoreResources;
`;

  writeFileSync(join(ROOT, "lib", "i18n", "resources.en-core.ts"), content);
}

function genLocale(locale: string): void {
  const dir = join(ROOT, "locales", locale);
  // A not-yet-translated locale has no directory: emit an empty bundle so the
  // build resolves its import and every key falls back to English at runtime.
  const namespaces = existsSync(dir)
    ? readdirSync(dir)
        .filter((f) => f.endsWith(".json") && !f.startsWith("."))
        .map((f) => f.slice(0, -".json".length))
        .sort()
    : [];

  const varName = (ns: string) => `${locale}${pascal(ns)}`;
  const imports = namespaces
    .map((ns) => `import ${varName(ns)} from "@/locales/${locale}/${ns}.json";`)
    .join("\n");
  const entries = namespaces
    .map((ns) => `  ${JSON.stringify(ns)}: ${varName(ns)},`)
    .join("\n");

  const content = `// AUTO-GENERATED by scripts/gen-i18n-resources.ts (do not edit by hand).
// Per-language i18n bundle for "${locale}". Only the namespaces translated for
// this locale are bundled; any other namespace falls back to English at runtime.
${imports}

const ${locale}Resources = {
${entries}
} as const;

export default ${locale}Resources;
`;

  writeFileSync(join(ROOT, "lib", "i18n", `resources.${locale}.ts`), content);
  console.log(`[i18n] wrote lib/i18n/resources.${locale}.ts (${namespaces.length} namespaces)`);
}

// Explicit args → just those locales. No args → regenerate every non-default
// locale (used by the deploy pipeline after a full translate run).
const args = process.argv.slice(2);
const targets = args.length > 0 ? args : LOCALES.filter((l) => l !== "en");
for (const locale of targets) genLocale(locale);
// The en core split is derived from the en catalog on disk; regenerate it
// whenever en is explicitly targeted so it can't drift from CORE_NAMESPACES.
if (targets.includes("en")) genEnCore();
