/**
 * Regenerate lib/i18n/resources.<locale>.ts for one or more locales from the
 * JSON catalogs present under locales/<locale>/.
 *
 * Only real namespace files are bundled; dot-prefixed pipeline artifacts
 * (.sources.*.json) are skipped. A locale only needs the namespaces it has been
 * translated for — anything missing falls back to English at runtime — so this
 * imports exactly the files on disk and can be re-run as more get translated.
 *
 * Usage: pnpm exec tsx scripts/gen-i18n-resources.ts es fr de ...
 */
import { readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = process.cwd();

/** "user-builds" -> "UserBuilds", "c-rmh-pmc" -> "CRmhPmc". */
function pascal(ns: string): string {
  return ns
    .split(/[-_.]/)
    .filter(Boolean)
    .map((p) => p[0].toUpperCase() + p.slice(1))
    .join("");
}

function genLocale(locale: string): void {
  const dir = join(ROOT, "locales", locale);
  const namespaces = readdirSync(dir)
    .filter((f) => f.endsWith(".json") && !f.startsWith("."))
    .map((f) => f.slice(0, -".json".length))
    .sort();

  const varName = (ns: string) => `${locale}${pascal(ns)}`;
  const imports = namespaces
    .map((ns) => `import ${varName(ns)} from "@/locales/${locale}/${ns}.json";`)
    .join("\n");
  const entries = namespaces
    .map((ns) => `  ${JSON.stringify(ns)}: ${varName(ns)},`)
    .join("\n");

  const content = `// AUTO-GENERATED by scripts/gen-i18n-resources.ts (do not edit by hand).
// Per-language i18n bundle for "${locale}". Only the namespaces translated for
// this locale are bundled; any other namespace falls back to English at runtime.
${imports}

const ${locale}Resources = {
${entries}
} as const;

export default ${locale}Resources;
`;

  writeFileSync(join(ROOT, "lib", "i18n", `resources.${locale}.ts`), content);
  console.log(`[i18n] wrote lib/i18n/resources.${locale}.ts (${namespaces.length} namespaces)`);
}

const locales = process.argv.slice(2);
if (locales.length === 0) {
  console.error("usage: pnpm exec tsx scripts/gen-i18n-resources.ts <locale>...");
  process.exit(1);
}
for (const locale of locales) genLocale(locale);
