#!/bin/bash
# ─────────────────────────────────────────────────────────────────────────────
# materialize-env.sh — build .env.<environment> from git-managed sources.
#
#   .env.<environment>  =  deploy/config/public[.<env>].env   (plaintext, git)
#                       +  deploy/secrets/<env>.enc.env        (SOPS-decrypted)
#
# This is the ONE integration point between the secret-management system and the
# deploy pipeline. Both deploy.sh (Compose) and deploy/deploy-k8s.sh consume
# .env.<environment> via `--env-file` / `--from-env-file`, so producing that
# file here means neither deploy script needs to change its env handling.
#
# Idempotent + deterministic: same inputs → byte-identical output, so deploy.sh's
# env-file fingerprint (change detection) only moves when a value actually moves.
#
# Requires: sops, and a decryption key. Provide the age key via either
#   SOPS_AGE_KEY_FILE=/path/to/key.txt   (recommended on the VPS)
# or SOPS_AGE_KEY="AGE-SECRET-KEY-..."   (e.g. injected from a secret store/CI).
#
# Usage:  scripts/materialize-env.sh <production|staging>
# Safe-by-default: if no encrypted file exists for the environment, this is a
# no-op and any pre-existing hand-maintained .env.<environment> is left intact
# (eases migration off the legacy "edit .env.production on the box" flow).
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

ENVIRONMENT="${1:?usage: materialize-env.sh <production|staging>}"
REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_DIR"

ENC_FILE="deploy/secrets/${ENVIRONMENT}.enc.env"
OUT_FILE=".env.${ENVIRONMENT}"
# Per-env public override (deploy/config/public.production.env) wins over the
# shared default if present.
PUBLIC_FILE="deploy/config/public.${ENVIRONMENT}.env"
[ -f "$PUBLIC_FILE" ] || PUBLIC_FILE="deploy/config/public.env"

log() { echo "[materialize-env] $*"; }

if [ ! -f "$ENC_FILE" ]; then
    log "no $ENC_FILE — skipping (using existing $OUT_FILE if present)."
    exit 0
fi

if ! command -v sops >/dev/null 2>&1; then
    echo "[materialize-env] FATAL: sops not installed but $ENC_FILE exists." >&2
    echo "  Install sops (https://github.com/getsops/sops) or remove $ENC_FILE." >&2
    exit 1
fi

if [ -z "${SOPS_AGE_KEY_FILE:-}" ] && [ -z "${SOPS_AGE_KEY:-}" ]; then
    echo "[materialize-env] FATAL: no age key available to decrypt $ENC_FILE." >&2
    echo "  Set SOPS_AGE_KEY_FILE=/path/to/key.txt (see deploy/SECRETS.md)." >&2
    exit 1
fi

TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT
umask 077   # secrets land in $OUT_FILE — keep it 0600

{
    echo "# ─────────────────────────────────────────────────────────────────"
    echo "# GENERATED by scripts/materialize-env.sh — DO NOT EDIT BY HAND."
    echo "# Public config: $PUBLIC_FILE   Secrets: $ENC_FILE (SOPS)"
    echo "# To change a value, edit the source and redeploy. See deploy/SECRETS.md."
    echo "# ─────────────────────────────────────────────────────────────────"
    if [ -f "$PUBLIC_FILE" ]; then
        echo "# --- public (plaintext) ---"
        cat "$PUBLIC_FILE"
    fi
    echo "# --- secrets (decrypted from SOPS) ---"
    # --output-type dotenv strips SOPS metadata; comments in the source are
    # emitted as #ENC-decoded comments — harmless in an env-file.
    sops --decrypt --output-type dotenv "$ENC_FILE"
} > "$TMP"

# Atomic swap so a half-written file is never read by a concurrent deploy.
mv "$TMP" "$OUT_FILE"
trap - EXIT
chmod 600 "$OUT_FILE"
log "wrote $OUT_FILE ($(grep -cvE '^\s*(#|$)' "$OUT_FILE") keys)."
