// GENERATED by scripts/gen-image-variants.ts — do not edit by hand.
// Run `pnpm images:variants` (or `pnpm build`) to regenerate;
// `pnpm images:variants:check` fails when this file is out of date.
//
// Maps a public image path to the content hash of its master and the widths
// generated under /images/_variants/. Every width exists in BOTH avif and webp;
// `variantUrl(src, width, format)` picks one. Callers emit a srcSet only for paths
// listed here, so an image with no entry is served exactly as it was before —
// which is why adding art without regenerating this file silently costs the
// optimization rather than breaking the page, and why the commit gate checks it.

export type ImageVariant = { readonly hash: string; readonly widths: readonly number[] };

export const IMAGE_VARIANTS: Readonly<Record<string, ImageVariant>> = {
  "/images/activities/lightsout.png": { hash: '4eda188b', widths: [320, 640, 960] },
  "/images/deeplink/agents-rl-1.jpg": { hash: '487028b2', widths: [320, 640] },
  "/images/deeplink/agents-rl-2.jpg": { hash: 'c81c096c', widths: [320, 640] },
  "/images/deeplink/agents-rl.jpg": { hash: '840cb968', widths: [320, 640] },
  "/images/deeplink/ai-for-science-1.jpg": { hash: '1d0128a3', widths: [320, 640] },
  "/images/deeplink/ai-for-science-2.jpg": { hash: '9265427d', widths: [320, 640] },
  "/images/deeplink/ai-for-science.jpg": { hash: 'c952a2b6', widths: [320, 640] },
  "/images/deeplink/alignment-1.jpg": { hash: '5ce3a152', widths: [320, 640] },
  "/images/deeplink/alignment-2.jpg": { hash: '5162a929', widths: [320, 640] },
  "/images/deeplink/alignment.jpg": { hash: '5676080d', widths: [320, 640] },
  "/images/deeplink/energy-climate-1.jpg": { hash: 'c499c47b', widths: [320, 640, 960] },
  "/images/deeplink/energy-climate-2.jpg": { hash: '65caf4a0', widths: [320, 640, 960] },
  "/images/deeplink/energy-climate.jpg": { hash: '2e69e5e6', widths: [320, 640] },
  "/images/deeplink/foundation-models-1.jpg": { hash: 'b4410e91', widths: [320, 640, 960] },
  "/images/deeplink/foundation-models-2.jpg": { hash: 'e8893d21', widths: [320, 640] },
  "/images/deeplink/foundation-models.jpg": { hash: '579561de', widths: [320, 640] },
  "/images/deeplink/frontier-safety-1.jpg": { hash: '0972582d', widths: [320, 640] },
  "/images/deeplink/frontier-safety-2.jpg": { hash: '1ae581c5', widths: [320, 640] },
  "/images/deeplink/frontier-safety.jpg": { hash: '90644415', widths: [320, 640] },
  "/images/deeplink/hero.jpg": { hash: '853e4452', widths: [320, 640] },
  "/images/deeplink/life-sciences-1.jpg": { hash: 'c0a09c0c', widths: [320, 640] },
  "/images/deeplink/life-sciences-2.jpg": { hash: '33aeabf2', widths: [320, 640] },
  "/images/deeplink/life-sciences.jpg": { hash: '67edf599', widths: [320, 640] },
  "/images/deeplink/mathematics-1.jpg": { hash: 'b05728e0', widths: [320, 640] },
  "/images/deeplink/mathematics-2.jpg": { hash: 'e7a08b64', widths: [320, 640] },
  "/images/deeplink/mathematics.jpg": { hash: '4609c222', widths: [320, 640] },
  "/images/deeplink/safety-alignment-1.jpg": { hash: '0d1a836b', widths: [320, 640] },
  "/images/deeplink/safety-alignment-2.jpg": { hash: 'ee5b3716', widths: [320, 640] },
  "/images/deeplink/safety-alignment.jpg": { hash: 'de681764', widths: [320, 640] },
  "/images/games/Kowloon-Knockout.webp": { hash: 'a122d9c1', widths: [320, 640] },
  "/images/games/altair.webp": { hash: '3c807ffa', widths: [320, 640] },
  "/images/games/cookgame.webp": { hash: 'c01c1a9c', widths: [320, 640] },
  "/images/games/cursed_logic.webp": { hash: 'f306e533', widths: [320, 640] },
  "/images/games/daily_puzzles.webp": { hash: '6da4a03b', widths: [320, 640] },
  "/images/games/dream-rift.webp": { hash: '75206d02', widths: [320, 640] },
  "/images/games/echoes_of_the_spire.webp": { hash: '93a88c35', widths: [320, 640] },
  "/images/games/forest_explorer.webp": { hash: 'de45727a', widths: [320, 640] },
  "/images/games/house_always_wins.webp": { hash: '24cae729', widths: [320, 640] },
  "/images/games/laundry_sort.webp": { hash: '2d06f63b', widths: [320, 640] },
  "/images/games/lights_out.webp": { hash: 'b74f007d', widths: [320, 640] },
  "/images/games/massive-march.webp": { hash: '3edc3f9f', widths: [320, 640] },
  "/images/games/neon_driftway.webp": { hash: 'da6c83ff', widths: [320, 640] },
  "/images/games/nightrail.webp": { hash: '0b78c19b', widths: [320, 640, 960] },
  "/images/games/project_vega.webp": { hash: '7503976e', widths: [320, 640] },
  "/images/games/rmh-farming-sim.webp": { hash: '77473c49', widths: [320, 640] },
  "/images/games/rmhbox.webp": { hash: '7d6b4a10', widths: [320] },
  "/images/games/rmhcode.webp": { hash: '74da2b35', widths: [320, 640] },
  "/images/games/rmhconnections.webp": { hash: '382fde50', widths: [320, 640] },
  "/images/games/rmhdle.webp": { hash: '5b0e4c15', widths: [320, 640] },
  "/images/games/rmhmusic.webp": { hash: '17f02970', widths: [320, 640] },
  "/images/games/rmhstrategies.webp": { hash: '17913189', widths: [320, 640] },
  "/images/games/rmhstudio.webp": { hash: 'b1d4973b', widths: [320, 640] },
  "/images/games/rmhstudy.webp": { hash: '805df622', widths: [320, 640] },
  "/images/games/rmhtube.webp": { hash: '0c84c5f4', widths: [320, 640] },
  "/images/games/rmhtype.webp": { hash: '593562e1', widths: [320, 640] },
  "/images/games/rochester-offensive.webp": { hash: 'e3dd0970', widths: [320, 640] },
  "/images/games/satans_library.webp": { hash: '18d03217', widths: [320, 640] },
  "/images/games/signal_forge.webp": { hash: 'dfe28d91', widths: [320, 640] },
  "/images/games/slice_it.webp": { hash: 'e39fb5b2', widths: [320, 640] },
  "/images/games/synapsestorm.webp": { hash: 'f07d37e8', widths: [320, 640] },
  "/images/games/temple_of_joy.webp": { hash: 'f0ceb416', widths: [320, 640] },
  "/images/games/velum2099.webp": { hash: 'a439dbe1', widths: [320, 640] },
  "/images/games/versecraft.webp": { hash: 'ebdcbba6', widths: [320, 640] },
  "/images/games/voidbreaker.webp": { hash: 'd3dfbe57', widths: [320, 640] },
  "/images/merch-mug.jpg": { hash: '96167d86', widths: [320, 640, 960] },
  "/images/merch-stickers.jpg": { hash: '2cae6ca9', widths: [320, 640, 960] },
  "/images/merch-tee.jpg": { hash: 'ef0d99f7', widths: [320, 640, 960] },
  "/images/screenshots/feed-wide.png": { hash: '92ee7dcb', widths: [320, 640, 960] },
  "/images/screenshots/games-narrow.png": { hash: 'bc390b5c', widths: [320, 640] },
};

/**
 * The variant URL for a source path and width. Returns null when the image has
 * no generated variants, so callers fall back to the original src.
 */
export function variantUrl(src: string, width: number, format: 'webp' | 'avif' = 'webp'): string | null {
  const entry = IMAGE_VARIANTS[src];
  if (!entry) return null;
  const stem = src.replace(/^\/images\//, '').replace(/\.[^.]+$/, '');
  return `/images/_variants/${stem}-${entry.hash}-${width}.${format}`;
}
