// ============================================================
// BREAKPOINT — Zustand store (menu, agent pick, mode, match config)
// The networked lobby lives in net/room.ts (RoomClient). This store
// holds local UI state and the resolved MatchConfig handed to the engine.
// ============================================================
import { create } from 'zustand';
import type { GamePhase, Team, MatchMode, NetMode } from './types';
import { AGENTS } from './agents';

const BOT_NAMES = [
  'gracepenguinator', 'Asao', 'drooooooo', 'gamecube', 'Kimmy', 'grape1617',
  'PizzaWaffleVT', 'Mahmoud', 'Andrew', 'shivam', 'NomNomFan', 'Empress', 'zzz', 'icy',
  'OchoCinco', 'BinkyTV', 'Lurk', 'Sage', 'kotato', 'wobble',
];

export interface ConfigHuman {
  id: string;
  name: string;
  agentId: string;
  team: Team;
  isLocal: boolean;
}

export interface MatchConfig {
  mode: MatchMode;
  netMode: NetMode;
  localId: string;
  localAgentId: string;
  localTeam: Team;
  botDifficulty: number;
  /** All human players (local + remote). Bots/zombies are generated by the engine. */
  humans: ConfigHuman[];
  /** standard: fill each side up to this with bots (solo/host). */
  fillToPerSide: number;
}

function randomName(): string {
  return BOT_NAMES[Math.floor(Math.random() * BOT_NAMES.length)] + Math.floor(Math.random() * 90 + 10);
}

interface BreakpointStore {
  phase: GamePhase;
  setPhase: (p: GamePhase) => void;

  selectedAgent: string;
  setSelectedAgent: (id: string) => void;

  playerName: string;
  setPlayerName: (n: string) => void;

  mode: MatchMode;
  setMode: (m: MatchMode) => void;

  /** Where AgentSelect's "lock in" returns to. */
  agentReturn: GamePhase;
  setAgentReturn: (p: GamePhase) => void;

  botDifficulty: number;
  setBotDifficulty: (d: number) => void;

  matchConfig: MatchConfig | null;
  setMatchConfig: (c: MatchConfig) => void;
  /** Build a solo (vs-bots) config for the chosen mode. */
  buildPracticeConfig: (mode: MatchMode) => MatchConfig;

  lastWinner: Team | null;
  lastScore: { att: number; def: number };
  lastMode: MatchMode;
  lastWave: number;
  setResult: (winner: Team | null, att: number, def: number, mode: MatchMode, wave: number) => void;

  reset: () => void;
}

export const useBreakpointStore = create<BreakpointStore>((set, get) => ({
  phase: 'menu',
  setPhase: (p) => set({ phase: p }),

  selectedAgent: AGENTS[0].id,
  setSelectedAgent: (id) => set({ selectedAgent: id }),

  playerName: randomName(),
  setPlayerName: (n) => set({ playerName: n.slice(0, 18) }),

  mode: 'standard',
  setMode: (m) => set({ mode: m }),

  agentReturn: 'menu',
  setAgentReturn: (p) => set({ agentReturn: p }),

  botDifficulty: 0.6,
  setBotDifficulty: (d) => set({ botDifficulty: Math.max(0, Math.min(1, d)) }),

  matchConfig: null,
  setMatchConfig: (c) => set({ matchConfig: c }),

  buildPracticeConfig: (mode) => {
    const s = get();
    const localTeam: Team = 'attackers';
    const config: MatchConfig = {
      mode,
      netMode: 'solo',
      localId: 'local',
      localAgentId: s.selectedAgent,
      localTeam,
      botDifficulty: s.botDifficulty,
      humans: [{ id: 'local', name: s.playerName || 'You', agentId: s.selectedAgent, team: localTeam, isLocal: true }],
      fillToPerSide: 5,
    };
    set({ matchConfig: config });
    return config;
  },

  lastWinner: null,
  lastScore: { att: 0, def: 0 },
  lastMode: 'standard',
  lastWave: 0,
  setResult: (winner, att, def, mode, wave) => set({ lastWinner: winner, lastScore: { att, def }, lastMode: mode, lastWave: wave }),

  reset: () => set({ phase: 'menu' }),
}));

export { BOT_NAMES };
