/**
 * Canvas-conversion route manifest — one entry per PAGE route file
 * (API routes and pathless layout files are exempt; layouts dissolve into
 * shell scenes as waves progress).
 *
 * Rules enforced by testing/canvas/route-conversion-guard.test.ts:
 *   - every page route file under app/routes/ must appear here (adding a
 *     route without registering it fails CI);
 *   - an entry with converted: true must render via CanvasPage and must not
 *     import banned DOM-era modules;
 *   - the overhaul merge gate requires converted: true for every entry.
 *
 * overlayAllow lists the data-overlay-allow kinds the route may render
 * (Playwright census allowlist) — omit for pure-canvas routes.
 */

export interface RouteManifestEntry {
  /** Route file path relative to app/routes/. */
  file: string;
  /** True once the route renders through CanvasPage (scene + mirror). */
  converted: boolean;
  /** Allowed overlay kinds (iframes, layered GL canvases) for the census. */
  overlayAllow?: string[];
}

export const ROUTE_MANIFEST: RouteManifestEntry[] = [
  { file: "_site/achievements.tsx", converted: false },
  { file: "_site/admin/albums/$id.tsx", converted: false },
  { file: "_site/admin/albums/index.tsx", converted: false },
  { file: "_site/admin/analytics.tsx", converted: false },
  { file: "_site/admin/announcements.tsx", converted: false },
  { file: "_site/admin/audit.tsx", converted: false },
  { file: "_site/admin/blog/$slug/edit.tsx", converted: false },
  { file: "_site/admin/blog/index.tsx", converted: false },
  { file: "_site/admin/blog/new.tsx", converted: false },
  { file: "_site/admin/index.tsx", converted: false },
  { file: "_site/admin/library-quota.tsx", converted: false },
  { file: "_site/admin/library-storage.tsx", converted: false },
  { file: "_site/admin/predictions.tsx", converted: false },
  { file: "_site/admin/reports.tsx", converted: false },
  { file: "_site/admin/rideshare.tsx", converted: false },
  { file: "_site/admin/security-reports.tsx", converted: false },
  { file: "_site/admin/user-builds.tsx", converted: false },
  { file: "_site/admin/users.tsx", converted: false },
  { file: "_site/blog/index.tsx", converted: true },
  { file: "_site/bookmarks.tsx", converted: false },
  { file: "_site/builds/index.tsx", converted: true },
  { file: "_site/c.$slug.tsx", converted: false },
  { file: "_site/communities.tsx", converted: false },
  { file: "_site/create/index.tsx", converted: false },
  { file: "_site/developer/docs/$page.tsx", converted: false },
  { file: "_site/developer/docs/index.tsx", converted: false },
  { file: "_site/developer/index.tsx", converted: false },
  { file: "_site/drafts.tsx", converted: false },
  { file: "_site/explore.tsx", converted: false },
  { file: "_site/groups/$id.tsx", converted: false },
  { file: "_site/groups/index.tsx", converted: false },
  { file: "_site/homes/index.tsx", converted: false },
  { file: "_site/homes/listing.$id.tsx", converted: false },
  { file: "_site/homes/manage.tsx", converted: false },
  { file: "_site/homes/saved.tsx", converted: false },
  { file: "_site/homes/submit.tsx", converted: false },
  { file: "_site/homes/watches.tsx", converted: false },
  { file: "_site/index.tsx", converted: false },
  { file: "_site/library/index.tsx", converted: false },
  { file: "_site/messages/$conversationId.tsx", converted: false },
  { file: "_site/messages/index.tsx", converted: false },
  { file: "_site/music-trivia.tsx", converted: false },
  { file: "_site/news/index.tsx", converted: false },
  { file: "_site/notifications.tsx", converted: false },
  { file: "_site/personas/$id.tsx", converted: false },
  { file: "_site/personas/index.tsx", converted: true },
  { file: "_site/predictions.tsx", converted: false },
  { file: "_site/pricing.tsx", converted: false },
  { file: "_site/profile/$id.tsx", converted: false },
  { file: "_site/progress.tsx", converted: false },
  { file: "_site/quotes.tsx", converted: true },
  { file: "_site/ranked.tsx", converted: false },
  { file: "_site/recap.tsx", converted: false },
  { file: "_site/rideshare/drive.tsx", converted: false },
  { file: "_site/rideshare/index.tsx", converted: false },
  { file: "_site/rideshare/ride.tsx", converted: false },
  { file: "_site/roadmap.tsx", converted: true },
  { file: "_site/search.tsx", converted: false },
  { file: "_site/settings/index.tsx", converted: false },
  { file: "_site/settings/privacy.tsx", converted: false },
  { file: "_site/settings/security.tsx", converted: false },
  { file: "_site/share.tsx", converted: false },
  { file: "_site/shop.tsx", converted: false },
  { file: "_site/store/$userid.tsx", converted: false },
  { file: "_site/store/index.tsx", converted: false },
  { file: "_site/study/$deckId.tsx", converted: false },
  { file: "_site/study/index.tsx", converted: false },
  { file: "_site/tag.$tag.tsx", converted: false },
  { file: "_site/u/$userid/index.tsx", converted: false },
  { file: "_site/u/$userid/post/$postid.tsx", converted: false },
  { file: "_site/user-builds/index.tsx", converted: true },
  { file: "_site/user-builds/manage.tsx", converted: false },
  { file: "_site/user-builds/submit.tsx", converted: false },
  { file: "_site/v/index.tsx", converted: true },
  { file: "_site/wallet.tsx", converted: true },
  { file: "_site/wrapped.tsx", converted: false },
  { file: "adaptive-intelligence.tsx", converted: false },
  { file: "altair.tsx", converted: false },
  { file: "altair/index.tsx", converted: false },
  { file: "altair/multiplayer.tsx", converted: true },
  { file: "altair/multiplayer/$lobbyId.tsx", converted: false },
  { file: "altair/multiplayer/index.tsx", converted: false },
  { file: "blog.$slug.tsx", converted: false },
  { file: "builds_.$slug.tsx", converted: false },
  { file: "cookgame.tsx", converted: false },
  { file: "cookies.tsx", converted: true },
  { file: "copyright.tsx", converted: true },
  { file: "daily.tsx", converted: false },
  { file: "daily/alibi.tsx", converted: false },
  { file: "daily/chainlink.tsx", converted: false },
  { file: "daily/impostor.tsx", converted: false },
  { file: "daily/index.tsx", converted: false },
  { file: "daily/lights-out.tsx", converted: false },
  { file: "daily/outcast.tsx", converted: false },
  { file: "daily/spectrum.tsx", converted: false },
  { file: "discord/lights-out.tsx", converted: false },
  { file: "discord/rmhbox.tsx", converted: false },
  { file: "dream-rift.tsx", converted: false },
  { file: "embed.post.$id.tsx", converted: false },
  { file: "forest-explorer.tsx", converted: true },
  { file: "forest-explorer/explore.tsx", converted: false },
  { file: "forest-explorer/index.tsx", converted: false },
  { file: "forest-explorer/story.tsx", converted: false },
  { file: "house-always-wins.tsx", converted: false },
  { file: "kowloon-knockout.tsx", converted: false },
  { file: "kowloon-knockout/index.tsx", converted: false },
  { file: "laundry-sort.tsx", converted: false },
  { file: "library.$slug.tsx", converted: false },
  { file: "library.albums.$albumId.tsx", converted: false },
  { file: "lights-out.tsx", converted: true },
  { file: "login.tsx", converted: false },
  { file: "neon-driftway.tsx", converted: false },
  { file: "news.$slug.tsx", converted: false },
  { file: "offline.tsx", converted: true },
  { file: "optimization.tsx", converted: false },
  { file: "privacy.tsx", converted: true },
  { file: "ref.$code.tsx", converted: false },
  { file: "rmh-capital.tsx", converted: false },
  { file: "rmh-capital/businesses.tsx", converted: false },
  { file: "rmh-capital/careers.tsx", converted: false },
  { file: "rmh-capital/contact.tsx", converted: false },
  { file: "rmh-capital/firm.tsx", converted: false },
  { file: "rmh-capital/index.tsx", converted: false },
  { file: "rmh-capital/insights.tsx", converted: false },
  { file: "rmh-farming-sim.tsx", converted: false },
  { file: "rmh-farming-sim/index.tsx", converted: false },
  { file: "rmh-pmc.tsx", converted: false },
  { file: "rmh-pmc/capabilities.tsx", converted: false },
  { file: "rmh-pmc/command.tsx", converted: false },
  { file: "rmh-pmc/contact.tsx", converted: false },
  { file: "rmh-pmc/index.tsx", converted: false },
  { file: "rmh-pmc/intelligence.tsx", converted: false },
  { file: "rmh-pmc/operators.tsx", converted: false },
  { file: "rmhbox.tsx", converted: false },
  { file: "rmhbox/$lobbyId.tsx", converted: false },
  { file: "rmhbox/index.tsx", converted: false },
  { file: "rmhbox/minigames/$minigameId/history.tsx", converted: false },
  { file: "rmhbox/minigames/index.tsx", converted: false },
  { file: "rmhcode.tsx", converted: true },
  { file: "rmhcode/auth.tsx", converted: false },
  { file: "rmhcode/index.tsx", converted: false },
  { file: "rmhladder.tsx", converted: false },
  { file: "rmhladder/alerts.tsx", converted: false },
  { file: "rmhladder/companies.tsx", converted: false },
  { file: "rmhladder/health.tsx", converted: false },
  { file: "rmhladder/index.tsx", converted: false },
  { file: "rmhladder/jobs.tsx", converted: false },
  { file: "rmhladder/pipeline.tsx", converted: false },
  { file: "rmhladder/review.tsx", converted: false },
  { file: "rmhladder/settings.tsx", converted: false },
  { file: "rmhmusic.tsx", converted: true },
  { file: "rmhmusic/$roomId.tsx", converted: false },
  { file: "rmhmusic/index.tsx", converted: false },
  { file: "rmhmusic/player.tsx", converted: false },
  { file: "rmhstudy.tsx", converted: false },
  { file: "rmhstudy/$roomId.tsx", converted: false },
  { file: "rmhstudy/index.tsx", converted: false },
  { file: "rmhtube.tsx", converted: false },
  { file: "rmhtube/$roomId.tsx", converted: false },
  { file: "rmhtube/index.tsx", converted: false },
  { file: "rmhtype.tsx", converted: false },
  { file: "rmhtype/$roomId.tsx", converted: false },
  { file: "rmhtype/index.tsx", converted: false },
  { file: "rmhtype/multiplayer.tsx", converted: false },
  { file: "rmhtype/solo.tsx", converted: false },
  { file: "rochester-offensive.tsx", converted: false },
  { file: "secret.tsx", converted: false },
  { file: "secret/cursed-logic.tsx", converted: true },
  { file: "secret/cursed-logic/index.tsx", converted: false },
  { file: "secret/index.tsx", converted: false },
  { file: "secret/signal-forge.tsx", converted: false },
  { file: "secret/vega.tsx", converted: false },
  { file: "security.tsx", converted: false },
  { file: "slice-it.tsx", converted: false },
  { file: "slice-it/index.tsx", converted: false },
  { file: "strategies.tsx", converted: false },
  { file: "strategies/incidents.tsx", converted: false },
  { file: "strategies/index.tsx", converted: false },
  { file: "strategies/profile/index.tsx", converted: false },
  { file: "strategies/profile/reputation.tsx", converted: true },
  { file: "strategies/profile/settings.tsx", converted: false },
  { file: "strategies/puzzles/$mode.tsx", converted: false },
  { file: "strategies/puzzles/archive.tsx", converted: true },
  { file: "strategies/puzzles/index.tsx", converted: false },
  { file: "strategies/puzzles/leaderboard.tsx", converted: false },
  { file: "strategies/safehouse/drops.tsx", converted: false },
  { file: "strategies/safehouse/index.tsx", converted: false },
  { file: "strategies/safehouse/recruit.tsx", converted: false },
  { file: "strategies/sahur.tsx", converted: false },
  { file: "studio.tsx", converted: true },
  { file: "studio/index.tsx", converted: false },
  { file: "synapse-storm.tsx", converted: false },
  { file: "temple-of-joy.tsx", converted: false },
  { file: "temple-of-joy/index.tsx", converted: false },
  { file: "terms.tsx", converted: true },
  { file: "user-builds.$slug.tsx", converted: false },
  { file: "v.$slug.tsx", converted: false },
  { file: "v.new.tsx", converted: false },
  { file: "velum2099.tsx", converted: false },
  { file: "versecraft.tsx", converted: false },
  { file: "versecraft/index.tsx", converted: false },
  { file: "void-breaker.tsx", converted: false },
];

export const CONVERTED_COUNT = ROUTE_MANIFEST.filter((r) => r.converted).length;
export const TOTAL_COUNT = ROUTE_MANIFEST.length;
