/**
 * RMHbox — Minigame Registry
 *
 * Maps minigame IDs to their metadata definitions.
 * Used for voting candidate selection, lobby validation,
 * and client-side game loading.
 *
 * Reference: docs/rmhbox/design-spec/core.md §20 (MinigameDefinition)
 */

import type { MinigameDefinition } from './types';

// ─── Registry ────────────────────────────────────────────────────

export const MINIGAME_REGISTRY: Record<string, MinigameDefinition> = {
  'rhyme-time': {
    id: 'rhyme-time',
    displayName: 'Rhyme Time',
    description: 'Chain rhyming words before the timer runs out.',
    category: 'word',
    icon: '🎤',
    minPlayers: 2,
    maxPlayers: 10,
    estimatedDurationSeconds: 120,
    supportsTeams: false,
    instructionDurationSeconds: 15,
    preloadAssets: { images: [], sounds: [], data: [], estimatedSizeBytes: 0 },
    joinInProgressPolicy: 'spectate_only',
    tags: ['word', 'fast-paced'],
  },
  'undercover-agent': {
    id: 'undercover-agent',
    displayName: 'Undercover Agent',
    description: 'A word-guessing team game inspired by Codenames.',
    category: 'word',
    icon: '🕵️',
    minPlayers: 4,
    maxPlayers: 16,
    estimatedDurationSeconds: 300,
    supportsTeams: true,
    instructionDurationSeconds: 20,
    preloadAssets: { images: [], sounds: [], data: [], estimatedSizeBytes: 0 },
    joinInProgressPolicy: 'spectate_only',
    tags: ['word', 'teams', 'strategy'],
  },
  'category-crash': {
    id: 'category-crash',
    displayName: 'Category Crash',
    description: 'Name items in a category before time runs out — duplicates crash!',
    category: 'word',
    icon: '💥',
    minPlayers: 3,
    maxPlayers: 12,
    estimatedDurationSeconds: 150,
    supportsTeams: false,
    instructionDurationSeconds: 15,
    preloadAssets: { images: [], sounds: [], data: [], estimatedSizeBytes: 0 },
    joinInProgressPolicy: 'join_next_subround',
    tags: ['word', 'categories'],
  },
  'wiki-race': {
    id: 'wiki-race',
    displayName: 'Wiki Race',
    description: 'Navigate Wikipedia from one article to another as fast as possible.',
    category: 'trivia',
    icon: '📚',
    minPlayers: 2,
    maxPlayers: 10,
    estimatedDurationSeconds: 193,
    supportsTeams: false,
    instructionDurationSeconds: 15,
    preloadAssets: { images: [], sounds: [], data: [], estimatedSizeBytes: 0 },
    joinInProgressPolicy: 'spectate_only',
    tags: ['trivia', 'race'],
  },
  'fact-or-friction': {
    id: 'fact-or-friction',
    displayName: 'Fact or Friction',
    description: 'Distinguish real facts from convincing fakes.',
    category: 'trivia',
    icon: '🤔',
    minPlayers: 2,
    maxPlayers: 16,
    estimatedDurationSeconds: 120,
    supportsTeams: false,
    instructionDurationSeconds: 15,
    preloadAssets: { images: [], sounds: [], data: [], estimatedSizeBytes: 0 },
    joinInProgressPolicy: 'join_next_subround',
    tags: ['trivia', 'bluffing'],
  },
  'undercover-editor': {
    id: 'undercover-editor',
    displayName: 'Undercover Editor',
    description: 'Collaboratively write a story — but one editor is sabotaging it.',
    category: 'creative',
    icon: '✏️',
    minPlayers: 4,
    maxPlayers: 10,
    estimatedDurationSeconds: 240,
    supportsTeams: false,
    instructionDurationSeconds: 20,
    preloadAssets: { images: [], sounds: [], data: [], estimatedSizeBytes: 0 },
    joinInProgressPolicy: 'spectate_only',
    tags: ['creative', 'deduction'],
  },
  'minimalist-masterpiece': {
    id: 'minimalist-masterpiece',
    displayName: 'Minimalist Masterpiece',
    description: 'Draw with limited strokes — the audience bids on your art.',
    category: 'creative',
    icon: '🎨',
    minPlayers: 3,
    maxPlayers: 12,
    estimatedDurationSeconds: 150,
    supportsTeams: false,
    instructionDurationSeconds: 15,
    preloadAssets: { images: [], sounds: [], data: [], estimatedSizeBytes: 0 },
    joinInProgressPolicy: 'spectate_only',
    tags: ['creative', 'drawing', 'auction'],
  },
  'emoji-cinema': {
    id: 'emoji-cinema',
    displayName: 'Emoji Cinema',
    description: 'Describe movies using only emojis — others guess the title.',
    category: 'word',
    icon: '🎬',
    minPlayers: 3,
    maxPlayers: 12,
    estimatedDurationSeconds: 180,
    supportsTeams: false,
    instructionDurationSeconds: 15,
    preloadAssets: { images: [], sounds: [], data: [], estimatedSizeBytes: 0 },
    joinInProgressPolicy: 'join_next_subround',
    tags: ['word', 'emoji', 'movies'],
  },
  'sequence-sam': {
    id: 'sequence-sam',
    displayName: 'Sequence Sam',
    description: 'Memorize and replicate increasingly complex sequences.',
    category: 'action',
    icon: '🧠',
    minPlayers: 2,
    maxPlayers: 10,
    estimatedDurationSeconds: 120,
    supportsTeams: false,
    instructionDurationSeconds: 15,
    preloadAssets: { images: [], sounds: [], data: [], estimatedSizeBytes: 0 },
    joinInProgressPolicy: 'spectate_only',
    tags: ['action', 'memory'],
  },
  'human-keyboard': {
    id: 'human-keyboard',
    displayName: 'Human Keyboard',
    description: 'Each player controls one key — type words together cooperatively.',
    category: 'action',
    icon: '⌨️',
    minPlayers: 3,
    maxPlayers: 10,
    estimatedDurationSeconds: 120,
    supportsTeams: true,
    instructionDurationSeconds: 15,
    preloadAssets: { images: [], sounds: [], data: [], estimatedSizeBytes: 0 },
    joinInProgressPolicy: 'spectate_only',
    tags: ['action', 'cooperative'],
  },
  'cursor-curling': {
    id: 'cursor-curling',
    displayName: 'Cursor Curling',
    description: 'Slide your cursor stone closest to the target on a digital rink.',
    category: 'action',
    icon: '🥌',
    minPlayers: 2,
    maxPlayers: 8,
    estimatedDurationSeconds: 150,
    supportsTeams: false,
    instructionDurationSeconds: 15,
    preloadAssets: { images: [], sounds: [], data: [], estimatedSizeBytes: 0 },
    joinInProgressPolicy: 'spectate_only',
    tags: ['action', 'physics'],
  },
  'human-tetris': {
    id: 'human-tetris',
    displayName: 'Human Tetris',
    description: 'Cooperatively fit your team through approaching wall shapes.',
    category: 'action',
    icon: '🧱',
    minPlayers: 4,
    maxPlayers: 10,
    estimatedDurationSeconds: 120,
    supportsTeams: true,
    instructionDurationSeconds: 15,
    preloadAssets: { images: [], sounds: [], data: [], estimatedSizeBytes: 0 },
    joinInProgressPolicy: 'spectate_only',
    tags: ['action', 'cooperative'],
  },
  'identity-crisis': {
    id: 'identity-crisis',
    displayName: 'Identity Crisis',
    description: 'Figure out who you are by asking yes/no questions.',
    category: 'word',
    icon: '🎭',
    minPlayers: 3,
    maxPlayers: 10,
    estimatedDurationSeconds: 180,
    supportsTeams: false,
    instructionDurationSeconds: 15,
    preloadAssets: { images: [], sounds: [], data: [], estimatedSizeBytes: 0 },
    joinInProgressPolicy: 'spectate_only',
    tags: ['word', 'deduction'],
  },
  'ranking-file': {
    id: 'ranking-file',
    displayName: 'Ranking File',
    description: 'Rank items in the correct order — closest to the official ranking wins.',
    category: 'trivia',
    icon: '📊',
    minPlayers: 3,
    maxPlayers: 12,
    estimatedDurationSeconds: 120,
    supportsTeams: false,
    instructionDurationSeconds: 15,
    preloadAssets: { images: [], sounds: [], data: [], estimatedSizeBytes: 0 },
    joinInProgressPolicy: 'join_next_subround',
    tags: ['trivia', 'ranking'],
  },
  'pixel-pushers': {
    id: 'pixel-pushers',
    displayName: 'Pixel Pushers',
    description: 'Cooperatively push pixels to match a target pattern using physics.',
    category: 'action',
    icon: '👾',
    minPlayers: 2,
    maxPlayers: 8,
    estimatedDurationSeconds: 120,
    supportsTeams: true,
    instructionDurationSeconds: 15,
    preloadAssets: { images: [], sounds: [], data: [], estimatedSizeBytes: 0 },
    joinInProgressPolicy: 'join_immediately',
    tags: ['action', 'cooperative', 'physics'],
  },
  'scroll-soul': {
    id: 'scroll-soul',
    displayName: 'Scroll Soul',
    description: 'Survive a fast-scrolling obstacle course — last one standing wins.',
    category: 'action',
    icon: '📜',
    minPlayers: 2,
    maxPlayers: 16,
    estimatedDurationSeconds: 90,
    supportsTeams: false,
    instructionDurationSeconds: 15,
    preloadAssets: { images: [], sounds: [], data: [], estimatedSizeBytes: 0 },
    joinInProgressPolicy: 'spectate_only',
    tags: ['action', 'survival'],
  },
};

// ─── Helper ──────────────────────────────────────────────────────

/**
 * Returns all minigames eligible for the given player count.
 * Filters by minPlayers <= playerCount <= maxPlayers.
 */
export function getEligibleMinigames(playerCount: number): MinigameDefinition[] {
  return Object.values(MINIGAME_REGISTRY).filter(
    (game) => playerCount >= game.minPlayers && playerCount <= game.maxPlayers,
  );
}
