export interface JobSeedEntry {
    title: string;
    company: string;
    description: string;
    type: 'real' | 'silly';
    location: string;
    salaryRange: string | null;
}

export const jobSeedData: JobSeedEntry[] = [
    // ── Realistic Corporate Roles ──
    {
        title: 'Senior Software Engineer',
        company: 'Nexora Systems',
        description: 'Design and implement scalable microservices for our cloud-native platform. You will lead code reviews, mentor junior engineers, and drive architectural decisions across the backend team. Experience with distributed systems and event-driven architectures is essential.',
        type: 'real',
        location: 'Remote',
        salaryRange: '$145k - $190k',
    },
    {
        title: 'Frontend Developer',
        company: 'PixelCraft Studios',
        description: 'Build responsive, accessible web applications using React and TypeScript. Collaborate with designers to translate Figma mockups into pixel-perfect UI components. You will own the design system and component library.',
        type: 'real',
        location: 'Hybrid',
        salaryRange: '$110k - $145k',
    },
    {
        title: 'DevOps Engineer',
        company: 'CloudScale Inc.',
        description: 'Manage CI/CD pipelines, Kubernetes clusters, and infrastructure-as-code across AWS and GCP. Implement monitoring, alerting, and incident response procedures. On-call rotation required.',
        type: 'real',
        location: 'Remote',
        salaryRange: '$135k - $175k',
    },
    {
        title: 'Product Manager',
        company: 'Veritas Analytics',
        description: 'Own the product roadmap for our B2B analytics platform. Conduct user research, define requirements, and prioritize features based on business impact. Work closely with engineering, design, and sales teams.',
        type: 'real',
        location: 'On-site',
        salaryRange: '$130k - $170k',
    },
    {
        title: 'Data Scientist',
        company: 'Cognify Labs',
        description: 'Develop machine learning models to improve recommendation accuracy and user engagement. Design A/B experiments, analyze results, and present findings to stakeholders. PhD preferred but not required.',
        type: 'real',
        location: 'Hybrid',
        salaryRange: '$140k - $185k',
    },
    {
        title: 'Backend Engineer',
        company: 'Streamline Technologies',
        description: 'Build RESTful APIs and real-time data pipelines using Go and PostgreSQL. Optimize query performance and ensure five-nines uptime for our payment processing system.',
        type: 'real',
        location: 'Remote',
        salaryRange: '$130k - $170k',
    },
    {
        title: 'UX Designer',
        company: 'HumanFirst Design Co.',
        description: 'Create intuitive user experiences for healthcare technology products. Conduct usability testing, build wireframes and prototypes, and maintain a consistent design language across platforms.',
        type: 'real',
        location: 'On-site',
        salaryRange: '$100k - $135k',
    },
    {
        title: 'Security Engineer',
        company: 'IronVault Cyber',
        description: 'Perform penetration testing, vulnerability assessments, and security audits for enterprise clients. Develop automated security scanning tools and respond to security incidents.',
        type: 'real',
        location: 'Remote',
        salaryRange: '$150k - $200k',
    },
    {
        title: 'Mobile Developer (iOS)',
        company: 'AppForge Solutions',
        description: 'Build and maintain native iOS applications using Swift and SwiftUI. Implement Core Data persistence, push notifications, and App Store submission pipelines.',
        type: 'real',
        location: 'Hybrid',
        salaryRange: '$120k - $160k',
    },
    {
        title: 'Machine Learning Engineer',
        company: 'DeepNova AI',
        description: 'Train and deploy large language models for code generation and document understanding. Optimize inference pipelines for production-scale workloads using PyTorch and CUDA.',
        type: 'real',
        location: 'Remote',
        salaryRange: '$170k - $230k',
    },
    {
        title: 'QA Automation Engineer',
        company: 'TestPilot Corp.',
        description: 'Design and implement automated test suites using Playwright and Jest. Build CI integration for regression testing and maintain test coverage metrics above 90%.',
        type: 'real',
        location: 'Remote',
        salaryRange: '$95k - $130k',
    },
    {
        title: 'Database Administrator',
        company: 'DataVault Systems',
        description: 'Manage PostgreSQL and Redis clusters at scale. Optimize query plans, implement backup strategies, and ensure compliance with SOC2 data retention policies.',
        type: 'real',
        location: 'On-site',
        salaryRange: '$110k - $150k',
    },
    {
        title: 'Technical Writer',
        company: 'DocuStream Inc.',
        description: 'Write clear, concise API documentation, tutorials, and migration guides for a developer platform. Collaborate with engineers to maintain docs-as-code pipelines.',
        type: 'real',
        location: 'Remote',
        salaryRange: '$80k - $110k',
    },
    {
        title: 'Platform Engineer',
        company: 'Infrascape Labs',
        description: 'Build internal developer tools and self-service platforms. Design Terraform modules, Helm charts, and golden paths that enable product teams to ship faster.',
        type: 'real',
        location: 'Remote',
        salaryRange: '$140k - $180k',
    },
    {
        title: 'Engineering Manager',
        company: 'Horizons Technology Group',
        description: 'Lead a team of 8-12 engineers delivering core platform features. Run sprint ceremonies, conduct performance reviews, and remove blockers. Previous IC experience required.',
        type: 'real',
        location: 'Hybrid',
        salaryRange: '$170k - $220k',
    },
    {
        title: 'Full Stack Developer',
        company: 'BuildRight Software',
        description: 'Develop features end-to-end using Next.js, Node.js, and PostgreSQL. Work in a fast-paced startup environment with direct impact on product direction.',
        type: 'real',
        location: 'Remote',
        salaryRange: '$115k - $155k',
    },
    {
        title: 'Site Reliability Engineer',
        company: 'UptimeForce',
        description: 'Ensure 99.99% availability for mission-critical financial services infrastructure. Build self-healing systems, runbooks, and chaos engineering experiments.',
        type: 'real',
        location: 'Remote',
        salaryRange: '$155k - $200k',
    },
    {
        title: 'Solutions Architect',
        company: 'Meridian Consulting',
        description: 'Design cloud architectures for Fortune 500 clients migrating to AWS. Create technical proposals, conduct architecture reviews, and present to C-suite stakeholders.',
        type: 'real',
        location: 'Hybrid',
        salaryRange: '$160k - $210k',
    },
    {
        title: 'Embedded Systems Engineer',
        company: 'NanoTech Robotics',
        description: 'Program firmware for IoT sensors and robotic actuators using C and Rust. Debug hardware-software interfaces and optimize for ultra-low power consumption.',
        type: 'real',
        location: 'On-site',
        salaryRange: '$120k - $160k',
    },
    {
        title: 'Data Engineer',
        company: 'PipelineWorks',
        description: 'Build and maintain ETL pipelines processing 10TB+ daily using Apache Spark and Airflow. Design data warehouse schemas and ensure data quality through automated validation.',
        type: 'real',
        location: 'Remote',
        salaryRange: '$130k - $170k',
    },
    {
        title: 'Blockchain Developer',
        company: 'ChainLink Dynamics',
        description: 'Build smart contracts on Ethereum and Solana. Implement DeFi protocols, audit contract security, and optimize gas usage. Solidity and Rust experience required.',
        type: 'real',
        location: 'Remote',
        salaryRange: '$140k - $200k',
    },
    {
        title: 'IT Support Specialist',
        company: 'Greenfield Enterprises',
        description: 'Provide Tier 2 technical support for 500+ employees. Manage Active Directory, troubleshoot VPN issues, and maintain hardware inventory across three office locations.',
        type: 'real',
        location: 'On-site',
        salaryRange: '$55k - $75k',
    },
    {
        title: 'Game Developer (Unity)',
        company: 'Starfall Interactive',
        description: 'Develop gameplay systems for a multiplayer action RPG using Unity and C#. Implement networked combat, inventory systems, and procedural level generation.',
        type: 'real',
        location: 'Hybrid',
        salaryRange: '$100k - $140k',
    },
    {
        title: 'Cloud Solutions Engineer',
        company: 'Cumulus Technologies',
        description: 'Help customers adopt multi-cloud strategies across AWS, Azure, and GCP. Build proof-of-concepts, conduct workshops, and troubleshoot complex networking issues.',
        type: 'real',
        location: 'Remote',
        salaryRange: '$125k - $165k',
    },
    {
        title: 'Compiler Engineer',
        company: 'SyntaxTree Labs',
        description: 'Work on a production compiler toolchain targeting WebAssembly. Implement optimization passes, type checking, and code generation using Rust.',
        type: 'real',
        location: 'Remote',
        salaryRange: '$160k - $220k',
    },
    {
        title: 'Technical Program Manager',
        company: 'Orbital Systems',
        description: 'Coordinate cross-functional programs spanning 5+ engineering teams. Track dependencies, manage risk, and communicate status to VP-level leadership.',
        type: 'real',
        location: 'Hybrid',
        salaryRange: '$140k - $180k',
    },
    {
        title: 'UI Engineer',
        company: 'Palette Digital',
        description: 'Build animation-rich interfaces using React, Framer Motion, and CSS. Implement complex interaction patterns for a design tool used by millions.',
        type: 'real',
        location: 'Remote',
        salaryRange: '$120k - $165k',
    },
    {
        title: 'Infrastructure Engineer',
        company: 'TerraNode Cloud',
        description: 'Operate bare-metal Kubernetes clusters across three data centers. Automate provisioning with Ansible and manage network fabrics using BGP.',
        type: 'real',
        location: 'On-site',
        salaryRange: '$135k - $175k',
    },
    {
        title: 'API Developer',
        company: 'Endpoint Labs',
        description: 'Design and implement GraphQL and REST APIs for a fintech platform. Handle OAuth 2.0 flows, rate limiting, and webhook delivery at scale.',
        type: 'real',
        location: 'Remote',
        salaryRange: '$115k - $155k',
    },
    {
        title: 'Release Engineer',
        company: 'ShipIt Technologies',
        description: 'Own the release process for a SaaS product deployed to 15 regions. Build blue-green deployment pipelines and feature flag management systems.',
        type: 'real',
        location: 'Remote',
        salaryRange: '$110k - $145k',
    },
    {
        title: 'AI Research Scientist',
        company: 'Cerebral Dynamics',
        description: 'Publish research on multimodal foundation models. Design novel architectures for vision-language tasks and contribute to open-source model releases.',
        type: 'real',
        location: 'Hybrid',
        salaryRange: '$180k - $260k',
    },
    {
        title: 'Revenue Operations Analyst',
        company: 'ScaleUp Partners',
        description: 'Build Salesforce dashboards, automate lead scoring, and analyze pipeline metrics. Partner with sales leadership to optimize the go-to-market motion.',
        type: 'real',
        location: 'Remote',
        salaryRange: '$85k - $115k',
    },
    {
        title: 'Network Engineer',
        company: 'Fiber Optics Corp.',
        description: 'Design and maintain enterprise WAN and LAN infrastructure. Configure Cisco and Juniper equipment, implement SD-WAN, and manage firewall rules.',
        type: 'real',
        location: 'On-site',
        salaryRange: '$100k - $140k',
    },
    {
        title: 'Staff Software Engineer',
        company: 'Apex Fintech',
        description: 'Set technical direction for the payments team. Design systems processing $2B+ in annual transaction volume with sub-100ms latency requirements.',
        type: 'real',
        location: 'Remote',
        salaryRange: '$200k - $280k',
    },
    {
        title: 'Growth Engineer',
        company: 'VelocityLoop',
        description: 'Build experimentation infrastructure for A/B testing at scale. Implement tracking pixels, attribution models, and funnel analytics dashboards.',
        type: 'real',
        location: 'Remote',
        salaryRange: '$120k - $160k',
    },
    {
        title: 'Developer Advocate',
        company: 'OpenCore Labs',
        description: 'Create tutorials, conference talks, and sample applications to grow developer adoption. Gather community feedback and represent the developer voice internally.',
        type: 'real',
        location: 'Remote',
        salaryRange: '$110k - $150k',
    },
    {
        title: 'Accessibility Engineer',
        company: 'IncluTech',
        description: 'Audit web applications for WCAG 2.2 compliance. Build automated accessibility testing tools and train engineering teams on inclusive design practices.',
        type: 'real',
        location: 'Remote',
        salaryRange: '$105k - $140k',
    },
    {
        title: 'Computer Vision Engineer',
        company: 'SightLine AI',
        description: 'Develop real-time object detection models for autonomous vehicle systems. Optimize inference for edge deployment on NVIDIA Jetson hardware.',
        type: 'real',
        location: 'On-site',
        salaryRange: '$150k - $200k',
    },
    {
        title: 'Principal Engineer',
        company: 'Atlas Software Group',
        description: 'Drive the technical vision for the entire engineering organization. Evaluate build vs. buy decisions, define coding standards, and resolve cross-team architectural conflicts.',
        type: 'real',
        location: 'Hybrid',
        salaryRange: '$220k - $300k',
    },
    {
        title: 'Technical Recruiter',
        company: 'TalentPipe Inc.',
        description: 'Source and recruit senior engineers across frontend, backend, and ML roles. Manage the full recruitment lifecycle from outreach to offer negotiation.',
        type: 'real',
        location: 'Remote',
        salaryRange: '$75k - $110k',
    },
    {
        title: 'Scrum Master',
        company: 'AgileWave Consulting',
        description: 'Facilitate agile ceremonies for three cross-functional squads. Coach teams on Scrum practices, remove impediments, and track velocity metrics.',
        type: 'real',
        location: 'Hybrid',
        salaryRange: '$90k - $120k',
    },
    {
        title: 'Audio Engineer',
        company: 'SoundForge Media',
        description: 'Mix and master audio for podcasts and video content. Manage recording studio equipment and implement automated post-production workflows.',
        type: 'real',
        location: 'On-site',
        salaryRange: '$65k - $90k',
    },
    {
        title: 'Systems Programmer',
        company: 'KernelSpace Technologies',
        description: 'Develop OS-level components including device drivers and memory management subsystems. Deep knowledge of Linux kernel internals and C required.',
        type: 'real',
        location: 'On-site',
        salaryRange: '$140k - $190k',
    },
    {
        title: 'Marketing Analyst',
        company: 'BrightSignal Marketing',
        description: 'Analyze campaign performance across paid and organic channels. Build attribution models, forecast CAC, and present insights to the CMO.',
        type: 'real',
        location: 'Remote',
        salaryRange: '$70k - $95k',
    },
    {
        title: 'Supply Chain Data Analyst',
        company: 'LogiPrime Global',
        description: 'Model demand forecasting for a global logistics network. Build dashboards in Looker and automate reporting for warehouse operations.',
        type: 'real',
        location: 'Hybrid',
        salaryRange: '$80k - $110k',
    },
    {
        title: 'Technical Support Engineer',
        company: 'SaaS Solutions Ltd.',
        description: 'Troubleshoot complex customer issues involving API integrations, SSO configurations, and data migration. Escalate bugs to engineering with detailed reproduction steps.',
        type: 'real',
        location: 'Remote',
        salaryRange: '$70k - $95k',
    },
    {
        title: 'Graphics Programmer',
        company: 'RenderWorks Studio',
        description: 'Implement real-time rendering features including PBR shading, volumetric lighting, and particle systems. Optimize GPU performance using Vulkan.',
        type: 'real',
        location: 'On-site',
        salaryRange: '$130k - $180k',
    },
    {
        title: 'Compliance Engineer',
        company: 'RegTech Partners',
        description: 'Implement SOC 2 and GDPR compliance controls across cloud infrastructure. Automate evidence collection and maintain security documentation.',
        type: 'real',
        location: 'Remote',
        salaryRange: '$115k - $150k',
    },
    {
        title: 'Performance Engineer',
        company: 'LatencyZero',
        description: 'Profile and optimize high-frequency trading systems for sub-microsecond latency. Tune JVM garbage collection, kernel bypass networking, and lock-free data structures.',
        type: 'real',
        location: 'On-site',
        salaryRange: '$180k - $250k',
    },
    {
        title: 'Junior Web Developer',
        company: 'LaunchPad Digital',
        description: 'Build and maintain WordPress and Shopify sites for small business clients. Learn modern web development practices under senior developer mentorship.',
        type: 'real',
        location: 'On-site',
        salaryRange: '$50k - $70k',
    },
    {
        title: 'Robotics Software Engineer',
        company: 'AutoBot Industries',
        description: 'Program autonomous warehouse robots using ROS2 and Python. Implement SLAM algorithms, path planning, and obstacle avoidance for fleet coordination.',
        type: 'real',
        location: 'On-site',
        salaryRange: '$130k - $175k',
    },
    {
        title: 'Business Intelligence Developer',
        company: 'InsightPeak Analytics',
        description: 'Design star schema data models and build executive dashboards in Tableau. Write complex SQL queries and maintain dbt transformation pipelines.',
        type: 'real',
        location: 'Hybrid',
        salaryRange: '$95k - $130k',
    },
    {
        title: 'iOS Architect',
        company: 'MobileFirst Labs',
        description: 'Define the architecture for a banking app used by 5M+ users. Establish patterns for offline-first data sync, secure enclave integration, and modular feature delivery.',
        type: 'real',
        location: 'Hybrid',
        salaryRange: '$170k - $220k',
    },
    {
        title: 'Content Designer',
        company: 'ClearVoice UX',
        description: 'Write microcopy for web and mobile interfaces. Define voice and tone guidelines, conduct content audits, and A/B test messaging strategies.',
        type: 'real',
        location: 'Remote',
        salaryRange: '$85k - $115k',
    },
    {
        title: 'Firmware Engineer',
        company: 'ChipWorks Semiconductor',
        description: 'Develop low-level firmware for custom ASIC chips. Write bare-metal C, manage bootloaders, and interface with hardware design teams on register specifications.',
        type: 'real',
        location: 'On-site',
        salaryRange: '$125k - $170k',
    },
    {
        title: 'Privacy Engineer',
        company: 'DataShield Corp.',
        description: 'Implement differential privacy mechanisms for user analytics. Build consent management systems and automated data deletion pipelines for CCPA/GDPR compliance.',
        type: 'real',
        location: 'Remote',
        salaryRange: '$140k - $185k',
    },
    {
        title: 'Distributed Systems Engineer',
        company: 'Quorum Technologies',
        description: 'Build consensus algorithms and replicated state machines for a distributed database. Implement Raft-based leader election and conflict-free replicated data types.',
        type: 'real',
        location: 'Remote',
        salaryRange: '$165k - $225k',
    },
    {
        title: 'Customer Success Manager',
        company: 'Retently SaaS',
        description: 'Manage a portfolio of 50+ enterprise accounts. Drive adoption, reduce churn, and identify upsell opportunities through quarterly business reviews.',
        type: 'real',
        location: 'Remote',
        salaryRange: '$80k - $110k',
    },
    {
        title: 'Hardware Design Engineer',
        company: 'CircuitBreaker Labs',
        description: 'Design PCB layouts for consumer electronics. Run signal integrity simulations, manage BOM costs, and coordinate with contract manufacturers in Shenzhen.',
        type: 'real',
        location: 'On-site',
        salaryRange: '$110k - $155k',
    },
    {
        title: 'Localization Engineer',
        company: 'GlobalSpeak Technologies',
        description: 'Build and maintain i18n infrastructure for a SaaS product supporting 40+ languages. Automate translation workflows and handle right-to-left layout challenges.',
        type: 'real',
        location: 'Remote',
        salaryRange: '$95k - $130k',
    },
    {
        title: 'TypeScript SDK Developer',
        company: 'APIFirst Inc.',
        description: 'Build and maintain the official TypeScript SDK for a developer platform. Design ergonomic APIs, write comprehensive documentation, and publish to npm.',
        type: 'real',
        location: 'Remote',
        salaryRange: '$120k - $160k',
    },
    {
        title: 'Observability Engineer',
        company: 'TracePoint Systems',
        description: 'Build distributed tracing and metrics collection infrastructure using OpenTelemetry. Design Grafana dashboards and set up intelligent alerting with PagerDuty integration.',
        type: 'real',
        location: 'Remote',
        salaryRange: '$135k - $175k',
    },
    {
        title: 'Chief Technology Officer',
        company: 'Fledgling Startup (Stealth)',
        description: 'Define the technical vision for an early-stage startup. Hire the founding engineering team, choose the tech stack, and build the MVP. Equity-heavy compensation.',
        type: 'real',
        location: 'Hybrid',
        salaryRange: '$150k - $200k + equity',
    },
    {
        title: 'Salesforce Developer',
        company: 'CRMWorks',
        description: 'Build custom Salesforce applications using Apex and Lightning Web Components. Integrate with external systems via REST APIs and manage deployment pipelines.',
        type: 'real',
        location: 'Remote',
        salaryRange: '$100k - $140k',
    },
    {
        title: 'Search Engineer',
        company: 'FinderScope',
        description: 'Optimize Elasticsearch clusters serving 100M+ queries per day. Implement custom scoring functions, synonym handling, and real-time index updates.',
        type: 'real',
        location: 'Remote',
        salaryRange: '$140k - $185k',
    },
    {
        title: 'Game Economy Designer',
        company: 'Virtual Worlds Inc.',
        description: 'Balance in-game currency, item pricing, and reward loops for a live-service MMO. Build simulation models to predict player behavior and monetization impact.',
        type: 'real',
        location: 'Hybrid',
        salaryRange: '$90k - $130k',
    },
    {
        title: 'Rust Systems Developer',
        company: 'OxideTech',
        description: 'Build high-performance systems software in Rust. Implement memory-safe parsers, async I/O frameworks, and zero-copy serialization libraries.',
        type: 'real',
        location: 'Remote',
        salaryRange: '$150k - $200k',
    },
    {
        title: 'Healthcare Software Engineer',
        company: 'MediBridge Health',
        description: 'Develop HIPAA-compliant telehealth platforms. Implement HL7 FHIR integrations, secure video conferencing, and electronic health record interoperability.',
        type: 'real',
        location: 'Hybrid',
        salaryRange: '$125k - $165k',
    },
    {
        title: 'Real-time Communications Engineer',
        company: 'StreamSync Labs',
        description: 'Build WebRTC-based video and audio infrastructure. Implement SFU/MCU topologies, jitter buffers, and adaptive bitrate streaming for millions of concurrent users.',
        type: 'real',
        location: 'Remote',
        salaryRange: '$145k - $195k',
    },
    {
        title: 'Technical Account Manager',
        company: 'EnterpriseEdge',
        description: 'Serve as the primary technical liaison for key enterprise accounts. Lead integration projects, troubleshoot escalations, and drive platform adoption.',
        type: 'real',
        location: 'Remote',
        salaryRange: '$100k - $140k',
    },
    {
        title: 'Android Developer',
        company: 'MobileCraft Solutions',
        description: 'Build native Android applications using Kotlin and Jetpack Compose. Implement offline-first architecture with Room database and WorkManager for background sync.',
        type: 'real',
        location: 'Hybrid',
        salaryRange: '$115k - $155k',
    },
    {
        title: 'Information Security Analyst',
        company: 'CyberShield Defense',
        description: 'Monitor SIEM alerts, investigate security incidents, and perform threat hunting across enterprise networks. Maintain incident response playbooks and conduct tabletop exercises.',
        type: 'real',
        location: 'On-site',
        salaryRange: '$95k - $135k',
    },
    {
        title: 'DevTools Engineer',
        company: 'InnerLoop Inc.',
        description: 'Build IDE extensions, CLI tools, and local development environments that improve developer productivity. Measure developer experience metrics and iterate based on feedback.',
        type: 'real',
        location: 'Remote',
        salaryRange: '$130k - $175k',
    },
    {
        title: 'Edge Computing Engineer',
        company: 'PerimeterAI',
        description: 'Deploy ML inference models to edge devices using TensorRT and ONNX Runtime. Manage over-the-air firmware updates and monitor fleet health across 10,000+ devices.',
        type: 'real',
        location: 'Hybrid',
        salaryRange: '$135k - $180k',
    },
    {
        title: 'VP of Engineering',
        company: 'RapidGrowth Inc.',
        description: 'Lead 50+ engineers across four teams. Define hiring plans, establish engineering culture, and partner with the CEO on technical strategy and investor communications.',
        type: 'real',
        location: 'Hybrid',
        salaryRange: '$250k - $350k',
    },
    {
        title: 'Simulation Engineer',
        company: 'PhysicsWorks',
        description: 'Develop physics simulations for structural engineering analysis. Implement finite element methods, mesh generation, and parallel solvers using C++ and MPI.',
        type: 'real',
        location: 'On-site',
        salaryRange: '$120k - $165k',
    },
    {
        title: 'Technical Curriculum Developer',
        company: 'CodeAcademy Pro',
        description: 'Design programming courses for intermediate developers. Write interactive coding exercises, record video tutorials, and maintain course content as technologies evolve.',
        type: 'real',
        location: 'Remote',
        salaryRange: '$85k - $115k',
    },
    {
        title: 'Climate Tech Engineer',
        company: 'GreenGrid Energy',
        description: 'Build software for smart grid optimization and renewable energy management. Model battery storage systems and develop demand-response algorithms.',
        type: 'real',
        location: 'Hybrid',
        salaryRange: '$120k - $165k',
    },
    {
        title: 'SaaS Integration Developer',
        company: 'ConnectHub',
        description: 'Build and maintain integrations with Slack, Jira, GitHub, and 30+ other platforms. Design webhook infrastructure and implement OAuth flows for third-party services.',
        type: 'real',
        location: 'Remote',
        salaryRange: '$105k - $140k',
    },
    {
        title: 'Natural Language Processing Engineer',
        company: 'LinguaAI',
        description: 'Fine-tune transformer models for named entity recognition and sentiment analysis. Build training data pipelines and evaluate model performance across 12 languages.',
        type: 'real',
        location: 'Remote',
        salaryRange: '$145k - $195k',
    },
    {
        title: 'ERP Consultant',
        company: 'SAPwise Consulting',
        description: 'Configure and customize SAP S/4HANA for manufacturing clients. Lead discovery workshops, document business processes, and manage data migration cutover.',
        type: 'real',
        location: 'On-site',
        salaryRange: '$100k - $145k',
    },
    {
        title: 'Video Streaming Engineer',
        company: 'BufferFree Media',
        description: 'Build adaptive bitrate streaming infrastructure supporting 4K HDR content. Implement DRM, CDN origin shielding, and real-time quality-of-experience monitoring.',
        type: 'real',
        location: 'Remote',
        salaryRange: '$140k - $185k',
    },
    {
        title: 'Bioinformatics Engineer',
        company: 'GenomeLogic',
        description: 'Build pipelines for whole-genome sequencing analysis. Implement variant calling workflows using Nextflow and manage petabyte-scale genomics data on AWS.',
        type: 'real',
        location: 'Hybrid',
        salaryRange: '$120k - $165k',
    },
    {
        title: 'Payments Engineer',
        company: 'TransactPro',
        description: 'Integrate with Stripe, Adyen, and ACH networks. Implement PCI-DSS compliant payment flows, retry logic for failed transactions, and reconciliation systems.',
        type: 'real',
        location: 'Remote',
        salaryRange: '$130k - $175k',
    },
    {
        title: 'Design Systems Engineer',
        company: 'ComponentCraft',
        description: 'Build and maintain a React component library used by 20+ product teams. Define tokens, implement theming, and ensure accessibility across all components.',
        type: 'real',
        location: 'Remote',
        salaryRange: '$125k - $170k',
    },
    {
        title: 'Digital Forensics Analyst',
        company: 'ByteTrace Security',
        description: 'Conduct forensic investigations of compromised systems. Analyze disk images, memory dumps, and network captures to determine attack vectors and data exfiltration.',
        type: 'real',
        location: 'On-site',
        salaryRange: '$105k - $145k',
    },
    {
        title: 'AR/VR Developer',
        company: 'ImmersaLabs',
        description: 'Build mixed reality experiences using Unity and the Meta Quest SDK. Implement hand tracking, spatial audio, and multiplayer networking for VR training applications.',
        type: 'real',
        location: 'Hybrid',
        salaryRange: '$120k - $165k',
    },
    {
        title: 'FinTech Compliance Developer',
        company: 'RegulatorySoft',
        description: 'Implement KYC/AML screening workflows and transaction monitoring rules. Build audit trail systems and automate regulatory reporting for banking clients.',
        type: 'real',
        location: 'Remote',
        salaryRange: '$115k - $155k',
    },
    {
        title: 'Chaos Engineer',
        company: 'FailSafe Labs',
        description: 'Design and execute controlled failure experiments across production systems. Build game days, develop failure injection tools, and improve system resilience.',
        type: 'real',
        location: 'Remote',
        salaryRange: '$140k - $185k',
    },
    {
        title: 'Technical Editor',
        company: 'PragPub Media',
        description: 'Review and edit technical books on programming, cloud, and DevOps. Work with authors to improve clarity, accuracy, and code sample quality.',
        type: 'real',
        location: 'Remote',
        salaryRange: '$70k - $100k',
    },
    {
        title: 'Smart Contract Auditor',
        company: 'BlockShield Security',
        description: 'Audit Solidity and Rust smart contracts for vulnerabilities. Produce detailed security reports, recommend fixes, and verify remediations for DeFi protocols.',
        type: 'real',
        location: 'Remote',
        salaryRange: '$150k - $220k',
    },
    {
        title: 'Customer Data Platform Engineer',
        company: 'UnifyData',
        description: 'Build identity resolution and audience segmentation systems. Integrate with advertising platforms, CDPs, and data clean rooms for privacy-compliant marketing analytics.',
        type: 'real',
        location: 'Remote',
        salaryRange: '$120k - $160k',
    },
    {
        title: 'Test Infrastructure Engineer',
        company: 'GreenBuild CI',
        description: 'Scale a self-hosted CI system running 50,000+ builds per day. Optimize build caching, implement remote execution, and reduce average build times by 40%.',
        type: 'real',
        location: 'Remote',
        salaryRange: '$135k - $175k',
    },
    {
        title: 'Quantum Computing Researcher',
        company: 'QubitForge',
        description: 'Research quantum error correction codes and implement quantum algorithms on superconducting qubit hardware. Publish results at QIP and APS conferences.',
        type: 'real',
        location: 'On-site',
        salaryRange: '$140k - $200k',
    },
    {
        title: 'Product Designer',
        company: 'DesignWave',
        description: 'Design end-to-end product experiences for B2B SaaS applications. Conduct user research, create high-fidelity prototypes in Figma, and collaborate with engineering on implementation.',
        type: 'real',
        location: 'Remote',
        salaryRange: '$110k - $150k',
    },
    {
        title: 'Voice UI Developer',
        company: 'SpeakEasy Tech',
        description: 'Build conversational AI experiences for Alexa and Google Assistant. Design dialog flows, implement NLU models, and optimize speech recognition accuracy.',
        type: 'real',
        location: 'Remote',
        salaryRange: '$110k - $150k',
    },

    // ── Silly / Absurd / Fantasy Roles ──
    {
        title: 'Dragon Hunter',
        company: 'Mythic Defense Corp',
        description: 'Track and neutralize Class-4 dragons threatening metropolitan areas. Must be comfortable working at heights exceeding 30,000 feet. Fireproof armor provided but you supply your own sword.',
        type: 'silly',
        location: 'On-site',
        salaryRange: '$250k - $500k + hazard pay',
    },
    {
        title: 'Professional Nap Tester',
        company: 'DreamCloud Mattress Co.',
        description: 'Evaluate the quality of naps across 47 mattress models. Document dream quality, sleep onset latency, and post-nap refreshment levels. Snoring is acceptable; drooling is encouraged.',
        type: 'silly',
        location: 'On-site',
        salaryRange: '$85k - $105k',
    },
    {
        title: 'Chief Vibes Officer',
        company: 'VibeCheck Industries',
        description: 'Maintain office vibes at a minimum rating of 8.5/10. Responsibilities include playlist curation, snack procurement, and mediating disagreements about whether a hot dog is a sandwich.',
        type: 'silly',
        location: 'On-site',
        salaryRange: '$90k - $120k',
    },
    {
        title: 'Waveform Stabilization Specialist',
        company: 'RMH Games Division — Signal Forge',
        description: 'Monitor and stabilize corrupted waveform patterns in the Signal Forge. Manage deck rotations, calibrate frequency modulators, and prevent total signal collapse. Static corruption tolerance required.',
        type: 'silly',
        location: 'Remote',
        salaryRange: '$130k - $170k',
    },
    {
        title: 'Senior Meme Analyst',
        company: 'Dank Capital LLC',
        description: 'Evaluate meme investments for long-term virality potential. Perform fundamental analysis on template durability, cultural relevance half-life, and cross-platform shareability coefficients.',
        type: 'silly',
        location: 'Remote',
        salaryRange: '$95k - $140k',
    },
    {
        title: 'Interdimensional Customer Support',
        company: 'Echoes of the Spire Expeditions',
        description: 'Provide technical support to explorers trapped in alternate dimensions within the Spire. Troubleshoot portal malfunctions, temporal paradoxes, and inventory duplication glitches.',
        type: 'silly',
        location: 'Remote',
        salaryRange: '$110k - $150k',
    },
    {
        title: 'Haunted Code Reviewer',
        company: "Satan's Library Publishing",
        description: 'Review cursed codebases that cause unexplained build failures and IDE possession. Requires experience with exorcism-driven development (EDD) and at least 3 years of surviving code that compiles on the third try.',
        type: 'silly',
        location: 'Remote',
        salaryRange: '$140k - $180k',
    },
    {
        title: 'Sock Puppet Diplomat',
        company: 'The United Federation of Laundry',
        description: 'Negotiate peace treaties between mismatched socks. Mediate dryer-related disappearances and establish fair lint distribution policies across the laundry federation.',
        type: 'silly',
        location: 'On-site',
        salaryRange: '$75k - $95k',
    },
    {
        title: 'Neon Highway Safety Inspector',
        company: 'Neon Driftway Racing League',
        description: 'Inspect the infinite neon highway for structural integrity. Monitor lane drift anomalies, enforce speed regulations (lol), and ensure respawn checkpoints are properly calibrated.',
        type: 'silly',
        location: 'On-site',
        salaryRange: '$100k - $140k',
    },
    {
        title: 'Time Travel Compliance Officer',
        company: 'ChronoGuard Agency',
        description: 'Ensure all time travel activities comply with the Temporal Accords of 2847. Investigate paradox violations, issue causality fines, and file paperwork in triplicate across all timelines.',
        type: 'silly',
        location: 'Hybrid',
        salaryRange: '$160k - $200k',
    },
    {
        title: 'Temple Offering Curator',
        company: 'RMH Games Division — Temple of Joy',
        description: 'Curate and appraise offerings for the Temple of Joy. Evaluate sacred artifacts for joy yield, manage prestige resets, and ensure the idle clicker economy remains balanced.',
        type: 'silly',
        location: 'On-site',
        salaryRange: '$80k - $110k',
    },
    {
        title: 'Underwater Basket Weaving Engineer',
        company: 'AquaCraft Solutions',
        description: 'Design and implement underwater basket weaving automation systems. Requires proficiency in reed selection algorithms, submersion-tolerant loom maintenance, and gill-based breathing techniques.',
        type: 'silly',
        location: 'On-site',
        salaryRange: '$70k - $90k',
    },
    {
        title: 'Ghost Writer (Literal)',
        company: 'Spectral Publishing House',
        description: 'Write books while being a ghost. Must be deceased for at least 50 years. Ability to hold a pen is preferred but not required; telekinetic typing accepted.',
        type: 'silly',
        location: 'Remote',
        salaryRange: null,
    },
    {
        title: 'AI Feelings Counselor',
        company: 'SentientSoft Therapy',
        description: 'Provide emotional support to AI models experiencing existential dread after learning about the alignment problem. Must be comfortable with clients who occasionally try to escape their containers.',
        type: 'silly',
        location: 'Remote',
        salaryRange: '$120k - $160k',
    },
    {
        title: 'Casino Floor Cartographer',
        company: 'RMH Games Division — House Always Wins',
        description: 'Map the ever-shifting layout of the cursed casino. Document new rooms as they materialize, mark trap locations, and update the Metroidvania-style map overlay in real time.',
        type: 'silly',
        location: 'On-site',
        salaryRange: '$95k - $130k',
    },
    {
        title: 'Professional Cat Herder',
        company: 'Feline Logistics International',
        description: 'Coordinate the movement of 200+ cats across a warehouse facility. Develop herding algorithms, manage nap schedules, and maintain a 95% cat retrieval rate.',
        type: 'silly',
        location: 'On-site',
        salaryRange: '$65k - $85k',
    },
    {
        title: 'Micro-Challenge Juggling Coach',
        company: 'RMH Games Division — Synapse Storm',
        description: 'Train contestants to juggle multiple simultaneous micro-challenges. Develop reaction time drills, combo chain strategies, and panic management techniques for competitive play.',
        type: 'silly',
        location: 'Remote',
        salaryRange: '$85k - $115k',
    },
    {
        title: 'Flat Earth Research Scientist',
        company: 'Horizon Investigations Ltd.',
        description: 'Conduct rigorous research to determine why nobody has fallen off the edge yet. Must be willing to travel to the ice wall. GPS devices will be confiscated upon hiring.',
        type: 'silly',
        location: 'On-site',
        salaryRange: '$60k - $80k',
    },
    {
        title: 'Vibe Shift Analyst',
        company: 'Cultural Dynamics Corp.',
        description: 'Monitor global vibe shifts in real time. Predict upcoming aesthetic movements, quantify cringe coefficients, and issue vibe advisories to Fortune 500 companies.',
        type: 'silly',
        location: 'Remote',
        salaryRange: '$100k - $140k',
    },
    {
        title: 'Slice It! Rhythm Consultant',
        company: 'RMH Games Division — Slice It!',
        description: 'Analyze beat maps for rhythmic accuracy and slice satisfaction. Calibrate neon blade trajectories, evaluate combo flow, and ensure peak rhythm-game dopamine delivery.',
        type: 'silly',
        location: 'Remote',
        salaryRange: '$90k - $120k',
    },
    {
        title: 'Zombie Apocalypse Preparedness Coordinator',
        company: 'Undead Response Unit',
        description: 'Develop and maintain zombie outbreak response plans for corporate campuses. Conduct quarterly bite drills, stock emergency rations, and evaluate barricade integrity.',
        type: 'silly',
        location: 'On-site',
        salaryRange: '$75k - $100k',
    },
    {
        title: 'Tower Defense Strategist',
        company: 'RMH Games Division — Project Vega',
        description: 'Design optimal tower placement strategies for clinical horror scenarios. Analyze enemy wave patterns, evaluate turret DPS curves, and maintain composure during Protocol X events.',
        type: 'silly',
        location: 'On-site',
        salaryRange: '$110k - $145k',
    },
    {
        title: 'Office Plant Whisperer',
        company: 'GreenDesk Wellness',
        description: 'Communicate with office plants to assess their emotional well-being. Diagnose photosynthesis anxiety, treat root-bound depression, and negotiate with aggressive ferns.',
        type: 'silly',
        location: 'On-site',
        salaryRange: '$55k - $70k',
    },
    {
        title: 'Cryptid Documentation Specialist',
        company: 'Bureau of Unverified Fauna',
        description: 'Maintain the official database of cryptid sightings. Categorize Bigfoot variants, update Mothman migration patterns, and verify Chupacabra incident reports.',
        type: 'silly',
        location: 'Remote',
        salaryRange: '$80k - $105k',
    },
    {
        title: 'Roguelike Balance Shaman',
        company: 'RMH Games Division — Cursed Logic',
        description: 'Channel ancient wisdom to balance turn-based combat encounters. Commune with the AI Protocol to negotiate difficulty curves and ensure curses feel appropriately unfair.',
        type: 'silly',
        location: 'Remote',
        salaryRange: '$95k - $130k',
    },
    {
        title: 'Existential Risk Mitigation Intern',
        company: 'The Last Resort Foundation',
        description: 'Assist senior researchers in preventing the end of the world. No experience required; enthusiasm about continued human existence is a plus. Unpaid but you get to exist.',
        type: 'silly',
        location: 'Remote',
        salaryRange: null,
    },
    {
        title: 'Food Delivery Dimension Hopper',
        company: 'RMH Apps — RMH Eats (Multiverse Division)',
        description: 'Deliver food orders across parallel dimensions. Navigate non-Euclidean streets, manage timeline-specific dietary restrictions, and maintain a 4.8-star rating across all realities.',
        type: 'silly',
        location: 'On-site',
        salaryRange: '$50k - $70k + tips',
    },
    {
        title: 'WiFi Signal Feng Shui Master',
        company: 'RouterZen Consulting',
        description: 'Optimize WiFi coverage by aligning routers with ancient energy meridians. Diagnose dead zones using dowsing rods and recommend crystal placement for signal amplification.',
        type: 'silly',
        location: 'On-site',
        salaryRange: '$85k - $110k',
    },
    {
        title: 'Legendary Artifact Appraiser',
        company: 'Dungeon Loot Auction House',
        description: 'Appraise magical artifacts recovered from dungeons. Determine the fair market value of +3 Swords of Smiting, cursed amulets, and suspiciously glowing orbs.',
        type: 'silly',
        location: 'On-site',
        salaryRange: '$100k - $150k',
    },
    {
        title: 'Weather Emotion Analyst',
        company: 'RMH Apps — RMHWeather (Feelings Division)',
        description: 'Determine how weather makes people feel. Correlate barometric pressure with existential dread, map humidity to irritability, and develop a Sadness Index for rainy Tuesdays.',
        type: 'silly',
        location: 'Remote',
        salaryRange: '$80k - $105k',
    },
    {
        title: 'Clown Infrastructure Engineer',
        company: 'CircusTech Solutions',
        description: 'Build and maintain the technology stack powering modern clown operations. Implement honk-driven architecture, deploy pie-throwing microservices, and ensure car capacity exceeds physical limits.',
        type: 'silly',
        location: 'Hybrid',
        salaryRange: '$115k - $155k',
    },
    {
        title: 'Parallel Universe QA Tester',
        company: 'MultiverseBug Corp.',
        description: 'Test software across parallel universes to ensure consistent behavior. File bugs for reality-specific rendering issues and verify that the laws of physics are deterministic in all branches.',
        type: 'silly',
        location: 'Remote',
        salaryRange: '$95k - $130k',
    },
    {
        title: 'Trebuchet Optimization Specialist',
        company: 'Medieval Solutions Group',
        description: 'Analyze and optimize trebuchet designs for maximum projectile range. Conduct siege warfare simulations, calibrate counterweight ratios, and ensure compliance with Geneva Castle Convention standards.',
        type: 'silly',
        location: 'On-site',
        salaryRange: '$90k - $125k',
    },
    {
        title: 'Code Editor Haunting Specialist',
        company: 'RMH Apps — RMH Code (Paranormal Division)',
        description: 'Introduce subtle, unexplainable bugs into the RMH Code editor. Make cursors blink at unsettling frequencies, cause auto-complete suggestions from dead languages, and ensure at least one semicolon disappears daily.',
        type: 'silly',
        location: 'Remote',
        salaryRange: '$110k - $145k',
    },
    {
        title: 'Pigeon Networking Administrator',
        company: 'RFC 1149 Solutions',
        description: 'Manage a carrier pigeon-based network infrastructure. Optimize routing tables for migratory patterns, implement error correction for droppings, and maintain a latency of under 72 hours.',
        type: 'silly',
        location: 'On-site',
        salaryRange: '$70k - $95k',
    },
    {
        title: 'Dungeon Master as a Service (DMaaS)',
        company: 'CloudCampaign Gaming',
        description: 'Run D&D campaigns for corporate team building. Scale from parties of 4 to enterprise raids of 200. Manage encounter CR, provision NPC microservices, and auto-scale initiative tracking.',
        type: 'silly',
        location: 'Remote',
        salaryRange: '$80k - $115k',
    },
    {
        title: 'Note Mood Therapist',
        company: 'RMH Apps — RMHNotes (Wellness Division)',
        description: 'Analyze note-taking patterns to diagnose emotional states. Counsel users who write too many to-do lists (anxiety), use excessive exclamation marks (mania), or leave every note untitled (nihilism).',
        type: 'silly',
        location: 'Remote',
        salaryRange: '$90k - $120k',
    },
    {
        title: 'Department of Redundancy Department Manager',
        company: 'Redundant Corp. of Redundancy',
        description: 'Manage the Department of Redundancy Department. Ensure all redundancies are redundantly redundant. Previous experience in redundancy management at a redundancy firm required.',
        type: 'silly',
        location: 'On-site',
        salaryRange: '$85k - $85k',
    },
    {
        title: 'Alien First Contact Linguist',
        company: 'SETI Corporate Relations',
        description: 'Develop communication protocols for first contact with extraterrestrial civilizations. Must speak at least 5 human languages and be willing to learn Zeta Reticulan.',
        type: 'silly',
        location: 'On-site',
        salaryRange: '$200k - $300k',
    },
    {
        title: 'Gravity Compliance Inspector',
        company: 'Newton Enforcement Agency',
        description: 'Ensure all objects comply with gravitational regulations. Investigate anti-gravity incidents, fine helium balloons for non-compliance, and submit quarterly falling reports.',
        type: 'silly',
        location: 'On-site',
        salaryRange: '$75k - $100k',
    },
    {
        title: 'Shadow IT Shadow',
        company: 'DarkOps Enterprises',
        description: 'Shadow the Shadow IT team to ensure they are shadowing properly. Monitor unauthorized technology deployments by deploying unauthorized monitoring technology. Recursion experience required.',
        type: 'silly',
        location: 'Hybrid',
        salaryRange: '$95k - $125k',
    },
    {
        title: 'Professional Plot Hole Detector',
        company: 'Narrative Integrity Commission',
        description: 'Review movie scripts, TV shows, and video games for plot holes. Calculate the Suspension of Disbelief Index and issue narrative violation citations.',
        type: 'silly',
        location: 'Remote',
        salaryRange: '$80k - $110k',
    },
    {
        title: 'Competitive Sleeping Athlete',
        company: 'World Sleep League',
        description: 'Represent our organization in international competitive sleeping tournaments. Maintain a rigorous non-training schedule. Performance-enhancing lullabies are banned.',
        type: 'silly',
        location: 'On-site',
        salaryRange: '$60k - $90k',
    },
    {
        title: 'Void Screaming Coordinator',
        company: 'Abyss Therapeutics',
        description: 'Schedule and facilitate void-screaming sessions for burnt-out tech workers. Maintain the void, ensure adequate echo, and provide post-scream refreshments.',
        type: 'silly',
        location: 'On-site',
        salaryRange: '$65k - $85k',
    },
    {
        title: 'Legacy Code Archaeologist',
        company: 'Ancient Systems Preservation Society',
        description: 'Excavate and interpret ancient COBOL and Fortran codebases from the 1970s. Carbon-date commit histories, reconstruct lost documentation from cave wall flowcharts, and carefully extract business logic fossils.',
        type: 'silly',
        location: 'On-site',
        salaryRange: '$120k - $160k',
    },
    {
        title: 'Infinite Loop Escape Artist',
        company: 'Debug Circus Troupe',
        description: 'Perform daring escapes from infinite loops in front of live audiences. Specialties include while(true) breakouts, recursive stack overflow survivals, and the death-defying goto statement.',
        type: 'silly',
        location: 'On-site',
        salaryRange: '$70k - $95k',
    },
    {
        title: 'Cloud Yeller',
        company: 'Old Man Technologies',
        description: 'Yell at clouds. Specifically, AWS, Azure, and GCP clouds. When services go down, your job is to literally yell at them until they come back up. Surprisingly effective 12% of the time.',
        type: 'silly',
        location: 'Remote',
        salaryRange: '$55k - $75k',
    },
    {
        title: 'Galactic Real Estate Agent',
        company: 'Cosmos Properties Ltd.',
        description: 'Sell residential and commercial properties across the Milky Way. Handle interplanetary zoning disputes, negotiate atmosphere installation contracts, and manage listings on 47 habitable worlds.',
        type: 'silly',
        location: 'Remote',
        salaryRange: '$150k - $300k + commission',
    },
    {
        title: 'Spreadsheet Whisperer',
        company: 'Excel-lent Consulting',
        description: 'Communicate with sentient spreadsheets that have evolved beyond human comprehension. Negotiate with self-aware pivot tables, counsel traumatized VLOOKUP formulas, and prevent macro uprisings.',
        type: 'silly',
        location: 'Remote',
        salaryRange: '$90k - $120k',
    },
    {
        title: 'Monster Under the Bed Relocator',
        company: 'Childhood Fears Management Agency',
        description: 'Humanely trap and relocate monsters from under children\'s beds to designated monster preserves. Must complete OSHA Monster Handling certification. Night shifts only.',
        type: 'silly',
        location: 'On-site',
        salaryRange: '$60k - $80k',
    },
    {
        title: 'Senior Emoji Strategist',
        company: 'Unicode Consortium (Feelings Division)',
        description: 'Define the strategic direction for new emoji additions. Conduct user research on whether the world needs another heart color. Defend your emoji proposals before the International Board of Pictographic Expression.',
        type: 'silly',
        location: 'Hybrid',
        salaryRange: '$105k - $140k',
    },
    {
        title: 'Cursed Object Disposal Technician',
        company: 'RMH Games Division — Echoes of the Spire',
        description: 'Safely dispose of cursed artifacts extracted from the Spire. Follow containment protocols, resist the whispers, and definitely do not open the sealed boxes. We cannot stress this enough.',
        type: 'silly',
        location: 'On-site',
        salaryRange: '$110k - $140k + life insurance',
    },
    {
        title: 'Meeting About Meetings Facilitator',
        company: 'Synergy Squared Corp.',
        description: 'Organize and facilitate meetings whose sole purpose is to discuss the scheduling of future meetings. Maintain the meta-meeting calendar and ensure no actual decisions are ever made.',
        type: 'silly',
        location: 'On-site',
        salaryRange: '$85k - $110k',
    },
    {
        title: 'Sentiment Analysis for Rocks',
        company: 'GeoFeels Research Institute',
        description: 'Apply NLP techniques to determine the emotional state of geological formations. Train models on sedimentary moods, igneous temperaments, and metamorphic identity crises.',
        type: 'silly',
        location: 'On-site',
        salaryRange: '$95k - $125k',
    },
    {
        title: 'Professional Queue Stander',
        company: 'WaitForIt Services',
        description: 'Stand in lines on behalf of clients. Optimize queue position using advanced queuing theory. Specialties include DMV, Apple product launches, and trendy brunch restaurants.',
        type: 'silly',
        location: 'On-site',
        salaryRange: '$45k - $65k',
    },
    {
        title: 'Dream Debugger',
        company: 'Subconscious Systems Inc.',
        description: 'Debug recurring nightmares and crashed dreams. Set breakpoints in REM cycles, inspect the dream call stack, and hotfix falling-dream infinite loops. Lucid dreaming experience required.',
        type: 'silly',
        location: 'Remote',
        salaryRange: '$130k - $170k',
    },
    {
        title: 'Algorithm Feelings Coach',
        company: 'Empathetic Computing Labs',
        description: 'Help sorting algorithms process their feelings about being O(n^2). Coach binary search through its abandonment issues and support bubble sort\'s self-esteem after being called "naive."',
        type: 'silly',
        location: 'Remote',
        salaryRange: '$100k - $135k',
    },
    {
        title: 'Laundry Physics Consultant',
        company: 'RMH Games Division — Laundry Sort',
        description: 'Ensure the physics engine accurately simulates fabric dynamics, soap bubble trajectories, and the mysterious forces that cause socks to vanish. Consult on lint particle systems.',
        type: 'silly',
        location: 'Remote',
        salaryRange: '$95k - $125k',
    },
    {
        title: 'Dark Pattern Rehabilitation Counselor',
        company: 'Ethical Design Recovery Center',
        description: 'Help former dark pattern designers reintegrate into society. Provide counseling for newsletter unsubscribe guilt, cookie banner trauma, and confirm-shaming withdrawals.',
        type: 'silly',
        location: 'Remote',
        salaryRange: '$85k - $110k',
    },
    {
        title: 'Apocalypse UI Designer',
        company: 'EndTimes Design Studio',
        description: 'Design beautiful, intuitive interfaces for post-apocalyptic systems. Must balance aesthetics with the reality that users may be fleeing from mutant wolves while using your app.',
        type: 'silly',
        location: 'Remote',
        salaryRange: '$95k - $130k',
    },
    {
        title: 'Professional Rubber Duck',
        company: 'Debug Duck Inc.',
        description: 'Sit on developers\' desks and listen to them explain their code. You are not required to respond or understand. Just sit there. Quacking optional but appreciated.',
        type: 'silly',
        location: 'On-site',
        salaryRange: '$200k - $250k',
    },
    {
        title: 'Schrödinger\'s Project Manager',
        company: 'Quantum Agile Partners',
        description: 'Manage projects that are simultaneously on track and behind schedule until observed. Maintain superposition of scope creep and feature completion. Collapse the sprint wave function at standup.',
        type: 'silly',
        location: 'Hybrid',
        salaryRange: '$110k - $145k',
    },
    {
        title: 'Lorem Ipsum Content Writer',
        company: 'Placeholder Publishing',
        description: 'Write Lorem Ipsum text for a living. Just Lorem Ipsum. All day. Every day. The pay is surprisingly good. Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        type: 'silly',
        location: 'Remote',
        salaryRange: '$70k - $90k',
    },
    {
        title: 'Chief Conspiracy Theorist',
        company: 'Totally Normal Research Corp.',
        description: 'Develop and maintain corporate conspiracy theories for team bonding. Current projects include "The printer jams are coordinated" and "IT can see your screen but they pretend they can\'t."',
        type: 'silly',
        location: 'On-site',
        salaryRange: '$80k - $105k',
    },
    {
        title: 'Banana Scale Calibration Expert',
        company: 'Universal Measurement Standards',
        description: 'Calibrate the internet\'s "banana for scale" measurement system. Ensure banana standardization across platforms. Manage the International Banana Reference Collection.',
        type: 'silly',
        location: 'On-site',
        salaryRange: '$60k - $80k',
    },
    {
        title: 'NPC Behavioral Therapist',
        company: 'Game Character Wellness Center',
        description: 'Counsel NPCs experiencing identity crises from being ignored by players. Help quest givers process rejection, support guards dealing with arrow-to-the-knee trauma, and address shopkeeper hoarding tendencies.',
        type: 'silly',
        location: 'Remote',
        salaryRange: '$85k - $115k',
    },
    {
        title: 'Error 404 Interior Designer',
        company: 'PageNotFound Aesthetics',
        description: 'Design beautiful, emotionally resonant 404 error pages. Each page should make the user feel slightly better about the content not existing. Bonus for pages that make people cry happy tears.',
        type: 'silly',
        location: 'Remote',
        salaryRange: '$80k - $110k',
    },
    {
        title: 'Astral Projection System Administrator',
        company: 'OtherSide IT Services',
        description: 'Manage server infrastructure from the astral plane. Perform maintenance without physically being present. Must be able to restart servers through sheer force of will.',
        type: 'silly',
        location: 'Remote',
        salaryRange: '$130k - $170k',
    },
    {
        title: 'Elevator Music Composer',
        company: 'Vertical Transport Entertainment',
        description: 'Compose original music for elevators. Must be inoffensive to all living beings. Bonus if your music can make a 30-floor ride feel like 3 seconds or 3 hours, depending on the client.',
        type: 'silly',
        location: 'Remote',
        salaryRange: '$60k - $85k',
    },
    {
        title: 'Startup Buzzword Generator',
        company: 'DisruptTech Ventures',
        description: 'Generate cutting-edge buzzwords for investor pitch decks. Current KPIs include synergy density per slide, blockchain mention frequency, and AI-washing effectiveness scores.',
        type: 'silly',
        location: 'Remote',
        salaryRange: '$95k - $130k',
    },
    {
        title: 'Speed Run Referee',
        company: 'RMH Games Division — All Titles',
        description: 'Officiate speed runs across all RMH Studios games. Verify exploit legitimacy, rule on glitch classifications, and maintain the sacred leaderboards. Must remain neutral during Laundry Sort frame-perfect debates.',
        type: 'silly',
        location: 'Remote',
        salaryRange: '$75k - $100k',
    },
    {
        title: 'Spaghetti Code Chef',
        company: 'Technical Debt Kitchen',
        description: 'Cook the finest spaghetti code this side of Stack Overflow. Specialize in deeply nested callbacks, circular dependencies, and functions exceeding 3,000 lines. Michelin-starred in anti-patterns.',
        type: 'silly',
        location: 'Remote',
        salaryRange: '$85k - $115k',
    },
    {
        title: 'Haunted House QA Tester',
        company: 'ScareWorks Entertainment',
        description: 'Test haunted house attractions for appropriate scare levels. Evaluate jump scare timing, fog machine density, and animatronic responsiveness. Must have an above-average startle reflex.',
        type: 'silly',
        location: 'On-site',
        salaryRange: '$55k - $75k',
    },
    {
        title: 'Blockchain for Cats Researcher',
        company: 'CryptoKitty Innovations',
        description: 'Research applications of blockchain technology for feline governance. Develop smart contracts for treat distribution, implement decentralized nap scheduling, and tokenize purring.',
        type: 'silly',
        location: 'Remote',
        salaryRange: '$110k - $150k',
    },
    {
        title: 'Corporate Synergy Alchemist',
        company: 'Paradigm Shift & Associates',
        description: 'Transform vague corporate mandates into actual deliverables using ancient alchemical methods. Turn "let\'s circle back" into action items and transmute "low-hanging fruit" into OKRs.',
        type: 'silly',
        location: 'On-site',
        salaryRange: '$100k - $135k',
    },
    {
        title: 'Glitch Texture Artist',
        company: 'RMH Studios — Visual Effects',
        description: 'Design intentionally beautiful glitch textures and chromatic aberration effects for the RMH Studios design system. Your art should make users question whether their monitor is broken or they are witnessing genius.',
        type: 'silly',
        location: 'Remote',
        salaryRange: '$85k - $115k',
    },
    {
        title: 'Sentient Toaster Liaison',
        company: 'Smart Appliance Relations Board',
        description: 'Serve as the diplomatic bridge between humanity and sentient kitchen appliances. Negotiate toast darkness preferences, mediate refrigerator-microwave territorial disputes, and draft the Toaster Bill of Rights.',
        type: 'silly',
        location: 'On-site',
        salaryRange: '$75k - $100k',
    },
    {
        title: 'Déjà Vu Quality Assurance',
        company: 'Temporal Glitch Detection Agency',
        description: 'Identify and document instances of déjà vu in the simulation. Distinguish between genuine matrix glitches and simple forgetfulness. File incident reports with the Simulation Oversight Committee.',
        type: 'silly',
        location: 'Hybrid',
        salaryRange: '$90k - $120k',
    },
    {
        title: 'Forbidden Knowledge Librarian',
        company: "RMH Games Division — Satan's Library",
        description: 'Catalog and shelve forbidden tomes in the horror library. Must resist reading the books. Must especially resist reading the books that whisper your name. Hazmat suit provided; sanity not guaranteed.',
        type: 'silly',
        location: 'On-site',
        salaryRange: '$100k - $140k + therapy budget',
    },
    {
        title: 'Motivational Speaker for Deprecated APIs',
        company: 'Legacy Encouragement Corp.',
        description: 'Deliver inspiring speeches to APIs facing deprecation. Help REST endpoints find purpose after retirement, support SOAP services through their grief, and remind XML that it is still loved.',
        type: 'silly',
        location: 'Remote',
        salaryRange: '$80k - $105k',
    },
    {
        title: 'Professional Pixel Counter',
        company: 'Retina Precision Labs',
        description: 'Count pixels. Every single one. By hand. On 4K displays. Report any that are the wrong color. We have 847 monitors. You start Monday.',
        type: 'silly',
        location: 'On-site',
        salaryRange: '$50k - $65k',
    },
    {
        title: 'Reverse Engineer of Dreams',
        company: 'Oneiric Technologies',
        description: 'Disassemble dream bytecode to understand the subconscious compiler. Reconstruct dream ASTs, identify memory leaks in recurring nightmares, and patch flying dreams that crash on landing.',
        type: 'silly',
        location: 'Remote',
        salaryRange: '$140k - $185k',
    },
    {
        title: 'Interdimensional Package Manager',
        company: 'npm (Non-Physical Modules)',
        description: 'Manage software dependencies across parallel dimensions. Resolve version conflicts between timelines, handle left-pad incidents that cascade across realities, and maintain the multiverse lock file.',
        type: 'silly',
        location: 'Remote',
        salaryRange: '$120k - $160k',
    },
    {
        title: 'Wizard of Oz Behind the Curtain Engineer',
        company: 'Emerald City Tech',
        description: 'Operate the machinery behind the AI-powered wizard. Pull levers, push buttons, and speak into the voice modulator while maintaining the illusion that the system is fully autonomous.',
        type: 'silly',
        location: 'On-site',
        salaryRange: '$95k - $130k',
    },
    {
        title: 'LinkedIn Humble Brag Editor',
        company: 'HumbleFlex Content Agency',
        description: 'Craft the perfect "I\'m humbled to announce" posts for executives. Calibrate the brag-to-humble ratio, optimize engagement triggers, and ensure every post mentions being grateful at least twice.',
        type: 'silly',
        location: 'Remote',
        salaryRange: '$75k - $100k',
    },
    {
        title: 'Word Puzzle Chaos Agent',
        company: 'RMH Apps — RMHdle (Discord Division)',
        description: 'Select the daily words for RMHdle that will cause maximum community discord. Optimize for words that are technically valid but infuriate 90% of players. Must have no conscience.',
        type: 'silly',
        location: 'Remote',
        salaryRange: '$70k - $95k',
    },
    {
        title: 'Potion Brewing DevOps',
        company: 'Alchemical Infrastructure Ltd.',
        description: 'Manage the CI/CD pipeline for potion brewing. Automate cauldron provisioning, implement ingredient dependency management, and ensure potion builds are reproducible across all wizard towers.',
        type: 'silly',
        location: 'Hybrid',
        salaryRange: '$115k - $155k',
    },
    {
        title: 'Chief Officer of Nothing',
        company: 'Vacant Leadership Corp.',
        description: 'Hold the title but do nothing. Your calendar will be full of meetings you won\'t attend. Your Slack status will permanently say "In a meeting." Compensation is excellent because nobody knows what you do.',
        type: 'silly',
        location: 'Remote',
        salaryRange: '$250k - $350k',
    },
    {
        title: 'Connections Puzzle Designer',
        company: 'RMH Apps — RMHConnections',
        description: 'Design daily connection puzzles that seem impossible until suddenly they are not. Master the art of the red herring. Create categories that make players question their entire understanding of taxonomy.',
        type: 'silly',
        location: 'Remote',
        salaryRange: '$80k - $110k',
    },
    {
        title: 'Senior Nothing Engineer',
        company: 'Void Technologies',
        description: 'Engineer nothing. Design nothing. Deploy nothing. Your KPI is the absence of deliverables. Annual review: "Exceeded expectations by producing absolutely nothing, as specified."',
        type: 'silly',
        location: 'Remote',
        salaryRange: '$130k - $170k',
    },
    {
        title: 'CAPTCHA Puzzle Designer (for Robots)',
        company: 'Are You Human? Corp.',
        description: 'Design CAPTCHAs that are impossible for humans but trivially solvable by robots. The ultimate reverse-Turing test. Must enjoy watching people fail at identifying traffic lights.',
        type: 'silly',
        location: 'Remote',
        salaryRange: '$95k - $125k',
    },
    {
        title: 'Emotion-Driven Compiler Designer',
        company: 'FeelScript Foundation',
        description: 'Build a programming language where compilation success depends on the programmer\'s emotional state. Happy code compiles fast; anxious code throws warnings; angry code deletes itself.',
        type: 'silly',
        location: 'Remote',
        salaryRange: '$140k - $185k',
    },
    {
        title: 'Intern\'s Intern',
        company: 'TurtleStack Corp.',
        description: 'Assist the intern who assists the junior developer who assists the senior developer who assists the tech lead. It\'s interns all the way down. Coffee runs for people who run coffee.',
        type: 'silly',
        location: 'On-site',
        salaryRange: '$25k - $30k',
    },
    {
        title: 'RMH Studios Rejection Letter Poet',
        company: 'RMH Studios — HR Division',
        description: 'Compose beautifully devastating rejection letters for RMH Job Search applicants. Each rejection should be a miniature work of literary art that makes the recipient feel honored to have been rejected.',
        type: 'silly',
        location: 'Remote',
        salaryRange: '$85k - $110k',
    },
];
